select
    id,
    `name`,
    `description`,
    lastmodifieddate as `last_modified_date`,
    isactive as `is_active`,
    businessprocessid as `business_process_id`,
    systemmodstamp as `system_modstamp`,
    sobjecttype as `sobject_type`,
    createdbyid as `created_by_id`,
    createddate as `created_date`,
    developername as `developer_name`,
    lastmodifiedbyid as `last_modified_by_id`,
    namespaceprefix as `namespace_prefix`,
from {{ source("kippadb", "record_type") }}
