select
    id,
    `name`,
    createdbyid as `created_by_id`,
    createddate as `created_date`,
    lastactivitydate as `last_activity_date`,
    lastmodifiedbyid as `last_modified_by_id`,
    lastmodifieddate as `last_modified_date`,
    lastreferenceddate as `last_referenced_date`,
    lastvieweddate as `last_viewed_date`,
    recordtypeid as `record_type_id`,
    systemmodstamp as `system_modstamp`,
    academic__c as `academic`,
    academic_category_score__c as `academic_category_score`,
    academic_color__c as `academic_color`,
    academic_notes__c as `academic_notes`,
    academic_preparedness__c as `academic_preparedness`,
    academic_score__c as `academic_score`,
    audit_date__c as `audit_date`,
    audit_tool__c as `audit_tool`,
    basic_needs__c as `basic_needs`,
    benchmark_date__c as `benchmark_date`,
    benchmark_location__c as `benchmark_location`,
    benchmark_path__c as `benchmark_path`,
    benchmark_period__c as `benchmark_period`,
    benchmark_status__c as `benchmark_status`,
    benchmark_type__c as `benchmark_type`,
    campus_integration__c as `campus_integration`,
    career_development_plan__c as `career_development_plan`,
    career_exploration__c as `career_exploration`,
    college_career_plan__c as `college_career_plan`,
    college_persistence_count__c as `college_persistence_count`,
    college_term__c as `college_term`,
    completed_initial_college_career_plan__c as `completed_initial_college_career_plan`,
    contact__c as `contact`,
    create_contact_note_from_benchmark_edit__c
    as `create_contact_note_from_benchmark_edit`,
    date_completed__c as `date_completed`,
    enrollment__c as `enrollment`,
    enrollment_matriculation__c as `enrollment_matriculation`,
    enrollment_preparation__c as `enrollment_preparation`,
    entrance_exams_and_assessments__c as `entrance_exams_and_assessments`,
    family_support__c as `family_support`,
    financial__c as `financial`,
    financial_aid__c as `financial_aid`,
    financial_category_score__c as `financial_category_score`,
    financial_color__c as `financial_color`,
    financial_notes__c as `financial_notes`,
    financial_score__c as `financial_score`,
    financial_stability__c as `financial_stability`,
    future_focus__c as `future_focus`,
    gpa__c as `gpa`,
    has_a_passion__c as `has_a_passion`,
    has_a_plan__c as `has_a_plan`,
    hs_academic_and_technical_profile__c as `hs_academic_and_technical_profile`,
    hs_academic_profile__c as `hs_academic_profile`,
    internship_summer_plan__c as `internship_summer_plan`,
    job_school_balance__c as `job_school_balance`,
    job_school_personal_life_balance__c as `job_school_personal_life_balance`,
    math_remedial_course_name__c as `math_remedial_course_name`,
    math_remedial_course_status__c as `math_remedial_course_status`,
    math_remediation__c as `math_remediation`,
    mental_health__c as `mental_health`,
    next_steps__c as `next_steps`,
    non_cognitive_color__c as `non_cognitive_color`,
    non_cognitive_notes__c as `non_cognitive_notes`,
    non_cognitive_preparedness__c as `non_cognitive_preparedness`,
    on_track_towards_education_plan_goals__c as `on_track_towards_education_plan_goals`,
    overall_benchmark_status__c as `overall_benchmark_status`,
    overall_score__c as `overall_score`,
    overall_student_score__c as `overall_student_score`,
    passion_purpose_plan__c as `passion_purpose_plan`,
    passion_purpose_plan_category_score__c as `passion_purpose_plan_category_score`,
    passion_purpose_plan_notes__c as `passion_purpose_plan_notes`,
    passion_purpose_plan_score__c as `passion_purpose_plan_score`,
    placement_tests__c as `placement_tests`,
    plan_to_pay__c as `plan_to_pay`,
    pursuing_degree_type__c as `pursuing_degree_type`,
    reading_or_english_remedial_course_name__c
    as `reading_or_english_remedial_course_name`,
    reading_or_english_remedial_course_statu__c
    as `reading_or_english_remedial_course_statu`,
    reading_or_english_remediation__c as `reading_or_english_remediation`,
    remedial_developmental_courses__c as `remedial_developmental_courses`,
    resources_support_system__c as `resources_support_system`,
    self_advocacy__c as `self_advocacy`,
    self_advocacy_resources__c as `self_advocacy_resources`,
    socio_emotional__c as `socio_emotional`,
    socio_emotional_category_score__c as `socio_emotional_category_score`,
    socio_emotional_color__c as `socio_emotional_color`,
    socio_emotional_notes__c as `socio_emotional_notes`,
    socio_emotional_score__c as `socio_emotional_score`,
    socio_emotional_wellness__c as `socio_emotional_wellness`,
    stable_housing_commuting_plan__c as `stable_housing_commuting_plan`,
    strong_academic_habits__c as `strong_academic_habits`,
    strong_study_habits__c as `strong_study_habits`,
    summer_plans__c as `summer_plans`,
    support_systems_and_obligations__c as `support_systems_and_obligations`,
    transfer_applications_complete__c as `transfer_applications_complete`,
    transfer_wishlist_and_application_plan__c
    as `transfer_wishlist_and_application_plan`,
    urgent_follow_up_required__c as `urgent_follow_up_required`,
    writing_remedial_course_name__c as `writing_remedial_course_name`,
    writing_remedial_course_status__c as `writing_remedial_course_status`,
    writing_remediation__c as `writing_remediation`,
    {{
        teamster_utils.date_to_fiscal_year(
            date_field="benchmark_date__c", start_month=7, year_source="start"
        )
    }} as academic_year,
from {{ source("kippadb", "college_persistence") }}
where not isdeleted
