assets:
  - query_config:
      type: schema
      value:
        table:
          name: rpt_parentsquare__schools
          schema: kipptaf_extracts
    file_config:
      stem: schools
      suffix: csv
  - query_config:
      type: schema
      value:
        table:
          name: rpt_parentsquare__students
          schema: kipptaf_extracts
    file_config:
      stem: students
      suffix: csv
  - query_config:
      type: schema
      value:
        table:
          name: rpt_parentsquare__parents
          schema: kipptaf_extracts
    file_config:
      stem: parents
      suffix: csv
  - query_config:
      type: schema
      value:
        table:
          name: rpt_parentsquare__emergency_contacts
          schema: kipptaf_extracts
    file_config:
      stem: emergency_contacts
      suffix: csv
  - query_config:
      type: schema
      value:
        table:
          name: rpt_parentsquare__staff
          schema: kipptaf_extracts
    file_config:
      stem: staff
      suffix: csv
  - query_config:
      type: schema
      value:
        table:
          name: rpt_parentsquare__sections
          schema: kipptaf_extracts
    file_config:
      stem: sections
      suffix: csv
  - query_config:
      type: schema
      value:
        table:
          name: rpt_parentsquare__rosters
          schema: kipptaf_extracts
    file_config:
      stem: rosters
      suffix: csv
