kippnewark:
  target: defer
  outputs:
    defer:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kippnewark
      method: oauth
      project: teamster-332318
      threads: 40
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kippnewark
      method: oauth
      project: teamster-332318
      threads: 40
    staging:
      type: bigquery
      schema: zz_stg_kippnewark
      method: oauth
      project: teamster-332318
      threads: 40
    prod:
      type: bigquery
      schema: kippnewark
      method: oauth
      project: teamster-332318
      threads: 40

kippcamden:
  target: defer
  outputs:
    defer:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kippcamden
      method: oauth
      project: teamster-332318
      threads: 40
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kippcamden
      method: oauth
      project: teamster-332318
      threads: 40
    staging:
      type: bigquery
      schema: zz_stg_kippcamden
      method: oauth
      project: teamster-332318
      threads: 40
    prod:
      type: bigquery
      schema: kippcamden
      method: oauth
      project: teamster-332318
      threads: 40

kippmiami:
  target: defer
  outputs:
    defer:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kippmiami
      method: oauth
      project: teamster-332318
      threads: 40
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kippmiami
      method: oauth
      project: teamster-332318
      threads: 40
    staging:
      type: bigquery
      schema: zz_stg_kippmiami
      method: oauth
      project: teamster-332318
      threads: 40
    prod:
      type: bigquery
      schema: kippmiami
      method: oauth
      project: teamster-332318
      threads: 40

kipppaterson:
  target: defer
  outputs:
    defer:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kipppaterson
      method: oauth
      project: teamster-332318
      threads: 40
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kipppaterson
      method: oauth
      project: teamster-332318
      threads: 40
    staging:
      type: bigquery
      schema: zz_stg_kipppaterson
      method: oauth
      project: teamster-332318
      threads: 40
    prod:
      type: bigquery
      schema: kipppaterson
      method: oauth
      project: teamster-332318
      threads: 40

kipptaf:
  target: defer
  outputs:
    defer:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kipptaf
      method: oauth
      project: teamster-332318
      threads: 40
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_kipptaf
      method: oauth
      project: teamster-332318
      threads: 40
    staging:
      type: bigquery
      schema: zz_stg_kipptaf
      method: oauth
      project: teamster-332318
      threads: 40
    prod:
      type: bigquery
      schema: kipptaf
      method: oauth
      project: teamster-332318
      threads: 40

deanslist:
  target: dev
  outputs:
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_deanslist
      method: oauth
      project: teamster-332318
      threads: 40

overgrad:
  target: dev
  outputs:
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_overgrad
      method: oauth
      project: teamster-332318
      threads: 40

powerschool:
  target: dev
  outputs:
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_powerschool
      method: oauth
      project: teamster-332318
      threads: 40

amplify:
  target: dev
  outputs:
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_amplify
      method: oauth
      project: teamster-332318
      threads: 40

finalsite:
  target: dev
  outputs:
    dev:
      type: bigquery
      schema: zz_{{ env_var('GITHUB_USER', 'dev') }}_finalsite
      method: oauth
      project: teamster-332318
      threads: 40

integration_tests:
  target: integration_tests
  outputs:
    integration_tests:
      type: bigquery
      schema: zz_dev
      threads: 40
      method: oauth
      project: teamster-332318
