sources:
  - name: smartrecruiters
    schema:
      "{%- if target.name in ['defer', 'dev'] -%}zz_{{ env_var('GITHUB_USER',
      'dev') }}_{%- elif target.name == 'staging' -%}zz_stg_{%- endif
      -%}kipptaf_smartrecruiters"
    tables:
      - name: src_smartrecruiters__applications
        external:
          location:
            "{{ var('cloud_storage_uri_base') }}/smartrecruiters/applications/*"
          options:
            connection_name: "{{ var('bigquery_external_connection_name') }}"
            metadata_cache_mode: MANUAL
            max_staleness: INTERVAL 7 DAY
            format: AVRO
            enable_logical_types: true
        config:
          meta:
            dagster:
              asset_key:
                - kipptaf
                - smartrecruiters
                - applications
      - name: src_smartrecruiters__applicants
        config:
          enabled: false
          meta:
            dagster:
              asset_key:
                - kipptaf
                - smartrecruiters
                - applicants
        external:
          location:
            "{{ var('cloud_storage_uri_base') }}/smartrecruiters/applicants/*"
          options:
            connection_name: "{{ var('bigquery_external_connection_name') }}"
            metadata_cache_mode: MANUAL
            max_staleness: INTERVAL 7 DAY
            format: AVRO
            enable_logical_types: true
