# https://www.mkdocs.org/user-guide/configuration/
# https://squidfunk.github.io/mkdocs-material/setup/

site_name: teamster
site_description: Data engineering platform for KIPP TEAM & Family Schools
repo_url: https://github.com/TEAMSchools/teamster
repo_name: TEAMSchools/teamster
edit_uri: edit/main/docs/
copyright: Copyright &copy; KIPP TEAM & Family Schools

theme:
  name: material
  favicon: images/horse-variant.svg
  icon:
    logo: material/horse-variant
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

nav:
  - Home: README.md
  - Getting Started: getting-started.md
  - Contributing:
      - Workflow: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Support: SUPPORT.md
      - Security: SECURITY.md
  - Reference:
      - Architecture: reference/architecture.md
      - dbt Conventions: reference/dbt-conventions.md
      - IO Managers: reference/io-managers.md
      - Adding an Integration: reference/adding-an-integration.md
      - Fiscal Year & Partitioning: reference/fiscal-year-partitioning.md
      - Automations: reference/automations.md
  - Guides:
      - Dagster: guides/dagster.md
      - dbt: guides/dbt.md
  - Troubleshooting:
      - Dagster: troubleshooting/dagster.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
