select
    df_employee_number as employee_number,
    salesforce_id,
    adp_associate_id as adp_associate_id_archive,
    first_name,
    last_name,
    common_name,
    preferred_last_name,
    legal_entity_name,
    primary_site,
    primary_on_site_department,
    primary_job,
    initcap(status) as status,
    status_reason,
    job_family,
    jobs_and_positions_flsa_status,
    paytype,
    payclass,
    annual_salary,
    is_manager,
    safe_cast(
        employee_s_manager_s_df_emp_number_id as int
    ) as manager_employee_number,
    ethnicity,
    gender,
    mobile_number,
    address,
    city,
    state,
    right(concat('0', safe_cast(postal_code as int)), 5) as postal_code,
    grades_taught,
    subjects_taught,
    safe_cast(birth_date as date) as birth_date,
    safe_cast(original_hire_date as date) as original_hire_date,
    safe_cast(rehire_date as date) as rehire_date,
    safe_cast(termination_date as date) as termination_date,
    safe_cast(position_effective_from_date as date) as position_effective_from_date,
    safe_cast(position_effective_to_date as date) as position_effective_to_date,
from {{ source("dayforce", "src_dayforce__employees") }}
