select
    assessmentid as `assessment_id`,
    completeddate as `completed_date`,
    completeddatelocal as `completed_date_local`,
    domainconfidencelevel as `domain_confidence_level`,
    domaingroup as `domain_group`,
    domainmasterylevel as `domain_mastery_level`,
    domainname as `domain_name`,
    domainpercentmastery as `domain_percent_mastery`,
    launchdate as `launch_date`,
    renaissanceclientid as `renaissance_client_id`,
    schoolyear as `school_year`,
    standardconfidencelevel as `standard_confidence_level`,
    standarddescription as `standard_description`,
    standardmasterylevel as `standard_mastery_level`,
    standardname as `standard_name`,
    standardpercentmastery as `standard_percent_mastery`,
    studentidentifier as `student_identifier`,
    studentrenaissanceid as `student_renaissance_id`,
    studentsourcedid as `student_sourced_id`,
    studentstateid as `student_state_id`,
    studentuserid as `student_user_id`,
    _dagster_partition_fiscal_year as `_dagster_partition_fiscal_year`,
    _dagster_partition_subject as `_dagster_partition_subject`,
from {{ source("renlearn", "src_renlearn__star_dashboard_standards") }}
