select
    _dagster_partition_fiscal_year,
    _dagster_partition_subject,
    assessmentid as assessment_id,
    completeddate as completed_date,
    completeddatelocal as completed_date_local,
    domaingroup as domain_group,
    domainname as domain_name,
    launchdate as launch_date,
    schoolyear as school_year,
    standardconfidencelevel as standard_confidence_level,
    standarddescription as standard_description,
    standardmasterylevel as standard_mastery_level,
    standardname as standard_name,
    studentrenaissanceid as student_renaissance_id,
    studentstateid as student_state_id,

    cast(renaissanceclientid as int) as renaissance_client_id,
    cast(standardpercentmastery as int) as standard_percent_mastery,
    cast(studentidentifier as int) as student_identifier,
    cast(studentsourcedid as int) as student_sourced_id,
    cast(studentuserid as int) as student_user_id,

    cast(cast(domainconfidencelevel as numeric) as int) as domain_confidence_level,
    cast(cast(domainmasterylevel as numeric) as int) as domain_mastery_level,
    cast(cast(domainpercentmastery as numeric) as int) as domain_percent_mastery,
from {{ source("renlearn", "src_renlearn__star_dashboard_standards") }}
