select
    _dagster_partition_fiscal_year,
    _dagster_partition_subject,
    `guid`,
    assess_status,
    cbtflag as cbt_flag,
    cid,
    classcode as class_code,
    cname,
    completeddate as completed_date,
    completeddatelocal as completed_date_local,
    dbmc,
    dbmp,
    disname as dis_name,
    email_s,
    email_t,
    enrolled,
    estorf as est_orf,
    ethhisp as eth_hisp,
    exempted_absence,
    exempted_failedprac as exempted_failed_prac,
    exempted_nonengspeaker as exempted_non_eng_speaker,
    exempted_wrongtest as exempted_wrong_test,
    extratime as extra_time,
    firstname as first_name,
    firstname_t as first_name_t,
    fleid,
    gender,
    gid_rid,
    gname,
    grade_e,
    grade_t,
    irl,
    lastname as last_name,
    lastname_t as last_name_t,
    launchdate as launch_date,
    lexile,
    lexilerange as lexile_range,
    litclassification as lit_classification,
    mi_t,
    mi,
    multirace as multi_race,
    paperaccommodations as paper_accommodations,
    passingscore_g3 as passing_score_g3,
    passingstatus_g3 as passing_status_g3,
    pnp_answer_eliminator,
    pnp_audio_options,
    pnp_calculator,
    pnp_color_scheme,
    pnp_contrast_overlay,
    pnp_enlarge_text,
    pnp_highlighter,
    pnp_line_reader,
    pnp_other_assistive_technology,
    pnp_screen_reader,
    pnp_unlimited_time,
    quantile,
    racea as race_a,
    raceb as race_b,
    racei as race_i,
    racep as race_p,
    racew as race_w,
    rbmc,
    reported,
    sbm,
    sbmc,
    sbmp,
    schbmc as sch_bmc,
    schbmp as sch_bmp,
    schname as sch_name,
    schoolyear as school_year,
    schoolyear_ed as school_year_ed,
    schoolyear_sd as school_year_sd,
    sgrade,
    sw_ed,
    sw_name,
    sw_sd,
    testingip as testing_ip,
    testingsite as testing_site,
    testname as test_name,
    tid_rid,
    zpd_lexile_lower,
    zpd_lexile_upper,
    zpd_lower,
    zpd_upper,

    cast(grade_p as numeric) as grade_p,
    cast(nce as numeric) as nce,
    cast(sem as numeric) as sem,
    cast(totalcorrect as numeric) as total_correct,
    cast(totalpossible as numeric) as total_possible,

    cast(assess_num as int) as assess_num,
    cast(attempts_g3 as int) as attempts_g3,
    cast(clientid as int) as client_id,
    cast(dbm_level as int) as dbm_level,
    cast(dbmc_nol as int) as dbmc_nol,
    cast(dbmc_pr_max as int) as dbmc_pr_max,
    cast(dbmc_pr_min as int) as dbmc_pr_min,
    cast(dis as int) as dis,
    cast(dob as int) as dob,
    cast(pr as int) as pr,
    cast(rbm_level as int) as rbm_level,
    cast(rbmc_nol as int) as rbmc_nol,
    cast(rbmc_pr_max as int) as rbmc_pr_max,
    cast(rbmc_pr_min as int) as rbmc_pr_min,
    cast(sbm_level as int) as sbm_level,
    cast(sbmc_nol as int) as sbmc_nol,
    cast(sbmc_ss_max as int) as sbmc_ss_max,
    cast(sbmc_ss_min as int) as sbmc_ss_min,
    cast(sch as int) as sch,
    cast(schbm_level as int) as sch_bm_level,
    cast(schbmc_nol as int) as sch_bmc_nol,
    cast(schbmc_pr_max as int) as sch_bmc_pr_max,
    cast(schbmc_pr_min as int) as sch_bmc_pr_min,
    cast(sid_sid as int) as sid_sid,
    cast(subdomain_ap as int) as sub_domain_ap,
    cast(subdomain_ap_skillset_a as int) as sub_domain_ap_skill_set_a,
    cast(subdomain_ap_skillset_b as int) as sub_domain_ap_skill_set_b,
    cast(subdomain_ap_skillset_c as int) as sub_domain_ap_skill_set_c,
    cast(subdomain_cw as int) as sub_domain_cw,
    cast(subdomain_cw_skillset_a as int) as sub_domain_cw_skill_set_a,
    cast(subdomain_cw_skillset_b as int) as sub_domain_cw_skill_set_b,
    cast(subdomain_cw_skillset_c as int) as sub_domain_cw_skill_set_c,
    cast(subdomain_cw_skillset_d as int) as sub_domain_cw_skill_set_d,
    cast(subdomain_en as int) as sub_domain_en,
    cast(subdomain_en_skillset_a as int) as sub_domain_en_skill_set_a,
    cast(subdomain_en_skillset_b as int) as sub_domain_en_skill_set_b,
    cast(subdomain_en_skillset_c as int) as sub_domain_en_skill_set_c,
    cast(subdomain_en_skillset_d as int) as sub_domain_en_skill_set_d,
    cast(subdomain_en_skillset_e as int) as sub_domain_en_skill_set_e,
    cast(subdomain_pa as int) as sub_domain_pa,
    cast(subdomain_pa_skillset_a as int) as sub_domain_pa_skill_set_a,
    cast(subdomain_pa_skillset_b as int) as sub_domain_pa_skill_set_b,
    cast(subdomain_pa_skillset_c as int) as sub_domain_pa_skill_set_c,
    cast(subdomain_pa_skillset_d as int) as sub_domain_pa_skill_set_d,
    cast(subdomain_pa_skillset_e as int) as sub_domain_pa_skill_set_e,
    cast(subdomain_pa_skillset_f as int) as sub_domain_pa_skill_set_f,
    cast(subdomain_pa_skillset_g as int) as sub_domain_pa_skill_set_g,
    cast(subdomain_pa_skillset_h as int) as sub_domain_pa_skill_set_h,
    cast(subdomain_pc as int) as sub_domain_pc,
    cast(subdomain_pc_skillset_a as int) as sub_domain_pc_skill_set_a,
    cast(subdomain_ph as int) as sub_domain_ph,
    cast(subdomain_ph_skillset_a as int) as sub_domain_ph_skill_set_a,
    cast(subdomain_ph_skillset_b as int) as sub_domain_ph_skill_set_b,
    cast(subdomain_ph_skillset_c as int) as sub_domain_ph_skill_set_c,
    cast(subdomain_ph_skillset_d as int) as sub_domain_ph_skill_set_d,
    cast(subdomain_ph_skillset_e as int) as sub_domain_ph_skill_set_e,
    cast(subdomain_ph_skillset_f as int) as sub_domain_ph_skill_set_f,
    cast(subdomain_ph_skillset_g as int) as sub_domain_ph_skill_set_g,
    cast(subdomain_ph_skillset_h as int) as sub_domain_ph_skill_set_h,
    cast(subdomain_ph_skillset_i as int) as sub_domain_ph_skill_set_i,
    cast(subdomain_ph_skillset_j as int) as sub_domain_ph_skill_set_j,
    cast(subdomain_ph_skillset_k as int) as sub_domain_ph_skill_set_k,
    cast(subdomain_ph_skillset_l as int) as sub_domain_ph_skill_set_l,
    cast(subdomain_sa as int) as sub_domain_sa,
    cast(subdomain_sa_skillset_a as int) as sub_domain_sa_skill_set_a,
    cast(subdomain_sa_skillset_b as int) as sub_domain_sa_skill_set_b,
    cast(subdomain_sa_skillset_c as int) as sub_domain_sa_skill_set_c,
    cast(subdomain_sa_skillset_d as int) as sub_domain_sa_skill_set_d,
    cast(subdomain_sc as int) as sub_domain_sc,
    cast(subdomain_sc_skillset_a as int) as sub_domain_sc_skill_set_a,
    cast(subdomain_vo as int) as sub_domain_vo,
    cast(subdomain_vo_skillset_a as int) as sub_domain_vo_skill_set_a,
    cast(subdomain_vo_skillset_b as int) as sub_domain_vo_skill_set_b,
    cast(subdomain_vo_skillset_c as int) as sub_domain_vo_skill_set_c,
    cast(subdomain_vs as int) as sub_domain_vs,
    cast(subdomain_vs_skillset_a as int) as sub_domain_vs_skill_set_a,
    cast(subdomain_vs_skillset_b as int) as sub_domain_vs_skill_set_b,
    cast(tid as int) as tid,
    cast(unifiedscore as int) as unified_score,

    cast(cast(currentsgp as numeric) as int) as current_sgp,
    cast(cast(sgp_ff as numeric) as int) as sgp_ff,
    cast(cast(sgp_fs as numeric) as int) as sgp_fs,
    cast(cast(sgp_fw as numeric) as int) as sgp_fw,
    cast(cast(sgp_sf as numeric) as int) as sgp_sf,
    cast(cast(sgp_ss as numeric) as int) as sgp_ss,
    cast(cast(sgp_ws as numeric) as int) as sgp_ws,
    cast(cast(totaltime as numeric) as int) as total_time,
from {{ source("renlearn", "src_renlearn__fast_star") }}
