select
    _dagster_partition_fiscal_year,
    _dagster_partition_subject,
    americanindianoralaskanative as american_indian_or_alaska_native,
    asian,
    audioused as audio_used,
    author,
    birthdate as birth_date,
    blackorafricanamerican as black_or_african_american,
    bookrating as book_rating,
    classcode as class_code,
    classrenaissanceid as class_renaissance_id,
    classsourcedid as class_sourced_id,
    contentlanguage as content_language,
    contenttitle as content_title,
    coursecode as course_code,
    coursename as course_name,
    courserenaissanceid as course_renaissance_id,
    coursesourcedid as course_sourced_id,
    currentgrade as current_grade,
    datequizcompleted as date_quiz_completed,
    datequizcompletedlocal as date_quiz_completed_local,
    districtidentifier as district_identifier,
    districtname as district_name,
    districtrenaissanceid as district_renaissance_id,
    districtsourcedid as district_sourced_id,
    enrollmentstatus as enrollment_status,
    fictionnonfiction as fiction_non_fiction,
    gender,
    groupid as group_id,
    grouporclassname as group_or_class_name,
    hispanicorlatino as hispanic_or_latino,
    interestlevel as interest_level,
    lexilemeasure as lexile_measure,
    multirace as multi_race,
    nativehawaiianorotherpacificislander as native_hawaiian_or_other_pacific_islander,
    quiztype as quiz_type,
    schoolname as school_name,
    schoolrenaissanceid as school_renaissance_id,
    schoolsourcedid as school_sourced_id,
    schoolyear as school_year,
    schoolyearenddate as school_year_end_date,
    schoolyearstartdate as school_year_start_date,
    studentemail as student_email,
    studentfirstname as student_first_name,
    studentlastname as student_last_name,
    studentmiddlename as student_middle_name,
    studentrenaissanceid as student_renaissance_id,
    studentstateid as student_state_id,
    teacheremail as teacher_email,
    teacherfirstname as teacher_first_name,
    teacheridentifier as teacher_identifier,
    teacherlastname as teacher_last_name,
    teachermiddlename as teacher_middle_name,
    teacherrenaissanceid as teacher_renaissance_id,
    teachersourcedid as teacher_sourced_id,
    teacheruserid as teacher_user_id,
    twi,
    white,

    cast(districtstateid as int) as district_state_id,
    cast(lexilelevel as int) as lexile_level,
    cast(questionscorrect as int) as questions_correct,
    cast(questionspresented as int) as questions_presented,
    cast(quizdeleted as int) as quiz_deleted,
    cast(quiznumber as int) as quiz_number,
    cast(renaissanceclientid as int) as renaissance_client_id,
    cast(schoolidentifier as int) as school_identifier,
    cast(schoolstateid as int) as school_state_id,
    cast(studentidentifier as int) as student_identifier,
    cast(studentsourcedid as int) as student_sourced_id,
    cast(studentuserid as int) as student_user_id,
    cast(teacherstateid as int) as teacher_state_id,
    cast(wordcount as int) as word_count,

    cast(booklevel as numeric) as book_level,
    cast(percentcorrect as numeric) as percent_correct,
    cast(pointsearned as numeric) as points_earned,
    cast(pointspossible as numeric) as points_possible,

    cast(passed as boolean) as passed,
from {{ source("renlearn", "src_renlearn__accelerated_reader") }}
