select
    _dagster_partition_fiscal_year,
    _dagster_partition_subject,

    `guid`,
    assess_num,
    assess_status,
    attempts_g3,
    cbtflag as cbt_flag,
    cid,
    classcode as class_code,
    clientid as client_id,
    cname,
    completeddate as completed_date,
    completeddatelocal as completed_date_local,
    currentsgp as current_sgp,
    dbm_level,
    dbmc_nol,
    dbmc_pr_max,
    dbmc_pr_min,
    dbmc,
    dbmp,
    dis,
    disname as dis_name,
    dob,
    email_s,
    email_t,
    enrolled,
    estorf as est_orf,
    ethhisp as eth_hisp,
    exempted_absence,
    exempted_failedprac as exempted_failed_prac,
    exempted_nonengspeaker as exempted_non_eng_speaker,
    exempted_wrongtest as exempted_wrong_test,
    extratime as extra_time,
    firstname as first_name,
    firstname_t as first_name_t,
    fleid,
    gender,
    gid_rid,
    gname,
    grade_e,
    grade_p,
    grade_t,
    irl,
    lastname as last_name,
    lastname_t as last_name_t,
    launchdate as launch_date,
    lexilerange as lexile_range,
    litclassification as lit_classification,
    mi_t,
    mi,
    multirace as multi_race,
    nce,
    paperaccommodations as paper_accommodations,
    passingscore_g3 as passing_score_g3,
    passingstatus_g3 as passing_status_g3,
    pnp_answer_eliminator,
    pnp_audio_options,
    pnp_calculator,
    pnp_color_scheme,
    pnp_contrast_overlay,
    pnp_enlarge_text,
    pnp_highlighter,
    pnp_line_reader,
    pnp_other_assistive_technology,
    pnp_screen_reader,
    pnp_unlimited_time,
    pr,
    quantile,
    racea as race_a,
    raceb as race_b,
    racei as race_i,
    racep as race_p,
    racew as race_w,
    rbm_level,
    rbmc_nol,
    rbmc_pr_max,
    rbmc_pr_min,
    rbmc,
    reported,
    sbm_level,
    sbm,
    sbmc_nol,
    sbmc_ss_max,
    sbmc_ss_min,
    sbmc,
    sbmp,
    sch,
    schbm_level as sch_bm_level,
    schbmc as sch_bmc,
    schbmc_nol as sch_bmc_nol,
    schbmc_pr_max as sch_bmc_pr_max,
    schbmc_pr_min as sch_bmc_pr_min,
    schbmp as sch_bmp,
    schname as sch_name,
    schoolyear as school_year,
    schoolyear_ed as school_year_ed,
    schoolyear_sd as school_year_sd,
    sem,
    sgp_ff,
    sgp_fs,
    sgp_fw,
    sgp_sf,
    sgp_ss,
    sgp_ws,
    sid_sid,
    sw_ed,
    sw_name,
    sw_sd,
    testingip as testing_ip,
    testingsite as testing_site,
    testname as test_name,
    tid_rid,
    tid,
    totalcorrect as total_correct,
    totalpossible as total_possible,
    totaltime as total_time,
    unifiedscore as unified_score,
    zpd_lexile_lower,
    zpd_lexile_upper,
    zpd_lower,
    zpd_upper,

    subdomain_ap as sub_domain_ap,
    subdomain_ap_skillset_a as sub_domain_ap_skill_set_a,
    subdomain_ap_skillset_b as sub_domain_ap_skill_set_b,
    subdomain_ap_skillset_c as sub_domain_ap_skill_set_c,
    subdomain_cw as sub_domain_cw,
    subdomain_cw_skillset_a as sub_domain_cw_skill_set_a,
    subdomain_cw_skillset_b as sub_domain_cw_skill_set_b,
    subdomain_cw_skillset_c as sub_domain_cw_skill_set_c,
    subdomain_cw_skillset_d as sub_domain_cw_skill_set_d,
    subdomain_en as sub_domain_en,
    subdomain_en_skillset_a as sub_domain_en_skill_set_a,
    subdomain_en_skillset_b as sub_domain_en_skill_set_b,
    subdomain_en_skillset_c as sub_domain_en_skill_set_c,
    subdomain_en_skillset_d as sub_domain_en_skill_set_d,
    subdomain_en_skillset_e as sub_domain_en_skill_set_e,
    subdomain_pa as sub_domain_pa,
    subdomain_pa_skillset_a as sub_domain_pa_skill_set_a,
    subdomain_pa_skillset_b as sub_domain_pa_skill_set_b,
    subdomain_pa_skillset_c as sub_domain_pa_skill_set_c,
    subdomain_pa_skillset_d as sub_domain_pa_skill_set_d,
    subdomain_pa_skillset_e as sub_domain_pa_skill_set_e,
    subdomain_pa_skillset_f as sub_domain_pa_skill_set_f,
    subdomain_pa_skillset_g as sub_domain_pa_skill_set_g,
    subdomain_pa_skillset_h as sub_domain_pa_skill_set_h,
    subdomain_pc as sub_domain_pc,
    subdomain_pc_skillset_a as sub_domain_pc_skill_set_a,
    subdomain_ph as sub_domain_ph,
    subdomain_ph_skillset_a as sub_domain_ph_skill_set_a,
    subdomain_ph_skillset_b as sub_domain_ph_skill_set_b,
    subdomain_ph_skillset_c as sub_domain_ph_skill_set_c,
    subdomain_ph_skillset_d as sub_domain_ph_skill_set_d,
    subdomain_ph_skillset_e as sub_domain_ph_skill_set_e,
    subdomain_ph_skillset_f as sub_domain_ph_skill_set_f,
    subdomain_ph_skillset_g as sub_domain_ph_skill_set_g,
    subdomain_ph_skillset_h as sub_domain_ph_skill_set_h,
    subdomain_ph_skillset_i as sub_domain_ph_skill_set_i,
    subdomain_ph_skillset_j as sub_domain_ph_skill_set_j,
    subdomain_ph_skillset_k as sub_domain_ph_skill_set_k,
    subdomain_ph_skillset_l as sub_domain_ph_skill_set_l,
    subdomain_sa as sub_domain_sa,
    subdomain_sa_skillset_a as sub_domain_sa_skill_set_a,
    subdomain_sa_skillset_b as sub_domain_sa_skill_set_b,
    subdomain_sa_skillset_c as sub_domain_sa_skill_set_c,
    subdomain_sa_skillset_d as sub_domain_sa_skill_set_d,
    subdomain_sc as sub_domain_sc,
    subdomain_sc_skillset_a as sub_domain_sc_skill_set_a,
    subdomain_vo as sub_domain_vo,
    subdomain_vo_skillset_a as sub_domain_vo_skill_set_a,
    subdomain_vo_skillset_b as sub_domain_vo_skill_set_b,
    subdomain_vo_skillset_c as sub_domain_vo_skill_set_c,
    subdomain_vs as sub_domain_vs,
    subdomain_vs_skillset_a as sub_domain_vs_skill_set_a,
    subdomain_vs_skillset_b as sub_domain_vs_skill_set_b,

    coalesce(lexile.string_value, cast(lexile.long_value as string)) as lexile,
    coalesce(sgrade.string_value, cast(sgrade.long_value as string)) as sgrade,
from {{ source("renlearn", "src_renlearn__fast_star") }}
