select
    _dagster_partition_fiscal_year,
    _dagster_partition_subject,
    assessmentid as assessment_id,
    completeddate as completed_date,
    completeddatelocal as completed_date_local,
    domainname as domain_name,
    familyname as family_name,
    launchdate as launch_date,
    schoolyear as school_year,
    skillareaname as skill_area_name,
    studentrenaissanceid as student_renaissance_id,
    studentstateid as student_state_id,

    cast(domainscore as int) as domain_score,
    cast(renaissanceclientid as int) as renaissance_client_id,
    cast(skillareamasteryscore as int) as skill_area_mastery_score,
    cast(studentidentifier as int) as student_identifier,
    cast(studentsourcedid as int) as student_sourced_id,
    cast(studentuserid as int) as student_user_id,
from {{ source("renlearn", "src_renlearn__star_skill_area") }}
