"""Stamp out MOY/EOY (or any other season) rows for
`stg_google_sheets__dibels_expected_assessments` from an existing season's rows.

Within one academic year, a benchmark season's rows (BOY/MOY/EOY) differ from
each other ONLY in Admin_Season, Test_Code, and Month_Round -- every other
column (Region, Grade, Measure_Standard, ...) is identical, because the same
measures get tested every round. So a new season is generated by copying the
source season's rows and overwriting those three fields, not by re-deriving
anything.

This reads the LIVE sheet via the Sheets API (read-only ADC) rather than
BigQuery, to avoid any type-normalization BigQuery's external table might
apply (e.g. Grade as int 0 vs the sheet's literal string "0") -- the output
must paste back in byte-identical to what the sheet already has.

Usage:
    uv run --with google-api-python-client --with google-auth python3 \
        .claude/skills/dibels-dashboard/scripts/roll_forward_expected_assessments_season.py \
        --spreadsheet-id 15u_nUWcJY5-3V2xT0ZvICkQ1nrpGuMI2LAy5UMmUbNs \
        --tab "Expected Assessments" \
        --academic-year 2026 \
        --source-season BOY --source-test-code LIT1 \
        --target MOY:LIT2:January \
        --target EOY:LIT3:May \
        --out out.tsv

Output has no header -- paste directly below the sheet's last row. Does not
write to the sheet itself; the skill's Step 4 is a human paste, on purpose --
this is a shared, actively-edited spreadsheet, and appending via API without
a second set of eyes on the diff is not worth the risk it saves.
"""

import argparse

import google.auth
from googleapiclient.discovery import build

ADMIN_SEASON_COL = 8  # 0-indexed: Admin_Season
TEST_CODE_COL = 7  # Test_Code
MONTH_ROUND_COL = 9  # Month_Round
ACADEMIC_YEAR_COL = 0  # Academic_Year


def parse_target(spec: str) -> tuple[str, str, str]:
    season, test_code, month_round = spec.split(":")
    return season, test_code, month_round


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spreadsheet-id", required=True)
    parser.add_argument("--tab", required=True)
    parser.add_argument("--academic-year", required=True)
    parser.add_argument("--source-season", required=True)
    parser.add_argument("--source-test-code", required=True)
    parser.add_argument(
        "--target",
        action="append",
        required=True,
        help="SEASON:TEST_CODE:MONTH_ROUND, repeatable",
    )
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    targets = [parse_target(t) for t in args.target]

    creds, _ = google.auth.default(
        scopes=["https://www.googleapis.com/auth/spreadsheets.readonly"]
    )
    svc = build("sheets", "v4", credentials=creds)
    res = (
        svc.spreadsheets()
        .values()
        .get(spreadsheetId=args.spreadsheet_id, range=f"'{args.tab}'!A1:P10000")
        .execute()
    )
    rows = res.get("values", [])[1:]  # drop header

    source_rows = [
        r
        for r in rows
        if r[ACADEMIC_YEAR_COL] == args.academic_year
        and r[ADMIN_SEASON_COL] == args.source_season
        and r[TEST_CODE_COL] == args.source_test_code
    ]

    if not source_rows:
        raise SystemExit(
            f"No rows found for academic_year={args.academic_year} "
            f"admin_season={args.source_season} test_code={args.source_test_code} "
            "-- check the filters, not just the output."
        )

    out_rows = []
    for season, test_code, month_round in targets:
        for row in source_rows:
            new_row = list(row)
            new_row[TEST_CODE_COL] = test_code
            new_row[ADMIN_SEASON_COL] = season
            new_row[MONTH_ROUND_COL] = month_round
            out_rows.append(new_row)

    with open(args.out, "w") as f:
        for row in out_rows:
            f.write("\t".join(row) + "\n")

    print(f"source rows matched: {len(source_rows)}")
    for season, test_code, _ in targets:
        print(f"  -> generated {len(source_rows)} rows for {season} ({test_code})")
    print(f"total rows written: {len(out_rows)} -> {args.out}")


if __name__ == "__main__":
    main()
