select
    examiner_smid,
    parcc_braille_paper,
    parcc_ela_test_code,
    parcc_ell_paper_accom,
    parcc_examiner_smid_ela,
    parcc_examiner_smid_math,
    parcc_exempt_from_passing,
    parcc_iep_paper_accom,
    parcc_large_print_paper,
    parcc_math_test_code,
    parcc_reader_signer_for_paper,
    parcc_retest,
    parcc_sec504_paper_accom,
    parcc_session_location_ela,
    parcc_session_location_math,
    parcc_test_format,
    parcc_testing_site_county,
    parcc_testing_site_district,
    parcc_testing_site_school,
    parcc_translation_math_paper,
    whocreated,
    whencreated,
    whomodified,
    whenmodified,
    asmt_alt_rep_paper,
    asmt_alternate_location,
    asmt_answer_masking,
    asmt_answers_recorded_paper,
    asmt_asl_video,
    asmt_braille_response,
    asmt_braille_tactile_paper,
    asmt_closed_caption_ela,
    asmt_color_contrast,
    asmt_dictionary,
    asmt_directions_aloud,
    asmt_directions_clarified,
    asmt_emergency_accommodation,
    asmt_extended_time,
    asmt_frequent_breaks,
    asmt_human_signer,
    asmt_humanreader_signer,
    asmt_math_response,
    asmt_math_response_el,
    asmt_monitor_response,
    asmt_non_screen_reader,
    asmt_read_aloud,
    asmt_refresh_braille_ela,
    asmt_screen_reader,
    asmt_selected_response_ela,
    asmt_small_group,
    asmt_special_equip,
    asmt_specified_area,
    asmt_text_to_speech,
    asmt_time_of_day,
    asmt_unique_accommodation,
    asmt_word_prediction,
    gifted_and_talented,
    parcc_class_name_override_ela,
    parcc_class_name_override_math,
    parcc_constructed_response_ela,
    parcc_math_tools,
    parcc_staff_smid_override_ela,
    parcc_staff_smid_override_math,
    parcc_student_identifier,
    state_lep_status,
    access_test_format_override,
    access_tier_paper_tests,
    alternate_access,
    asmt_ac,
    asmt_at,
    asmt_bw,
    asmt_em,
    asmt_es,
    asmt_et,
    asmt_ih,
    asmt_length_in_ell,
    asmt_lh,
    asmt_mc,
    asmt_ns,
    asmt_ra,
    asmt_rd,
    asmt_ri,
    asmt_rl,
    asmt_sd,
    asmt_wd,
    calculation_device_math_tools,
    math_state_assessment_name,
    state_assessment_name,
    state_ell_status,
    parcc_text_to_speech,
    counseling_services_yn,
    determined_ineligible_yn,
    early_intervention_yn,
    iep_level,
    initial_process_delay_reason,
    nonpublic,
    occupational_therapy_serv_yn,
    other_related_services_yn,
    parent_consent_obtain_code,
    physical_therapy_services_yn,
    special_education_placement,
    specialed_classification,
    speech_lang_theapy_services_yn,
    time_in_regular_program,
    block_schedule_session_ela,
    block_schedule_session_math,
    parcc_text_to_speech_math,
    asmt_extended_time_math,
    pid_testformat,
    pid_brailletest_yn,
    pid_contentareatutoring_yn,
    pid_contentbasedesl_yn,
    pid_developbilingual_yn,
    pid_heritagelanguage_yn,
    pid_inclusionarysupport_yn,
    pid_largeprint_yn,
    pid_noadditionalservices_yn,
    pid_notapplicable_yn,
    pid_parentalrefusal_yn,
    pid_pullout_yn,
    pid_pulloutesl_yn,
    pid_scribedresponse_yn,
    pid_selfcontained_yn,
    pid_shelteredenginstruct_yn,
    pid_structengimmersion_yn,
    pid_transbilingual_yn,
    pid_twowayimmersion_yn,
    ctepostsecondaryinstitution,
    cteprogramofstudy_yn,
    cteprogramstatus,
    ctesingleparentstatus_yn,
    ctetestskillassesment,
    primarycipcode,
    access_accountablecounty,
    access_accountabledistrict,
    access_accountableschool,
    access_testingsitecounty,
    access_testingsitedistrict,
    access_testingsiteschool,
    districttimeless1year_yn,
    pid_sendingcds,
    schooltimeless1year_yn,
    school_disabled,
    special_status,
    pid_title3status,
    ask_specialcodesa,
    ask_specialcodesb,
    ask_specialcodesc,
    ask_specialcodesd,
    district_studentid,
    examinersmid1,
    examinersmid2,
    examinersmid3,
    examinersmid4,
    examinersmid5,
    leadlevel,
    native_language,
    pid_apatestingcds,
    pid_audioamplification,
    pid_classroom,
    pid_computerassisted,
    pid_lowvisionaids,
    pid_modifiedtestdirections,
    pid_nativelang,
    pid_otherapproved,
    pid_presentationformat,
    pid_settingformat,
    pid_timingscheduling,
    spedtier,
    supplementaleduserv,
    programtypecode,
    cityofbirth,
    countryofbirth,
    countycodeattending,
    countycodereceiving,
    countycoderesident,
    districtcodeattending,
    districtcodereceiving,
    districtcoderesident,
    generationcodesuffix,
    gradelevelcode,
    immigrantstatus_yn,
    residentmunicipalcode,
    schoolcodeattending,
    schoolcodereceiving,
    schoolcoderesident,
    shared_time_code,
    stateofbirth,
    tuition_code,
    alternativeeducationprogram_yn,
    eighthtechlit,
    healthinsprovider,
    healthinsstatus_yn,
    home_language,
    home_language_name,
    titleilanguage_yn,
    titleimath_yn,
    titleiscience_yn,
    pid_supplementaleduserv,
    pid_timeinlep2,
    charter_assigned_school,
    charter_school_loc,
    charter_school_name,
    ctetestdevelopercode,
    ctetestname,
    nces_course_id,
    nces_subject_area,
    graduation_pathway_ela,
    graduation_pathway_math,
    former_iep,
    liep_classification,
    liep_data,
    liep_refusal,
    secondary_disability,
    sla_class_name_override,
    sla_retest,
    sla_session_loc_override,
    sla_test_code,
    sla_test_format,
    sla_testing_site_county,
    sla_testing_site_district,
    sla_testing_site_school,
    student_type,
    sla_accountable_site_county,
    sla_accountable_site_district,
    sla_accountable_site_school,
    sla_braille_response,
    sla_braille_tactile_paper,
    sla_color_contrast,
    sla_constructed_response,
    sla_directions_aloud,
    sla_emergency_accommodation,
    sla_examiner_smid,
    sla_extended_time,
    sla_humanreader_signer,
    sla_presentation,
    sla_science_response_el,
    sla_selected_response,
    sla_spanish_trans,
    sla_staffoverride_smid,
    sla_text_to_speech,
    family_care_release_yn,
    indistrictplacement,
    liep_type,
    stureporting_name,
    biliterate_yn,
    worldlang_assessed1,
    worldlang_assessed1_name,
    worldlang_assessed2,
    worldlang_assessed2_name,
    worldlang_assessed3,
    worldlang_assessed3_name,
    worldlang_assessed4,
    worldlang_assessed4_name,
    worldlang_assessed5,
    worldlang_assessed5_name,
    worldlang_assessment1,
    worldlang_assessment2,
    worldlang_assessment3,
    worldlang_assessment4,
    worldlang_assessment5,
    assessmt_ms_accomm_resp,
    birthplace_refusal,
    ctewblearning,
    firsthsmathassessment_yn,
    remotelearninghelpline_yn,
    speassessmentparticipant_yn,
    speassignmentsubmissions_yn,
    specoachingorcheckin_yn,
    speechtotextwordprediction,
    speelectroniccomm_yn,
    speonlinelearningplatforms,
    speother_yn,
    spesynchonlineclass_yn,
    studentslearningmodel,
    bridge_year,
    federalhsmathtestingreq,
    iepgradcourserequirement,
    iepgraduationattendance,
    typeofearnedcollegecredits,
    typeofworkbasedlearning,
    liep_languageofinstruction,
    reportedsharedvoc_yn,
    science_test_name,
    deafhardofhearing_yn,
    district_status_override,
    proofofage,
    homelessinstrucservice,
    homelesssupportservice,
    lunchstatusoverride,
    mddisablingcondition1,
    mddisablingcondition2,
    mddisablingcondition3,
    mddisablingcondition4,
    mddisablingcondition5,
    titleiindicator,
    eligible_for_liep,
    home_language2,
    home_language3,
    home_language4,
    home_language5,
    home_language_name2,
    home_language_name3,
    home_language_name4,
    home_language_name5,
    sld_basic_reading_yn,
    sld_listen_comp_yn,
    sld_math_cal_yn,
    sld_math_prob_solve_yn,
    sld_oral_expresn_yn,
    sld_read_fluency_yn,
    sld_reading_comp_yn,
    sld_writn_exprsn_yn,
    embedded_co_writer_ela,
    presentation,

    cast(studentsdcid as int) as studentsdcid,
    cast(asmt_first_enroll_in_us_school as date) as asmt_first_enroll_in_us_school,
    cast(annual_iep_review_meeting_date as date) as annual_iep_review_meeting_date,
    cast(eligibility_determ_date as date) as eligibility_determ_date,
    cast(iep_begin_date as date) as iep_begin_date,
    cast(iep_end_date as date) as iep_end_date,
    cast(initial_iep_meeting_date as date) as initial_iep_meeting_date,
    cast(parent_consent_intial_iep_date as date) as parent_consent_intial_iep_date,
    cast(parental_consent_eval_date as date) as parental_consent_eval_date,
    cast(reevaluation_date as date) as reevaluation_date,
    cast(referral_date as date) as referral_date,
    cast(datelastleadtest as date) as datelastleadtest,
    cast(datelastmedexam as date) as datelastmedexam,
    cast(dateofpolioimmun as date) as dateofpolioimmun,
    cast(firstentrydateintoausschool as date) as firstentrydateintoausschool,
    cast(lepbegindate as date) as lepbegindate,
    cast(lependdate as date) as lependdate,
    cast(charter_date as date) as charter_date,
    cast(withdrawal_date as date) as withdrawal_date,
    cast(sid_entrydate as date) as sid_entrydate,
    cast(sid_exitdate as date) as sid_exitdate,
    cast(declassificationspeddate as date) as declassificationspeddate,
    cast(elp_screener_date as date) as elp_screener_date,
    cast(lepbegindate2 as date) as lepbegindate2,
    cast(liep_parent_refusal_date as date) as liep_parent_refusal_date,
    cast(liependdate2 as date) as liependdate2,
    cast(lep_completion_date_refused as int) as lep_completion_date_refused,
    cast(military_connected_indicator as int) as military_connected_indicator,
    cast(asmt_exclude_ela as int) as asmt_exclude_ela,
    cast(asmt_exclude_math as int) as asmt_exclude_math,
    cast(iep_exemptpassinglal_tf as int) as iep_exemptpassinglal_tf,
    cast(iep_exemptpassingmath_tf as int) as iep_exemptpassingmath_tf,
    cast(iep_exempttakinglal_tf as int) as iep_exempttakinglal_tf,
    cast(iep_exempttakingmath_tf as int) as iep_exempttakingmath_tf,
    cast(pid_title1langartslit_tf as int) as pid_title1langartslit_tf,
    cast(pid_title1math_tf as int) as pid_title1math_tf,
    cast(ctecollegecredits as int) as ctecollegecredits,
    cast(pid_504_tf as int) as pid_504_tf,
    cast(pid_accommodations_a_tf as int) as pid_accommodations_a_tf,
    cast(pid_accommodations_b_tf as int) as pid_accommodations_b_tf,
    cast(pid_accommodations_c_tf as int) as pid_accommodations_c_tf,
    cast(pid_accommodations_d_tf as int) as pid_accommodations_d_tf,
    cast(pid_apascience_tf as int) as pid_apascience_tf,
    cast(adulths_nb_credits as numeric) as adulths_nb_credits,
    cast(pid_lepexemptlal_tf as int) as pid_lepexemptlal_tf,
    cast(pid_apalangartsliteracy_tf as int) as pid_apalangartsliteracy_tf,
    cast(pid_apamath_tf as int) as pid_apamath_tf,
    cast(pid_madetape_tf as int) as pid_madetape_tf,
    cast(pid_outofdistplacement_tf as int) as pid_outofdistplacement_tf,
    cast(pid_outresidenceplacement_tf as int) as pid_outresidenceplacement_tf,
    cast(pid_shortsegmenttestadmin_tf as int) as pid_shortsegmenttestadmin_tf,
    cast(pid_title1science_tf as int) as pid_title1science_tf,
    cast(title1_status_tf as int) as title1_status_tf,
    cast(tiv_serv_aide_tf as int) as tiv_serv_aide_tf,
    cast(tiv_serv_assist_tf as int) as tiv_serv_assist_tf,
    cast(tiv_serv_extyear_tf as int) as tiv_serv_extyear_tf,
    cast(tiv_serv_ind_instr_tf as int) as tiv_serv_ind_instr_tf,
    cast(tiv_serv_indnursing_tf as int) as tiv_serv_indnursing_tf,
    cast(tiv_serv_intensive_tf as int) as tiv_serv_intensive_tf,
    cast(tiv_serv_interpreter_tf as int) as tiv_serv_interpreter_tf,
    cast(tiv_serv_pupil_tf as int) as tiv_serv_pupil_tf,
    cast(tiv_serv_resplacement_tf as int) as tiv_serv_resplacement_tf,
    cast(lep_tf as int) as lep_tf,
    cast(retained_tf as int) as retained_tf,
    cast(cumdaysinmembershipaddto_tf as int) as cumdaysinmembershipaddto_tf,
    cast(cumdayspresentaddto_tf as int) as cumdayspresentaddto_tf,
    cast(cumdaystowardtruancyaddto_tf as int) as cumdaystowardtruancyaddto_tf,
    cast(cumulativedaysinmembership as numeric) as cumulativedaysinmembership,
    cast(cumulativedayspresent as numeric) as cumulativedayspresent,
    cast(cumulativedaystowardtruancy as numeric) as cumulativedaystowardtruancy,
    cast(homelessprimarynighttimeres as int) as homelessprimarynighttimeres,
    cast(migrant_tf as int) as migrant_tf,
    cast(includeinctereport_tf as int) as includeinctereport_tf,
    cast(includeinnjsmart_tf as int) as includeinnjsmart_tf,
    cast(includeinstucourse_tf as int) as includeinstucourse_tf,
    cast(eoc_title1biology_tf as int) as eoc_title1biology_tf,
    cast(iep_exemptpassingbiology_tf as int) as iep_exemptpassingbiology_tf,
    cast(iep_exempttakingbiology_tf as int) as iep_exempttakingbiology_tf,
    cast(sla_alt_rep_paper as int) as sla_alt_rep_paper,
    cast(sla_alternate_location as int) as sla_alternate_location,
    cast(sla_answer_masking as int) as sla_answer_masking,
    cast(sla_answers_recorded_paper as int) as sla_answers_recorded_paper,
    cast(sla_asl_video as int) as sla_asl_video,
    cast(sla_closed_caption as int) as sla_closed_caption,
    cast(sla_dictionary as int) as sla_dictionary,
    cast(sla_directions_clarified as int) as sla_directions_clarified,
    cast(sla_exclude_tf as int) as sla_exclude_tf,
    cast(sla_frequent_breaks as int) as sla_frequent_breaks,
    cast(sla_human_signer as int) as sla_human_signer,
    cast(sla_large_print_paper as int) as sla_large_print_paper,
    cast(sla_monitor_response as int) as sla_monitor_response,
    cast(sla_non_screen_reader as int) as sla_non_screen_reader,
    cast(sla_read_aloud as int) as sla_read_aloud,
    cast(sla_refresh_braille as int) as sla_refresh_braille,
    cast(sla_screen_reader as int) as sla_screen_reader,
    cast(sla_small_group as int) as sla_small_group,
    cast(sla_special_equip as int) as sla_special_equip,
    cast(sla_specified_area as int) as sla_specified_area,
    cast(sla_time_of_day as int) as sla_time_of_day,
    cast(sla_unique_accommodation as int) as sla_unique_accommodation,
    cast(sla_word_prediction as int) as sla_word_prediction,
    cast(includeinassareport_tf as int) as includeinassareport_tf,
    cast(caresactfunds as int) as caresactfunds,
    cast(deviceowner as int) as deviceowner,
    cast(devicetype as int) as devicetype,
    cast(internetconnectivity as int) as internetconnectivity,
    cast(learningenvironment as int) as learningenvironment,
    cast(remotedaysmembership as numeric) as remotedaysmembership,
    cast(remotedayspresent as numeric) as remotedayspresent,
    cast(remotepercentageofday as int) as remotepercentageofday,
    cast(cumulativedaysabsent as numeric) as cumulativedaysabsent,
    cast(cumulativestateabs as int) as cumulativestateabs,
    cast(daysopen as int) as daysopen,
    cast(remotedaysabsent as numeric) as remotedaysabsent,
    cast(languageacquisition as int) as languageacquisition,
    cast(collegecreditsearned as int) as collegecreditsearned,
    cast(cteworkbasedlearning as int) as cteworkbasedlearning,
    cast(sid_excludeenrollment as int) as sid_excludeenrollment,
from {{ source("powerschool_dlt", "s_nj_stu_x") }}
