select
    course_number,
    course_name,
    code,
    prerequisitesvalue,
    corequisites,
    powerlink,
    powerlinkspan,
    reggradelevels,
    regteachers,
    regcoursegroup,
    multiterm,
    termsoffered,
    credittype,
    sched_department,
    sched_coursesubjectareacode,
    sched_fullcatalogdescription,
    sched_coursepkgcontents,
    sched_scheduletypecode,
    sched_validstartperiods,
    sched_validdaycombinations,
    validextradaycombinations,
    sched_extradayscheduletypecode,
    sched_facilities,
    sched_loadtype,
    sched_globalsubstitution1,
    sched_globalsubstitution2,
    sched_globalsubstitution3,
    sched_balancepriority,
    psguid,
    ip_address,
    whomodifiedtype,
    transaction_date,

    cast(dcid as int) as dcid,
    cast(id as int) as id,
    cast(credit_hours as float64) as credit_hours,
    cast(add_to_gpa as float64) as add_to_gpa,
    cast(schoolid as int) as schoolid,
    cast(regavailable as int) as regavailable,
    cast(targetclasssize as int) as targetclasssize,
    cast(maxclasssize as int) as maxclasssize,
    cast(sectionstooffer as int) as sectionstooffer,
    cast(schoolgroup as int) as schoolgroup,
    cast(vocational as int) as vocational,
    cast(`status` as int) as `status`,
    cast(crhrweight as float64) as crhrweight,
    cast(sched_year as int) as sched_year,
    cast(sched_coursepackage as int) as sched_coursepackage,
    cast(sched_scheduled as int) as sched_scheduled,
    cast(sched_sectionsoffered as int) as sched_sectionsoffered,
    cast(sched_teachercount as int) as sched_teachercount,
    cast(sched_periodspermeeting as int) as sched_periodspermeeting,
    cast(sched_frequency as int) as sched_frequency,
    cast(sched_maximumperiodsperday as int) as sched_maximumperiodsperday,
    cast(sched_minimumperiodsperday as int) as sched_minimumperiodsperday,
    cast(sched_maximumdayspercycle as int) as sched_maximumdayspercycle,
    cast(sched_minimumdayspercycle as int) as sched_minimumdayspercycle,
    cast(sched_consecutiveperiods as int) as sched_consecutiveperiods,
    cast(sched_blockstart as int) as sched_blockstart,
    cast(sched_lengthinnumberofterms as int) as sched_lengthinnumberofterms,
    cast(sched_consecutiveterms as int) as sched_consecutiveterms,
    cast(sched_balanceterms as int) as sched_balanceterms,
    cast(sched_maximumenrollment as int) as sched_maximumenrollment,
    cast(sched_concurrentflag as int) as sched_concurrentflag,
    cast(sched_multiplerooms as int) as sched_multiplerooms,
    cast(sched_labflag as int) as sched_labflag,
    cast(sched_labfrequency as int) as sched_labfrequency,
    cast(sched_labperiodspermeeting as int) as sched_labperiodspermeeting,
    cast(sched_repeatsallowed as int) as sched_repeatsallowed,
    cast(sched_loadpriority as int) as sched_loadpriority,
    cast(sched_substitutionallowed as int) as sched_substitutionallowed,
    cast(sched_usepreestablishedteams as int) as sched_usepreestablishedteams,
    cast(sched_closesectionaftermax as int) as sched_closesectionaftermax,
    cast(sched_usesectiontypes as int) as sched_usesectiontypes,
    cast(sched_periodspercycle as int) as sched_periodspercycle,
    cast(gradescaleid as int) as gradescaleid,
    cast(gpa_addedvalue as float64) as gpa_addedvalue,
    cast(excludefromgpa as int) as excludefromgpa,
    cast(excludefromclassrank as int) as excludefromclassrank,
    cast(excludefromhonorroll as int) as excludefromhonorroll,
    cast(sched_lunchcourse as int) as sched_lunchcourse,
    cast(sched_do_not_print as int) as sched_do_not_print,
    cast(exclude_ada as int) as exclude_ada,
    cast(programid as int) as programid,
    cast(excludefromstoredgrades as int) as excludefromstoredgrades,
    cast(maxcredit as float64) as maxcredit,
    cast(iscareertech as int) as iscareertech,
    cast(whomodifiedid as int) as whomodifiedid,
    cast(isfitnesscourse as int) as isfitnesscourse,
    cast(ispewaiver as int) as ispewaiver,
from {{ source("powerschool_dlt", "courses") }}
