select
    `name`,
    `description`,
    gradescaletype,
    color,
    numericextras,
    conversiontonumeric,
    altfinalnumericrange,
    psguid,
    whocreated,
    whencreated,
    whomodified,
    whenmodified,
    numericmode,
    numericcutoff,
    numericvalue,
    altfinalnumericcutoff,

    cast(dcid as int) as dcid,
    cast(id as int) as id,
    cast(gradescaleid as int) as gradescaleid,
    cast(isforcoursegrade as int) as isforcoursegrade,
    cast(isforstandards as int) as isforstandards,
    cast(isgpashown as int) as isgpashown,
    cast(countsingpa as int) as countsingpa,
    cast(displayposition as int) as displayposition,
    cast(grade_points as float64) as grade_points,
    cast(addedvalue as int) as addedvalue,
    cast(graduationcredit as int) as graduationcredit,
    cast(teacherscale as int) as teacherscale,
    cast(cutoffpercentage as float64) as cutoffpercentage,
    cast(`value` as int) as `value`,
    cast(colorlevels as int) as colorlevels,
    cast(isproficient as int) as isproficient,
    cast(isscorecodeonassignments as int) as isscorecodeonassignments,
    cast(modify_code as int) as modify_code,
    cast(numericmin as int) as numericmin,
    cast(numericmax as int) as numericmax,
    cast(numericdecimals as int) as numericdecimals,
    cast(hasspecialgrades as int) as hasspecialgrades,
    cast(specialgradescaledcid as int) as specialgradescaledcid,
    cast(hasrelatedscales as int) as hasrelatedscales,
    cast(altconvertgradescaledcid as int) as altconvertgradescaledcid,
    cast(istermweightingshown as int) as istermweightingshown,
    cast(alt_grade_points as int) as alt_grade_points,
    cast(cutoffpoints as int) as cutoffpoints,
    cast(excludefromafg as int) as excludefromafg,
    cast(grade_replacement_policy as int) as grade_replacement_policy,
    cast(parentgradescaledcid as int) as parentgradescaledcid,
from {{ source("powerschool_dlt", "gradescaleitem") }}
