select
    `name`,
    `description`,
    color,
    defaultpublishstate,
    defaultpublishoption,
    defaultscoretype,
    whocreated,
    whencreated,
    whomodified,
    whenmodified,
    ip_address,
    whomodifiedtype,
    transaction_date,
    executionid,
    defaultscoreentrypoints,
    defaultextracreditpoints,
    defaultweight,
    defaulttotalvalue,

    cast(districtteachercategoryid as int) as districtteachercategoryid,
    cast(isinfinalgrades as int) as isinfinalgrades,
    cast(isactive as int) as isactive,
    cast(isusermodifiable as int) as isusermodifiable,
    cast(displayposition as int) as displayposition,
    cast(isdefaultpublishscores as int) as isdefaultpublishscores,
    cast(defaultdaysbeforedue as int) as defaultdaysbeforedue,
    cast(whomodifiedid as int) as whomodifiedid,
from {{ source("powerschool_dlt", "districtteachercategory") }}
