select
    lastfirst,
    first_name,
    middle_name,
    last_name,
    title,
    homeroom,
    email_addr,
    password,
    ipaddrrestrict,
    accessvalue,
    homepage,
    loginid,
    defaultstudscrn,
    teachernumber,
    ssn,
    home_phone,
    school_phone,
    street,
    city,
    state,
    zip,
    periodsavail,
    powergradepw,
    canchangeschool,
    teacherloginpw,
    nameasimported,
    teacherloginid,
    teacherloginip,
    wm_status,
    wm_address,
    wm_password,
    wm_ta_flag,
    wm_alias,
    ethnicity,
    preferredname,
    lastmeal,
    staffpers_guid,
    sif_stateprid,
    psguid,
    ip_address,
    whomodifiedtype,
    transaction_date,

    cast(dcid as int) as dcid,
    cast(wm_statusdate as date) as wm_statusdate,
    cast(wm_createdate as date) as wm_createdate,
    cast(wm_ta_date as date) as wm_ta_date,
    cast(homeschoolid as int) as homeschoolid,
    cast(photo as int) as photo,
    cast(numlogins as int) as numlogins,
    cast(allowloginstart as int) as allowloginstart,
    cast(allowloginend as int) as allowloginend,
    cast(psaccess as int) as psaccess,
    cast(groupvalue as int) as groupvalue,
    cast(lunch_id as float64) as lunch_id,
    cast(supportcontact as int) as supportcontact,
    cast(wm_tier as int) as wm_tier,
    cast(wm_createtime as int) as wm_createtime,
    cast(wm_exclude as int) as wm_exclude,
    cast(adminldapenabled as int) as adminldapenabled,
    cast(teacherldapenabled as int) as teacherldapenabled,
    cast(maximum_load as int) as maximum_load,
    cast(gradebooktype as int) as gradebooktype,
    cast(fedethnicity as int) as fedethnicity,
    cast(fedracedecline as int) as fedracedecline,
    cast(ptaccess as int) as ptaccess,
    cast(prefixcodesetid as int) as prefixcodesetid,
    cast(whomodifiedid as int) as whomodifiedid,
from {{ source("powerschool_dlt", "users") }}
