select
    * except (
        addedvalue,
        alt_grade_points,
        altconvertgradescaledcid,
        colorlevels,
        countsingpa,
        cutoffpercentage,
        cutoffpoints,
        dcid,
        displayposition,
        excludefromafg,
        grade_points,
        grade_replacement_policy,
        gradescaleid,
        graduationcredit,
        hasrelatedscales,
        hasspecialgrades,
        id,
        isforcoursegrade,
        isforstandards,
        isgpashown,
        isproficient,
        isscorecodeonassignments,
        istermweightingshown,
        modify_code,
        numericdecimals,
        numericmax,
        numericmin,
        parentgradescaledcid,
        specialgradescaledcid,
        teacherscale,
        value
    ),

    cast(addedvalue as int) as addedvalue,
    cast(alt_grade_points as int) as alt_grade_points,
    cast(altconvertgradescaledcid as int) as altconvertgradescaledcid,
    cast(colorlevels as int) as colorlevels,
    cast(countsingpa as int) as countsingpa,
    cast(cutoffpoints as int) as cutoffpoints,
    cast(dcid as int) as dcid,
    cast(displayposition as int) as displayposition,
    cast(excludefromafg as int) as excludefromafg,
    cast(grade_replacement_policy as int) as grade_replacement_policy,
    cast(gradescaleid as int) as gradescaleid,
    cast(graduationcredit as int) as graduationcredit,
    cast(hasrelatedscales as int) as hasrelatedscales,
    cast(hasspecialgrades as int) as hasspecialgrades,
    cast(id as int) as id,
    cast(isforcoursegrade as int) as isforcoursegrade,
    cast(isforstandards as int) as isforstandards,
    cast(isgpashown as int) as isgpashown,
    cast(isproficient as int) as isproficient,
    cast(isscorecodeonassignments as int) as isscorecodeonassignments,
    cast(istermweightingshown as int) as istermweightingshown,
    cast(modify_code as int) as modify_code,
    cast(numericdecimals as int) as numericdecimals,
    cast(numericmax as int) as numericmax,
    cast(numericmin as int) as numericmin,
    cast(parentgradescaledcid as int) as parentgradescaledcid,
    cast(specialgradescaledcid as int) as specialgradescaledcid,
    cast(teacherscale as int) as teacherscale,
    cast(value as int) as value,

    cast(cutoffpercentage as float64) as cutoffpercentage,
    cast(grade_points as float64) as grade_points,
from {{ source("powerschool_dlt", "gradescaleitem") }}
