select
    whocreated,
    whencreated,
    whomodified,
    whenmodified,
    liep_type,
    alternativeeducationprogram_yn,
    city,
    countycodeattending,
    countycodereceiving,
    countycoderesident,
    districtcodeattending,
    districtcodereceiving,
    districtcoderesident,
    gifted_and_talented,
    homeless_code,
    indistrictplacement,
    liep_languageofinstruction,
    nonpublic,
    programtypecode,
    residentmunicipalcode,
    schoolcodeattending,
    schoolcodereceiving,
    schoolcoderesident,
    shared_time_code,
    studentslearningmodel,
    titleilanguage_yn,
    titleimath_yn,
    titleiscience_yn,
    reportedsharedvoc_yn,
    specialed_classification,
    tuition_code,
    deafhardofhearing_yn,
    district_status_override,
    gradelevelcode,
    homelessinstrucservice,
    homelesssupportservice,
    mddisablingcondition1,
    mddisablingcondition2,
    mddisablingcondition3,
    mddisablingcondition4,
    mddisablingcondition5,
    titleiindicator,
    eligible_for_liep,
    home_language2,
    home_language3,
    home_language4,
    home_language5,
    home_language_name2,
    home_language_name3,
    home_language_name4,
    home_language_name5,
    sld_basic_reading_yn,
    sld_listen_comp_yn,
    sld_math_cal_yn,
    sld_math_prob_solve_yn,
    sld_oral_expresn_yn,
    sld_read_fluency_yn,
    sld_reading_comp_yn,
    sld_writn_exprsn_yn,

    cast(lepbegindate as date) as lepbegindate,
    cast(lependdate as date) as lependdate,
    cast(withdrawal_date as date) as withdrawal_date,
    cast(schoolentrydate as date) as schoolentrydate,
    cast(districtentrydate as date) as districtentrydate,
    cast(sid_entrydate as date) as sid_entrydate,
    cast(sid_exitdate as date) as sid_exitdate,
    cast(declassificationspeddate as date) as declassificationspeddate,
    cast(elp_screener_date as date) as elp_screener_date,
    cast(lepbegindate2 as date) as lepbegindate2,
    cast(liep_parent_refusal_date as date) as liep_parent_refusal_date,
    cast(liependdate2 as date) as liependdate2,
    cast(reenrollmentsdcid as int) as reenrollmentsdcid,
    cast(lep_tf as int) as lep_tf,
    cast(cumulativedaysabsent as int) as cumulativedaysabsent,
    cast(cumulativedayspresent as int) as cumulativedayspresent,
    cast(cumulativestateabs as int) as cumulativestateabs,
    cast(daysopen as int) as daysopen,
    cast(deviceowner as int) as deviceowner,
    cast(devicetype as int) as devicetype,
    cast(homelessprimarynighttimeres as int) as homelessprimarynighttimeres,
    cast(internetconnectivity as int) as internetconnectivity,
    cast(remotedaysabsent as int) as remotedaysabsent,
    cast(remotedayspresent as int) as remotedayspresent,
    cast(learningenvironment as int) as learningenvironment,
    cast(retained_tf as int) as retained_tf,
    cast(languageacquisition as int) as languageacquisition,
    cast(lep_completion_date_refused as int) as lep_completion_date_refused,
    cast(sid_excludeenrollment as int) as sid_excludeenrollment,

    if(pid_504_tf = 1, true, false) as pid_504_tf,
from {{ source("powerschool_dlt", "s_nj_ren_x") }}
