select
    * except (
        category,
        consequence,
        custom,
        discipline_actiondate,
        discipline_actiontaken,
        discipline_actiontakendetail,
        discipline_actiontakenenddate,
        discipline_administratorid,
        discipline_alcoholrelatedflag,
        discipline_drugrelatedflag,
        discipline_drugtypedetail,
        discipline_durationactual,
        discipline_durationassigned,
        discipline_durationnotes,
        discipline_felonyflag,
        discipline_gangrelatedflag,
        discipline_hatecrimeflag,
        discipline_hearingofficerflag,
        discipline_incidentcontext,
        discipline_incidentdate,
        discipline_incidentlocation,
        discipline_incidentlocdetail,
        discipline_incidenttype,
        discipline_incidenttypedetail,
        discipline_likelyinjuryflag,
        discipline_moneylossvalue,
        discipline_offender,
        discipline_policeinvolvedflag,
        discipline_reporter,
        discipline_reporterid,
        discipline_schoolrulesvioflag,
        discipline_sequence,
        discipline_victimtype,
        discipline_weaponrelatedflag,
        discipline_weapontype,
        discipline_weapontypenotes,
        durationchangesource,
        entry_author,
        entry_time,
        id,
        incidenttypecategory,
        psguid,
        schoolid,
        student_number,
        subject,
        subtype,
        teacherid
    ) replace (
        cast(dcid as int) as dcid,
        cast(logtypeid as int) as logtypeid,
        cast(studentid as int) as studentid,
        cast(entry_date as date) as entry_date
    ),
from {{ source("powerschool_dlt", "log") }}
