select
    entrycode,
    entrycomment,
    exitcode,
    exitcomment,
    track,
    districtofresidence,
    enrollmenttype,
    lunchstatus,
    withdrawal_reason_code,
    studentschlenrl_guid,
    psguid,

    cast(dcid as int) as dcid,
    cast(entrydate as date) as entrydate,
    cast(exitdate as date) as exitdate,
    cast(id as int) as id,
    cast(studentid as int) as studentid,
    cast(schoolid as int) as schoolid,
    cast(grade_level as int) as grade_level,
    cast(`type` as int) as `type`,
    cast(enrollmentcode as int) as enrollmentcode,
    cast(fulltimeequiv_obsolete as float64) as fulltimeequiv_obsolete,
    cast(membershipshare as float64) as membershipshare,
    cast(tuitionpayer as int) as tuitionpayer,
    cast(fteid as int) as fteid,
from {{ source("powerschool_dlt", "reenrollments") }}
