select
    section_number,
    course_number,
    period_obsolete,
    room,
    fastperlist,
    ccrnarray,
    attendance,
    pgflags,
    days_obsolete,
    gradeprofile,
    `log`,
    teacherdescr,
    blockperiods_obsolete,
    dependent_secs,
    expression,
    original_expression,
    comment_value,
    section_type,
    team,
    house,
    instruction_lang,
    sectioninfo_guid,
    att_mode_code,
    max_load_status,
    psguid,
    external_expression,
    ip_address,
    whomodifiedtype,
    transaction_date,

    cast(dcid as int) as dcid,
    cast(id as int) as id,
    cast(lastattupdate as date) as lastattupdate,
    cast(bitmap as bytes) as bitmap,
    cast(teacher as int) as teacher,
    cast(termid as int) as termid,
    cast(no_of_students as int) as no_of_students,
    cast(schoolid as int) as schoolid,
    cast(noofterms as int) as noofterms,
    cast(trackteacheratt as int) as trackteacheratt,
    cast(maxenrollment as int) as maxenrollment,
    cast(distuniqueid as int) as distuniqueid,
    cast(wheretaught as int) as wheretaught,
    cast(rostermodser as int) as rostermodser,
    cast(pgversion as int) as pgversion,
    cast(grade_level as int) as grade_level,
    cast(campusid as int) as campusid,
    cast(exclude_ada as int) as exclude_ada,
    cast(gradescaleid as int) as gradescaleid,
    cast(excludefromgpa as int) as excludefromgpa,
    cast(buildid as int) as buildid,
    cast(schedulesectionid as int) as schedulesectionid,
    cast(wheretaughtdistrict as int) as wheretaughtdistrict,
    cast(excludefromclassrank as int) as excludefromclassrank,
    cast(excludefromhonorroll as int) as excludefromhonorroll,
    cast(parent_section_id as int) as parent_section_id,
    cast(attendance_type_code as int) as attendance_type_code,
    cast(maxcut as int) as maxcut,
    cast(exclude_state_rpt_yn as int) as exclude_state_rpt_yn,
    cast(sortorder as int) as sortorder,
    cast(programid as int) as programid,
    cast(excludefromstoredgrades as int) as excludefromstoredgrades,
    cast(gradebooktype as int) as gradebooktype,
    cast(whomodifiedid as int) as whomodifiedid,
from {{ source("powerschool_dlt", "sections") }}
