select
    att_code,
    alternate_code,
    `description`,
    presence_status_cd,
    unused1,
    attendancecodeinfo_guid,
    psguid,

    cast(id as int) as id,
    cast(lock_teacher_yn as int) as lock_teacher_yn,
    cast(dcid as int) as dcid,
    cast(schoolid as int) as schoolid,
    cast(yearid as int) as yearid,
    cast(course_credit_points as float64) as course_credit_points,
    cast(assignment_filter_yn as int) as assignment_filter_yn,
    cast(calculate_ada_yn as int) as calculate_ada_yn,
    cast(calculate_adm_yn as int) as calculate_adm_yn,
    cast(sortorder as int) as sortorder,
from {{ source("powerschool_dlt", "attendance_code") }}
