select
    gradecalcpreferenceorder,
    defaultroundingrule,
    calculationmetric,
    higherlevelstndmetric,
    recentscoreweightlist,
    calcmetricschoolfromstd,
    sectionnames,
    standardtraditionalorder,
    whocreated,
    whencreated,
    whomodified,
    whenmodified,
    startingpagekey,
    startingpageurl,

    cast(gradeschoolconfigid as int) as gradeschoolconfigid,
    cast(schoolsdcid as int) as schoolsdcid,
    cast(yearid as int) as yearid,
    cast(defaultdecimalcount as int) as defaultdecimalcount,
    cast(iscalcformulaeditable as int) as iscalcformulaeditable,
    cast(isdropscoreeditable as int) as isdropscoreeditable,
    cast(iscalcprecisioneditable as int) as iscalcprecisioneditable,
    cast(iscalcmetriceditable as int) as iscalcmetriceditable,
    cast(isrecentscoreeditable as int) as isrecentscoreeditable,
    cast(ishigherstndautocalc as int) as ishigherstndautocalc,
    cast(ishigherstndcalceditable as int) as ishigherstndcalceditable,
    cast(ishighstandardeditable as int) as ishighstandardeditable,
    cast(iscalcmetricschooledit as int) as iscalcmetricschooledit,
    cast(isstandardsshown as int) as isstandardsshown,
    cast(isstandardsshownonasgmt as int) as isstandardsshownonasgmt,
    cast(istraditionalgradeshown as int) as istraditionalgradeshown,
    cast(iscitizenshipdisplayed as int) as iscitizenshipdisplayed,
    cast(termbinlockoffset as int) as termbinlockoffset,
    cast(lockwarningoffset as int) as lockwarningoffset,
    cast(issectstndweighteditable as int) as issectstndweighteditable,
    cast(minimumassignmentvalue as int) as minimumassignmentvalue,
    cast(isgradescaleteachereditable as int) as isgradescaleteachereditable,
    cast(isstandardslimited as int) as isstandardslimited,
    cast(isstandardslimitededitable as int) as isstandardslimitededitable,
    cast(isusingpercentforstndautocalc as int) as isusingpercentforstndautocalc,
    cast(ismulticategoryallowed as int) as ismulticategoryallowed,
    cast(ismulticategoryeditable as int) as ismulticategoryeditable,
from {{ source("powerschool_dlt", "gradeschoolconfig") }}
