with
    staging as (
        select
            lastfirst,
            first_name,
            middle_name,
            last_name,
            gender,
            web_id,
            web_password,
            street,
            city,
            state,
            zip,
            guardianemail,
            transfercomment,
            guardianfax,
            ssn,
            entrycode,
            exitcode,
            lunchstatus,
            ethnicity,
            lastmeal,
            pl_language,
            family_ident,
            `log`,
            track,
            gradreqset,
            student_web_id,
            student_web_password,
            bus_route,
            bus_stop,
            doctor_name,
            doctor_phone,
            emerg_contact_1,
            emerg_contact_2,
            emerg_phone_1,
            emerg_phone_2,
            father,
            home_phone,
            home_room,
            locker_combination,
            locker_number,
            mailing_city,
            mailing_street,
            mailing_state,
            mailing_zip,
            mother,
            wm_status,
            wm_address,
            wm_password,
            sched_nextyearhouse,
            sched_nextyearbuilding,
            sched_nextyearteam,
            sched_nextyearhomeroom,
            sched_nextyearbus,
            wm_ta_flag,
            graduated_schoolname,
            alert_discipline,
            alert_guardian,
            alert_medical,
            alert_other,
            state_studentnumber,
            districtofresidence,
            enrollmenttype,
            exitcomment,
            team,
            house,
            building,
            withdrawal_reason_code,
            guardian_studentcont_guid,
            father_studentcont_guid,
            mother_studentcont_guid,
            studentpers_guid,
            studentpict_guid,
            studentschlenrl_guid,
            summerschoolnote,
            geocode,
            mailing_geocode,
            psguid,
            ip_address,
            whomodifiedtype,
            transaction_date,

            cast(id as int) as id,
            cast(entrydate as date) as entrydate,
            cast(exitdate as date) as exitdate,
            cast(dob as date) as dob,
            cast(applic_submitted_date as date) as applic_submitted_date,
            cast(applic_response_recvd_date as date) as applic_response_recvd_date,
            cast(wm_statusdate as date) as wm_statusdate,
            cast(wm_createdate as date) as wm_createdate,
            cast(wm_ta_date as date) as wm_ta_date,
            cast(districtentrydate as date) as districtentrydate,
            cast(schoolentrydate as date) as schoolentrydate,
            cast(alert_disciplineexpires as date) as alert_disciplineexpires,
            cast(alert_guardianexpires as date) as alert_guardianexpires,
            cast(alert_medicalexpires as date) as alert_medicalexpires,
            cast(alert_otherexpires as date) as alert_otherexpires,
            cast(
                enrollment_transfer_date_pend as date
            ) as enrollment_transfer_date_pend,
            cast(enrollment_transfer_info as bytes) as enrollment_transfer_info,
            cast(allowwebaccess as int) as allowwebaccess,
            cast(balance1 as float64) as balance1,
            cast(balance2 as float64) as balance2,
            cast(balance3 as float64) as balance3,
            cast(balance4 as float64) as balance4,
            cast(campusid as int) as campusid,
            cast(classof as int) as classof,
            cast(cumulative_gpa as float64) as cumulative_gpa,
            cast(cumulative_pct as float64) as cumulative_pct,
            cast(customrank_gpa as float64) as customrank_gpa,
            cast(dcid as int) as dcid,
            cast(districtentrygradelevel as int) as districtentrygradelevel,
            cast(enroll_status as int) as enroll_status,
            cast(enrollment_schoolid as int) as enrollment_schoolid,
            cast(enrollmentcode as int) as enrollmentcode,
            cast(enrollmentid as int) as enrollmentid,
            cast(exclude_fr_rank as int) as exclude_fr_rank,
            cast(fedethnicity as int) as fedethnicity,
            cast(fedracedecline as int) as fedracedecline,
            cast(fee_exemption_status as int) as fee_exemption_status,
            cast(fteid as int) as fteid,
            cast(fulltimeequiv_obsolete as float64) as fulltimeequiv_obsolete,
            cast(gpentryyear as int) as gpentryyear,
            cast(grade_level as int) as grade_level,
            cast(gradreqsetid as int) as gradreqsetid,
            cast(graduated_rank as int) as graduated_rank,
            cast(graduated_schoolid as int) as graduated_schoolid,
            cast(ldapenabled as int) as ldapenabled,
            cast(lunch_id as float64) as lunch_id,
            cast(membershipshare as float64) as membershipshare,
            cast(next_school as int) as next_school,
            cast(person_id as int) as person_id,
            cast(phone_id as int) as phone_id,
            cast(photoflag as int) as photoflag,
            cast(sched_loadlock as int) as sched_loadlock,
            cast(sched_lockstudentschedule as int) as sched_lockstudentschedule,
            cast(sched_nextyeargrade as int) as sched_nextyeargrade,
            cast(sched_priority as int) as sched_priority,
            cast(sched_scheduled as int) as sched_scheduled,
            cast(sched_yearofgraduation as int) as sched_yearofgraduation,
            cast(schoolentrygradelevel as int) as schoolentrygradelevel,
            cast(schoolid as int) as schoolid,
            cast(sdatarn as int) as sdatarn,
            cast(simple_gpa as float64) as simple_gpa,
            cast(simple_pct as float64) as simple_pct,
            cast(state_enrollflag as int) as state_enrollflag,
            cast(state_excludefromreporting as int) as state_excludefromreporting,
            cast(student_allowwebaccess as int) as student_allowwebaccess,
            cast(summerschoolid as int) as summerschoolid,
            cast(teachergroupid as int) as teachergroupid,
            cast(tuitionpayer as int) as tuitionpayer,
            cast(whomodifiedid as int) as whomodifiedid,
            cast(wm_createtime as int) as wm_createtime,
            cast(wm_tier as int) as wm_tier,
            cast(student_number as int) as student_number,
        from {{ source("powerschool_dlt", "students") }}
    )

select
    *,

    left(upper(gender), 1) as gender_code,
    left(upper(ethnicity), 1) as ethnicity_code,
from staging
