select
    abbreviation,
    storecode,
    `type`,
    droplowscoreoption,
    whocreated,
    whencreated,
    whomodified,
    whenmodified,

    cast(gradecalculationtypeid as int) as gradecalculationtypeid,
    cast(gradeformulasetid as int) as gradeformulasetid,
    cast(yearid as int) as yearid,
    cast(isnograde as int) as isnograde,
    cast(isdroplowstudentfavor as int) as isdroplowstudentfavor,
    cast(isalternatepointsused as int) as isalternatepointsused,
    cast(iscalcformulaeditable as int) as iscalcformulaeditable,
    cast(isdropscoreeditable as int) as isdropscoreeditable,
    cast(ismulticategoryeditable as int) as ismulticategoryeditable,
from {{ source("powerschool_dlt", "gradecalculationtype") }}
