select
    classpua,
    `log`,
    sched_gender,
    sched_classroom,
    sched_homeroom,
    sched_department,
    sched_housecode,
    sched_buildingcode,
    sched_activitystatuscode,
    sched_primaryschoolcode,
    sched_team,
    notes,
    psguid,
    ip_address,
    whomodifiedtype,
    transaction_date,

    cast(dcid as int) as dcid,
    cast(id as int) as id,
    cast(schoolid as int) as schoolid,
    cast(users_dcid as int) as users_dcid,
    cast(balance1 as float64) as balance1,
    cast(balance2 as float64) as balance2,
    cast(balance3 as float64) as balance3,
    cast(balance4 as float64) as balance4,
    cast(noofcurclasses as int) as noofcurclasses,
    cast(staffstatus as int) as staffstatus,
    cast(`status` as int) as `status`,
    cast(sched_maximumcourses as int) as sched_maximumcourses,
    cast(sched_maximumduty as int) as sched_maximumduty,
    cast(sched_maximumfree as int) as sched_maximumfree,
    cast(sched_totalcourses as int) as sched_totalcourses,
    cast(sched_maximumconsecutive as int) as sched_maximumconsecutive,
    cast(sched_isteacherfree as int) as sched_isteacherfree,
    cast(sched_teachermoreoneschool as int) as sched_teachermoreoneschool,
    cast(sched_substitute as int) as sched_substitute,
    cast(sched_scheduled as int) as sched_scheduled,
    cast(sched_usebuilding as int) as sched_usebuilding,
    cast(sched_usehouse as int) as sched_usehouse,
    cast(sched_lunch as int) as sched_lunch,
    cast(sched_maxpers as int) as sched_maxpers,
    cast(sched_maxpreps as int) as sched_maxpreps,
    cast(whomodifiedid as int) as whomodifiedid,
from {{ source("powerschool_dlt", "schoolstaff") }}
