select
    priorityforservice,
    sealofbiliteracy,
    twentyfirstcenturyserved,
    activedutyparent,
    immigrant,
    jobcorps,
    youthchallenge,
    singleparent,
    virtualstudent,
    steamstemparticipant,
    birthcity,
    birthcountry,
    birthcounty,
    birthstate,
    residencystatus,
    economicdisadvantage,
    luncheligibility,
    maritalstatus,
    reportedvalue,
    suffix,
    healthid,
    deviceaccess,
    devicetype,
    internetaccess,
    internetinresidence,
    internetperformance,
    pref_first,
    pref_last,
    pref_middle,
    tribal_affiliation_1,
    tribal_affiliation_2,
    tribal_affiliation_3,
    tribal_affiliation_sif_1,
    tribal_affiliation_sif_2,
    tribal_affiliation_sif_3,
    county,
    maiden_name,
    ontracktograduate,
    privateschool,
    graduation_class_rank,
    contact_email,
    contact_fname,
    contact_lname,
    contact_phone,
    barrierintaccess,
    fafsa,
    outofdistrict_distoverride,
    section504_yn,
    careertechedu_yn,
    careerworkreadiness_yn,
    clgcareerreadiness_yn,
    comctzn_yn,
    postsecedu_yn,

    cast(entrydateintousschool as date) as entrydateintousschool,
    cast(programenddate as date) as programenddate,
    cast(programstartdate as date) as programstartdate,
    cast(studentsdcid as int) as studentsdcid,
    cast(excludefromedfi as int) as excludefromedfi,
    cast(repeatgradeindicator as int) as repeatgradeindicator,
    cast(schoolchoicetransfer as int) as schoolchoicetransfer,
    cast(home_language as int) as home_language,
    cast(native_language as int) as native_language,
    cast(foster_care as int) as foster_care,
    cast(parentrefusalofimmaccuracy as int) as parentrefusalofimmaccuracy,
from {{ source("powerschool_dlt", "s_stu_x") }}
