select
    `name`,
    `description`,
    scoretype,
    publishoption,
    whocreated,
    whencreated,
    whomodified,
    whenmodified,
    ip_address,
    whomodifiedtype,
    transaction_date,
    executionid,
    extracreditpoints,
    `weight`,

    cast(assignmentsectionid as int) as assignmentsectionid,
    cast(duedate as date) as duedate,
    cast(publishonspecificdate as date) as publishonspecificdate,
    cast(publisheddate as date) as publisheddate,
    cast(assignmentid as int) as assignmentid,
    cast(iscountedinfinalgrade as int) as iscountedinfinalgrade,
    cast(isscorespublish as int) as isscorespublish,
    cast(isscoringneeded as int) as isscoringneeded,
    cast(maxretakeallowed as int) as maxretakeallowed,
    cast(publishdaysbeforedue as int) as publishdaysbeforedue,
    cast(publishedscoretypeid as int) as publishedscoretypeid,
    cast(relatedgradescaleitemdcid as int) as relatedgradescaleitemdcid,
    cast(sectionsdcid as int) as sectionsdcid,
    cast(whomodifiedid as int) as whomodifiedid,
    cast(yearid as int) as yearid,
    cast(scoreentrypoints as float64) as scoreentrypoints,
    cast(totalpointvalue as float64) as totalpointvalue,
from {{ source("powerschool_dlt", "assignmentsection") }}
