select
    cat,
    `name`,
    `value`,
    valuet,
    value2,
    valuet2,
    powerlink,
    powerlinkspan,
    `log`,
    psguid,

    cast(dcid as int) as dcid,
    cast(id as int) as id,
    cast(date_value as date) as date_value,
    cast(date2 as date) as date2,
    cast(value_x as bytes) as value_x,
    cast(valueli as int) as valueli,
    cast(valueli2 as int) as valueli2,
    cast(valuer as float64) as valuer,
    cast(sortorder as int) as sortorder,
    cast(schoolid as int) as schoolid,
    cast(valueli3 as int) as valueli3,
    cast(valuer2 as float64) as valuer2,
    cast(time1 as int) as time1,
    cast(time2 as int) as time2,
    cast(spedindicator as int) as spedindicator,
    cast(valueli4 as int) as valueli4,
    cast(yearid as int) as yearid,
from {{ source("powerschool_dlt", "gen") }}
