select
    calcmetricsectionfromstnd,
    defaultroundingrule,
    higherlevelstndmetric,
    recentscoreweightlist,
    stndcalculationmetric,
    `type`,
    whencreated,
    whenmodified,
    whocreated,
    whomodified,

    cast(defaultdecimalcount as int) as defaultdecimalcount,
    cast(gradeformulasetid as int) as gradeformulasetid,
    cast(gradesectionconfigid as int) as gradesectionconfigid,
    cast(iscalcformulaeditable as int) as iscalcformulaeditable,
    cast(iscalcprecisioneditable as int) as iscalcprecisioneditable,
    cast(iscalcsectionfromstndedit as int) as iscalcsectionfromstndedit,
    cast(isdropscoreeditable as int) as isdropscoreeditable,
    cast(isgradescaleteachereditable as int) as isgradescaleteachereditable,
    cast(ishigherlvlstndeditable as int) as ishigherlvlstndeditable,
    cast(ishigherstndautocalc as int) as ishigherstndautocalc,
    cast(ishigherstndcalceditable as int) as ishigherstndcalceditable,
    cast(issectstndweighteditable as int) as issectstndweighteditable,
    cast(isstndcalcmeteditable as int) as isstndcalcmeteditable,
    cast(isstndrcntscoreeditable as int) as isstndrcntscoreeditable,
    cast(isusingpercentforstndautocalc as int) as isusingpercentforstndautocalc,
    cast(minimumassignmentvalue as int) as minimumassignmentvalue,
    cast(sectionsdcid as int) as sectionsdcid,
from {{ source("powerschool_dlt", "gradesectionconfig") }}
