select
    your_unique_identifier,
    first_name,
    middle_initial,
    last_name,
    name_suffix,
    requester_return_field,
    record_found_y_n,
    college_code_branch,
    college_name,
    college_state,
    two_year_four_year,
    public_private,
    enrollment_status,
    graduated,
    degree_title,
    class_level,
    enrollment_major_1,
    enrollment_major_2,
    degree_major_1,
    degree_major_2,
    degree_major_3,
    degree_major_4,

    cast(college_sequence as int) as college_sequence,
    cast(degree_cip_1 as int) as degree_cip_1,
    cast(degree_cip_2 as int) as degree_cip_2,
    cast(degree_cip_3 as int) as degree_cip_3,
    cast(degree_cip_4 as int) as degree_cip_4,
    cast(enrollment_cip_1 as int) as enrollment_cip_1,
    cast(enrollment_cip_2 as int) as enrollment_cip_2,

    parse_date('%Y%m%d', enrollment_begin) as enrollment_begin,
    parse_date('%Y%m%d', enrollment_end) as enrollment_end,
    parse_date('%Y%m%d', graduation_date) as graduation_date,
    parse_date('%Y%m%d', search_date) as search_date,
from {{ source("nsc", "src_nsc__student_tracker") }}
