select
    _dagster_partition_key as school_id,
    studentid as student_id,
    studentschoolid as student_school_id,
{#
    secondarystudentid as secondary_student_id,
    integrationid as integration_id,
    secondaryintegrationid as secondary_integration_id,
    firstname as first_name,
    middlename as middle_name,
    lastname as last_name,
    legalfirstname as legal_first_name,
    preferredname as preferred_name,
    enrollmentstatus as enrollment_status,
    isnslp as is_nslp,
    genderletter as gender_letter,
    ethnicity,
    streetaddress1 as street_address_1,
    streetaddress2 as street_address_2,
    city,
    `state`,
    zipcode as zip_code,
    behaviorplan as behavior_plan,
    cellphone as cell_phone,
    departmentid as department_id,
    department,
    dlps_validationcode as dlps_validation_code,
    ellstatus as ell_status,
    email,
    emoji,
    enrollmentid as enrollment_id,
    sourceschoolid as source_school_id,
    gradelevelid as grade_level_id,
    gradelevel as grade_level,
    gradelevelkey as grade_level_key,
    gradelevelshort as grade_level_short,
    gradelevelsort as grade_level_sort,
    homelanguageid as home_language_id,
    homelanguagecode as home_language_code,
    homelanguage as home_language,
    homeroomid as homeroom_id,
    homeroom,
    is504 as is_504,
    spedplan as sped_plan,
    gender,
    pronouns,
    messagemerge1 as message_merge_1,
    messagemerge2 as message_merge_2,
    messagemerge3 as message_merge_3,
    photofile as photo_file,
    photofileurl as photo_file_url,
    transportationnotes as transportation_notes,
#}
from {{ source("deanslist", "src_deanslist__students") }}
