select
    cast(nullif(rosterid, '') as int) as roster_id,
    cast(nullif(masterid, '') as int) as master_id,
    cast(nullif(rostertypeid, '') as int) as roster_type_id,
    cast(nullif(rtifocusid, '') as int) as rti_focus_id,
    cast(nullif(schoolid, '') as int) as school_id,
    cast(nullif(screensetid, '') as int) as screen_set_id,
    cast(nullif(secondaryintegrationid, '') as int) as secondary_integration_id,
    cast(nullif(subjectid, '') as int) as subject_id,

    nullif(active, '') as active,
    nullif(collecthw, '') as collect_hw,
    nullif(coursenumber, '') as course_number,
    nullif(gradelevels, '') as grade_levels,
    nullif(lastsynced, '') as last_synced,
    nullif(markercolor, '') as marker_color,
    nullif(mastername, '') as master_name,
    nullif(meetingdays, '') as meeting_days,
    nullif(`period`, '') as `period`,
    nullif(room, '') as room,
    nullif(rostername, '') as roster_name,
    nullif(rostertype, '') as roster_type,
    nullif(rtitier, '') as rti_tier,
    nullif(screensetname, '') as screen_set_name,
    nullif(sectionnumber, '') as section_number,
    nullif(showroster, '') as show_roster,
    nullif(sisexpression, '') as sis_expression,
    nullif(sisgradebookname, '') as sis_gradebook_name,
    nullif(siskey, '') as sis_key,
    nullif(studentcount, '') as student_count,
    nullif(subjectname, '') as subject_name,
    nullif(takeattendance, '') as take_attendance,
    nullif(takeclassattendance, '') as take_class_attendance,
from {{ source("deanslist", "src_deanslist__rosters") }}
