select
    id,
    `name`,
    createdbyid as created_by_id,
    createddate as created_date,
    lastactivitydate as last_activity_date,
    lastmodifiedbyid as last_modified_by_id,
    lastmodifieddate as last_modified_date,
    systemmodstamp as system_modstamp,
    actual_job_duration__c as actual_job_duration,
    anticipated_job_duration_in_weeks__c as anticipated_job_duration_in_weeks,
    average_hours_per_week__c as average_hours_per_week,
    benefits__c as benefits,
    bmt_end_date__c as bmt_end_date,
    bmt_start_date__c as bmt_start_date,
    career_readiness_and_college_ambassadors__c
    as career_readiness_and_college_ambassadors,
    category__c as category,
    contact__c as contact,
    currently_employed__c as currently_employed,
    currently_seeking__c as currently_seeking,
    delayed_entry_enlistment_program_dep__c as delayed_entry_enlistment_program_dep,
    did_not_complete_bmt__c as did_not_complete_bmt,
    discharge_date__c as discharge_date,
    discharge_type__c as discharge_type,
    employed_by_kipp__c as employed_by_kipp,
    employer__c as employer,
    employer_organization_look_up__c as employer_organization_look_up,
    employer_web_page__c as employer_web_page,
    employment_count__c as employment_count,
    end_date__c as end_date,
    enlist_date__c as enlist_date,
    hourly_rate__c as hourly_rate,
    ineligible_for_military_enlistment__c as ineligible_for_military_enlistment,
    internship_type__c as internship_type,
    job__c as job,
    job_lead_source__c as job_lead_source,
    last_verified_date__c as last_verified_date,
    meps_end_date__c as meps_end_date,
    meps_location__c as meps_location,
    meps_start_date__c as meps_start_date,
    military_branch__c as military_branch,
    military_notes__c as military_notes,
    military_occupational_specialty_mos__c as military_occupational_specialty_mos,
    notes__c as notes,
    other_ineligible_for_military_reason__c as other_ineligible_for_military_reason,
    other_job_industry__c as other_job_industry,
    payment_type__c as payment_type,
    salary_annual__c as salary_annual,
    self_sufficient__c as self_sufficient,
    source__c as `source`,
    start_date__c as `start_date`,
    status__c as `status`,
    subcategory__c as subcategory,
from {{ source("kippadb", "employment") }}
where not isdeleted
