BENCHMARK_STUDENT_SUMMARY_FIELDS = [
    {"name": "account_name", "type": ["null", "string"], "default": None},
    {"name": "administration_type", "type": ["null", "string"], "default": None},
    {"name": "alternate_assessment", "type": ["null", "string"], "default": None},
    {"name": "approved_accommodations", "type": ["null", "string"], "default": None},
    {"name": "assessing_teacher_name", "type": ["null", "string"], "default": None},
    {"name": "assessing_teacher_staff_id", "type": ["null", "string"], "default": None},
    {"name": "assessment_edition", "type": ["null", "string"], "default": None},
    {"name": "assessment_grade", "type": ["null", "string"], "default": None},
    {"name": "assessment", "type": ["null", "string"], "default": None},
    {"name": "benchmark_period", "type": ["null", "string"], "default": None},
    {"name": "classed", "type": ["null", "string"], "default": None},
    {"name": "composite_level", "type": ["null", "string"], "default": None},
    {"name": "composite_score", "type": ["null", "long", "double"], "default": None},
    {"name": "composite_semester_growth", "type": ["null", "string"], "default": None},
    {"name": "composite_year_growth", "type": ["null", "string"], "default": None},
    {"name": "decoding_nwf_wrc_level", "type": ["null", "string"], "default": None},
    {"name": "decoding_nwf_wrc_score", "type": ["null", "double"], "default": None},
    {"name": "disability", "type": ["null", "string"], "default": None},
    {"name": "district_name", "type": ["null", "string"], "default": None},
    {"name": "district_primary_id", "type": ["null", "string"], "default": None},
    {"name": "economically_disadvantaged", "type": ["null", "string"], "default": None},
    {"name": "ell_status", "type": ["null", "string"], "default": None},
    {"name": "english_proficiency", "type": ["null", "string"], "default": None},
    {"name": "enrollment_grade", "type": ["null", "string"], "default": None},
    {"name": "error_rate_orf_score", "type": ["null", "double"], "default": None},
    {"name": "external_program", "type": ["null", "string"], "default": None},
    {"name": "gender", "type": ["null", "string"], "default": None},
    {"name": "home_language", "type": ["null", "string"], "default": None},
    {"name": "internal_program", "type": ["null", "string"], "default": None},
    {"name": "letter_names_lnf_level", "type": ["null", "string"], "default": None},
    {"name": "letter_names_lnf_score", "type": ["null", "double"], "default": None},
    {"name": "meal_status", "type": ["null", "string"], "default": None},
    {"name": "migrant", "type": ["null", "string"], "default": None},
    {"name": "municipality_name", "type": ["null", "string"], "default": None},
    {"name": "municipality_primary_id", "type": ["null", "string"], "default": None},
    {"name": "official_teacher_name", "type": ["null", "string"], "default": None},
    {
        "name": "official_teacher_staff_id",
        "type": ["null", "long", "string"],
        "default": None,
    },
    {"name": "primary_school_id", "type": ["null", "string"], "default": None},
    {"name": "race", "type": ["null", "string"], "default": None},
    {"name": "ran_level", "type": ["null", "string"], "default": None},
    {"name": "ran_score", "type": ["null", "double"], "default": None},
    {"name": "reading_fluency_orf_level", "type": ["null", "string"], "default": None},
    {"name": "reading_fluency_orf_score", "type": ["null", "double"], "default": None},
    {"name": "reporting_class_id", "type": ["null", "string"], "default": None},
    {"name": "reporting_class_name", "type": ["null", "string"], "default": None},
    {"name": "risk_indicator_level", "type": ["null", "string"], "default": None},
    {"name": "school_name", "type": ["null", "string"], "default": None},
    {"name": "school_year", "type": ["null", "string"], "default": None},
    {"name": "secondary_school_id", "type": ["null", "string"], "default": None},
    {"name": "section_504", "type": ["null", "string"], "default": None},
    {"name": "special_education", "type": ["null", "string"], "default": None},
    {"name": "specific_disability", "type": ["null", "string"], "default": None},
    {"name": "spelling_level", "type": ["null", "string"], "default": None},
    {"name": "spelling_score", "type": ["null", "double"], "default": None},
    {"name": "state", "type": ["null", "string"], "default": None},
    {"name": "student_first_name", "type": ["null", "string"], "default": None},
    {"name": "student_last_name", "type": ["null", "string"], "default": None},
    {"name": "student_middle_name", "type": ["null", "string"], "default": None},
    {"name": "student_primary_id", "type": ["null", "long"], "default": None},
    {"name": "student_id_state_id", "type": ["null", "string"], "default": None},
    {"name": "title_1", "type": ["null", "string"], "default": None},
    {"name": "vocabulary_level", "type": ["null", "string"], "default": None},
    {"name": "vocabulary_score", "type": ["null", "double"], "default": None},
    {"name": "word_reading_wrf_level", "type": ["null", "string"], "default": None},
    {"name": "word_reading_wrf_score", "type": ["null", "double"], "default": None},
    {
        "name": "composite_national_norm_percentile",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "correct_responses_maze_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "decoding_nwf_wrc_national_norm_percentile",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "decoding_nwf_wrc_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "decoding_nwf_wrc_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "dibels_composite_score_lexile",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "incorrect_responses_maze_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "letter_names_lnf_national_norm_percentile",
        "type": ["null", "string", "double"],
        "default": None,
    },
    {
        "name": "letter_names_lnf_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "letter_names_lnf_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "letter_sounds_nwf_cls_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "letter_sounds_nwf_cls_national_norm_percentile",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "letter_sounds_nwf_cls_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "letter_sounds_nwf_cls_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "letter_sounds_nwf_cls_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "phonemic_awareness_psf_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "phonemic_awareness_psf_national_norm_percentile",
        "type": ["null", "string", "double"],
        "default": None,
    },
    {
        "name": "phonemic_awareness_psf_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "phonemic_awareness_psf_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "phonemic_awareness_psf_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "primary_id_student_id_district_id",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "reading_accuracy_orf_accu_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_accuracy_orf_accu_national_norm_percentile",
        "type": ["null", "double", "string"],
        "default": None,
    },
    {
        "name": "reading_accuracy_orf_accu_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_accuracy_orf_accu_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_accuracy_orf_accu_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_maze_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_maze_national_norm_percentile",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_comprehension_maze_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_comprehension_maze_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_maze_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_fluency_orf_national_norm_percentile",
        "type": ["null", "double", "string"],
        "default": None,
    },
    {
        "name": "reading_fluency_orf_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_fluency_orf_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "word_reading_wrf_national_norm_percentile",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "word_reading_wrf_semester_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "word_reading_wrf_year_growth",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "client_date",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {
        "name": "date_of_birth",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {
        "name": "enrollment_date",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {
        "name": "sync_date",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
]

PM_STUDENT_SUMMARY_FIELDS = [
    {"name": "account_name", "type": ["null", "string"], "default": None},
    {"name": "alternate_assessment", "type": ["null", "string"], "default": None},
    {"name": "approved_accommodations", "type": ["null", "string"], "default": None},
    {"name": "assessing_teacher_name", "type": ["null", "string"], "default": None},
    {
        "name": "assessing_teacher_staff_id",
        "type": ["null", "double", "string"],
        "default": None,
    },
    {"name": "assessment_edition", "type": ["null", "string"], "default": None},
    {"name": "assessment_grade", "type": ["null", "long", "string"], "default": None},
    {"name": "assessment", "type": ["null", "string"], "default": None},
    {"name": "classed", "type": ["null", "string"], "default": None},
    {"name": "disability", "type": ["null", "string"], "default": None},
    {"name": "district_name", "type": ["null", "string"], "default": None},
    {"name": "district_primary_id", "type": ["null", "string"], "default": None},
    {"name": "economically_disadvantaged", "type": ["null", "string"], "default": None},
    {"name": "ell_status", "type": ["null", "string"], "default": None},
    {"name": "english_proficiency", "type": ["null", "string"], "default": None},
    {"name": "enrollment_grade", "type": ["null", "long", "string"], "default": None},
    {"name": "external_program", "type": ["null", "string"], "default": None},
    {"name": "gender", "type": ["null", "string"], "default": None},
    {"name": "home_language", "type": ["null", "string"], "default": None},
    {"name": "internal_program", "type": ["null", "string"], "default": None},
    {"name": "meal_status", "type": ["null", "string"], "default": None},
    {"name": "measure", "type": ["null", "string"], "default": None},
    {"name": "migrant", "type": ["null", "string"], "default": None},
    {"name": "municipality_name", "type": ["null", "string"], "default": None},
    {"name": "municipality_primary_id", "type": ["null", "string"], "default": None},
    {"name": "official_teacher_name", "type": ["null", "string"], "default": None},
    {
        "name": "official_teacher_staff_id",
        "type": ["null", "long", "string"],
        "default": None,
    },
    {"name": "pm_period", "type": ["null", "string"], "default": None},
    {"name": "primary_school_id", "type": ["null", "string"], "default": None},
    {"name": "probe_number", "type": ["null", "long"], "default": None},
    {"name": "race", "type": ["null", "string"], "default": None},
    {"name": "reporting_class_id", "type": ["null", "string"], "default": None},
    {"name": "reporting_class_name", "type": ["null", "string"], "default": None},
    {"name": "school_name", "type": ["null", "string"], "default": None},
    {"name": "school_year", "type": ["null", "string"], "default": None},
    {"name": "score_change", "type": ["null", "string", "double"], "default": None},
    {"name": "score", "type": ["null", "long", "double"], "default": None},
    {"name": "secondary_school_id", "type": ["null", "string"], "default": None},
    {"name": "section_504", "type": ["null", "string"], "default": None},
    {"name": "special_education", "type": ["null", "string"], "default": None},
    {"name": "specific_disability", "type": ["null", "string"], "default": None},
    {"name": "state", "type": ["null", "string"], "default": None},
    {"name": "student_first_name", "type": ["null", "string"], "default": None},
    {"name": "student_last_name", "type": ["null", "string"], "default": None},
    {"name": "student_middle_name", "type": ["null", "string"], "default": None},
    {"name": "student_primary_id", "type": ["null", "long"], "default": None},
    {"name": "title_1", "type": ["null", "string"], "default": None},
    {"name": "total_number_of_probes", "type": ["null", "long"], "default": None},
    {
        "name": "primary_id_student_id_district_id",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "student_id_state_id", "type": ["null", "long"], "default": None},
    {
        "name": "client_date",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {
        "name": "date_of_birth",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {
        "name": "enrollment_date",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {
        "name": "sync_date",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
]

ASSET_FIELDS = {
    "benchmark_student_summary": BENCHMARK_STUDENT_SUMMARY_FIELDS,
    "pm_student_summary": PM_STUDENT_SUMMARY_FIELDS,
}
