with
    simple_view as (
        select
            cast(
                replace(replace(last_submitted_time, 'T', ' '), 'Z', '') as datetime
            ) as last_submitted_time,
            respondent_email,
            rn_form_respondent_submitted_desc,
            rn_form_item_respondent_submitted_desc,
            item_abbreviation,
            coalesce(text_value, file_upload_file_id) as value
        from {{ ref("base_google_forms__form_responses") }}
        where form_id = '1jpeMof_oQ9NzTw85VFsA5A7G9VrH3XkSc_nZDFz07nA'
    ),
    full_data as (

        select
            regexp_extract(respondent_name, r'\((\d{6})\)') as employee_number,
            last_submitted_time,
            respondent_email,
            respondent_name,
            -- multiselect_options
            string_agg(languages_spoken) as languages_spoken,
            string_agg(replace(relay_status, ',', '.')) as relay_status,
            string_agg(
                replace(
                    community_grew_up,
                    'Newark, Camden, and/or Miami',
                    'the cities we serve'
                )
            ) as community_grew_up,
            string_agg(
                replace(
                    community_professional_exp,
                    'Newark, Camden, and/or Miami',
                    'the cities we serve'
                )
            ) as community_professional_exp,
            string_agg(race_ethnicity) as race_ethnicity,
            string_agg(replace(alumni_status, ',', '.')) as alumni_status,
            string_agg(replace(path_to_education, ',', '.')) as path_to_education,
            -- single select options
            nj_cert_document_link_2,
            cert_required,
            nj_cert_additional_1,
            fl_additional_cert_1,
            cert_status,
            nj_cert_document_link_5,
            nj_cert_document_link_4,
            nj_cert_issue_date_5,
            fl_open_to_student_teacher,
            cert_barriers,
            nj_cert_issue_date_2,
            fl_cert_expiration_5,
            nj_cert_document_link_3,
            nj_cert_endorsement_5,
            nj_cert_type_2,
            level_of_education,
            fl_cert_expiration_3,
            nj_cert_type_1,
            nj_cert_endorsement_2,
            nj_cert_type_4,
            nj_cert_document_link_1,
            cast(years_teaching_outside_njfl as int64) as years_teaching_outside_njfl,
            nj_cert_endorsement_1,
            fl_cert_endorsement_1,
            fl_cert_endorsement_5,
            nj_cert_type_3,
            fl_cert_expiration_2,
            nj_cert_type_5,
            fl_cert_expiration_1,
            fl_cert_endorsement_4,
            additional_languages,
            nj_cert_issue_date_4,
            cast(years_teaching_in_njfl as int64) as years_teaching_in_njfl,
            fl_cert_expiration_4,
            undergraduate_school,
            nj_cert_issue_date_3,
            fl_cert_endorsement_2,
            nj_cert_endorsement_3,
            nj_cert_issue_date_1,
            fl_cert_endorsement_3,
            cert_steps_taken,
            nj_cert_endorsement_4,
            cert_out_of_state_details,
            gender_identity
        from
            simple_view pivot (
                max(value) for item_abbreviation in (
                    'nj_cert_document_link_2',
                    'cert_required',
                    'nj_cert_additional_1',
                    'fl_additional_cert_1',
                    'cert_status',
                    'nj_cert_document_link_5',
                    'respondent_name',
                    'nj_cert_document_link_4',
                    'nj_cert_issue_date_5',
                    'fl_open_to_student_teacher',
                    'cert_barriers',
                    'nj_cert_issue_date_2',
                    'fl_cert_expiration_5',
                    'nj_cert_document_link_3',
                    'nj_cert_endorsement_5',
                    'nj_cert_type_2',
                    'path_to_education',
                    'community_grew_up',
                    'relay_status',
                    'fl_cert_expiration_3',
                    'nj_cert_type_1',
                    'nj_cert_endorsement_2',
                    'nj_cert_type_4',
                    'nj_cert_document_link_1',
                    'years_teaching_outside_njfl',
                    'nj_cert_endorsement_1',
                    'fl_cert_endorsement_1',
                    'fl_cert_endorsement_5',
                    'nj_cert_type_3',
                    'fl_cert_expiration_2',
                    'nj_cert_type_5',
                    'fl_cert_expiration_1',
                    'race_ethnicity',
                    'languages_spoken',
                    'fl_cert_endorsement_4',
                    'additional_languages',
                    'nj_cert_issue_date_4',
                    'years_teaching_in_njfl',
                    'fl_cert_expiration_4',
                    'undergraduate_school',
                    'nj_cert_issue_date_3',
                    'fl_cert_endorsement_2',
                    'community_professional_exp',
                    'alumni_status',
                    'nj_cert_endorsement_3',
                    'nj_cert_issue_date_1',
                    'fl_cert_endorsement_3',
                    'cert_steps_taken',
                    'nj_cert_endorsement_4',
                    'cert_out_of_state_details',
                    'gender_identity',
                    'level_of_education'
                )
            )
        group by
            last_submitted_time,
            respondent_email,
            rn_form_respondent_submitted_desc,
            respondent_name,
            nj_cert_document_link_2,
            cert_required,
            nj_cert_additional_1,
            fl_additional_cert_1,
            cert_status,
            nj_cert_document_link_5,
            nj_cert_document_link_4,
            nj_cert_issue_date_5,
            fl_open_to_student_teacher,
            cert_barriers,
            nj_cert_issue_date_2,
            fl_cert_expiration_5,
            nj_cert_document_link_3,
            nj_cert_endorsement_5,
            nj_cert_type_2,
            fl_cert_expiration_3,
            nj_cert_type_1,
            nj_cert_endorsement_2,
            nj_cert_type_4,
            nj_cert_document_link_1,
            years_teaching_outside_njfl,
            nj_cert_endorsement_1,
            fl_cert_endorsement_1,
            fl_cert_endorsement_5,
            nj_cert_type_3,
            fl_cert_expiration_2,
            nj_cert_type_5,
            fl_cert_expiration_1,
            fl_cert_endorsement_4,
            additional_languages,
            nj_cert_issue_date_4,
            years_teaching_in_njfl,
            fl_cert_expiration_4,
            undergraduate_school,
            nj_cert_issue_date_3,
            fl_cert_endorsement_2,
            nj_cert_endorsement_3,
            nj_cert_issue_date_1,
            fl_cert_endorsement_3,
            cert_steps_taken,
            nj_cert_endorsement_4,
            cert_out_of_state_details,
            gender_identity,
            level_of_education

        union distinct

        select
            regexp_extract(respondent_name, r'\((\d{6})\)') as employee_number,
            cast(
                timestamp as datetime format 'MM/DD/YYYY HH24:MI:SS'
            ) as last_submitted_time,
            respondent_email,
            respondent_name,
            -- multiselect_options
            languages_spoken,
            relay_status,
            community_grew_up,
            community_professional_experience as community_professional_exp,
            race_ethnicity,
            alumni_status,
            path_to_education,
            -- single select options
            nj_cert_document_link_2,
            cast(cert_required as string) as cert_required,
            nj_cert_additional_1,
            fl_additional_cert_1,
            cert_status,
            nj_cert_document_link_5,
            nj_cert_document_link_4,
            nj_cert_issue_date_5,
            fl_open_to_student_teacher,
            cert_barriers,
            nj_cert_issue_date_2,
            fl_cert_expiration_5,
            nj_cert_document_link_3,
            nj_cert_endorsement_5,
            nj_cert_type_2,
            level_of_education,
            fl_cert_expiration_3,
            nj_cert_type_1,
            nj_cert_endorsement_2,
            nj_cert_type_4,
            nj_cert_document_link_1,
            years_teaching_outside_njfl,
            nj_cert_endorsement_1,
            fl_cert_endorsement_1,
            fl_cert_endorsement_5,
            nj_cert_type_3,
            fl_cert_expiration_2,
            nj_cert_type_5,
            fl_cert_expiration_1,
            fl_cert_endorsement_4,
            additional_languages,
            nj_cert_issue_date_4,
            years_teaching_in_njfl,
            fl_cert_expiration_4,
            undergraduate_school,
            nj_cert_issue_date_3,
            fl_cert_endorsement_2,
            nj_cert_endorsement_3,
            nj_cert_issue_date_1,
            fl_cert_endorsement_3,
            cert_steps_taken,
            nj_cert_endorsement_4,
            cert_out_of_state_details,
            gender_identity

        from `teamster-332318.kipptaf_surveys.src_surveys__staff_info_certification`
    )

select
    *,
    row_number() over (
        partition by employee_number order by last_submitted_time desc
    ) as rn_submission
from full_data
