with
    combined_years as (
        select
            student_id,
            psat89_2025_id as id,
            psat89_2025_formcode as form_code,
            psat89_2025_newdistrict_id as new_district_id,
            psat89_2025_cbstudentid as cb_student_id,
            psat89_2025_district_student_id as district_student_id,
            psat89_2025_local_student_id as local_student_id,
            psat89_2025_state_student_id as state_student_id,
            psat89_2025_newssid as new_ssid,
            psat89_2025_gradeassessed as grade_assessed,
            psat89_2025_testdate as test_date,
            psat89_2025_reportdate as report_date,
            psat89_2025_selfassessmentdate as self_assessment_date,
            psat89_2025_gpa as gpa,
            psat89_2025_student_first_name as student_first_name,
            psat89_2025_student_last_name as student_last_name,
            psat89_2025_student_middle_initial as student_middle_initial,
            psat89_2025_cohortyear as cohort_year,
            psat89_2025_birthdate as birth_date,
            psat89_2025_latestpsataccesscode as latest_psat_access_code,
            psat89_2025_sectionindex as selection_index,
            psat89_2025_hsstudent as hs_student,
            psat89_2025_ebrwccrbenchmark as ebrw_ccr_benchmark,
            psat89_2025_mathccrbenchmark as math_ccr_benchmark,
            psat89_2025_totalscore as total_score,
            psat89_2025_historycrosstestscore as history_cross_test_score,
            psat89_2025_mathtestscore as math_test_score,
            psat89_2025_readingtestscore as reading_test_score,
            psat89_2025_sciencecrosstestscore as science_cross_test_score,
            psat89_2025_writingtestscore as writing_test_score,
            psat89_2025_ebreadwritesectionscore as eb_read_write_section_score,
            psat89_2025_mathsectionscore as math_section_score,
            psat89_2025_mathtestscore as advanced_math_subscore,
            psat89_2025_commandevidencesubscore as command_evidence_subscore,
            psat89_2025_englishconvsubscore as english_conv_subscore,
            psat89_2025_expressionideassubscore as expression_ideas_subscore,
            psat89_2025_heartalgebrasubscore as heart_algebra_subscore,
            psat89_2025_probsolvedatasubscore as prob_solve_data_subscore,
            psat89_2025_relevantwordssubscore as relevant_words_subscore,
            psat89_2025_algebrareppercentile as algebra_rep_percentile,
            psat89_2025_commandreppercentile as command_rep_percentile,
            psat89_2025_ebrwreppercentile as ebrw_rep_percentile,
            psat89_2025_engconventionsreppercentile as eng_conventions_rep_percentile,
            psat89_2025_expressionideareppercentile as expression_idea_rep_percentile,
            psat89_2025_histreppercentile as hist_rep_percentile,
            psat89_2025_mathreppercentile as math_rep_percentile,
            psat89_2025_mathsectreppercentile as math_sect_rep_percentile,
            psat89_2025_problemsolvereppercentile as problem_solve_rep_percentile,
            psat89_2025_readingreppercentile as reading_rep_percentile,
            psat89_2025_scireppercentile as sci_rep_percentile,
            psat89_2025_totalreppercentile as total_rep_percentile,
            psat89_2025_wordscontextreppercentile as words_context_rep_percentile,
            psat89_2025_writinglangreppercentile as writing_lang_rep_percentile,
            psat89_2025_ksmathadvancedscore as advanced_math_usr_percentile,
            psat89_2025_algebrausrpercentile as algebra_usr_percentile,
            psat89_2025_commandusrpercentile as command_usr_percentile,
            psat89_2025_ebrwusrpercentile as ebrw_usr_percentile,
            psat89_2025_engconventionsusrpercentile as eng_conventions_usr_percentile,
            psat89_2025_expressionideausrpercentile as expression_idea_usr_percentile,
            psat89_2025_histusrpercentile as hist_usr_percentile,
            psat89_2025_mathsectusrpercentile as math_sect_usr_percentile,
            psat89_2025_mathusrpercentile as math_usr_percentile,
            psat89_2025_problemsolveusrpercentile as problem_solve_usr_percentile,
            psat89_2025_readingusrpercentile as reading_usr_percentile,
            psat89_2025_sciusrpercentile as sci_usr_percentile,
            psat89_2025_totalusrpercentile as total_usr_percentile,
            psat89_2025_wordscontextusrpercentile as words_context_usr_percentile,
            psat89_2025_writinglangusrpercentile as writing_lang_usr_percentile,
            psat89_2025_aparthist as ap_art_hist,
            psat89_2025_apeurohist as ap_euro_hist,
            psat89_2025_aphumgeo as ap_hum_geo,
            psat89_2025_apphysii as ap_phys_ii,
            psat89_2025_apseminar as ap_seminar,
            psat89_2025_apworldhist as ap_world_hist,
        from {{ source("illuminate_national_assessments", "psat89_2025") }}
    )

select
    id,
    form_code,
    cb_student_id,
    district_student_id,
    state_student_id,
    new_district_id,
    new_ssid,
    grade_assessed,
    test_date,
    report_date,
    self_assessment_date,
    gpa,
    student_first_name,
    student_last_name,
    student_middle_initial,
    cohort_year,
    birth_date,
    latest_psat_access_code,
    hs_student,
    ebrw_ccr_benchmark,
    math_ccr_benchmark,
    algebra_rep_percentile,
    command_rep_percentile,
    ebrw_rep_percentile,
    eng_conventions_rep_percentile,
    expression_idea_rep_percentile,
    hist_rep_percentile,
    math_rep_percentile,
    math_sect_rep_percentile,
    problem_solve_rep_percentile,
    reading_rep_percentile,
    sci_rep_percentile,
    total_rep_percentile,
    words_context_rep_percentile,
    writing_lang_rep_percentile,
    algebra_usr_percentile,
    command_usr_percentile,
    ebrw_usr_percentile,
    eng_conventions_usr_percentile,
    expression_idea_usr_percentile,
    hist_usr_percentile,
    math_sect_usr_percentile,
    math_usr_percentile,
    problem_solve_usr_percentile,
    reading_usr_percentile,
    sci_usr_percentile,
    total_usr_percentile,
    words_context_usr_percentile,
    writing_lang_usr_percentile,
    ap_art_hist,
    ap_euro_hist,
    ap_hum_geo,
    ap_phys_ii,
    ap_seminar,
    ap_world_hist,

    safe_cast(local_student_id as int) as local_student_id,

    safe_cast(selection_index as numeric) as selection_index,
    safe_cast(total_score as numeric) as total_score,
    safe_cast(math_test_score as numeric) as math_test_score,
    safe_cast(history_cross_test_score as numeric) as history_cross_test_score,
    safe_cast(reading_test_score as numeric) as reading_test_score,
    safe_cast(science_cross_test_score as numeric) as science_cross_test_score,
    safe_cast(writing_test_score as numeric) as writing_test_score,
    safe_cast(eb_read_write_section_score as numeric) as eb_read_write_section_score,
    safe_cast(math_section_score as numeric) as math_section_score,
    safe_cast(advanced_math_subscore as numeric) as advanced_math_subscore,
    safe_cast(command_evidence_subscore as numeric) as command_evidence_subscore,
    safe_cast(english_conv_subscore as numeric) as english_conv_subscore,
    safe_cast(expression_ideas_subscore as numeric) as expression_ideas_subscore,
    safe_cast(heart_algebra_subscore as numeric) as heart_algebra_subscore,
    safe_cast(prob_solve_data_subscore as numeric) as prob_solve_data_subscore,
    safe_cast(relevant_words_subscore as numeric) as relevant_words_subscore,

    {{
        date_to_fiscal_year(
            date_field="test_date", start_month=7, year_source="start"
        )
    }} as academic_year,
from combined_years
