EMPLOYEE_FIELDS = [
    {"name": "file", "type": ["null", "string"], "default": None},
    {"name": "line", "type": ["null", "long"], "default": None},
    {"name": "df_employee_number", "type": ["null", "long"], "default": None},
    {"name": "preferred_last_name", "type": ["null", "string"], "default": None},
    {"name": "common_name", "type": ["null", "string"], "default": None},
    {"name": "last_name", "type": ["null", "string"], "default": None},
    {"name": "first_name", "type": ["null", "string"], "default": None},
    {"name": "ethnicity", "type": ["null", "string"], "default": None},
    {"name": "gender", "type": ["null", "string"], "default": None},
    {
        "name": "primary_on_site_department_entity",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "primary_on_site_department", "type": ["null", "string"], "default": None},
    {"name": "primary_site_entity", "type": ["null", "string"], "default": None},
    {"name": "primary_site", "type": ["null", "string"], "default": None},
    {"name": "legal_entity_name", "type": ["null", "string"], "default": None},
    {"name": "primary_job", "type": ["null", "string"], "default": None},
    {"name": "position_title", "type": ["null", "string"], "default": None},
    {"name": "status", "type": ["null", "string"], "default": None},
    {"name": "status_reason", "type": ["null", "string"], "default": None},
    {"name": "mobile_number", "type": ["null", "string"], "default": None},
    {"name": "address", "type": ["null", "string"], "default": None},
    {"name": "city", "type": ["null", "string"], "default": None},
    {"name": "state", "type": ["null", "string"], "default": None},
    {"name": "postal_code", "type": ["null", "double"], "default": None},
    {"name": "paytype", "type": ["null", "string"], "default": None},
    {"name": "payclass", "type": ["null", "string"], "default": None},
    {
        "name": "jobs_and_positions_flsa_status",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "is_manager", "type": ["null", "string"], "default": None},
    {
        "name": "employee_s_manager_s_df_emp_number_id",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "salesforce_id", "type": ["null", "string"], "default": None},
    {"name": "adp_associate_id", "type": ["null", "string"], "default": None},
    {"name": "grades_taught", "type": ["null", "string"], "default": None},
    {"name": "subjects_taught", "type": ["null", "string"], "default": None},
    {"name": "job_family", "type": ["null", "string"], "default": None},
    {"name": "annual_salary", "type": ["null", "double"], "default": None},
    {
        "name": "primary_on_site_department_clean",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "primary_site_clean", "type": ["null", "string"], "default": None},
    {"name": "legal_entity_name_clean", "type": ["null", "string"], "default": None},
    {"name": "adp_associate_id_clean", "type": ["null", "string"], "default": None},
    {"name": "birth_date", "type": ["null", "string"], "default": None},
    {"name": "original_hire_date", "type": ["null", "string"], "default": None},
    {
        "name": "position_effective_from_date",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "position_effective_to_date", "type": ["null", "string"], "default": None},
    {"name": "rehire_date", "type": ["null", "string"], "default": None},
    {"name": "termination_date", "type": ["null", "string"], "default": None},
    {"name": "fivetran_synced", "type": ["null", "string"], "default": None},
    {"name": "modified", "type": ["null", "string"], "default": None},
]

ASSET_FIELDS = {
    "employees": EMPLOYEE_FIELDS,
}
