with
    deduplicate as (
        {{
            dbt_utils.deduplicate(
                relation=source("powerschool", "src_powerschool__sections"),
                partition_by="dcid.int_value",
                order_by="_file_name desc",
            )
        }}
    )

-- trunk-ignore(sqlfluff/AM04)
select
    * except (
        dcid,
        id,
        teacher,
        termid,
        no_of_students,
        schoolid,
        noofterms,
        trackteacheratt,
        maxenrollment,
        distuniqueid,
        wheretaught,
        rostermodser,
        pgversion,
        grade_level,
        campusid,
        exclude_ada,
        gradescaleid,
        excludefromgpa,
        buildid,
        schedulesectionid,
        wheretaughtdistrict,
        excludefromclassrank,
        excludefromhonorroll,
        parent_section_id,
        attendance_type_code,
        maxcut,
        exclude_state_rpt_yn,
        sortorder,
        programid,
        excludefromstoredgrades,
        gradebooktype,
        whomodifiedid
    ),

    /* column transformations */
    dcid.int_value as dcid,
    id.int_value as id,
    teacher.int_value as teacher,
    termid.int_value as termid,
    no_of_students.int_value as no_of_students,
    schoolid.int_value as schoolid,
    noofterms.int_value as noofterms,
    trackteacheratt.int_value as trackteacheratt,
    maxenrollment.int_value as maxenrollment,
    distuniqueid.int_value as distuniqueid,
    wheretaught.int_value as wheretaught,
    rostermodser.int_value as rostermodser,
    pgversion.int_value as pgversion,
    grade_level.int_value as grade_level,
    campusid.int_value as campusid,
    exclude_ada.int_value as exclude_ada,
    gradescaleid.int_value as gradescaleid,
    excludefromgpa.int_value as excludefromgpa,
    buildid.int_value as buildid,
    schedulesectionid.int_value as schedulesectionid,
    wheretaughtdistrict.int_value as wheretaughtdistrict,
    excludefromclassrank.int_value as excludefromclassrank,
    excludefromhonorroll.int_value as excludefromhonorroll,
    parent_section_id.int_value as parent_section_id,
    attendance_type_code.int_value as attendance_type_code,
    maxcut.int_value as maxcut,
    exclude_state_rpt_yn.int_value as exclude_state_rpt_yn,
    sortorder.int_value as sortorder,
    programid.int_value as programid,
    excludefromstoredgrades.int_value as excludefromstoredgrades,
    gradebooktype.int_value as gradebooktype,
    whomodifiedid.int_value as whomodifiedid,
from deduplicate
