select
    student_number,
    s_nj_stu_x__referral_date,
    s_nj_stu_x__parental_consent_eval_date,
    s_nj_stu_x__eligibility_determ_date,
    s_nj_stu_x__early_intervention_yn,
    s_nj_stu_x__initial_iep_meeting_date,
    s_nj_stu_x__parent_consent_obtain_code,
    s_nj_stu_x__parent_consent_intial_iep_date,
    s_nj_stu_x__annual_iep_review_meeting_date,
    s_nj_stu_x__specialed_classification,
    s_nj_stu_x__reevaluation_date,
    s_nj_stu_x__initial_process_delay_reason,
    s_nj_stu_x__special_education_placement,
    s_nj_stu_x__time_in_regular_program,
    s_nj_stu_x__counseling_services_yn,
    s_nj_stu_x__occupational_therapy_serv_yn,
    s_nj_stu_x__physical_therapy_services_yn,
    s_nj_stu_x__speech_lang_theapy_services_yn,
    s_nj_stu_x__other_related_services_yn,
    studentcorefields__spedlep,
    s_nj_stu_x__determined_ineligible_yn,
from {{ source("kipptaf_extracts", "rpt_powerschool__autocomm_students_iep") }}
where code_location = '{{ project_name }}'
