select
    {{ dbt_utils.generate_surrogate_key(["application_id"]) }}
    as job_candidate_application_key,

    {{ dbt_utils.generate_surrogate_key(["candidate_id"]) }} as job_candidate_key,

    {{
        dbt_utils.generate_surrogate_key(
            ["job_title", "department_internal", "job_city"]
        )
    }} as job_posting_key,

    new_date as created_date_key,

    application_id,
    candidate_id,
    job_title,
    department_internal,
    department_org_field_value,
    job_city,
    recruiters,
    application_state,
    application_status,
    application_custom_step,
    application_reason_for_rejection,
    application_reason_for_withdrawal,
    application_status_before_rejection,
    application_status_before_withdrawal,
    candidate_source,
    candidate_source_type,
    candidate_source_subtype,
    source,
    source_type,
    source_subtype,
    subject_preference,
    school_shared_with,
    average_rating,
    resume_score,

    new_date,
    new_datetime,
    lead_date,
    lead_datetime,
    hired_date,
    hired_datetime,
    offer_date,
    offer_datetime,
    rejected_date,
    rejected_datetime,
    last_update_date,
    last_update_datetime,
    demo_date,
    demo_datetime,
    phone_screen_requested_date,
    phone_screen_requested_datetime,
    phone_screen_complete_date,
    phone_screen_complete_datetime,
    invited_to_selection_day_date,
    invited_to_selection_day_datetime,
    selection_day_date,
    selection_day_datetime,

    time_in_application_state_new,
    time_in_application_state_lead,
    time_in_application_state_in_review,
    time_in_application_state_interview,
    time_in_application_state_offered,
    time_in_application_status_in_review_resume_review,
    time_in_application_status_interview_demo,
    time_in_application_status_interview_phone_screen_requested,
    time_in_application_status_interview_phone_screen_complete,

    application_state_in_review_date,
    application_state_interview_date,
    application_state_transferred_date,
    application_state_withdrawn_date,
    application_status_in_review_performance_task_date,
    application_status_in_review_resume_review_date,
    application_status_interview_performance_task_date,

    application_field_application_review_score,
    application_field_job_title,
    application_field_phone_interview_score,
    application_url,
from {{ ref("stg_smartrecruiters__applications") }}
