#!/bin/bash

LOCATION_NAME_UPPER=${DAGSTER_LOCATION_NAME^^}

PS_SSH_PASSWORD=${LOCATION_NAME_UPPER}_PS_SSH_PASSWORD
PS_SSH_USERNAME=${LOCATION_NAME_UPPER}_PS_SSH_USERNAME
PS_SSH_HOST=${LOCATION_NAME_UPPER}_PS_SSH_HOST
PS_SSH_PORT=${LOCATION_NAME_UPPER}_PS_SSH_PORT
PS_SSH_REMOTE_BIND_HOST=${LOCATION_NAME_UPPER}_PS_SSH_REMOTE_BIND_HOST

# start powerschool ssh tunnel
sshpass -p "${!PS_SSH_PASSWORD}" \
  ssh "${!PS_SSH_USERNAME}"@"${!PS_SSH_HOST}" \
  -p "${!PS_SSH_PORT}" \
  -L 1521:"${!PS_SSH_REMOTE_BIND_HOST}":1521 \
  -o StrictHostKeyChecking=no \
  -4fN

# Run the passed-in Dagster CMD
exec "$@"
