select
    /* records */
    id.int_value as id,
    studentsdcid.int_value as studentsdcid,
    gpnodeid.int_value as gpnodeid,
    nodetype.int_value as nodetype,
    isadvancedplan.int_value as isadvancedplan,
    issinglesitting.int_value as issinglesitting,
    issummation.int_value as issummation,
    isgroupsatisfied.int_value as isgroupsatisfied,
    istestgroupwaived.int_value as istestgroupwaived,
    mingpamet.int_value as mingpamet,
    testnodepassed.int_value as testnodepassed,
    requiredcredits.double_value as requiredcredits,
    enrolledcredits.double_value as enrolledcredits,
    requestedcredits.double_value as requestedcredits,
    earnedcredits.double_value as earnedcredits,
    waivedcredits.double_value as waivedcredits,
    appliedwaivedcredits.double_value as appliedwaivedcredits,
    nodegpa.double_value as nodegpa,
from {{ source("powerschool_odbc", "src_powerschool__gpprogresssubject") }}
