select
    * except (islimitcategoryeditable, islimitcategoryenabled) replace (
        defaultdecimalcount.int_value as defaultdecimalcount,
        gradeschoolconfigid.int_value as gradeschoolconfigid,
        iscalcformulaeditable.int_value as iscalcformulaeditable,
        iscalcmetriceditable.int_value as iscalcmetriceditable,
        iscalcmetricschooledit.int_value as iscalcmetricschooledit,
        iscalcprecisioneditable.int_value as iscalcprecisioneditable,
        iscitizenshipdisplayed.int_value as iscitizenshipdisplayed,
        isdropscoreeditable.int_value as isdropscoreeditable,
        isgradescaleteachereditable.int_value as isgradescaleteachereditable,
        ishigherstndautocalc.int_value as ishigherstndautocalc,
        ishigherstndcalceditable.int_value as ishigherstndcalceditable,
        ishighstandardeditable.int_value as ishighstandardeditable,
        ismulticategoryallowed.int_value as ismulticategoryallowed,
        ismulticategoryeditable.int_value as ismulticategoryeditable,
        isrecentscoreeditable.int_value as isrecentscoreeditable,
        issectstndweighteditable.int_value as issectstndweighteditable,
        isstandardslimited.int_value as isstandardslimited,
        isstandardslimitededitable.int_value as isstandardslimitededitable,
        isstandardsshown.int_value as isstandardsshown,
        isstandardsshownonasgmt.int_value as isstandardsshownonasgmt,
        istraditionalgradeshown.int_value as istraditionalgradeshown,
        isusingpercentforstndautocalc.int_value as isusingpercentforstndautocalc,
        lockwarningoffset.int_value as lockwarningoffset,
        minimumassignmentvalue.int_value as minimumassignmentvalue,
        schoolsdcid.int_value as schoolsdcid,
        termbinlockoffset.int_value as termbinlockoffset,
        yearid.int_value as yearid
    ),
from {{ source("powerschool_odbc", "src_powerschool__gradeschoolconfig") }}
