select
    * except (
        `status`,
        add_to_gpa,
        credit_hours,
        crhrweight,
        custom,
        dcid,
        exclude_ada,
        excludefromclassrank,
        excludefromgpa,
        excludefromhonorroll,
        excludefromstoredgrades,
        executionid,
        gpa_addedvalue,
        gradescaleid,
        id,
        iscareertech,
        isfitnesscourse,
        ispewaiver,
        maxclasssize,
        maxcredit,
        programid,
        regavailable,
        sched_balanceterms,
        sched_blockstart,
        sched_closesectionaftermax,
        sched_concurrentflag,
        sched_consecutiveperiods,
        sched_consecutiveterms,
        sched_coursepackage,
        sched_do_not_print,
        sched_frequency,
        sched_labflag,
        sched_labfrequency,
        sched_labperiodspermeeting,
        sched_lengthinnumberofterms,
        sched_loadpriority,
        sched_lunchcourse,
        sched_maximumdayspercycle,
        sched_maximumenrollment,
        sched_maximumperiodsperday,
        sched_minimumdayspercycle,
        sched_minimumperiodsperday,
        sched_multiplerooms,
        sched_periodspercycle,
        sched_periodspermeeting,
        sched_repeatsallowed,
        sched_scheduled,
        sched_sectionsoffered,
        sched_substitutionallowed,
        sched_teachercount,
        sched_usepreestablishedteams,
        sched_usesectiontypes,
        sched_year,
        schoolgroup,
        schoolid,
        sectionstooffer,
        targetclasssize,
        vocational,
        whomodifiedid
    ),

    /* column transformations */
    dcid.int_value as dcid,
    id.int_value as id,
    credit_hours.double_value as credit_hours,
    add_to_gpa.double_value as add_to_gpa,
    schoolid.int_value as schoolid,
    regavailable.int_value as regavailable,
    targetclasssize.int_value as targetclasssize,
    maxclasssize.int_value as maxclasssize,
    sectionstooffer.int_value as sectionstooffer,
    schoolgroup.int_value as schoolgroup,
    vocational.int_value as vocational,
    status.int_value as status,
    crhrweight.double_value as crhrweight,
    sched_year.int_value as sched_year,
    sched_coursepackage.int_value as sched_coursepackage,
    sched_scheduled.int_value as sched_scheduled,
    sched_sectionsoffered.int_value as sched_sectionsoffered,
    sched_teachercount.int_value as sched_teachercount,
    sched_periodspermeeting.int_value as sched_periodspermeeting,
    sched_frequency.int_value as sched_frequency,
    sched_maximumperiodsperday.int_value as sched_maximumperiodsperday,
    sched_minimumperiodsperday.int_value as sched_minimumperiodsperday,
    sched_maximumdayspercycle.int_value as sched_maximumdayspercycle,
    sched_minimumdayspercycle.int_value as sched_minimumdayspercycle,
    sched_consecutiveperiods.int_value as sched_consecutiveperiods,
    sched_blockstart.int_value as sched_blockstart,
    sched_lengthinnumberofterms.int_value as sched_lengthinnumberofterms,
    sched_consecutiveterms.int_value as sched_consecutiveterms,
    sched_balanceterms.int_value as sched_balanceterms,
    sched_maximumenrollment.int_value as sched_maximumenrollment,
    sched_concurrentflag.int_value as sched_concurrentflag,
    sched_multiplerooms.int_value as sched_multiplerooms,
    sched_labflag.int_value as sched_labflag,
    sched_labfrequency.int_value as sched_labfrequency,
    sched_labperiodspermeeting.int_value as sched_labperiodspermeeting,
    sched_repeatsallowed.int_value as sched_repeatsallowed,
    sched_loadpriority.int_value as sched_loadpriority,
    sched_substitutionallowed.int_value as sched_substitutionallowed,
    sched_usepreestablishedteams.int_value as sched_usepreestablishedteams,
    sched_closesectionaftermax.int_value as sched_closesectionaftermax,
    sched_usesectiontypes.int_value as sched_usesectiontypes,
    sched_periodspercycle.int_value as sched_periodspercycle,
    gradescaleid.int_value as gradescaleid,
    gpa_addedvalue.double_value as gpa_addedvalue,
    excludefromgpa.int_value as excludefromgpa,
    excludefromclassrank.int_value as excludefromclassrank,
    excludefromhonorroll.int_value as excludefromhonorroll,
    sched_lunchcourse.int_value as sched_lunchcourse,
    sched_do_not_print.int_value as sched_do_not_print,
    exclude_ada.int_value as exclude_ada,
    programid.int_value as programid,
    excludefromstoredgrades.int_value as excludefromstoredgrades,
    maxcredit.double_value as maxcredit,
    iscareertech.int_value as iscareertech,
    whomodifiedid.int_value as whomodifiedid,
    isfitnesscourse.int_value as isfitnesscourse,
    ispewaiver.int_value as ispewaiver,
from {{ source("powerschool_odbc", "src_powerschool__courses") }}
