PARCC_FIELDS = [
    {"name": "accountabledistrictcode", "type": ["null", "long"], "default": None},
    {"name": "accountabledistrictname", "type": ["null", "string"], "default": None},
    {
        "name": "accountableorganizationaltype",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "accountableschoolcode", "type": ["null", "long"], "default": None},
    {"name": "accountableschoolname", "type": ["null", "string"], "default": None},
    {
        "name": "administrationdirectionsclarifiedinstudentsnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "administrationdirectionsreadaloudinstudentsnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "alternaterepresentationpapertest",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "americanindianoralaskanative",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "answermasking", "type": ["null", "string"], "default": None},
    {
        "name": "answersrecordedintestbooklet",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "asian", "type": ["null", "string"], "default": None},
    {"name": "aslvideo", "type": ["null", "string"], "default": None},
    {"name": "assessmentgrade", "type": ["null", "string"], "default": None},
    {"name": "assessmentyear", "type": ["null", "string"], "default": None},
    {
        "name": "assistivetechnologynonscreenreader",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "assistivetechnologyscreenreader",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "batteryformid", "type": ["null", "string"], "default": None},
    {"name": "birthdate", "type": ["null", "string"], "default": None},
    {"name": "blackorafricanamerican", "type": ["null", "string"], "default": None},
    {"name": "braillewithtactilegraphics", "type": ["null", "string"], "default": None},
    {
        "name": "calculationdeviceandmathematicstools",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "classname", "type": ["null", "string"], "default": None},
    {"name": "closedcaptioningforela", "type": ["null", "string"], "default": None},
    {"name": "colorcontrast", "type": ["null", "double"], "default": None},
    {
        "name": "datefirstenrolledinusschool",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "economicdisadvantagestatus", "type": ["null", "string"], "default": None},
    {"name": "elaccommodation", "type": ["null", "string"], "default": None},
    {"name": "elaconstructedresponse", "type": ["null", "double"], "default": None},
    {
        "name": "elaselectedresponseortechnologyenhanceditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "electronicbrailleresponse", "type": ["null", "string"], "default": None},
    {"name": "elexemptfromtakingela", "type": ["null", "string"], "default": None},
    {"name": "emergencyaccommodation", "type": ["null", "double"], "default": None},
    {
        "name": "englishlearneraccommodatedresponses",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "englishlearnerel", "type": ["null", "string"], "default": None},
    {"name": "extendedtime", "type": ["null", "string"], "default": None},
    {"name": "federalraceethnicity", "type": ["null", "long"], "default": None},
    {"name": "filler10", "type": ["null", "string"], "default": None},
    {"name": "filler11", "type": ["null", "string"], "default": None},
    {"name": "filler12", "type": ["null", "string"], "default": None},
    {"name": "filler13", "type": ["null", "string"], "default": None},
    {"name": "filler14", "type": ["null", "string"], "default": None},
    {"name": "filler15", "type": ["null", "string"], "default": None},
    {"name": "filler16", "type": ["null", "string"], "default": None},
    {"name": "filler17", "type": ["null", "string"], "default": None},
    {"name": "filler18", "type": ["null", "string"], "default": None},
    {"name": "filler19", "type": ["null", "string"], "default": None},
    {"name": "filler2", "type": ["null", "string"], "default": None},
    {"name": "filler20", "type": ["null", "string"], "default": None},
    {"name": "filler21", "type": ["null", "string"], "default": None},
    {"name": "filler22", "type": ["null", "string"], "default": None},
    {"name": "filler23", "type": ["null", "string"], "default": None},
    {"name": "filler24", "type": ["null", "string"], "default": None},
    {"name": "filler25", "type": ["null", "string"], "default": None},
    {"name": "filler26", "type": ["null", "string"], "default": None},
    {"name": "filler3", "type": ["null", "string"], "default": None},
    {"name": "filler4", "type": ["null", "string"], "default": None},
    {"name": "filler5", "type": ["null", "string"], "default": None},
    {"name": "filler6", "type": ["null", "string"], "default": None},
    {"name": "filler7", "type": ["null", "string"], "default": None},
    {"name": "filler8", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_1", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_10", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_11", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_12", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_13", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_14", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_15", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_2", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_3", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_4", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_5", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_6", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_7", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_8", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_9", "type": ["null", "string"], "default": None},
    {"name": "fillerfield", "type": ["null", "string"], "default": None},
    {
        "name": "firsthighschoolmathassessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "firstname", "type": ["null", "string"], "default": None},
    {"name": "formeriep", "type": ["null", "string"], "default": None},
    {"name": "frequentbreaks", "type": ["null", "string"], "default": None},
    {"name": "gender", "type": ["null", "string"], "default": None},
    {"name": "gradelevelwhenassessed", "type": ["null", "long"], "default": None},
    {"name": "hispanicorlatinoethnicity", "type": ["null", "string"], "default": None},
    {"name": "home_language", "type": ["null", "string"], "default": None},
    {"name": "homeless", "type": ["null", "string"], "default": None},
    {"name": "humanreaderorhumansigner", "type": ["null", "double"], "default": None},
    {
        "name": "humansignerfortestdirections",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "iepexemptfrompassing", "type": ["null", "string"], "default": None},
    {"name": "largeprint", "type": ["null", "string"], "default": None},
    {"name": "lastorsurname", "type": ["null", "string"], "default": None},
    {"name": "localstudentidentifier", "type": ["null", "double"], "default": None},
    {
        "name": "mathematicsscienceaccommodatedresponse",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "middlename", "type": ["null", "string"], "default": None},
    {"name": "migrantstatus", "type": ["null", "string"], "default": None},
    {"name": "monitortestresponse", "type": ["null", "string"], "default": None},
    {"name": "multipletestregistration", "type": ["null", "string"], "default": None},
    {
        "name": "nativehawaiianorotherpacificislander",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "njelstatus", "type": ["null", "string"], "default": None},
    {"name": "njnotattemptflag", "type": ["null", "string"], "default": None},
    {"name": "nottestedcode", "type": ["null", "string"], "default": None},
    {"name": "nottestedreason", "type": ["null", "double"], "default": None},
    {"name": "onlinepcr1", "type": ["null", "string"], "default": None},
    {"name": "onlinepcr2", "type": ["null", "string"], "default": None},
    {"name": "paperattemptcreatedate", "type": ["null", "string"], "default": None},
    {"name": "paperformid", "type": ["null", "string"], "default": None},
    {"name": "paperpcr1", "type": ["null", "double"], "default": None},
    {"name": "paperpcr2", "type": ["null", "double"], "default": None},
    {
        "name": "papersection1numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "papersection1totaltestitems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "papersection2numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "papersection2totaltestitems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "papersection3numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "papersection3totaltestitems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "papersection4numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "papersection4totaltestitems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "period", "type": ["null", "string"], "default": None},
    {"name": "primarydisabilitytype", "type": ["null", "string"], "default": None},
    {"name": "refreshablebrailledisplay", "type": ["null", "string"], "default": None},
    {"name": "reportsuppressionaction", "type": ["null", "string"], "default": None},
    {"name": "reportsuppressioncode", "type": ["null", "string"], "default": None},
    {"name": "retest", "type": ["null", "string"], "default": None},
    {"name": "rosterflag", "type": ["null", "string"], "default": None},
    {"name": "separatealternatelocation", "type": ["null", "string"], "default": None},
    {
        "name": "shipreportdistrictcode",
        "type": ["null", "long", "float"],
        "default": None,
    },
    {"name": "shipreportschoolcode", "type": ["null", "long"], "default": None},
    {"name": "smallgrouptesting", "type": ["null", "string"], "default": None},
    {"name": "spanishtransadaptation", "type": ["null", "string"], "default": None},
    {"name": "specialeducationplacement", "type": ["null", "double"], "default": None},
    {
        "name": "specializedequipmentorfurniture",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "specifiedareaorsetting", "type": ["null", "string"], "default": None},
    {
        "name": "speechtotextandwordprediction",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "staffmemberidentifier",
        "type": ["null", "double", "string"],
        "default": None,
    },
    {"name": "statestudentidentifier", "type": ["null", "long"], "default": None},
    {
        "name": "studentassessmentidentifier",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "studentreadsassessmentaloudtoself",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "studenttestuuid", "type": ["null", "string"], "default": None},
    {"name": "studentunit1testuuid", "type": ["null", "string"], "default": None},
    {"name": "studentunit2testuuid", "type": ["null", "string"], "default": None},
    {"name": "studentunit3testuuid", "type": ["null", "string"], "default": None},
    {"name": "studentuuid", "type": ["null", "string"], "default": None},
    {"name": "studentwithdisabilities", "type": ["null", "string"], "default": None},
    {"name": "subclaim1category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim1categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim2category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim2categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim3category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim3categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim4category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim4categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim5category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim5categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subject", "type": ["null", "string"], "default": None},
    {"name": "summativeflag", "type": ["null", "string"], "default": None},
    {"name": "testadministration", "type": ["null", "string"], "default": None},
    {
        "name": "testadministrator",
        "type": ["null", "double", "string"],
        "default": None,
    },
    {"name": "testattemptednessflag", "type": ["null", "string"], "default": None},
    {"name": "testcode", "type": ["null", "string"], "default": None},
    {"name": "testcsemprobablerange", "type": ["null", "double"], "default": None},
    {
        "name": "testcsemprobablerangeifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testingdistrictcode", "type": ["null", "long"], "default": None},
    {"name": "testingdistrictname", "type": ["null", "string"], "default": None},
    {"name": "testingorganizationaltype", "type": ["null", "long"], "default": None},
    {"name": "testingschoolcode", "type": ["null", "long"], "default": None},
    {"name": "testingschoolname", "type": ["null", "string"], "default": None},
    {"name": "testperformancelevel", "type": ["null", "double"], "default": None},
    {
        "name": "testperformancelevelifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testreadingcsem", "type": ["null", "double"], "default": None},
    {
        "name": "testreadingcsemifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testreadingscalescore", "type": ["null", "double"], "default": None},
    {
        "name": "testreadingscalescoreifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testscalescore", "type": ["null", "double"], "default": None},
    {
        "name": "testscalescoreifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testscorecomplete", "type": ["null", "double"], "default": None},
    {"name": "teststatus", "type": ["null", "string"], "default": None},
    {"name": "testwritingcsem", "type": ["null", "double"], "default": None},
    {
        "name": "testwritingcsemifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testwritingscalescore", "type": ["null", "double"], "default": None},
    {
        "name": "testwritingscalescoreifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "texttospeech", "type": ["null", "double"], "default": None},
    {"name": "timeofday", "type": ["null", "string"], "default": None},
    {"name": "totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "totaltestitemsattempted", "type": ["null", "double"], "default": None},
    {"name": "twoormoreraces", "type": ["null", "string"], "default": None},
    {"name": "uniqueaccommodation", "type": ["null", "string"], "default": None},
    {"name": "unit1formid", "type": ["null", "string"], "default": None},
    {
        "name": "unit1numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "unit1onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit1onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit1totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "unit2formid", "type": ["null", "string"], "default": None},
    {
        "name": "unit2numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "unit2onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit2onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit2totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "unit3formid", "type": ["null", "string"], "default": None},
    {
        "name": "unit3numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "unit3onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit3onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit3totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "voidscorecode", "type": ["null", "string"], "default": None},
    {"name": "voidscorereason", "type": ["null", "double"], "default": None},
    {"name": "white", "type": ["null", "string"], "default": None},
    {"name": "wordprediction", "type": ["null", "string"], "default": None},
    {
        "name": "wordtoworddictionaryenglishnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "languagecode", "type": ["null", "string"], "default": None},
    {
        "name": "elalselectedresponseortechnologyenhanceditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "elalconstructedresponse", "type": ["null", "double"], "default": None},
    {"name": "sex", "type": ["null", "string"], "default": None},
    {"name": "elexemptfromtakingelal", "type": ["null", "string"], "default": None},
    {"name": "filler1", "type": ["null", "string"], "default": None},
    {"name": "closedcaptioningforelal", "type": ["null", "string"], "default": None},
    {"name": "answersrecordedintestbook", "type": ["null", "string"], "default": None},
    {"name": "brailleresponse", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_16", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_17", "type": ["null", "string"], "default": None},
    {"name": "fillerfield1", "type": ["null", "string"], "default": None},
    {"name": "fillerfield2", "type": ["null", "string"], "default": None},
    {"name": "fillerfield4", "type": ["null", "string"], "default": None},
    {"name": "fillerfield5", "type": ["null", "string"], "default": None},
    {"name": "fillerfield7", "type": ["null", "string"], "default": None},
    {"name": "giftedandtalented", "type": ["null", "string"], "default": None},
    {"name": "mathematicsresponse", "type": ["null", "double"], "default": None},
    {"name": "mathematicsresponseel", "type": ["null", "string"], "default": None},
    {"name": "onlineformid", "type": ["null", "string"], "default": None},
    {"name": "parccstudentidentifier", "type": ["null", "string"], "default": None},
    {"name": "percentofitemsattempted", "type": ["null", "string"], "default": None},
    {
        "name": "refreshablebrailledisplayforelal",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "responsibleaccountabledistrictcode",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "responsibleaccountableschoolcode",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "responsibledistrictname", "type": ["null", "string"], "default": None},
    {
        "name": "responsibleorganizationaltype",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "responsibleschoolname", "type": ["null", "string"], "default": None},
    {
        "name": "spanishtransadaptationofthemathematicsassessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "stateabbreviation", "type": ["null", "string"], "default": None},
    {"name": "statefield1", "type": ["null", "string"], "default": None},
    {"name": "statefield10", "type": ["null", "string"], "default": None},
    {"name": "statefield11", "type": ["null", "string"], "default": None},
    {"name": "statefield12", "type": ["null", "string"], "default": None},
    {"name": "statefield13", "type": ["null", "string"], "default": None},
    {"name": "statefield14", "type": ["null", "string"], "default": None},
    {"name": "statefield15", "type": ["null", "string"], "default": None},
    {"name": "statefield2", "type": ["null", "string"], "default": None},
    {"name": "statefield3", "type": ["null", "string"], "default": None},
    {"name": "statefield4", "type": ["null", "string"], "default": None},
    {"name": "statefield5", "type": ["null", "string"], "default": None},
    {"name": "statefield6", "type": ["null", "double", "string"], "default": None},
    {"name": "statefield7", "type": ["null", "double"], "default": None},
    {"name": "statefield8", "type": ["null", "double"], "default": None},
    {"name": "statefield9", "type": ["null", "double"], "default": None},
    {"name": "studentunit4testuuid", "type": ["null", "string"], "default": None},
    {
        "name": "titleiiilimitedenglishproficientparticipationstatus",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit4formid", "type": ["null", "string"], "default": None},
    {
        "name": "unit4numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "unit4onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit4onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit4totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "wordpredictionforelal", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_18", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_19", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_20", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_21", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_22", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_23", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_24", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_25", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_26", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_27", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_28", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_29", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_30", "type": ["null", "string"], "default": None},
    {"name": "responsibledistrictcode", "type": ["null", "long"], "default": None},
    {"name": "responsibleschoolcode", "type": ["null", "long"], "default": None},
    {"name": "smalltestinggroup", "type": ["null", "string"], "default": None},
    {
        "name": "studentreadsassessmentaloudtothemselves",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "attemptcreatedate", "type": ["null", "string"], "default": None},
    {"name": "filler", "type": ["null", "string"], "default": None},
    {"name": "filler_1", "type": ["null", "string"], "default": None},
    {"name": "filler_10", "type": ["null", "string"], "default": None},
    {"name": "filler_11", "type": ["null", "string"], "default": None},
    {"name": "filler_2", "type": ["null", "string"], "default": None},
    {"name": "filler_3", "type": ["null", "string"], "default": None},
    {"name": "filler_4", "type": ["null", "string"], "default": None},
    {"name": "filler_5", "type": ["null", "string"], "default": None},
    {"name": "filler_6", "type": ["null", "string"], "default": None},
    {"name": "filler_7", "type": ["null", "string"], "default": None},
    {"name": "filler_8", "type": ["null", "string"], "default": None},
    {"name": "filler_9", "type": ["null", "string"], "default": None},
    {"name": "paperunit1totaltestitems", "type": ["null", "string"], "default": None},
    {
        "name": "responsibleorganizationcodetype",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "subclaim6category", "type": ["null", "string"], "default": None},
    {
        "name": "translationofthemathematicsassessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "filler27", "type": ["null", "string"], "default": None},
    {"name": "filler28", "type": ["null", "string"], "default": None},
    {"name": "filler29", "type": ["null", "string"], "default": None},
    {"name": "filler30", "type": ["null", "string"], "default": None},
    {"name": "filler31", "type": ["null", "string"], "default": None},
    {"name": "filler32", "type": ["null", "string"], "default": None},
    {"name": "filler33", "type": ["null", "string"], "default": None},
    {"name": "filler34", "type": ["null", "string"], "default": None},
    {"name": "filler35", "type": ["null", "string"], "default": None},
    {"name": "filler36", "type": ["null", "string"], "default": None},
    {"name": "filler37", "type": ["null", "string"], "default": None},
    {"name": "filler38", "type": ["null", "string"], "default": None},
    {"name": "filler39", "type": ["null", "string"], "default": None},
]

NJSLA_FIELDS = [
    {"name": "accountabledistrictcode", "type": ["null", "long"], "default": None},
    {"name": "accountabledistrictname", "type": ["null", "string"], "default": None},
    {
        "name": "accountableorganizationaltype",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "accountableschoolcode", "type": ["null", "long"], "default": None},
    {"name": "accountableschoolname", "type": ["null", "string"], "default": None},
    {
        "name": "administrationdirectionsclarifiedinstudentsnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "administrationdirectionsreadaloudinstudentsnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "alternaterepresentationpapertest",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "americanindianoralaskanative",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "answermasking", "type": ["null", "string"], "default": None},
    {
        "name": "answersrecordedintestbooklet",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "answersrecordedintest_booklet",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "asian", "type": ["null", "string"], "default": None},
    {"name": "aslvideo", "type": ["null", "string"], "default": None},
    {"name": "assessmentgrade", "type": ["null", "string"], "default": None},
    {"name": "assessmentyear", "type": ["null", "string"], "default": None},
    {
        "name": "assistivetechnologynonscreenreader",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "assistivetechnologyscreenreader",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "birthdate", "type": ["null", "string"], "default": None},
    {"name": "blackorafricanamerican", "type": ["null", "string"], "default": None},
    {"name": "braillewithtactilegraphics", "type": ["null", "string"], "default": None},
    {"name": "claimcode", "type": ["null", "string"], "default": None},
    {"name": "classname", "type": ["null", "string"], "default": None},
    {"name": "colorcontrast", "type": ["null", "double"], "default": None},
    {
        "name": "critiquingpracticesperformancelevel",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "datefirstenrolledinusschool",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "earthandspacescienceperformancelevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "economicdisadvantagestatus", "type": ["null", "string"], "default": None},
    {"name": "elaccommodation", "type": ["null", "string"], "default": None},
    {"name": "electronicbrailleresponse", "type": ["null", "string"], "default": None},
    {"name": "emergencyaccommodation", "type": ["null", "double"], "default": None},
    {
        "name": "englishlearneraccommodatedresponses",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "englishlearnerel", "type": ["null", "string"], "default": None},
    {"name": "extendedtime", "type": ["null", "string"], "default": None},
    {"name": "federalraceethnicity", "type": ["null", "long"], "default": None},
    {"name": "filler_1", "type": ["null", "string"], "default": None},
    {"name": "filler_10", "type": ["null", "string"], "default": None},
    {"name": "filler_11", "type": ["null", "string"], "default": None},
    {"name": "filler_12", "type": ["null", "string"], "default": None},
    {"name": "filler_13", "type": ["null", "string"], "default": None},
    {"name": "filler_14", "type": ["null", "string"], "default": None},
    {"name": "filler_15", "type": ["null", "string"], "default": None},
    {"name": "filler_16", "type": ["null", "string"], "default": None},
    {"name": "filler_17", "type": ["null", "string"], "default": None},
    {"name": "filler_18", "type": ["null", "string"], "default": None},
    {"name": "filler_19", "type": ["null", "string"], "default": None},
    {"name": "filler_2", "type": ["null", "string"], "default": None},
    {"name": "filler_20", "type": ["null", "string"], "default": None},
    {"name": "filler_21", "type": ["null", "string"], "default": None},
    {"name": "filler_22", "type": ["null", "string"], "default": None},
    {"name": "filler_23", "type": ["null", "string"], "default": None},
    {"name": "filler_24", "type": ["null", "string"], "default": None},
    {"name": "filler_25", "type": ["null", "string"], "default": None},
    {"name": "filler_26", "type": ["null", "string"], "default": None},
    {"name": "filler_27", "type": ["null", "string"], "default": None},
    {"name": "filler_28", "type": ["null", "string"], "default": None},
    {"name": "filler_29", "type": ["null", "string"], "default": None},
    {"name": "filler_3", "type": ["null", "string"], "default": None},
    {"name": "filler_30", "type": ["null", "string"], "default": None},
    {"name": "filler_31", "type": ["null", "string"], "default": None},
    {"name": "filler_32", "type": ["null", "string"], "default": None},
    {"name": "filler_33", "type": ["null", "string"], "default": None},
    {"name": "filler_34", "type": ["null", "string"], "default": None},
    {"name": "filler_35", "type": ["null", "string"], "default": None},
    {"name": "filler_36", "type": ["null", "string"], "default": None},
    {"name": "filler_37", "type": ["null", "string"], "default": None},
    {"name": "filler_38", "type": ["null", "string"], "default": None},
    {"name": "filler_39", "type": ["null", "string"], "default": None},
    {"name": "filler_4", "type": ["null", "string"], "default": None},
    {"name": "filler_40", "type": ["null", "string"], "default": None},
    {"name": "filler_41", "type": ["null", "string"], "default": None},
    {"name": "filler_42", "type": ["null", "string"], "default": None},
    {"name": "filler_43", "type": ["null", "string"], "default": None},
    {"name": "filler_44", "type": ["null", "string"], "default": None},
    {"name": "filler_45", "type": ["null", "string"], "default": None},
    {"name": "filler_46", "type": ["null", "string"], "default": None},
    {"name": "filler_47", "type": ["null", "string"], "default": None},
    {"name": "filler_48", "type": ["null", "string"], "default": None},
    {"name": "filler_49", "type": ["null", "string"], "default": None},
    {"name": "filler_5", "type": ["null", "string"], "default": None},
    {"name": "filler_50", "type": ["null", "string"], "default": None},
    {"name": "filler_51", "type": ["null", "string"], "default": None},
    {"name": "filler_52", "type": ["null", "string"], "default": None},
    {"name": "filler_53", "type": ["null", "string"], "default": None},
    {"name": "filler_54", "type": ["null", "string"], "default": None},
    {"name": "filler_55", "type": ["null", "string"], "default": None},
    {"name": "filler_56", "type": ["null", "string"], "default": None},
    {"name": "filler_57", "type": ["null", "string"], "default": None},
    {"name": "filler_58", "type": ["null", "string"], "default": None},
    {"name": "filler_59", "type": ["null", "string"], "default": None},
    {"name": "filler_6", "type": ["null", "string"], "default": None},
    {"name": "filler_60", "type": ["null", "string"], "default": None},
    {"name": "filler_61", "type": ["null", "string"], "default": None},
    {"name": "filler_62", "type": ["null", "string"], "default": None},
    {"name": "filler_63", "type": ["null", "string"], "default": None},
    {"name": "filler_64", "type": ["null", "string"], "default": None},
    {"name": "filler_65", "type": ["null", "string"], "default": None},
    {"name": "filler_66", "type": ["null", "string"], "default": None},
    {"name": "filler_67", "type": ["null", "string"], "default": None},
    {"name": "filler_68", "type": ["null", "string"], "default": None},
    {"name": "filler_69", "type": ["null", "string"], "default": None},
    {"name": "filler_7", "type": ["null", "string"], "default": None},
    {"name": "filler_70", "type": ["null", "string"], "default": None},
    {"name": "filler_71", "type": ["null", "string"], "default": None},
    {"name": "filler_72", "type": ["null", "string"], "default": None},
    {"name": "filler_73", "type": ["null", "string"], "default": None},
    {"name": "filler_74", "type": ["null", "string"], "default": None},
    {"name": "filler_75", "type": ["null", "string"], "default": None},
    {"name": "filler_76", "type": ["null", "string"], "default": None},
    {"name": "filler_77", "type": ["null", "string"], "default": None},
    {"name": "filler_78", "type": ["null", "string"], "default": None},
    {"name": "filler_79", "type": ["null", "string"], "default": None},
    {"name": "filler_8", "type": ["null", "string"], "default": None},
    {"name": "filler_80", "type": ["null", "string"], "default": None},
    {"name": "filler_81", "type": ["null", "string"], "default": None},
    {"name": "filler_82", "type": ["null", "string"], "default": None},
    {"name": "filler_83", "type": ["null", "string"], "default": None},
    {"name": "filler_84", "type": ["null", "string"], "default": None},
    {"name": "filler_9", "type": ["null", "string"], "default": None},
    {"name": "filler", "type": ["null", "string"], "default": None},
    {
        "name": "firsthighschoolmathassessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "firstname", "type": ["null", "string"], "default": None},
    {"name": "formeriep", "type": ["null", "string"], "default": None},
    {"name": "formid", "type": ["null", "string"], "default": None},
    {"name": "frequentbreaks", "type": ["null", "string"], "default": None},
    {"name": "gender", "type": ["null", "string"], "default": None},
    {"name": "gradelevelwhenassessed", "type": ["null", "long"], "default": None},
    {"name": "hispanicorlatinoethnicity", "type": ["null", "string"], "default": None},
    {"name": "homelanguage", "type": ["null", "string"], "default": None},
    {"name": "homeless", "type": ["null", "string"], "default": None},
    {"name": "humanreaderorhumansigner", "type": ["null", "double"], "default": None},
    {
        "name": "humansignerfortestdirections",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "investigatingpracticesperformancelevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "largeprint", "type": ["null", "string"], "default": None},
    {"name": "lastorsurname", "type": ["null", "string"], "default": None},
    {
        "name": "lifescienceperformancelevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "localstudentidentifier", "type": ["null", "long"], "default": None},
    {
        "name": "mathematicsscienceaccommodatedresponse",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "middlename", "type": ["null", "string"], "default": None},
    {"name": "migrantstatus", "type": ["null", "string"], "default": None},
    {"name": "monitortestresponse", "type": ["null", "string"], "default": None},
    {"name": "multipletestregistration", "type": ["null", "string"], "default": None},
    {
        "name": "nativehawaiianorotherpacificislander",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "njelstatus", "type": ["null", "string"], "default": None},
    {"name": "nottestedcode", "type": ["null", "string"], "default": None},
    {"name": "nottestedreason", "type": ["null", "double"], "default": None},
    {"name": "percentofitemsattempted", "type": ["null", "long"], "default": None},
    {"name": "period", "type": ["null", "string"], "default": None},
    {
        "name": "physicalscienceperformancelevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "primarydisabilitytype", "type": ["null", "string"], "default": None},
    {"name": "reportsuppressionaction", "type": ["null", "string"], "default": None},
    {"name": "reportsuppressioncode", "type": ["null", "string"], "default": None},
    {"name": "retest", "type": ["null", "string"], "default": None},
    {"name": "rosterflag", "type": ["null", "string"], "default": None},
    {
        "name": "sensemakingpracticesperformancelevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "separatealternatelocation", "type": ["null", "string"], "default": None},
    {"name": "shipreportdistrictcode", "type": ["null", "long"], "default": None},
    {"name": "shipreportschoolcode", "type": ["null", "long"], "default": None},
    {"name": "smallgrouptesting", "type": ["null", "string"], "default": None},
    {"name": "spanishtransadaptation", "type": ["null", "string"], "default": None},
    {"name": "specialeducationplacement", "type": ["null", "double"], "default": None},
    {
        "name": "specializedequipmentorfurniture",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "specifiedareaorsetting", "type": ["null", "string"], "default": None},
    {
        "name": "speechtotextandwordprediction",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "staffmemberidentifier", "type": ["null", "double"], "default": None},
    {"name": "statestudentidentifier", "type": ["null", "long"], "default": None},
    {
        "name": "studentassessmentidentifier",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "studentreadsassessmentaloudtoself",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "studenttestuuid", "type": ["null", "string"], "default": None},
    {"name": "studentuuid", "type": ["null", "string"], "default": None},
    {"name": "studentwithdisabilities", "type": ["null", "string"], "default": None},
    {"name": "subject", "type": ["null", "string"], "default": None},
    {"name": "summativeflag", "type": ["null", "string"], "default": None},
    {"name": "testadministration", "type": ["null", "string"], "default": None},
    {"name": "testadministrator", "type": ["null", "double"], "default": None},
    {"name": "testattemptednessflag", "type": ["null", "string"], "default": None},
    {"name": "testcode", "type": ["null", "string"], "default": None},
    {"name": "testcsemprobablerange", "type": ["null", "double"], "default": None},
    {"name": "testformat", "type": ["null", "string"], "default": None},
    {"name": "testingdistrictcode", "type": ["null", "long"], "default": None},
    {"name": "testingdistrictname", "type": ["null", "string"], "default": None},
    {"name": "testingorganizationaltype", "type": ["null", "long"], "default": None},
    {"name": "testingschoolcode", "type": ["null", "long"], "default": None},
    {"name": "testingschoolname", "type": ["null", "string"], "default": None},
    {"name": "testperformancelevel", "type": ["null", "double"], "default": None},
    {"name": "testscalescore", "type": ["null", "double"], "default": None},
    {"name": "testscorecomplete", "type": ["null", "double"], "default": None},
    {"name": "teststatus", "type": ["null", "string"], "default": None},
    {"name": "texttospeech", "type": ["null", "double"], "default": None},
    {"name": "timeofday", "type": ["null", "string"], "default": None},
    {"name": "totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "totaltestitemsattempted", "type": ["null", "double"], "default": None},
    {"name": "twoormoreraces", "type": ["null", "string"], "default": None},
    {"name": "uniqueaccommodation", "type": ["null", "string"], "default": None},
    {"name": "unit1onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit1onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit2onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit2onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit3onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit3onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit4onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit4onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "voidscorecode", "type": ["null", "string"], "default": None},
    {"name": "voidscorereason", "type": ["null", "double"], "default": None},
    {"name": "white", "type": ["null", "string"], "default": None},
    {"name": "wordprediction", "type": ["null", "string"], "default": None},
    {
        "name": "wordtoworddictionaryenglishnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "filler_85", "type": ["null", "string"], "default": None},
    {
        "name": "mathematics_scienceaccommodatedresponse",
        "type": ["null", "double"],
        "default": None,
    },
]

NJGPA_FIELDS = [
    {"name": "accountabledistrictcode", "type": ["null", "long"], "default": None},
    {"name": "accountabledistrictname", "type": ["null", "string"], "default": None},
    {
        "name": "accountableorganizationaltype",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "accountableschoolcode", "type": ["null", "long"], "default": None},
    {"name": "accountableschoolname", "type": ["null", "string"], "default": None},
    {
        "name": "administrationdirectionsclarifiedinstudentsnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "administrationdirectionsreadaloudinstudentsnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "alternaterepresentationpapertest",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "americanindianoralaskanative",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "answermasking", "type": ["null", "string"], "default": None},
    {
        "name": "answersrecordedintestbooklet",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "asian", "type": ["null", "string"], "default": None},
    {"name": "aslvideo", "type": ["null", "string"], "default": None},
    {"name": "assessmentgrade", "type": ["null", "string"], "default": None},
    {"name": "assessmentyear", "type": ["null", "string"], "default": None},
    {
        "name": "assistivetechnologynonscreenreader",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "assistivetechnologyscreenreader",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "batteryformid", "type": ["null", "string"], "default": None},
    {"name": "birthdate", "type": ["null", "string"], "default": None},
    {"name": "blackorafricanamerican", "type": ["null", "string"], "default": None},
    {"name": "braillewithtactilegraphics", "type": ["null", "string"], "default": None},
    {
        "name": "calculationdeviceandmathematicstools",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "classname", "type": ["null", "string"], "default": None},
    {"name": "closedcaptioningforela", "type": ["null", "string"], "default": None},
    {"name": "colorcontrast", "type": ["null", "string"], "default": None},
    {
        "name": "datefirstenrolledinusschool",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "economicdisadvantagestatus", "type": ["null", "string"], "default": None},
    {"name": "elaccommodation", "type": ["null", "string"], "default": None},
    {"name": "elaconstructedresponse", "type": ["null", "double"], "default": None},
    {
        "name": "elaselectedresponseortechnologyenhanceditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "electronicbrailleresponse", "type": ["null", "string"], "default": None},
    {"name": "elexemptfromtakingela", "type": ["null", "string"], "default": None},
    {"name": "emergencyaccommodation", "type": ["null", "string"], "default": None},
    {
        "name": "englishlearneraccommodatedresponses",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "englishlearnerel", "type": ["null", "string"], "default": None},
    {"name": "extendedtime", "type": ["null", "string"], "default": None},
    {"name": "federalraceethnicity", "type": ["null", "long"], "default": None},
    {"name": "filler10", "type": ["null", "string"], "default": None},
    {"name": "filler11", "type": ["null", "string"], "default": None},
    {"name": "filler12", "type": ["null", "string"], "default": None},
    {"name": "filler13", "type": ["null", "string"], "default": None},
    {"name": "filler14", "type": ["null", "string"], "default": None},
    {"name": "filler15", "type": ["null", "string"], "default": None},
    {"name": "filler16", "type": ["null", "string"], "default": None},
    {"name": "filler17", "type": ["null", "string"], "default": None},
    {"name": "filler18", "type": ["null", "string"], "default": None},
    {"name": "filler19", "type": ["null", "string"], "default": None},
    {"name": "filler2", "type": ["null", "string"], "default": None},
    {"name": "filler20", "type": ["null", "string"], "default": None},
    {"name": "filler21", "type": ["null", "string"], "default": None},
    {"name": "filler22", "type": ["null", "string"], "default": None},
    {"name": "filler23", "type": ["null", "string"], "default": None},
    {"name": "filler24", "type": ["null", "string"], "default": None},
    {"name": "filler25", "type": ["null", "string"], "default": None},
    {"name": "filler26", "type": ["null", "string"], "default": None},
    {"name": "filler3", "type": ["null", "string"], "default": None},
    {"name": "filler4", "type": ["null", "string"], "default": None},
    {"name": "filler5", "type": ["null", "string"], "default": None},
    {"name": "filler6", "type": ["null", "string"], "default": None},
    {"name": "filler7", "type": ["null", "string"], "default": None},
    {"name": "filler8", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_1", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_10", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_11", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_12", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_13", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_14", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_15", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_2", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_3", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_4", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_5", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_6", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_7", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_8", "type": ["null", "string"], "default": None},
    {"name": "fillerfield_9", "type": ["null", "string"], "default": None},
    {"name": "fillerfield", "type": ["null", "string"], "default": None},
    {
        "name": "firsthighschoolmathassessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "firstname", "type": ["null", "string"], "default": None},
    {"name": "formeriep", "type": ["null", "string"], "default": None},
    {"name": "frequentbreaks", "type": ["null", "string"], "default": None},
    {"name": "gender", "type": ["null", "string"], "default": None},
    {"name": "gradelevelwhenassessed", "type": ["null", "long"], "default": None},
    {"name": "hispanicorlatinoethnicity", "type": ["null", "string"], "default": None},
    {"name": "home_language", "type": ["null", "string"], "default": None},
    {"name": "homeless", "type": ["null", "string"], "default": None},
    {"name": "humanreaderorhumansigner", "type": ["null", "string"], "default": None},
    {
        "name": "humansignerfortestdirections",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "iepexemptfrompassing", "type": ["null", "string"], "default": None},
    {"name": "largeprint", "type": ["null", "string"], "default": None},
    {"name": "lastorsurname", "type": ["null", "string"], "default": None},
    {"name": "localstudentidentifier", "type": ["null", "long"], "default": None},
    {
        "name": "mathematicsscienceaccommodatedresponse",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "middlename", "type": ["null", "string"], "default": None},
    {"name": "migrantstatus", "type": ["null", "string"], "default": None},
    {"name": "monitortestresponse", "type": ["null", "string"], "default": None},
    {"name": "multipletestregistration", "type": ["null", "string"], "default": None},
    {
        "name": "nativehawaiianorotherpacificislander",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "njelstatus", "type": ["null", "string"], "default": None},
    {"name": "njnotattemptflag", "type": ["null", "string"], "default": None},
    {"name": "nottestedcode", "type": ["null", "string"], "default": None},
    {"name": "nottestedreason", "type": ["null", "double"], "default": None},
    {"name": "onlinepcr1", "type": ["null", "string"], "default": None},
    {"name": "onlinepcr2", "type": ["null", "string"], "default": None},
    {"name": "paperattemptcreatedate", "type": ["null", "string"], "default": None},
    {"name": "paperformid", "type": ["null", "string"], "default": None},
    {"name": "paperpcr1", "type": ["null", "string"], "default": None},
    {"name": "paperpcr2", "type": ["null", "string"], "default": None},
    {
        "name": "papersection1numberofattempteditems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "papersection1totaltestitems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "papersection2numberofattempteditems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "papersection2totaltestitems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "papersection3numberofattempteditems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "papersection3totaltestitems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "papersection4numberofattempteditems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "papersection4totaltestitems",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "period", "type": ["null", "string"], "default": None},
    {"name": "primarydisabilitytype", "type": ["null", "string"], "default": None},
    {"name": "refreshablebrailledisplay", "type": ["null", "string"], "default": None},
    {"name": "reportsuppressionaction", "type": ["null", "string"], "default": None},
    {"name": "reportsuppressioncode", "type": ["null", "string"], "default": None},
    {"name": "retest", "type": ["null", "string"], "default": None},
    {"name": "rosterflag", "type": ["null", "string"], "default": None},
    {"name": "separatealternatelocation", "type": ["null", "string"], "default": None},
    {"name": "shipreportdistrictcode", "type": ["null", "long"], "default": None},
    {"name": "shipreportschoolcode", "type": ["null", "long"], "default": None},
    {"name": "smallgrouptesting", "type": ["null", "string"], "default": None},
    {"name": "spanishtransadaptation", "type": ["null", "string"], "default": None},
    {"name": "specialeducationplacement", "type": ["null", "double"], "default": None},
    {
        "name": "specializedequipmentorfurniture",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "specifiedareaorsetting", "type": ["null", "string"], "default": None},
    {
        "name": "speechtotextandwordprediction",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "staffmemberidentifier",
        "type": ["null", "long", "double"],
        "default": None,
    },
    {"name": "statestudentidentifier", "type": ["null", "long"], "default": None},
    {
        "name": "studentassessmentidentifier",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "studentreadsassessmentaloudtoself",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "studenttestuuid", "type": ["null", "string"], "default": None},
    {"name": "studentunit1testuuid", "type": ["null", "string"], "default": None},
    {"name": "studentunit2testuuid", "type": ["null", "string"], "default": None},
    {"name": "studentunit3testuuid", "type": ["null", "string"], "default": None},
    {"name": "studentuuid", "type": ["null", "string"], "default": None},
    {"name": "studentwithdisabilities", "type": ["null", "string"], "default": None},
    {"name": "subclaim1category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim1categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim2category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim2categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim3category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim3categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim4category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim4categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subclaim5category", "type": ["null", "double"], "default": None},
    {
        "name": "subclaim5categoryifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "subject", "type": ["null", "string"], "default": None},
    {"name": "summativeflag", "type": ["null", "string"], "default": None},
    {"name": "testadministration", "type": ["null", "string"], "default": None},
    {"name": "testadministrator", "type": ["null", "long", "double"], "default": None},
    {"name": "testattemptednessflag", "type": ["null", "string"], "default": None},
    {"name": "testcode", "type": ["null", "string"], "default": None},
    {"name": "testcsemprobablerange", "type": ["null", "double"], "default": None},
    {
        "name": "testcsemprobablerangeifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testingdistrictcode", "type": ["null", "long"], "default": None},
    {"name": "testingdistrictname", "type": ["null", "string"], "default": None},
    {"name": "testingorganizationaltype", "type": ["null", "long"], "default": None},
    {"name": "testingschoolcode", "type": ["null", "long"], "default": None},
    {"name": "testingschoolname", "type": ["null", "string"], "default": None},
    {"name": "testperformancelevel", "type": ["null", "double"], "default": None},
    {
        "name": "testperformancelevelifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testreadingcsem", "type": ["null", "double"], "default": None},
    {
        "name": "testreadingcsemifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testreadingscalescore", "type": ["null", "double"], "default": None},
    {
        "name": "testreadingscalescoreifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testscalescore", "type": ["null", "double"], "default": None},
    {
        "name": "testscalescoreifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testscorecomplete", "type": ["null", "double"], "default": None},
    {"name": "teststatus", "type": ["null", "string"], "default": None},
    {"name": "testwritingcsem", "type": ["null", "double"], "default": None},
    {
        "name": "testwritingcsemifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "testwritingscalescore", "type": ["null", "double"], "default": None},
    {
        "name": "testwritingscalescoreifnotattempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "texttospeech", "type": ["null", "double"], "default": None},
    {"name": "timeofday", "type": ["null", "string"], "default": None},
    {"name": "totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "totaltestitemsattempted", "type": ["null", "double"], "default": None},
    {"name": "twoormoreraces", "type": ["null", "string"], "default": None},
    {"name": "uniqueaccommodation", "type": ["null", "string"], "default": None},
    {"name": "unit1formid", "type": ["null", "string"], "default": None},
    {
        "name": "unit1numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "unit1onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit1onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit1totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "unit2formid", "type": ["null", "string"], "default": None},
    {
        "name": "unit2numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "unit2onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit2onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit2totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "unit3formid", "type": ["null", "string"], "default": None},
    {
        "name": "unit3numberofattempteditems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "unit3onlinetestenddatetime", "type": ["null", "string"], "default": None},
    {
        "name": "unit3onlineteststartdatetime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "unit3totaltestitems", "type": ["null", "double"], "default": None},
    {"name": "voidscorecode", "type": ["null", "string"], "default": None},
    {"name": "voidscorereason", "type": ["null", "string"], "default": None},
    {"name": "white", "type": ["null", "string"], "default": None},
    {"name": "wordprediction", "type": ["null", "string"], "default": None},
    {
        "name": "wordtoworddictionaryenglishnativelanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "filler33", "type": ["null", "string"], "default": None},
    {"name": "filler39", "type": ["null", "string"], "default": None},
    {"name": "filler35", "type": ["null", "string"], "default": None},
    {"name": "filler34", "type": ["null", "string"], "default": None},
    {"name": "filler30", "type": ["null", "string"], "default": None},
    {"name": "filler32", "type": ["null", "string"], "default": None},
    {"name": "filler38", "type": ["null", "string"], "default": None},
    {"name": "filler29", "type": ["null", "string"], "default": None},
    {"name": "filler37", "type": ["null", "string"], "default": None},
    {"name": "filler28", "type": ["null", "string"], "default": None},
    {"name": "filler27", "type": ["null", "string"], "default": None},
    {"name": "filler36", "type": ["null", "string"], "default": None},
    {"name": "filler31", "type": ["null", "string"], "default": None},
]

ASSET_FIELDS = {
    "parcc": PARCC_FIELDS,
    "njsla": NJSLA_FIELDS,
    "njgpa": NJGPA_FIELDS,
}
