PARCC_FIELDS = [
    {"name": "AccountableDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "AccountableDistrictName", "type": ["null", "string"], "default": None},
    {
        "name": "AccountableOrganizationalType",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "AccountableSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "AccountableSchoolName", "type": ["null", "string"], "default": None},
    {
        "name": "AdministrationDirectionsClarifiedinStudentsNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AdministrationDirectionsReadAloudinStudentsNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AlternateRepresentationPaperTest",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AmericanIndianOrAlaskaNative",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "AnswerMasking", "type": ["null", "string"], "default": None},
    {
        "name": "AnswersRecordedinTestBooklet",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Asian", "type": ["null", "string"], "default": None},
    {"name": "ASLVideo", "type": ["null", "string"], "default": None},
    {"name": "AssessmentGrade", "type": ["null", "string"], "default": None},
    {"name": "AssessmentYear", "type": ["null", "string"], "default": None},
    {
        "name": "AssistiveTechnologyNonScreenReader",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AssistiveTechnologyScreenReader",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "BatteryFormID", "type": ["null", "string"], "default": None},
    {"name": "BirthDate", "type": ["null", "string"], "default": None},
    {"name": "BlackOrAfricanAmerican", "type": ["null", "string"], "default": None},
    {"name": "BrailleWithTactileGraphics", "type": ["null", "string"], "default": None},
    {
        "name": "CalculationDeviceAndMathematicsTools",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "ClassName", "type": ["null", "string"], "default": None},
    {"name": "ClosedCaptioningForELA", "type": ["null", "string"], "default": None},
    {"name": "ColorContrast", "type": ["null", "double"], "default": None},
    {
        "name": "DateFirstEnrolledinUSSchool",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "EconomicDisadvantageStatus", "type": ["null", "string"], "default": None},
    {"name": "ELAccommodation", "type": ["null", "string"], "default": None},
    {"name": "ELAConstructedResponse", "type": ["null", "double"], "default": None},
    {
        "name": "ELASelectedResponseOrTechnologyEnhancedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "ElectronicBrailleResponse", "type": ["null", "string"], "default": None},
    {"name": "ELExemptfromTakingELA", "type": ["null", "string"], "default": None},
    {"name": "EmergencyAccommodation", "type": ["null", "double"], "default": None},
    {
        "name": "EnglishLearnerAccommodatedResponses",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "EnglishLearnerEL", "type": ["null", "string"], "default": None},
    {"name": "ExtendedTime", "type": ["null", "string"], "default": None},
    {"name": "FederalRaceEthnicity", "type": ["null", "long"], "default": None},
    {"name": "Filler10", "type": ["null", "string"], "default": None},
    {"name": "Filler11", "type": ["null", "string"], "default": None},
    {"name": "Filler12", "type": ["null", "string"], "default": None},
    {"name": "Filler13", "type": ["null", "string"], "default": None},
    {"name": "Filler14", "type": ["null", "string"], "default": None},
    {"name": "Filler15", "type": ["null", "string"], "default": None},
    {"name": "Filler16", "type": ["null", "string"], "default": None},
    {"name": "Filler17", "type": ["null", "string"], "default": None},
    {"name": "Filler18", "type": ["null", "string"], "default": None},
    {"name": "Filler19", "type": ["null", "string"], "default": None},
    {"name": "Filler2", "type": ["null", "string"], "default": None},
    {"name": "Filler20", "type": ["null", "string"], "default": None},
    {"name": "Filler21", "type": ["null", "string"], "default": None},
    {"name": "Filler22", "type": ["null", "string"], "default": None},
    {"name": "Filler23", "type": ["null", "string"], "default": None},
    {"name": "Filler24", "type": ["null", "string"], "default": None},
    {"name": "Filler25", "type": ["null", "string"], "default": None},
    {"name": "Filler26", "type": ["null", "string"], "default": None},
    {"name": "Filler3", "type": ["null", "string"], "default": None},
    {"name": "Filler4", "type": ["null", "string"], "default": None},
    {"name": "Filler5", "type": ["null", "string"], "default": None},
    {"name": "Filler6", "type": ["null", "string"], "default": None},
    {"name": "Filler7", "type": ["null", "string"], "default": None},
    {"name": "Filler8", "type": ["null", "string"], "default": None},
    {"name": "FillerField.1", "type": ["null", "string"], "default": None},
    {"name": "FillerField.10", "type": ["null", "string"], "default": None},
    {"name": "FillerField.11", "type": ["null", "string"], "default": None},
    {"name": "FillerField.12", "type": ["null", "string"], "default": None},
    {"name": "FillerField.13", "type": ["null", "string"], "default": None},
    {"name": "FillerField.14", "type": ["null", "string"], "default": None},
    {"name": "FillerField.15", "type": ["null", "string"], "default": None},
    {"name": "FillerField.2", "type": ["null", "string"], "default": None},
    {"name": "FillerField.3", "type": ["null", "string"], "default": None},
    {"name": "FillerField.4", "type": ["null", "string"], "default": None},
    {"name": "FillerField.5", "type": ["null", "string"], "default": None},
    {"name": "FillerField.6", "type": ["null", "string"], "default": None},
    {"name": "FillerField.7", "type": ["null", "string"], "default": None},
    {"name": "FillerField.8", "type": ["null", "string"], "default": None},
    {"name": "FillerField.9", "type": ["null", "string"], "default": None},
    {"name": "FillerField", "type": ["null", "string"], "default": None},
    {
        "name": "FirstHighSchoolMathAssessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "FirstName", "type": ["null", "string"], "default": None},
    {"name": "FormerIEP", "type": ["null", "string"], "default": None},
    {"name": "FrequentBreaks", "type": ["null", "string"], "default": None},
    {"name": "Gender", "type": ["null", "string"], "default": None},
    {"name": "GradeLevelWhenAssessed", "type": ["null", "long"], "default": None},
    {"name": "HispanicOrLatinoEthnicity", "type": ["null", "string"], "default": None},
    {"name": "Home Language", "type": ["null", "string"], "default": None},
    {"name": "Homeless", "type": ["null", "string"], "default": None},
    {"name": "HumanReaderOrHumanSigner", "type": ["null", "double"], "default": None},
    {
        "name": "HumanSignerForTestDirections",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "IEPExemptFromPassing", "type": ["null", "string"], "default": None},
    {"name": "LargePrint", "type": ["null", "string"], "default": None},
    {"name": "LastOrSurname", "type": ["null", "string"], "default": None},
    {"name": "LocalStudentIdentifier", "type": ["null", "double"], "default": None},
    {
        "name": "MathematicsScienceAccommodatedResponse",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "MiddleName", "type": ["null", "string"], "default": None},
    {"name": "MigrantStatus", "type": ["null", "string"], "default": None},
    {"name": "MonitorTestResponse", "type": ["null", "string"], "default": None},
    {"name": "MultipleTestRegistration", "type": ["null", "string"], "default": None},
    {
        "name": "NativeHawaiianOrOtherPacificIslander",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "NJELStatus", "type": ["null", "string"], "default": None},
    {"name": "NJNotAttemptFlag", "type": ["null", "string"], "default": None},
    {"name": "NotTestedCode", "type": ["null", "string"], "default": None},
    {"name": "NotTestedReason", "type": ["null", "double"], "default": None},
    {"name": "OnlinePCR1", "type": ["null", "string"], "default": None},
    {"name": "OnlinePCR2", "type": ["null", "string"], "default": None},
    {"name": "PaperAttemptCreateDate", "type": ["null", "string"], "default": None},
    {"name": "PaperFormID", "type": ["null", "string"], "default": None},
    {"name": "PaperPCR1", "type": ["null", "double"], "default": None},
    {"name": "PaperPCR2", "type": ["null", "double"], "default": None},
    {
        "name": "PaperSection1NumberofAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "PaperSection1TotalTestItems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "PaperSection2NumberofAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "PaperSection2TotalTestItems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "PaperSection3NumberofAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "PaperSection3TotalTestItems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "PaperSection4NumberofAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "PaperSection4TotalTestItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Period", "type": ["null", "string"], "default": None},
    {"name": "PrimaryDisabilityType", "type": ["null", "string"], "default": None},
    {"name": "RefreshableBrailleDisplay", "type": ["null", "string"], "default": None},
    {"name": "ReportSuppressionAction", "type": ["null", "string"], "default": None},
    {"name": "ReportSuppressionCode", "type": ["null", "string"], "default": None},
    {"name": "Retest", "type": ["null", "string"], "default": None},
    {"name": "RosterFlag", "type": ["null", "string"], "default": None},
    {"name": "SeparateAlternateLocation", "type": ["null", "string"], "default": None},
    {"name": "ShipReportDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "ShipReportSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "SmallGroupTesting", "type": ["null", "string"], "default": None},
    {"name": "SpanishTransadaptation", "type": ["null", "string"], "default": None},
    {"name": "SpecialEducationPlacement", "type": ["null", "double"], "default": None},
    {
        "name": "SpecializedEquipmentOrFurniture",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "SpecifiedAreaOrSetting", "type": ["null", "string"], "default": None},
    {
        "name": "SpeechtoTextandWordPrediction",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "StaffMemberIdentifier",
        "type": ["null", "double", "string"],
        "default": None,
    },
    {"name": "StateStudentIdentifier", "type": ["null", "long"], "default": None},
    {
        "name": "StudentAssessmentIdentifier",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "StudentReadsAssessmentAloudtoSelf",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "StudentTestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUnit1TestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUnit2TestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUnit3TestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentWithDisabilities", "type": ["null", "string"], "default": None},
    {"name": "Subclaim1Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim1CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim2Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim2CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim3Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim3CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim4Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim4CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim5Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim5CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subject", "type": ["null", "string"], "default": None},
    {"name": "SummativeFlag", "type": ["null", "string"], "default": None},
    {"name": "TestAdministration", "type": ["null", "string"], "default": None},
    {
        "name": "TestAdministrator",
        "type": ["null", "double", "string"],
        "default": None,
    },
    {"name": "TestAttemptednessFlag", "type": ["null", "string"], "default": None},
    {"name": "TestCode", "type": ["null", "string"], "default": None},
    {"name": "TestCSEMProbableRange", "type": ["null", "double"], "default": None},
    {
        "name": "TestCSEMProbableRangeIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestingDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "TestingDistrictName", "type": ["null", "string"], "default": None},
    {"name": "TestingOrganizationalType", "type": ["null", "long"], "default": None},
    {"name": "TestingSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "TestingSchoolName", "type": ["null", "string"], "default": None},
    {"name": "TestPerformanceLevel", "type": ["null", "double"], "default": None},
    {
        "name": "TestPerformanceLevelIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestReadingCSEM", "type": ["null", "double"], "default": None},
    {
        "name": "TestReadingCSEMIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestReadingScaleScore", "type": ["null", "double"], "default": None},
    {
        "name": "TestReadingScaleScoreIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestScaleScore", "type": ["null", "double"], "default": None},
    {
        "name": "TestScaleScoreIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestScoreComplete", "type": ["null", "double"], "default": None},
    {"name": "TestStatus", "type": ["null", "string"], "default": None},
    {"name": "TestWritingCSEM", "type": ["null", "double"], "default": None},
    {
        "name": "TestWritingCSEMIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestWritingScaleScore", "type": ["null", "double"], "default": None},
    {
        "name": "TestWritingScaleScoreIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TextToSpeech", "type": ["null", "double"], "default": None},
    {"name": "TimeOfDay", "type": ["null", "string"], "default": None},
    {"name": "TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "TotalTestItemsAttempted", "type": ["null", "double"], "default": None},
    {"name": "TwoOrMoreRaces", "type": ["null", "string"], "default": None},
    {"name": "UniqueAccommodation", "type": ["null", "string"], "default": None},
    {"name": "Unit1FormID", "type": ["null", "string"], "default": None},
    {
        "name": "Unit1NumberofAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Unit1OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit1OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit1TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "Unit2FormID", "type": ["null", "string"], "default": None},
    {
        "name": "Unit2NumberOfAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Unit2OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit2OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit2TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "Unit3FormID", "type": ["null", "string"], "default": None},
    {
        "name": "Unit3NumberOfAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Unit3OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit3OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit3TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "VoidScoreCode", "type": ["null", "string"], "default": None},
    {"name": "VoidScoreReason", "type": ["null", "double"], "default": None},
    {"name": "White", "type": ["null", "string"], "default": None},
    {"name": "WordPrediction", "type": ["null", "string"], "default": None},
    {
        "name": "WordtoWordDictionaryEnglishNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "LanguageCode", "type": ["null", "string"], "default": None},
    {
        "name": "ELALSelectedResponseOrTechnologyEnhancedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "ELALConstructedResponse", "type": ["null", "double"], "default": None},
    {"name": "Sex", "type": ["null", "string"], "default": None},
    {"name": "ELExemptfromTakingELAL", "type": ["null", "string"], "default": None},
    {"name": "Filler1", "type": ["null", "string"], "default": None},
    {"name": "ClosedCaptioningForELAL", "type": ["null", "string"], "default": None},
    {"name": "AnswersRecordedInTestBook", "type": ["null", "string"], "default": None},
    {"name": "Birthdate", "type": ["null", "string"], "default": None},
    {"name": "BrailleResponse", "type": ["null", "string"], "default": None},
    {"name": "FillerField.16", "type": ["null", "string"], "default": None},
    {"name": "FillerField.17", "type": ["null", "string"], "default": None},
    {"name": "FillerField1", "type": ["null", "string"], "default": None},
    {"name": "FillerField2", "type": ["null", "string"], "default": None},
    {"name": "FillerField4", "type": ["null", "string"], "default": None},
    {"name": "FillerField5", "type": ["null", "string"], "default": None},
    {"name": "FillerField7", "type": ["null", "string"], "default": None},
    {"name": "GiftedandTalented", "type": ["null", "string"], "default": None},
    {"name": "MathematicsResponse", "type": ["null", "double"], "default": None},
    {"name": "MathematicsResponseEL", "type": ["null", "string"], "default": None},
    {"name": "OnlineFormID", "type": ["null", "string"], "default": None},
    {"name": "PARCCStudentIdentifier", "type": ["null", "string"], "default": None},
    {"name": "PercentOfItemsAttempted", "type": ["null", "string"], "default": None},
    {
        "name": "RefreshableBrailleDisplayForELAL",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "ResponsibleAccountableDistrictCode",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "ResponsibleAccountableSchoolCode",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "ResponsibleDistrictName", "type": ["null", "string"], "default": None},
    {
        "name": "ResponsibleOrganizationalType",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "ResponsibleSchoolName", "type": ["null", "string"], "default": None},
    {
        "name": "SpanishTransadaptationOfTheMathematicsAssessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "StateAbbreviation", "type": ["null", "string"], "default": None},
    {"name": "StateField1", "type": ["null", "string"], "default": None},
    {"name": "StateField10", "type": ["null", "string"], "default": None},
    {"name": "StateField11", "type": ["null", "string"], "default": None},
    {"name": "StateField12", "type": ["null", "string"], "default": None},
    {"name": "StateField13", "type": ["null", "string"], "default": None},
    {"name": "StateField14", "type": ["null", "string"], "default": None},
    {"name": "StateField15", "type": ["null", "string"], "default": None},
    {"name": "StateField2", "type": ["null", "string"], "default": None},
    {"name": "StateField3", "type": ["null", "string"], "default": None},
    {"name": "StateField4", "type": ["null", "string"], "default": None},
    {"name": "StateField5", "type": ["null", "string"], "default": None},
    {"name": "StateField6", "type": ["null", "double", "string"], "default": None},
    {"name": "StateField7", "type": ["null", "double"], "default": None},
    {"name": "StateField8", "type": ["null", "double"], "default": None},
    {"name": "StateField9", "type": ["null", "double"], "default": None},
    {"name": "StudentUnit4TestUUID", "type": ["null", "string"], "default": None},
    {
        "name": "TitleIIILimitedEnglishProficientParticipationStatus",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit4FormID", "type": ["null", "string"], "default": None},
    {
        "name": "Unit4NumberofAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Unit4OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit4OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit4TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "WordPredictionForELAL", "type": ["null", "string"], "default": None},
    {"name": "FillerField.18", "type": ["null", "string"], "default": None},
    {"name": "FillerField.19", "type": ["null", "string"], "default": None},
    {"name": "FillerField.20", "type": ["null", "string"], "default": None},
    {"name": "FillerField.21", "type": ["null", "string"], "default": None},
    {"name": "FillerField.22", "type": ["null", "string"], "default": None},
    {"name": "FillerField.23", "type": ["null", "string"], "default": None},
    {"name": "FillerField.24", "type": ["null", "string"], "default": None},
    {"name": "FillerField.25", "type": ["null", "string"], "default": None},
    {"name": "FillerField.26", "type": ["null", "string"], "default": None},
    {"name": "FillerField.27", "type": ["null", "string"], "default": None},
    {"name": "FillerField.28", "type": ["null", "string"], "default": None},
    {"name": "FillerField.29", "type": ["null", "string"], "default": None},
    {"name": "FillerField.30", "type": ["null", "string"], "default": None},
    {"name": "ResponsibleDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "ResponsibleSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "SmallTestingGroup", "type": ["null", "string"], "default": None},
    {
        "name": "StudentReadsAssessmentAloudToThemselves",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AmericanIndianOrAlaskaNative ",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "AttemptCreateDate", "type": ["null", "string"], "default": None},
    {"name": "Filler", "type": ["null", "string"], "default": None},
    {"name": "Filler.1", "type": ["null", "string"], "default": None},
    {"name": "Filler.10", "type": ["null", "string"], "default": None},
    {"name": "Filler.11", "type": ["null", "string"], "default": None},
    {"name": "Filler.2", "type": ["null", "string"], "default": None},
    {"name": "Filler.3", "type": ["null", "string"], "default": None},
    {"name": "Filler.4", "type": ["null", "string"], "default": None},
    {"name": "Filler.5", "type": ["null", "string"], "default": None},
    {"name": "Filler.6", "type": ["null", "string"], "default": None},
    {"name": "Filler.7", "type": ["null", "string"], "default": None},
    {"name": "Filler.8", "type": ["null", "string"], "default": None},
    {"name": "Filler.9", "type": ["null", "string"], "default": None},
    {"name": "PaperUnit1TotalTestItems", "type": ["null", "string"], "default": None},
    {
        "name": "ResponsibleOrganizationCodeType",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "StudentWithDisabilities ", "type": ["null", "string"], "default": None},
    {"name": "Subclaim6Category", "type": ["null", "string"], "default": None},
    {
        "name": "TranslationOfTheMathematicsAssessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Filler27", "type": ["null", "string"], "default": None},
    {"name": "Filler28", "type": ["null", "string"], "default": None},
    {"name": "Filler29", "type": ["null", "string"], "default": None},
    {"name": "Filler30", "type": ["null", "string"], "default": None},
    {"name": "Filler31", "type": ["null", "string"], "default": None},
    {"name": "Filler32", "type": ["null", "string"], "default": None},
    {"name": "Filler33", "type": ["null", "string"], "default": None},
    {"name": "Filler34", "type": ["null", "string"], "default": None},
    {"name": "Filler35", "type": ["null", "string"], "default": None},
    {"name": "Filler36", "type": ["null", "string"], "default": None},
    {"name": "Filler37", "type": ["null", "string"], "default": None},
    {"name": "Filler38", "type": ["null", "string"], "default": None},
    {"name": "Filler39", "type": ["null", "string"], "default": None},
]

NJSLA_FIELDS = [
    {"name": "AccountableDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "AccountableDistrictName", "type": ["null", "string"], "default": None},
    {
        "name": "AccountableOrganizationalType",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "AccountableSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "AccountableSchoolName", "type": ["null", "string"], "default": None},
    {
        "name": "AdministrationDirectionsClarifiedinStudentsNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AdministrationDirectionsReadAloudinStudentsNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AlternateRepresentationPaperTest",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AmericanIndianorAlaskaNative",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "AnswerMasking", "type": ["null", "string"], "default": None},
    {
        "name": "AnswersRecordedinTestBooklet",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Asian", "type": ["null", "string"], "default": None},
    {"name": "ASLVideo", "type": ["null", "string"], "default": None},
    {"name": "AssessmentGrade", "type": ["null", "string"], "default": None},
    {"name": "AssessmentYear", "type": ["null", "string"], "default": None},
    {
        "name": "AssistiveTechnologyNonScreenReader",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AssistiveTechnologyScreenReader",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "BirthDate", "type": ["null", "string"], "default": None},
    {"name": "BlackorAfricanAmerican", "type": ["null", "string"], "default": None},
    {"name": "BraillewithTactileGraphics", "type": ["null", "string"], "default": None},
    {"name": "ClaimCode", "type": ["null", "string"], "default": None},
    {"name": "ClassName", "type": ["null", "string"], "default": None},
    {"name": "ColorContrast", "type": ["null", "double"], "default": None},
    {
        "name": "CritiquingPracticesPerformanceLevel",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "DateFirstEnrolledinUSSchool",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "EarthandSpaceSciencePerformanceLevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "EconomicDisadvantageStatus", "type": ["null", "string"], "default": None},
    {"name": "ELAccommodation", "type": ["null", "string"], "default": None},
    {"name": "ElectronicBrailleResponse", "type": ["null", "string"], "default": None},
    {"name": "EmergencyAccommodation", "type": ["null", "double"], "default": None},
    {
        "name": "EnglishLearnerAccommodatedResponses",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "EnglishLearnerEL", "type": ["null", "string"], "default": None},
    {"name": "ExtendedTime", "type": ["null", "string"], "default": None},
    {"name": "FederalRaceEthnicity", "type": ["null", "long"], "default": None},
    {"name": "Filler.1", "type": ["null", "string"], "default": None},
    {"name": "Filler.10", "type": ["null", "string"], "default": None},
    {"name": "Filler.11", "type": ["null", "string"], "default": None},
    {"name": "Filler.12", "type": ["null", "string"], "default": None},
    {"name": "Filler.13", "type": ["null", "string"], "default": None},
    {"name": "Filler.14", "type": ["null", "string"], "default": None},
    {"name": "Filler.15", "type": ["null", "string"], "default": None},
    {"name": "Filler.16", "type": ["null", "string"], "default": None},
    {"name": "Filler.17", "type": ["null", "string"], "default": None},
    {"name": "Filler.18", "type": ["null", "string"], "default": None},
    {"name": "Filler.19", "type": ["null", "string"], "default": None},
    {"name": "Filler.2", "type": ["null", "string"], "default": None},
    {"name": "Filler.20", "type": ["null", "string"], "default": None},
    {"name": "Filler.21", "type": ["null", "string"], "default": None},
    {"name": "Filler.22", "type": ["null", "string"], "default": None},
    {"name": "Filler.23", "type": ["null", "string"], "default": None},
    {"name": "Filler.24", "type": ["null", "string"], "default": None},
    {"name": "Filler.25", "type": ["null", "string"], "default": None},
    {"name": "Filler.26", "type": ["null", "string"], "default": None},
    {"name": "Filler.27", "type": ["null", "string"], "default": None},
    {"name": "Filler.28", "type": ["null", "string"], "default": None},
    {"name": "Filler.29", "type": ["null", "string"], "default": None},
    {"name": "Filler.3", "type": ["null", "string"], "default": None},
    {"name": "Filler.30", "type": ["null", "string"], "default": None},
    {"name": "Filler.31", "type": ["null", "string"], "default": None},
    {"name": "Filler.32", "type": ["null", "string"], "default": None},
    {"name": "Filler.33", "type": ["null", "string"], "default": None},
    {"name": "Filler.34", "type": ["null", "string"], "default": None},
    {"name": "Filler.35", "type": ["null", "string"], "default": None},
    {"name": "Filler.36", "type": ["null", "string"], "default": None},
    {"name": "Filler.37", "type": ["null", "string"], "default": None},
    {"name": "Filler.38", "type": ["null", "string"], "default": None},
    {"name": "Filler.39", "type": ["null", "string"], "default": None},
    {"name": "Filler.4", "type": ["null", "string"], "default": None},
    {"name": "Filler.40", "type": ["null", "string"], "default": None},
    {"name": "Filler.41", "type": ["null", "string"], "default": None},
    {"name": "Filler.42", "type": ["null", "string"], "default": None},
    {"name": "Filler.43", "type": ["null", "string"], "default": None},
    {"name": "Filler.44", "type": ["null", "string"], "default": None},
    {"name": "Filler.45", "type": ["null", "string"], "default": None},
    {"name": "Filler.46", "type": ["null", "string"], "default": None},
    {"name": "Filler.47", "type": ["null", "string"], "default": None},
    {"name": "Filler.48", "type": ["null", "string"], "default": None},
    {"name": "Filler.49", "type": ["null", "string"], "default": None},
    {"name": "Filler.5", "type": ["null", "string"], "default": None},
    {"name": "Filler.50", "type": ["null", "string"], "default": None},
    {"name": "Filler.51", "type": ["null", "string"], "default": None},
    {"name": "Filler.52", "type": ["null", "string"], "default": None},
    {"name": "Filler.53", "type": ["null", "string"], "default": None},
    {"name": "Filler.54", "type": ["null", "string"], "default": None},
    {"name": "Filler.55", "type": ["null", "string"], "default": None},
    {"name": "Filler.56", "type": ["null", "string"], "default": None},
    {"name": "Filler.57", "type": ["null", "string"], "default": None},
    {"name": "Filler.58", "type": ["null", "string"], "default": None},
    {"name": "Filler.59", "type": ["null", "string"], "default": None},
    {"name": "Filler.6", "type": ["null", "string"], "default": None},
    {"name": "Filler.60", "type": ["null", "string"], "default": None},
    {"name": "Filler.61", "type": ["null", "string"], "default": None},
    {"name": "Filler.62", "type": ["null", "string"], "default": None},
    {"name": "Filler.63", "type": ["null", "string"], "default": None},
    {"name": "Filler.64", "type": ["null", "string"], "default": None},
    {"name": "Filler.65", "type": ["null", "string"], "default": None},
    {"name": "Filler.66", "type": ["null", "string"], "default": None},
    {"name": "Filler.67", "type": ["null", "string"], "default": None},
    {"name": "Filler.68", "type": ["null", "string"], "default": None},
    {"name": "Filler.69", "type": ["null", "string"], "default": None},
    {"name": "Filler.7", "type": ["null", "string"], "default": None},
    {"name": "Filler.70", "type": ["null", "string"], "default": None},
    {"name": "Filler.71", "type": ["null", "string"], "default": None},
    {"name": "Filler.72", "type": ["null", "string"], "default": None},
    {"name": "Filler.73", "type": ["null", "string"], "default": None},
    {"name": "Filler.74", "type": ["null", "string"], "default": None},
    {"name": "Filler.75", "type": ["null", "string"], "default": None},
    {"name": "Filler.76", "type": ["null", "string"], "default": None},
    {"name": "Filler.77", "type": ["null", "string"], "default": None},
    {"name": "Filler.78", "type": ["null", "string"], "default": None},
    {"name": "Filler.79", "type": ["null", "string"], "default": None},
    {"name": "Filler.8", "type": ["null", "string"], "default": None},
    {"name": "Filler.80", "type": ["null", "string"], "default": None},
    {"name": "Filler.81", "type": ["null", "string"], "default": None},
    {"name": "Filler.82", "type": ["null", "string"], "default": None},
    {"name": "Filler.83", "type": ["null", "string"], "default": None},
    {"name": "Filler.84", "type": ["null", "string"], "default": None},
    {"name": "Filler.9", "type": ["null", "string"], "default": None},
    {"name": "Filler", "type": ["null", "string"], "default": None},
    {
        "name": "FirstHighSchoolMathAssessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "FirstName", "type": ["null", "string"], "default": None},
    {"name": "FormerIEP", "type": ["null", "string"], "default": None},
    {"name": "FormID", "type": ["null", "string"], "default": None},
    {"name": "FrequentBreaks", "type": ["null", "string"], "default": None},
    {"name": "Gender", "type": ["null", "string"], "default": None},
    {"name": "GradeLevelWhenAssessed", "type": ["null", "long"], "default": None},
    {"name": "HispanicorLatinoEthnicity", "type": ["null", "string"], "default": None},
    {"name": "HomeLanguage", "type": ["null", "string"], "default": None},
    {"name": "Homeless", "type": ["null", "string"], "default": None},
    {"name": "HumanReaderorHumanSigner", "type": ["null", "double"], "default": None},
    {
        "name": "HumanSignerForTestDirections",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "InvestigatingPracticesPerformanceLevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "LargePrint", "type": ["null", "string"], "default": None},
    {"name": "LastOrSurname", "type": ["null", "string"], "default": None},
    {
        "name": "LifeSciencePerformanceLevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "LocalStudentIdentifier", "type": ["null", "long"], "default": None},
    {
        "name": "MathematicsScienceAccommodatedResponse",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "MiddleName", "type": ["null", "string"], "default": None},
    {"name": "MigrantStatus", "type": ["null", "string"], "default": None},
    {"name": "MonitorTestResponse", "type": ["null", "string"], "default": None},
    {"name": "MultipleTestRegistration", "type": ["null", "string"], "default": None},
    {
        "name": "NativeHawaiianorOtherPacificIslander",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "NJELStatus", "type": ["null", "string"], "default": None},
    {"name": "NotTestedCode", "type": ["null", "string"], "default": None},
    {"name": "NotTestedReason", "type": ["null", "double"], "default": None},
    {"name": "PercentOfItemsAttempted", "type": ["null", "long"], "default": None},
    {"name": "Period", "type": ["null", "string"], "default": None},
    {
        "name": "PhysicalSciencePerformanceLevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "PrimaryDisabilityType", "type": ["null", "string"], "default": None},
    {"name": "ReportSuppressionAction", "type": ["null", "string"], "default": None},
    {"name": "ReportSuppressionCode", "type": ["null", "string"], "default": None},
    {"name": "Retest", "type": ["null", "string"], "default": None},
    {"name": "RosterFlag", "type": ["null", "string"], "default": None},
    {
        "name": "SensemakingPracticesPerformanceLevel",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "SeparateAlternateLocation", "type": ["null", "string"], "default": None},
    {"name": "ShipReportDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "ShipReportSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "SmallGroupTesting", "type": ["null", "string"], "default": None},
    {"name": "SpanishTransadaptation", "type": ["null", "string"], "default": None},
    {"name": "SpecialEducationPlacement", "type": ["null", "double"], "default": None},
    {
        "name": "SpecializedEquipmentorFurniture",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "SpecifiedAreaOrSetting", "type": ["null", "string"], "default": None},
    {
        "name": "SpeechtoTextandWordPrediction",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "StaffMemberIdentifier", "type": ["null", "double"], "default": None},
    {"name": "StateStudentIdentifier", "type": ["null", "long"], "default": None},
    {
        "name": "StudentAssessmentIdentifier",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "StudentReadsAssessmentAloudtoSelf",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "StudentTestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentWithDisabilities", "type": ["null", "string"], "default": None},
    {"name": "Subject", "type": ["null", "string"], "default": None},
    {"name": "SummativeFlag", "type": ["null", "string"], "default": None},
    {"name": "TestAdministration", "type": ["null", "string"], "default": None},
    {"name": "TestAdministrator", "type": ["null", "double"], "default": None},
    {"name": "TestAttemptednessFlag", "type": ["null", "string"], "default": None},
    {"name": "TestCode", "type": ["null", "string"], "default": None},
    {"name": "TestCSEMProbableRange", "type": ["null", "double"], "default": None},
    {"name": "TestFormat", "type": ["null", "string"], "default": None},
    {"name": "TestingDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "TestingDistrictName", "type": ["null", "string"], "default": None},
    {"name": "TestingOrganizationalType", "type": ["null", "long"], "default": None},
    {"name": "TestingSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "TestingSchoolName", "type": ["null", "string"], "default": None},
    {"name": "TestPerformanceLevel", "type": ["null", "double"], "default": None},
    {"name": "TestScaleScore", "type": ["null", "double"], "default": None},
    {"name": "TestScoreComplete", "type": ["null", "double"], "default": None},
    {"name": "TestStatus", "type": ["null", "string"], "default": None},
    {"name": "TextToSpeech", "type": ["null", "double"], "default": None},
    {"name": "TimeOfDay", "type": ["null", "string"], "default": None},
    {"name": "TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "TotalTestItemsAttempted", "type": ["null", "double"], "default": None},
    {"name": "TwoOrMoreRaces", "type": ["null", "string"], "default": None},
    {"name": "UniqueAccommodation", "type": ["null", "string"], "default": None},
    {"name": "Unit1OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit1OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit2OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit2OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit3OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit3OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit4OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit4OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "VoidScoreCode", "type": ["null", "string"], "default": None},
    {"name": "VoidScoreReason", "type": ["null", "double"], "default": None},
    {"name": "White", "type": ["null", "string"], "default": None},
    {"name": "WordPrediction", "type": ["null", "string"], "default": None},
    {
        "name": "WordtoWordDictionaryEnglishNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AnswersRecordedinTest Booklet",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Filler.85", "type": ["null", "string"], "default": None},
    {
        "name": "Mathematics/ScienceAccommodatedResponse",
        "type": ["null", "double"],
        "default": None,
    },
]

NJGPA_FIELDS = [
    {"name": "AccountableDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "AccountableDistrictName", "type": ["null", "string"], "default": None},
    {
        "name": "AccountableOrganizationalType",
        "type": ["null", "long"],
        "default": None,
    },
    {"name": "AccountableSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "AccountableSchoolName", "type": ["null", "string"], "default": None},
    {
        "name": "AdministrationDirectionsClarifiedinStudentsNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AdministrationDirectionsReadAloudinStudentsNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AlternateRepresentationPaperTest",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AmericanIndianOrAlaskaNative",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "AnswerMasking", "type": ["null", "string"], "default": None},
    {
        "name": "AnswersRecordedinTestBooklet",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Asian", "type": ["null", "string"], "default": None},
    {"name": "ASLVideo", "type": ["null", "string"], "default": None},
    {"name": "AssessmentGrade", "type": ["null", "string"], "default": None},
    {"name": "AssessmentYear", "type": ["null", "string"], "default": None},
    {
        "name": "AssistiveTechnologyNonScreenReader",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "AssistiveTechnologyScreenReader",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "BatteryFormID", "type": ["null", "string"], "default": None},
    {"name": "BirthDate", "type": ["null", "string"], "default": None},
    {"name": "BlackOrAfricanAmerican", "type": ["null", "string"], "default": None},
    {"name": "BrailleWithTactileGraphics", "type": ["null", "string"], "default": None},
    {
        "name": "CalculationDeviceAndMathematicsTools",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "ClassName", "type": ["null", "string"], "default": None},
    {"name": "ClosedCaptioningForELA", "type": ["null", "string"], "default": None},
    {"name": "ColorContrast", "type": ["null", "string"], "default": None},
    {
        "name": "DateFirstEnrolledinUSSchool",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "EconomicDisadvantageStatus", "type": ["null", "string"], "default": None},
    {"name": "ELAccommodation", "type": ["null", "string"], "default": None},
    {"name": "ELAConstructedResponse", "type": ["null", "double"], "default": None},
    {
        "name": "ELASelectedResponseOrTechnologyEnhancedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "ElectronicBrailleResponse", "type": ["null", "string"], "default": None},
    {"name": "ELExemptfromTakingELA", "type": ["null", "string"], "default": None},
    {"name": "EmergencyAccommodation", "type": ["null", "string"], "default": None},
    {
        "name": "EnglishLearnerAccommodatedResponses",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "EnglishLearnerEL", "type": ["null", "string"], "default": None},
    {"name": "ExtendedTime", "type": ["null", "string"], "default": None},
    {"name": "FederalRaceEthnicity", "type": ["null", "long"], "default": None},
    {"name": "Filler10", "type": ["null", "string"], "default": None},
    {"name": "Filler11", "type": ["null", "string"], "default": None},
    {"name": "Filler12", "type": ["null", "string"], "default": None},
    {"name": "Filler13", "type": ["null", "string"], "default": None},
    {"name": "Filler14", "type": ["null", "string"], "default": None},
    {"name": "Filler15", "type": ["null", "string"], "default": None},
    {"name": "Filler16", "type": ["null", "string"], "default": None},
    {"name": "Filler17", "type": ["null", "string"], "default": None},
    {"name": "Filler18", "type": ["null", "string"], "default": None},
    {"name": "Filler19", "type": ["null", "string"], "default": None},
    {"name": "Filler2", "type": ["null", "string"], "default": None},
    {"name": "Filler20", "type": ["null", "string"], "default": None},
    {"name": "Filler21", "type": ["null", "string"], "default": None},
    {"name": "Filler22", "type": ["null", "string"], "default": None},
    {"name": "Filler23", "type": ["null", "string"], "default": None},
    {"name": "Filler24", "type": ["null", "string"], "default": None},
    {"name": "Filler25", "type": ["null", "string"], "default": None},
    {"name": "Filler26", "type": ["null", "string"], "default": None},
    {"name": "Filler3", "type": ["null", "string"], "default": None},
    {"name": "Filler4", "type": ["null", "string"], "default": None},
    {"name": "Filler5", "type": ["null", "string"], "default": None},
    {"name": "Filler6", "type": ["null", "string"], "default": None},
    {"name": "Filler7", "type": ["null", "string"], "default": None},
    {"name": "Filler8", "type": ["null", "string"], "default": None},
    {"name": "FillerField.1", "type": ["null", "string"], "default": None},
    {"name": "FillerField.10", "type": ["null", "string"], "default": None},
    {"name": "FillerField.11", "type": ["null", "string"], "default": None},
    {"name": "FillerField.12", "type": ["null", "string"], "default": None},
    {"name": "FillerField.13", "type": ["null", "string"], "default": None},
    {"name": "FillerField.14", "type": ["null", "string"], "default": None},
    {"name": "FillerField.15", "type": ["null", "string"], "default": None},
    {"name": "FillerField.2", "type": ["null", "string"], "default": None},
    {"name": "FillerField.3", "type": ["null", "string"], "default": None},
    {"name": "FillerField.4", "type": ["null", "string"], "default": None},
    {"name": "FillerField.5", "type": ["null", "string"], "default": None},
    {"name": "FillerField.6", "type": ["null", "string"], "default": None},
    {"name": "FillerField.7", "type": ["null", "string"], "default": None},
    {"name": "FillerField.8", "type": ["null", "string"], "default": None},
    {"name": "FillerField.9", "type": ["null", "string"], "default": None},
    {"name": "FillerField", "type": ["null", "string"], "default": None},
    {
        "name": "FirstHighSchoolMathAssessment",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "FirstName", "type": ["null", "string"], "default": None},
    {"name": "FormerIEP", "type": ["null", "string"], "default": None},
    {"name": "FrequentBreaks", "type": ["null", "string"], "default": None},
    {"name": "Gender", "type": ["null", "string"], "default": None},
    {"name": "GradeLevelWhenAssessed", "type": ["null", "long"], "default": None},
    {"name": "HispanicOrLatinoEthnicity", "type": ["null", "string"], "default": None},
    {"name": "Home Language", "type": ["null", "string"], "default": None},
    {"name": "Homeless", "type": ["null", "string"], "default": None},
    {"name": "HumanReaderOrHumanSigner", "type": ["null", "string"], "default": None},
    {
        "name": "HumanSignerForTestDirections",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "IEPExemptFromPassing", "type": ["null", "string"], "default": None},
    {"name": "LargePrint", "type": ["null", "string"], "default": None},
    {"name": "LastOrSurname", "type": ["null", "string"], "default": None},
    {"name": "LocalStudentIdentifier", "type": ["null", "long"], "default": None},
    {
        "name": "MathematicsScienceAccommodatedResponse",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "MiddleName", "type": ["null", "string"], "default": None},
    {"name": "MigrantStatus", "type": ["null", "string"], "default": None},
    {"name": "MonitorTestResponse", "type": ["null", "string"], "default": None},
    {"name": "MultipleTestRegistration", "type": ["null", "string"], "default": None},
    {
        "name": "NativeHawaiianOrOtherPacificIslander",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "NJELStatus", "type": ["null", "string"], "default": None},
    {"name": "NJNotAttemptFlag", "type": ["null", "string"], "default": None},
    {"name": "NotTestedCode", "type": ["null", "string"], "default": None},
    {"name": "NotTestedReason", "type": ["null", "double"], "default": None},
    {"name": "OnlinePCR1", "type": ["null", "string"], "default": None},
    {"name": "OnlinePCR2", "type": ["null", "string"], "default": None},
    {"name": "PaperAttemptCreateDate", "type": ["null", "string"], "default": None},
    {"name": "PaperFormID", "type": ["null", "string"], "default": None},
    {"name": "PaperPCR1", "type": ["null", "string"], "default": None},
    {"name": "PaperPCR2", "type": ["null", "string"], "default": None},
    {
        "name": "PaperSection1NumberofAttemptedItems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "PaperSection1TotalTestItems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "PaperSection2NumberofAttemptedItems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "PaperSection2TotalTestItems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "PaperSection3NumberofAttemptedItems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "PaperSection3TotalTestItems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "PaperSection4NumberofAttemptedItems",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "PaperSection4TotalTestItems",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Period", "type": ["null", "string"], "default": None},
    {"name": "PrimaryDisabilityType", "type": ["null", "string"], "default": None},
    {"name": "RefreshableBrailleDisplay", "type": ["null", "string"], "default": None},
    {"name": "ReportSuppressionAction", "type": ["null", "string"], "default": None},
    {"name": "ReportSuppressionCode", "type": ["null", "string"], "default": None},
    {"name": "Retest", "type": ["null", "string"], "default": None},
    {"name": "RosterFlag", "type": ["null", "string"], "default": None},
    {"name": "SeparateAlternateLocation", "type": ["null", "string"], "default": None},
    {"name": "ShipReportDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "ShipReportSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "SmallGroupTesting", "type": ["null", "string"], "default": None},
    {"name": "SpanishTransadaptation", "type": ["null", "string"], "default": None},
    {"name": "SpecialEducationPlacement", "type": ["null", "double"], "default": None},
    {
        "name": "SpecializedEquipmentOrFurniture",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "SpecifiedAreaOrSetting", "type": ["null", "string"], "default": None},
    {
        "name": "SpeechtoTextandWordPrediction",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "StaffMemberIdentifier",
        "type": ["null", "long", "double"],
        "default": None,
    },
    {"name": "StateStudentIdentifier", "type": ["null", "long"], "default": None},
    {
        "name": "StudentAssessmentIdentifier",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "StudentReadsAssessmentAloudtoSelf",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "StudentTestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUnit1TestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUnit2TestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUnit3TestUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentUUID", "type": ["null", "string"], "default": None},
    {"name": "StudentWithDisabilities", "type": ["null", "string"], "default": None},
    {"name": "Subclaim1Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim1CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim2Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim2CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim3Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim3CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim4Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim4CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subclaim5Category", "type": ["null", "double"], "default": None},
    {
        "name": "Subclaim5CategoryIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Subject", "type": ["null", "string"], "default": None},
    {"name": "SummativeFlag", "type": ["null", "string"], "default": None},
    {"name": "TestAdministration", "type": ["null", "string"], "default": None},
    {"name": "TestAdministrator", "type": ["null", "long", "double"], "default": None},
    {"name": "TestAttemptednessFlag", "type": ["null", "string"], "default": None},
    {"name": "TestCode", "type": ["null", "string"], "default": None},
    {"name": "TestCSEMProbableRange", "type": ["null", "double"], "default": None},
    {
        "name": "TestCSEMProbableRangeIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestingDistrictCode", "type": ["null", "long"], "default": None},
    {"name": "TestingDistrictName", "type": ["null", "string"], "default": None},
    {"name": "TestingOrganizationalType", "type": ["null", "long"], "default": None},
    {"name": "TestingSchoolCode", "type": ["null", "long"], "default": None},
    {"name": "TestingSchoolName", "type": ["null", "string"], "default": None},
    {"name": "TestPerformanceLevel", "type": ["null", "double"], "default": None},
    {
        "name": "TestPerformanceLevelIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestReadingCSEM", "type": ["null", "double"], "default": None},
    {
        "name": "TestReadingCSEMIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestReadingScaleScore", "type": ["null", "double"], "default": None},
    {
        "name": "TestReadingScaleScoreIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestScaleScore", "type": ["null", "double"], "default": None},
    {
        "name": "TestScaleScoreIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestScoreComplete", "type": ["null", "double"], "default": None},
    {"name": "TestStatus", "type": ["null", "string"], "default": None},
    {"name": "TestWritingCSEM", "type": ["null", "double"], "default": None},
    {
        "name": "TestWritingCSEMIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TestWritingScaleScore", "type": ["null", "double"], "default": None},
    {
        "name": "TestWritingScaleScoreIfNotAttempted",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "TextToSpeech", "type": ["null", "double"], "default": None},
    {"name": "TimeOfDay", "type": ["null", "string"], "default": None},
    {"name": "TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "TotalTestItemsAttempted", "type": ["null", "double"], "default": None},
    {"name": "TwoOrMoreRaces", "type": ["null", "string"], "default": None},
    {"name": "UniqueAccommodation", "type": ["null", "string"], "default": None},
    {"name": "Unit1FormID", "type": ["null", "string"], "default": None},
    {
        "name": "Unit1NumberofAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Unit1OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit1OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit1TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "Unit2FormID", "type": ["null", "string"], "default": None},
    {
        "name": "Unit2NumberOfAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Unit2OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit2OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit2TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "Unit3FormID", "type": ["null", "string"], "default": None},
    {
        "name": "Unit3NumberOfAttemptedItems",
        "type": ["null", "double"],
        "default": None,
    },
    {"name": "Unit3OnlineTestEndDateTime", "type": ["null", "string"], "default": None},
    {
        "name": "Unit3OnlineTestStartDateTime",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Unit3TotalTestItems", "type": ["null", "double"], "default": None},
    {"name": "VoidScoreCode", "type": ["null", "string"], "default": None},
    {"name": "VoidScoreReason", "type": ["null", "string"], "default": None},
    {"name": "White", "type": ["null", "string"], "default": None},
    {"name": "WordPrediction", "type": ["null", "string"], "default": None},
    {
        "name": "WordtoWordDictionaryEnglishNativeLanguage",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "Filler33", "type": ["null", "string"], "default": None},
    {"name": "Filler39", "type": ["null", "string"], "default": None},
    {"name": "Filler35", "type": ["null", "string"], "default": None},
    {"name": "Filler34", "type": ["null", "string"], "default": None},
    {"name": "Filler30", "type": ["null", "string"], "default": None},
    {"name": "Filler32", "type": ["null", "string"], "default": None},
    {"name": "Filler38", "type": ["null", "string"], "default": None},
    {"name": "Filler29", "type": ["null", "string"], "default": None},
    {"name": "Filler37", "type": ["null", "string"], "default": None},
    {"name": "Filler28", "type": ["null", "string"], "default": None},
    {"name": "Filler27", "type": ["null", "string"], "default": None},
    {"name": "Filler36", "type": ["null", "string"], "default": None},
    {"name": "Filler31", "type": ["null", "string"], "default": None},
]

ASSET_FIELDS = {
    "parcc": PARCC_FIELDS,
    "njsla": NJSLA_FIELDS,
    "njgpa": NJGPA_FIELDS,
}
