name: kippmiami
version: 1.0.0
config-version: 2

profile: kippmiami

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

target-path: target
clean-targets:
  - target
  - dbt_packages

data_tests:
  +severity: warn
  +store_failures: true
  +store_failures_as: view

vars:
  local_timezone: America/New_York
  current_academic_year: 2026
  current_fiscal_year: 2027
  cloud_storage_uri_base: gs://teamster-kippmiami/dagster/kippmiami
  bigquery_external_connection_name: projects/teamster-332318/locations/us/connections/biglake-teamster-gcs
  focus_schema: dagster_kippmiami_dlt_focus

models:
  kippmiami:
    extracts:
      +schema: extracts
      +contract:
        enforced: true
    fldoe:
      +schema: fldoe
      +materialized: table
      staging:
        +contract:
          enforced: true
  focus:
    +materialized: table
    staging:
      +contract:
        enforced: true
  deanslist:
    +materialized: table
    staging:
      stg_deanslist__followups:
        +enabled: false
  iready:
    +materialized: table
    staging:
      stg_iready__instructional_usage_data:
        +enabled: false
  renlearn:
    +materialized: table
    staging:
      stg_renlearn__accelerated_reader:
        +enabled: false
      stg_renlearn__star_skill_area:
        +enabled: false
