select
    employee_number as df_employee_number,
    worker_id as associate_id,
    position_id as position_id,
    payroll_file_number as file_number,
    legal_name_given_name as first_name,
    legal_name_family_name as last_name,
    preferred_name_given_name as preferred_first,
    preferred_name_family_name as preferred_last,
    preferred_name_lastfirst as preferred_name,
    null as maiden_name,
    null as eeo_ethnic_code,
    ethnicity_long_name as eeo_ethnic_description,
    null as is_hispanic,  -- TODO: add logic
    gender_long_name as gender,
    birth_date as birth_date,
    legal_address_line_one as `address`,
    legal_address_city_name as primary_address_city,
    legal_address_country_subdivision_level_1 as primary_address_state_territory_code,
    legal_address_postal_code as primary_address_zip_postal_code,
    communication_person_mobile as personal_contact_personal_mobile,
    department_home_name as subject_dept_custom,
    primary_grade_level_taught as grades_taught_custom,
    worker_original_hire_date as original_hire_date,
    worker_rehire_date as rehire_date,
    job_title as job_title_description,
    job_title as job_title_custom,
    payroll_group_code as payroll_company_code,
    business_unit_home_name as legal_entity_name,
    null as is_regional_staff,  -- TODO
    assignment_status as position_status,
    home_work_location_name as location_description,
    home_work_location_name as location_custom,
    department_home_name as home_department_description,
    assignment_status_reason as termination_reason_description,
    worker_type as worker_category_description,
    worker_group_value as benefits_eligibility_class_description,
    wage_law_coverage_short_name as flsa_description,
    management_position_indicator as this_is_a_management_position,
    management_position_indicator as is_management,
    null as salesforce_job_position_name_custom,  -- TODO
    report_to_preferred_name_lastfirst as reports_to_name,
    report_to_employee_number as manager_df_employee_number,
    report_to_worker_id as manager_custom_assoc_id,
    report_to_preferred_name_lastfirst as manager_name,
    work_assignment_actual_start_date as position_start_date,
    worker_termination_date as termination_date,
    mail as mail,
    user_principal_name as userprincipalname,
    null as manager_mail,  -- TODO
from {{ ref("base_people__staff_roster") }}
