with
    deduplicate as (
        {{
            dbt_utils.deduplicate(
                relation=source("powerschool", "src_powerschool__students"),
                partition_by="dcid.int_value",
                order_by="_file_name desc",
            )
        }}
    ),

    staging as (
        -- trunk-ignore(sqlfluff/AM04,sqlfluff/ST06)
        select
            * except (
                allowwebaccess,
                balance1,
                balance2,
                balance3,
                balance4,
                campusid,
                classof,
                cumulative_gpa,
                cumulative_pct,
                customrank_gpa,
                dcid,
                districtentrygradelevel,
                enroll_status,
                enrollment_schoolid,
                enrollmentcode,
                enrollmentid,
                exclude_fr_rank,
                fedethnicity,
                fedracedecline,
                fee_exemption_status,
                fteid,
                fulltimeequiv_obsolete,
                gpentryyear,
                grade_level,
                gradreqsetid,
                graduated_rank,
                graduated_schoolid,
                id,
                ismigrated,
                ldapenabled,
                lunch_id,
                membershipshare,
                next_school,
                person_id,
                phone_id,
                photoflag,
                sched_loadlock,
                sched_lockstudentschedule,
                sched_nextyeargrade,
                sched_priority,
                sched_scheduled,
                sched_yearofgraduation,
                schoolentrygradelevel,
                schoolid,
                sdatarn,
                simple_gpa,
                simple_pct,
                state_enrollflag,
                state_excludefromreporting,
                student_allowwebaccess,
                student_number,
                summerschoolid,
                teachergroupid,
                tuitionpayer,
                whomodifiedid,
                wm_createtime,
                wm_tier
            ),

            /* column transformations */
            allowwebaccess.int_value as allowwebaccess,
            balance1.double_value as balance1,
            balance2.double_value as balance2,
            balance3.double_value as balance3,
            balance4.double_value as balance4,
            campusid.int_value as campusid,
            classof.int_value as classof,
            cumulative_gpa.double_value as cumulative_gpa,
            cumulative_pct.double_value as cumulative_pct,
            customrank_gpa.double_value as customrank_gpa,
            dcid.int_value as dcid,
            districtentrygradelevel.int_value as districtentrygradelevel,
            enroll_status.int_value as enroll_status,
            enrollment_schoolid.int_value as enrollment_schoolid,
            enrollmentcode.int_value as enrollmentcode,
            enrollmentid.int_value as enrollmentid,
            exclude_fr_rank.int_value as exclude_fr_rank,
            fedethnicity.int_value as fedethnicity,
            fedracedecline.int_value as fedracedecline,
            fee_exemption_status.int_value as fee_exemption_status,
            fteid.int_value as fteid,
            fulltimeequiv_obsolete.double_value as fulltimeequiv_obsolete,
            gpentryyear.int_value as gpentryyear,
            grade_level.int_value as grade_level,
            gradreqsetid.int_value as gradreqsetid,
            graduated_rank.int_value as graduated_rank,
            graduated_schoolid.int_value as graduated_schoolid,
            id.int_value as id,
            ismigrated.int_value as ismigrated,
            ldapenabled.int_value as ldapenabled,
            lunch_id.double_value as lunch_id,
            membershipshare.double_value as membershipshare,
            next_school.int_value as next_school,
            person_id.int_value as person_id,
            phone_id.int_value as phone_id,
            photoflag.int_value as photoflag,
            safe_cast(student_number.double_value as int) as student_number,
            sched_loadlock.int_value as sched_loadlock,
            sched_lockstudentschedule.int_value as sched_lockstudentschedule,
            sched_nextyeargrade.int_value as sched_nextyeargrade,
            sched_priority.int_value as sched_priority,
            sched_scheduled.int_value as sched_scheduled,
            sched_yearofgraduation.int_value as sched_yearofgraduation,
            schoolentrygradelevel.int_value as schoolentrygradelevel,
            schoolid.int_value as schoolid,
            sdatarn.int_value as sdatarn,
            simple_gpa.double_value as simple_gpa,
            simple_pct.double_value as simple_pct,
            state_enrollflag.int_value as state_enrollflag,
            state_excludefromreporting.int_value as state_excludefromreporting,
            student_allowwebaccess.int_value as student_allowwebaccess,
            summerschoolid.int_value as summerschoolid,
            teachergroupid.int_value as teachergroupid,
            tuitionpayer.int_value as tuitionpayer,
            whomodifiedid.int_value as whomodifiedid,
            wm_createtime.int_value as wm_createtime,
            wm_tier.int_value as wm_tier,
        from deduplicate
    )

select
    *,

    left(upper(gender), 1) as gender_code,
    left(upper(ethnicity), 1) as ethnicity_code,
from staging
