with
    deduplicate as (
        {{
            dbt_utils.deduplicate(
                relation=source("powerschool", "src_powerschool__gradescaleitem"),
                partition_by="dcid.int_value",
                order_by="_file_name desc",
            )
        }}
    )

-- trunk-ignore(sqlfluff/AM04)
select
    * except (
        dcid,
        id,
        gradescaleid,
        isforcoursegrade,
        isforstandards,
        isgpashown,
        countsingpa,
        displayposition,
        grade_points,
        addedvalue,
        graduationcredit,
        teacherscale,
        cutoffpercentage,
        `value`,
        colorlevels,
        isproficient,
        isscorecodeonassignments,
        modify_code,
        numericmin,
        numericmax,
        numericdecimals,
        numericcutoff,
        numericvalue,
        hasspecialgrades,
        specialgradescaledcid,
        hasrelatedscales,
        altconvertgradescaledcid,
        altfinalnumericcutoff,
        istermweightingshown,
        alt_grade_points,
        cutoffpoints,
        excludefromafg,
        grade_replacement_policy,
        parentgradescaledcid
    ),

    /* column transformations */
    dcid.int_value as dcid,
    id.int_value as id,
    gradescaleid.int_value as gradescaleid,
    isforcoursegrade.int_value as isforcoursegrade,
    isforstandards.int_value as isforstandards,
    isgpashown.int_value as isgpashown,
    countsingpa.int_value as countsingpa,
    displayposition.int_value as displayposition,
    grade_points.double_value as grade_points,
    addedvalue.int_value as addedvalue,
    graduationcredit.int_value as graduationcredit,
    teacherscale.int_value as teacherscale,
    cutoffpercentage.double_value as cutoffpercentage,
    value.int_value as `value`,
    colorlevels.int_value as colorlevels,
    isproficient.int_value as isproficient,
    isscorecodeonassignments.int_value as isscorecodeonassignments,
    modify_code.int_value as modify_code,
    numericmin.int_value as numericmin,
    numericmax.int_value as numericmax,
    numericdecimals.int_value as numericdecimals,
    numericcutoff.bytes_decimal_value as numericcutoff,
    numericvalue.bytes_decimal_value as numericvalue,
    hasspecialgrades.int_value as hasspecialgrades,
    specialgradescaledcid.int_value as specialgradescaledcid,
    hasrelatedscales.int_value as hasrelatedscales,
    altconvertgradescaledcid.int_value as altconvertgradescaledcid,
    altfinalnumericcutoff.bytes_decimal_value as altfinalnumericcutoff,
    istermweightingshown.int_value as istermweightingshown,
    alt_grade_points.int_value as alt_grade_points,
    cutoffpoints.int_value as cutoffpoints,
    excludefromafg.int_value as excludefromafg,
    grade_replacement_policy.int_value as grade_replacement_policy,
    parentgradescaledcid.int_value as parentgradescaledcid,
from deduplicate
