with
    deduplicate as (
        {{
            dbt_utils.deduplicate(
                relation=source("powerschool", "src_powerschool__s_nj_stu_x"),
                partition_by="studentsdcid.int_value",
                order_by="_file_name desc",
            )
        }}
    )

-- trunk-ignore(sqlfluff/AM04)
select
    * except (
        studentsdcid,
        lep_completion_date_refused,
        military_connected_indicator,
        asmt_exclude_ela,
        asmt_exclude_math,
        iep_exemptpassinglal_tf,
        iep_exemptpassingmath_tf,
        iep_exempttakinglal_tf,
        iep_exempttakingmath_tf,
        pid_title1langartslit_tf,
        pid_title1math_tf,
        ctecollegecredits,
        pid_504_tf,
        pid_accommodations_a_tf,
        pid_accommodations_b_tf,
        pid_accommodations_c_tf,
        pid_accommodations_d_tf,
        pid_apascience_tf,
        adulths_nb_credits,
        pid_lepexemptlal_tf,
        pid_apalangartsliteracy_tf,
        pid_apamath_tf,
        pid_madetape_tf,
        pid_outofdistplacement_tf,
        pid_outresidenceplacement_tf,
        pid_shortsegmenttestadmin_tf,
        pid_title1science_tf,
        title1_status_tf,
        tiv_serv_aide_tf,
        tiv_serv_assist_tf,
        tiv_serv_extyear_tf,
        tiv_serv_ind_instr_tf,
        tiv_serv_indnursing_tf,
        tiv_serv_intensive_tf,
        tiv_serv_interpreter_tf,
        tiv_serv_pupil_tf,
        tiv_serv_resplacement_tf,
        lep_tf,
        retained_tf,
        cumdaysinmembershipaddto_tf,
        cumdayspresentaddto_tf,
        cumdaystowardtruancyaddto_tf,
        cumulativedaysinmembership,
        cumulativedayspresent,
        cumulativedaystowardtruancy,
        homelessprimarynighttimeres,
        migrant_tf,
        includeinctereport_tf,
        includeinnjsmart_tf,
        includeinstucourse_tf,
        eoc_title1biology_tf,
        iep_exemptpassingbiology_tf,
        iep_exempttakingbiology_tf,
        sla_alt_rep_paper,
        sla_alternate_location,
        sla_answer_masking,
        sla_answers_recorded_paper,
        sla_asl_video,
        sla_closed_caption,
        sla_dictionary,
        sla_directions_clarified,
        sla_exclude_tf,
        sla_frequent_breaks,
        sla_human_signer,
        sla_large_print_paper,
        sla_monitor_response,
        sla_non_screen_reader,
        sla_read_aloud,
        sla_refresh_braille,
        sla_screen_reader,
        sla_small_group,
        sla_special_equip,
        sla_specified_area,
        sla_time_of_day,
        sla_unique_accommodation,
        sla_word_prediction,
        includeinassareport_tf,
        caresactfunds,
        deviceowner,
        devicetype,
        internetconnectivity,
        learningenvironment,
        remotedaysmembership,
        remotedayspresent,
        remotepercentageofday,
        cumulativedaysabsent,
        cumulativestateabs,
        daysopen,
        remotedaysabsent,
        languageacquisition,
        collegecreditsearned,
        cteworkbasedlearning,
        sid_excludeenrollment
    ),

    /* column transformations */
    studentsdcid.int_value as studentsdcid,
    lep_completion_date_refused.int_value as lep_completion_date_refused,
    military_connected_indicator.int_value as military_connected_indicator,
    asmt_exclude_ela.int_value as asmt_exclude_ela,
    asmt_exclude_math.int_value as asmt_exclude_math,
    iep_exemptpassinglal_tf.int_value as iep_exemptpassinglal_tf,
    iep_exemptpassingmath_tf.int_value as iep_exemptpassingmath_tf,
    iep_exempttakinglal_tf.int_value as iep_exempttakinglal_tf,
    iep_exempttakingmath_tf.int_value as iep_exempttakingmath_tf,
    pid_title1langartslit_tf.int_value as pid_title1langartslit_tf,
    pid_title1math_tf.int_value as pid_title1math_tf,
    ctecollegecredits.int_value as ctecollegecredits,
    pid_504_tf.int_value as pid_504_tf,
    pid_accommodations_a_tf.int_value as pid_accommodations_a_tf,
    pid_accommodations_b_tf.int_value as pid_accommodations_b_tf,
    pid_accommodations_c_tf.int_value as pid_accommodations_c_tf,
    pid_accommodations_d_tf.int_value as pid_accommodations_d_tf,
    pid_apascience_tf.int_value as pid_apascience_tf,
    adulths_nb_credits.bytes_decimal_value as adulths_nb_credits,
    pid_lepexemptlal_tf.int_value as pid_lepexemptlal_tf,
    pid_apalangartsliteracy_tf.int_value as pid_apalangartsliteracy_tf,
    pid_apamath_tf.int_value as pid_apamath_tf,
    pid_madetape_tf.int_value as pid_madetape_tf,
    pid_outofdistplacement_tf.int_value as pid_outofdistplacement_tf,
    pid_outresidenceplacement_tf.int_value as pid_outresidenceplacement_tf,
    pid_shortsegmenttestadmin_tf.int_value as pid_shortsegmenttestadmin_tf,
    pid_title1science_tf.int_value as pid_title1science_tf,
    title1_status_tf.int_value as title1_status_tf,
    tiv_serv_aide_tf.int_value as tiv_serv_aide_tf,
    tiv_serv_assist_tf.int_value as tiv_serv_assist_tf,
    tiv_serv_extyear_tf.int_value as tiv_serv_extyear_tf,
    tiv_serv_ind_instr_tf.int_value as tiv_serv_ind_instr_tf,
    tiv_serv_indnursing_tf.int_value as tiv_serv_indnursing_tf,
    tiv_serv_intensive_tf.int_value as tiv_serv_intensive_tf,
    tiv_serv_interpreter_tf.int_value as tiv_serv_interpreter_tf,
    tiv_serv_pupil_tf.int_value as tiv_serv_pupil_tf,
    tiv_serv_resplacement_tf.int_value as tiv_serv_resplacement_tf,
    lep_tf.int_value as lep_tf,
    retained_tf.int_value as retained_tf,
    cumdaysinmembershipaddto_tf.int_value as cumdaysinmembershipaddto_tf,
    cumdayspresentaddto_tf.int_value as cumdayspresentaddto_tf,
    cumdaystowardtruancyaddto_tf.int_value as cumdaystowardtruancyaddto_tf,
    cumulativedaysinmembership.bytes_decimal_value as cumulativedaysinmembership,
    cumulativedayspresent.bytes_decimal_value as cumulativedayspresent,
    cumulativedaystowardtruancy.bytes_decimal_value as cumulativedaystowardtruancy,
    homelessprimarynighttimeres.int_value as homelessprimarynighttimeres,
    migrant_tf.int_value as migrant_tf,
    includeinctereport_tf.int_value as includeinctereport_tf,
    includeinnjsmart_tf.int_value as includeinnjsmart_tf,
    includeinstucourse_tf.int_value as includeinstucourse_tf,
    eoc_title1biology_tf.int_value as eoc_title1biology_tf,
    iep_exemptpassingbiology_tf.int_value as iep_exemptpassingbiology_tf,
    iep_exempttakingbiology_tf.int_value as iep_exempttakingbiology_tf,
    sla_alt_rep_paper.int_value as sla_alt_rep_paper,
    sla_alternate_location.int_value as sla_alternate_location,
    sla_answer_masking.int_value as sla_answer_masking,
    sla_answers_recorded_paper.int_value as sla_answers_recorded_paper,
    sla_asl_video.int_value as sla_asl_video,
    sla_closed_caption.int_value as sla_closed_caption,
    sla_dictionary.int_value as sla_dictionary,
    sla_directions_clarified.int_value as sla_directions_clarified,
    sla_exclude_tf.int_value as sla_exclude_tf,
    sla_frequent_breaks.int_value as sla_frequent_breaks,
    sla_human_signer.int_value as sla_human_signer,
    sla_large_print_paper.int_value as sla_large_print_paper,
    sla_monitor_response.int_value as sla_monitor_response,
    sla_non_screen_reader.int_value as sla_non_screen_reader,
    sla_read_aloud.int_value as sla_read_aloud,
    sla_refresh_braille.int_value as sla_refresh_braille,
    sla_screen_reader.int_value as sla_screen_reader,
    sla_small_group.int_value as sla_small_group,
    sla_special_equip.int_value as sla_special_equip,
    sla_specified_area.int_value as sla_specified_area,
    sla_time_of_day.int_value as sla_time_of_day,
    sla_unique_accommodation.int_value as sla_unique_accommodation,
    sla_word_prediction.int_value as sla_word_prediction,
    includeinassareport_tf.int_value as includeinassareport_tf,
    caresactfunds.int_value as caresactfunds,
    deviceowner.int_value as deviceowner,
    devicetype.int_value as devicetype,
    internetconnectivity.int_value as internetconnectivity,
    learningenvironment.int_value as learningenvironment,
    remotedaysmembership.bytes_decimal_value as remotedaysmembership,
    remotedayspresent.bytes_decimal_value as remotedayspresent,
    remotepercentageofday.int_value as remotepercentageofday,
    cumulativedaysabsent.bytes_decimal_value as cumulativedaysabsent,
    cumulativestateabs.int_value as cumulativestateabs,
    daysopen.int_value as daysopen,
    remotedaysabsent.bytes_decimal_value as remotedaysabsent,
    languageacquisition.int_value as languageacquisition,
    collegecreditsearned.int_value as collegecreditsearned,
    cteworkbasedlearning.int_value as cteworkbasedlearning,
    sid_excludeenrollment.int_value as sid_excludeenrollment,
from deduplicate
