with
    deduplicate as (
        {{
            dbt_utils.deduplicate(
                relation=source("powerschool", "src_powerschool__s_stu_x"),
                partition_by="studentsdcid.int_value",
                order_by="_file_name desc",
            )
        }}
    )

select
    priorityforservice,
    sealofbiliteracy,
    twentyfirstcenturyserved,
    activedutyparent,
    immigrant,
    jobcorps,
    youthchallenge,
    entrydateintousschool,
    singleparent,
    virtualstudent,
    steamstemparticipant,
    birthcity,
    birthcountry,
    birthcounty,
    birthstate,
    residencystatus,
    economicdisadvantage,
    luncheligibility,
    maritalstatus,
    reportedvalue,
    suffix,
    healthid,
    deviceaccess,
    devicetype,
    internetaccess,
    internetinresidence,
    internetperformance,
    pref_first,
    pref_last,
    pref_middle,
    tribal_affiliation_1,
    tribal_affiliation_2,
    tribal_affiliation_3,
    tribal_affiliation_sif_1,
    tribal_affiliation_sif_2,
    tribal_affiliation_sif_3,
    county,
    maiden_name,
    ontracktograduate,
    privateschool,
    graduation_class_rank,
    contact_email,
    contact_fname,
    contact_lname,
    contact_phone,
    barrierintaccess,
    fafsa,
    programenddate,
    programstartdate,
    outofdistrict_distoverride,
    section504_yn,
    careertechedu_yn,
    careerworkreadiness_yn,
    clgcareerreadiness_yn,
    comctzn_yn,
    postsecedu_yn,

    /* column transformations */
    studentsdcid.int_value as studentsdcid,
    excludefromedfi.int_value as excludefromedfi,
    repeatgradeindicator.int_value as repeatgradeindicator,
    schoolchoicetransfer.int_value as schoolchoicetransfer,
    home_language.int_value as home_language,
    native_language.int_value as native_language,
    foster_care.int_value as foster_care,
    parentrefusalofimmaccuracy.int_value as parentrefusalofimmaccuracy,
from deduplicate
