{{
    transform_cols_base_model(
        from_source=source("powerschool", this.identifier | replace("stg", "src")),
        transform_cols=[
            {"name": "dcid", "type": "int_value"},
            {"name": "id", "type": "int_value"},
            {"name": "studentid", "type": "int_value"},
            {"name": "teacherid", "type": "int_value"},
            {"name": "entry_time", "type": "int_value"},
            {"name": "category", "type": "int_value"},
            {"name": "schoolid", "type": "int_value"},
            {"name": "logtypeid", "type": "int_value"},
            {"name": "student_number", "type": "double_value"},
            {"name": "discipline_felonyflag", "type": "int_value"},
            {"name": "discipline_likelyinjuryflag", "type": "int_value"},
            {"name": "discipline_schoolrulesvioflag", "type": "int_value"},
            {"name": "discipline_policeinvolvedflag", "type": "int_value"},
            {"name": "discipline_hearingofficerflag", "type": "int_value"},
            {"name": "discipline_gangrelatedflag", "type": "int_value"},
            {"name": "discipline_hatecrimeflag", "type": "int_value"},
            {"name": "discipline_alcoholrelatedflag", "type": "int_value"},
            {"name": "discipline_drugrelatedflag", "type": "int_value"},
            {"name": "discipline_weaponrelatedflag", "type": "int_value"},
            {"name": "discipline_moneylossvalue", "type": "double_value"},
            {"name": "discipline_durationassigned", "type": "double_value"},
            {"name": "discipline_durationactual", "type": "double_value"},
            {"name": "discipline_sequence", "type": "int_value"},
        ],
    )
}}
