with
    -- trunk-ignore(sqlfluff/ST03)
    ap as (
        select
            a._dagster_partition_school_year as enrollment_school_year,
            a.ap_number_ap_id,
            a.student_identifier,
            a.first_name,
            a.middle_initial,
            a.last_name,
            a.grade_level,
            a.date_of_birth,
            a.gender,
            a.ai_code,
            a.ai_institution_name,
            a.admin_year_01,
            a.admin_year_02,
            a.admin_year_03,
            a.admin_year_04,
            a.admin_year_05,
            a.admin_year_06,
            a.admin_year_07,
            a.admin_year_08,
            a.admin_year_09,
            a.admin_year_10,
            a.admin_year_11,
            a.admin_year_12,
            a.admin_year_13,
            a.admin_year_14,
            a.admin_year_15,
            a.admin_year_16,
            a.admin_year_17,
            a.admin_year_18,
            a.admin_year_19,
            a.admin_year_20,
            a.admin_year_21,
            a.admin_year_22,
            a.admin_year_23,
            a.admin_year_24,
            a.admin_year_25,
            a.admin_year_26,
            a.admin_year_27,
            a.admin_year_28,
            a.admin_year_29,
            a.admin_year_30,
            a.exam_code_01,
            a.exam_code_02,
            a.exam_code_03,
            a.exam_code_04,
            a.exam_code_05,
            a.exam_code_06,
            a.exam_code_07,
            a.exam_code_08,
            a.exam_code_09,
            a.exam_code_10,
            a.exam_code_11,
            a.exam_code_12,
            a.exam_code_13,
            a.exam_code_14,
            a.exam_code_15,
            a.exam_code_16,
            a.exam_code_17,
            a.exam_code_18,
            a.exam_code_19,
            a.exam_code_20,
            a.exam_code_21,
            a.exam_code_22,
            a.exam_code_23,
            a.exam_code_24,
            a.exam_code_25,
            a.exam_code_26,
            a.exam_code_27,
            a.exam_code_28,
            a.exam_code_29,
            a.exam_code_30,
            a.exam_grade_01,
            a.exam_grade_02,
            a.exam_grade_03,
            a.exam_grade_04,
            a.exam_grade_05,
            a.exam_grade_06,
            a.exam_grade_07,
            a.exam_grade_08,
            a.exam_grade_09,
            a.exam_grade_10,
            a.exam_grade_11,
            a.exam_grade_12,
            a.exam_grade_13,
            a.exam_grade_14,
            a.exam_grade_15,
            a.exam_grade_16,
            a.exam_grade_17,
            a.exam_grade_18,
            a.exam_grade_19,
            a.exam_grade_20,
            a.exam_grade_21,
            a.exam_grade_22,
            a.exam_grade_23,
            a.exam_grade_24,
            a.exam_grade_25,
            a.exam_grade_26,
            a.exam_grade_27,
            a.exam_grade_28,
            a.exam_grade_29,
            a.exam_grade_30,
            a.irregularity_code_1_01,
            a.irregularity_code_1_02,
            a.irregularity_code_1_03,
            a.irregularity_code_1_04,
            a.irregularity_code_1_05,
            a.irregularity_code_1_06,
            a.irregularity_code_1_07,
            a.irregularity_code_1_08,
            a.irregularity_code_1_09,
            a.irregularity_code_1_10,
            a.irregularity_code_1_11,
            a.irregularity_code_1_12,
            a.irregularity_code_1_13,
            a.irregularity_code_1_14,
            a.irregularity_code_1_15,
            a.irregularity_code_1_16,
            a.irregularity_code_1_17,
            a.irregularity_code_1_18,
            a.irregularity_code_1_19,
            a.irregularity_code_1_20,
            a.irregularity_code_1_21,
            a.irregularity_code_1_22,
            a.irregularity_code_1_23,
            a.irregularity_code_1_24,
            a.irregularity_code_1_25,
            a.irregularity_code_1_26,
            a.irregularity_code_1_27,
            a.irregularity_code_1_28,
            a.irregularity_code_1_29,
            a.irregularity_code_1_30,
            a.irregularity_code_2_01,
            a.irregularity_code_2_02,
            a.irregularity_code_2_03,
            a.irregularity_code_2_04,
            a.irregularity_code_2_05,
            a.irregularity_code_2_06,
            a.irregularity_code_2_07,
            a.irregularity_code_2_08,
            a.irregularity_code_2_09,
            a.irregularity_code_2_10,
            a.irregularity_code_2_11,
            a.irregularity_code_2_12,
            a.irregularity_code_2_13,
            a.irregularity_code_2_14,
            a.irregularity_code_2_15,
            a.irregularity_code_2_16,
            a.irregularity_code_2_17,
            a.irregularity_code_2_18,
            a.irregularity_code_2_19,
            a.irregularity_code_2_20,
            a.irregularity_code_2_21,
            a.irregularity_code_2_22,
            a.irregularity_code_2_23,
            a.irregularity_code_2_24,
            a.irregularity_code_2_25,
            a.irregularity_code_2_26,
            a.irregularity_code_2_27,
            a.irregularity_code_2_28,
            a.irregularity_code_2_29,
            a.irregularity_code_2_30,

            x.powerschool_student_number,
        from {{ source("collegeboard", "src_collegeboard__ap") }} as a
        left join
            {{ ref("stg_collegeboard__ap_id_crosswalk") }} as x
            on a.ap_number_ap_id = x.college_board_id
    ),

    deduplicate as (
        {{
            dbt_utils.deduplicate(
                relation="ap",
                partition_by="powerschool_student_number",
                order_by="enrollment_school_year desc",
            )
        }}
    )

-- trunk-ignore(sqlfluff/AM04)
select
    * except (date_of_birth, grade_level),

    parse_date('%m%d%y', date_of_birth) as date_of_birth,

    case
        grade_level when '4' then 9 when '5' then 10 when '6' then 11 when '7' then 12
    end as grade_level,
from deduplicate
