select
    student_number,
    student_name as lastfirst,
    academic_year,
    region,
    school_level,
    school as school_abbreviation,
    grade_level,
    team,
    iep_status,
    gender,
    is_retained_year,
    enroll_status,
    absences_unexcused_year as abs_count,
    unweighted_ada as ada,
    calendardate as att_date,
    att_code,
    commlog_staff_name,
    commlog_reason,
    commlog_notes,
    commlog_topic,
    commlog_type,
    commlog_status,
    term,
    is_successful,
    is_successful_int,

    /* TODO: Remove deprecated columns */
    null as rn_date,
    null as homeroom,
    null as att_comment,
    null as reporting_schoolid,
    null as followup_staff_name,
    null as followup_init_notes,
    null as followup_close_notes,
    null as drill_down,
from {{ ref("int_topline__attendance_contacts") }}
where academic_year = {{ var("current_academic_year") }}
