select
    s._dbt_source_relation,
    s.academic_year,
    s.academic_year_display,
    s.region,
    s.school_level,
    s.schoolid,
    s.school,
    s.studentid,
    s.student_number,
    s.student_name,
    s.grade_level,
    s.salesforce_id,
    s.ktc_cohort,
    s.enroll_status,
    s.cohort,
    s.gender,
    s.ethnicity,
    s.advisory,
    s.hos,
    s.region_school_level,
    s.year_in_school,
    s.year_in_network,
    s.rn_undergrad,
    s.is_out_of_district,
    s.is_pathways,
    s.is_retained_year,
    s.is_retained_ever,
    s.lunch_status,
    s.gifted_and_talented,
    s.iep_status,
    s.lep_status,
    s.is_504,
    s.is_counseling_services,
    s.is_student_athlete,
    s.ada,
    s.`quarter`,
    s.semester,
    s.quarter_start_date,
    s.quarter_end_date,
    s.cal_quarter_end_date,
    s.is_current_quarter,
    s.is_quarter_end_date_range,

    s.sectionid,
    s.sections_dcid,
    s.section_number,
    s.external_expression,
    s.date_enrolled,
    s.credit_type,
    s.course_number,
    s.course_name,
    s.exclude_from_gpa,
    s.teacher_number,
    s.teacher_name,
    s.tutoring_nj,
    s.nj_student_tier,
    s.is_ap_course,
    s.tableau_username,
    s.ada_above_or_at_80,
    s.section_or_period,

from {{ ref("int_tableau__gradebook_audit_roster") }} as s
left join
    {{ ref("int_tableau__gradebook_audit_teacher_flags_fl_ms") }} as tcc
    on s.quarter = tcc.quarter
    and s.week_number
    and tcc.groupings = 'Teacher Class Category'
    and {{ union_dataset_join_clause(left_alias="s", right_alias="tcc") }}
