select
    s.academic_year,
    s.org,
    s.region,
    s.schoolid,
    s.school,
    s.grade_level,

    d.aligned_enrollment_academic_year,
    d.aligned_enrollment_academic_year_display,
    d.enrollment_academic_year,
    d.enrollment_academic_year_display,
    d.sre_aligned_academic_year_start,
    d.sre_aligned_academic_year_end,
    d.finalsite_student_id,
    d.latest_grade_level,
    d.next_year_enrollment_type,
    d.overall_status,
    d.funnel_status,
    d.status_category,
    d.offered_status,
    d.offered_status_detailed,
    d.detailed_status_ranking,
    d.detailed_status_branched_ranking,
    d.detailed_status,
    d.calendar_day,
    d.sre_aligned_academic_year_wk_start_monday,
    d.sre_aligned_academic_year_wk_end_sunday,
    d.student_org,
    d.student_region,
    d.student_latest_region,
    d.student_schoolid,
    d.student_latest_schoolid,
    d.student_school,
    d.student_latest_school,
    d.student_finalsite_student_id,
    d.student_last_name,
    d.student_first_name,
    d.student_grade_level,
    d.student_next_year_enrollment_type,
    d.student_detailed_status,
    d.student_latest_status,
    d.student_status_start_date,
    d.student_status_end_date,
    d.student_days_in_status,
    d.student_applicant_ops,
    d.student_offered_ops,
    d.student_pending_offer_ops,
    d.student_overall_conversion_ops,
    d.student_offers_to_accepted_num,
    d.student_offers_to_accepted_den,
    d.student_accepted_to_enrolled_num,
    d.student_accepted_to_enrolled_den,
    d.student_offers_to_enrolled_num,
    d.student_offers_to_enrolled_den,

from {{ ref("stg_google_sheets__finalsite__school_scaffold") }} as s
left join
    {{ ref("int_tableau__finalsite_student_scaffold") }} as d
    on s.academic_year = d.aligned_enrollment_academic_year
    and s.schoolid = d.latest_schoolid
    and s.grade_level = d.latest_grade_level
