select
    t.academic_year,
    t.academic_year_display,
    t.region,
    t.school_level,
    t.region_school_level,
    t.schoolid,
    t.school,
    t.`quarter`,
    t.semester,
    t.audit_qt_week_number,
    t.quarter_start_date,
    t.quarter_end_date,
    t.is_current_quarter,
    t.is_quarter_end_date_range,
    t.audit_start_date,
    t.audit_end_date,
    t.audit_due_date,
    t.assignment_category_name,
    t.assignment_category_code,
    t.assignment_category_term,
    t.expectation,
    t.notes,
    t.section_or_period,
    t.sectionid,
    t.sections_dcid,
    t.section_number,
    t.external_expression,
    t.credit_type,
    t.course_number,
    t.course_name,
    t.exclude_from_gpa,
    t.is_ap_course,
    t.teacher_number,
    t.teacher_name,
    t.teacher_tableau_username,
    t.school_leader,
    t.school_leader_tableau_username,
    t.teacher_assign_id,
    t.teacher_assign_name,
    t.teacher_assign_due_date,
    t.teacher_assign_score_type,
    t.teacher_assign_max_score,
    t.n_students,
    t.n_late,
    t.n_exempt,
    t.n_missing,
    t.n_null,
    t.n_is_null_missing,
    t.n_is_null_not_missing,
    t.n_expected,
    t.n_expected_scored,
    t.total_expected_scored_section_quarter_week_category,
    t.total_expected_section_quarter_week_category,
    t.percent_graded_for_quarter_week_class,
    t.sum_totalpointvalue_section_quarter_category,
    t.teacher_running_total_assign_by_cat,
    t.teacher_avg_score_for_assign_per_class_section_and_assign_id,
    t.audit_category,
    t.cte_grouping,
    t.code_type,
    t.audit_flag_name,
    t.audit_flag_value,

    v.studentid,
    v.student_number,
    v.student_name,
    v.grade_level,
    v.salesforce_id,
    v.ktc_cohort,
    v.enroll_status,
    v.cohort,
    v.gender,
    v.ethnicity,
    v.advisory,
    v.year_in_school,
    v.year_in_network,
    v.rn_undergrad,
    v.is_out_of_district,
    v.is_retained_year,
    v.is_retained_ever,
    v.lunch_status,
    v.gifted_and_talented,
    v.iep_status,
    v.lep_status,
    v.is_504,
    v.is_counseling_services,
    v.is_student_athlete,
    v.ada,
    v.ada_above_or_at_80,
    v.date_enrolled,
    v.category_quarter_average_all_courses,
    v.quarter_course_percent_grade,
    v.quarter_course_grade_points,
    v.quarter_conduct,
    v.quarter_comment_value,
    v.scorepoints as raw_score,
    v.score_entered,
    v.assign_final_score_percent,
    v.is_exempt,
    v.is_expected_late,
    v.is_expected_missing,

    coalesce(v.audit_flag_value, 0) as flag_value,

from {{ ref("int_tableau__gradebook_audit_teacher_aggs") }} as t
inner join
    {{ ref("int_tableau__gradebook_audit_flags__student") }} as v
    on t.academic_year = v.academic_year
    and t.region = v.region
    and t.schoolid = v.schoolid
    and t.quarter = v.`quarter`
    and t.audit_qt_week_number = v.week_number_quarter
    and t.sectionid = v.sectionid
    and t.teacher_number = v.teacher_number
    and t.audit_category = v.audit_category
    and t.cte_grouping = v.cte_grouping
    and t.audit_flag_name = v.audit_flag_name
    and v.audit_flag_value = 1
where
    t.audit_flag_name = 'qt_grade_70_comment_missing'
    and t.credit_type != 'HR'
    and t.audit_start_date <= current_date('{{ var("local_timezone") }}')
    and t.code_type = 'Quarter'
