select
    e._dbt_source_relation,
    e.academic_year,
    e.academic_year_display,
    e.district,
    e.schoolid,
    e.region,
    e.school,
    e.studentid,
    e.students_dcid,
    e.student_number,
    e.state_studentnumber,
    e.salesforce_id,
    e.student_name,
    e.student_first_name,
    e.student_last_name,
    e.grade_level,
    e.enroll_status,
    e.student_email,
    e.cohort,
    e.ktc_cohort,
    e.gender,
    e.ethnicity,
    e.lep_status,
    e.iep_status,
    e.gifted_and_talented,
    e.is_504,
    e.is_out_of_district,
    e.is_self_contained,
    e.is_counseling_services,
    e.is_student_athlete,
    e.advisory,
    e.college_match_gpa,
    e.college_match_gpa_bands,

from {{ ref("int_extracts__student_enrollments") }} as e
where
    e.grade_level >= 9
    and e.academic_year = {{ var("current_academic_year") }}
    and e.student_number = 203535
