select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    schoolid,
    school,
    grade_level,
    sre_year_start,
    sre_year_end,
    week_start_monday,
    week_end_sunday,
    enrollment_type,
    overall_status,
    funnel_status,
    status_category,
    offered_status,
    offered_status_detailed,
    detailed_status,
    detailed_status_ranking,
    detailed_status_branched_ranking,
    powerschool_enroll_status,
    valid_detailed_status,
    applicant_ops,
    offered_ops,
    pending_offer_ops,
    overall_conversion_ops,
    offers_to_accepted_den,
    offers_to_accepted_num,
    accepted_to_enrolled_den,
    accepted_to_enrolled_num,
    offers_to_enrolled_den,
    offers_to_enrolled_num,
    waitlisted,
    finalsite_student_id,
    student_enrollment_year,
    student_region,
    student_schoolid,
    student_school,
    student_number,
    student_last_name,
    student_first_name,
    student_grade_level,
    student_grade_level_string,
    student_detailed_status,
    status_start_date,
    status_end_date,
    days_in_status,
    student_enrollment_type,

    first_value(detailed_status) over (
        partition by academic_year, finalsite_student_id order by status_start_date desc
    ) as latest_status,

from {{ ref("int_students__finalsite_student_roster") }}
