select
    b.employee_number as df_employee_number,
    b.legal_name_given_name as first_name,
    b.legal_name_family_name as last_name,
    b.preferred_name_given_name as preferred_first,
    b.preferred_name_family_name as preferred_last,
    b.preferred_name_lastfirst as preferred_name,
    b.assignment_status as position_status,
    b.worker_original_hire_date as original_hire_date,
    b.worker_rehire_date as rehire_date,
    b.worker_termination_date as termination_date,
    b.worker_type as worker_category_description,
    b.worker_group_value as benefits_eligibility_class_description,
    b.wage_law_coverage_short_name as flsa_description,
    b.ethnicity_long_name as eeo_ethnic_description,
    b.mail,
    b.user_principal_name as userprincipalname,
    b.report_to_employee_number as manager_df_employee_number,
    b.report_to_preferred_name_lastfirst as manager_name,
    b.report_to_mail as manager_mail,
    b.race_ethnicity_reporting,
    b.gender_identity,

    s.ay_business_unit,
    s.ay_job_title,
    s.ay_location,
    s.ay_salary,
    s.academic_year,
    s.ay_pm4_overall_score,
    s.ay_pm4_overall_tier,
    s.ay_primary_grade_level_taught,
    s.scale_cy_salary,
    s.scale_ny_salary,
    s.scale_step,
    s.pm_salary_increase,
    s.seat_tracker_id_number,
    s.ny_location,
    s.ny_dept,
    s.ny_title,
    s.nonrenewal_reason,
    s.nonrenewal_notes,
    s.ny_salary,
    s.salary_rule,
from {{ ref("base_people__staff_roster") }} as b
left join
    {{ ref("int_people__renewal_status") }} as s
    on b.employee_number = s.employee_number
    and s.academic_year = {{ var("current_academic_year") }}


