with
    student_teacher_aggs as (
        select
            academic_year,
            academic_year_display,
            region,
            school_level,
            region_school_level,
            schoolid,
            school,
            `quarter`,
            semester,
            week_number_quarter as audit_qt_week_number,
            quarter_start_date,
            quarter_end_date,
            is_current_term as is_current_quarter,
            is_quarter_end_date_range,
            week_start_monday as audit_start_date,
            week_end_sunday as audit_end_date,
            school_week_start_date_lead as audit_due_date,
            is_current_week,
            assignment_category_name,
            assignment_category_code,
            assignment_category_term,
            expectation,
            notes,
            section_or_period,
            sectionid,
            sections_dcid,
            section_number,
            external_expression,
            credit_type,
            course_number,
            course_name,
            exclude_from_gpa,
            is_ap_course,
            teacher_number,
            teacher_name,
            teacher_tableau_username,
            school_leader,
            school_leader_tableau_username,
            assignmentid as teacher_assign_id,
            assignment_name as teacher_assign_name,
            duedate as teacher_assign_due_date,
            scoretype as teacher_assign_score_type,
            totalpointvalue as teacher_assign_max_score,
            n_students,
            n_late,
            n_exempt,
            n_missing,
            n_null,
            n_academic_dishonesty,
            n_is_null_missing,
            n_is_null_not_missing,
            n_expected,
            n_expected_scored,

            null as total_expected_scored_section_quarter_week_category,
            null as total_expected_section_quarter_week_category,
            null as percent_graded_for_quarter_week_class,

            sum_totalpointvalue_section_quarter_category,
            teacher_running_total_assign_by_cat,
            teacher_avg_score_for_assign_per_class_section_and_assign_id,
            audit_category,
            cte_grouping,
            code_type,
            audit_flag_name,

            max(audit_flag_value) as audit_flag_value,

        from {{ ref("int_tableau__gradebook_audit_flags__student") }}
        group by
            academic_year,
            academic_year_display,
            region,
            school_level,
            region_school_level,
            schoolid,
            school,
            `quarter`,
            semester,
            week_number_quarter,
            quarter_start_date,
            quarter_end_date,
            is_current_term,
            is_quarter_end_date_range,
            week_start_monday,
            week_end_sunday,
            school_week_start_date_lead,
            is_current_week,
            assignment_category_name,
            assignment_category_code,
            assignment_category_term,
            expectation,
            notes,
            section_or_period,
            sectionid,
            sections_dcid,
            section_number,
            external_expression,
            credit_type,
            course_number,
            course_name,
            exclude_from_gpa,
            is_ap_course,
            teacher_number,
            teacher_name,
            teacher_tableau_username,
            school_leader,
            school_leader_tableau_username,
            assignmentid,
            assignment_name,
            duedate,
            scoretype,
            totalpointvalue,
            n_students,
            n_late,
            n_exempt,
            n_missing,
            n_null,
            n_academic_dishonesty,
            n_is_null_missing,
            n_is_null_not_missing,
            n_expected,
            n_expected_scored,
            sum_totalpointvalue_section_quarter_category,
            teacher_running_total_assign_by_cat,
            teacher_avg_score_for_assign_per_class_section_and_assign_id,
            audit_category,
            cte_grouping,
            code_type,
            audit_flag_name
    ),

    teacher_teacher_aggs as (
        select
            academic_year,
            academic_year_display,
            region,
            school_level,
            region_school_level,
            schoolid,
            school,
            `quarter`,
            semester,
            week_number_quarter as audit_qt_week_number,
            quarter_start_date,
            quarter_end_date,
            is_current_term as is_current_quarter,
            is_quarter_end_date_range,
            week_start_monday as audit_start_date,
            week_end_sunday as audit_end_date,
            school_week_start_date_lead as audit_due_date,
            is_current_week,
            assignment_category_name,
            assignment_category_code,
            assignment_category_term,
            expectation,
            notes,
            section_or_period,
            sectionid,
            sections_dcid,
            section_number,
            external_expression,
            credit_type,
            course_number,
            course_name,
            exclude_from_gpa,
            is_ap_course,
            teacher_number,
            teacher_name,
            teacher_tableau_username,
            school_leader,
            school_leader_tableau_username,
            assignmentid as teacher_assign_id,
            assignment_name as teacher_assign_name,
            duedate as teacher_assign_due_date,
            scoretype as teacher_assign_score_type,
            totalpointvalue as teacher_assign_max_score,
            n_students,
            n_late,
            n_exempt,
            n_missing,
            n_null,
            n_academic_dishonesty,
            n_is_null_missing,
            n_is_null_not_missing,
            n_expected,
            n_expected_scored,
            total_expected_scored_section_quarter_week_category,
            total_expected_section_quarter_week_category,
            percent_graded_for_quarter_week_class,
            sum_totalpointvalue_section_quarter_category,
            teacher_running_total_assign_by_cat,
            teacher_avg_score_for_assign_per_class_section_and_assign_id,
            audit_category,
            cte_grouping,
            code_type,
            audit_flag_name,

            max(audit_flag_value) as audit_flag_value,

        from {{ ref("int_tableau__gradebook_audit_flags__teacher") }}
        group by
            academic_year,
            academic_year_display,
            region,
            school_level,
            region_school_level,
            schoolid,
            school,
            `quarter`,
            semester,
            week_number_quarter,
            quarter_start_date,
            quarter_end_date,
            is_current_term,
            is_quarter_end_date_range,
            week_start_monday,
            week_end_sunday,
            school_week_start_date_lead,
            is_current_week,
            assignment_category_name,
            assignment_category_code,
            assignment_category_term,
            expectation,
            notes,
            section_or_period,
            sectionid,
            sections_dcid,
            section_number,
            external_expression,
            credit_type,
            course_number,
            course_name,
            exclude_from_gpa,
            is_ap_course,
            teacher_number,
            teacher_name,
            teacher_tableau_username,
            school_leader,
            school_leader_tableau_username,
            assignmentid,
            assignment_name,
            duedate,
            scoretype,
            totalpointvalue,
            n_students,
            n_late,
            n_exempt,
            n_missing,
            n_null,
            n_academic_dishonesty,
            n_is_null_missing,
            n_is_null_not_missing,
            n_expected,
            n_expected_scored,
            total_expected_scored_section_quarter_week_category,
            total_expected_section_quarter_week_category,
            percent_graded_for_quarter_week_class,
            sum_totalpointvalue_section_quarter_category,
            teacher_running_total_assign_by_cat,
            teacher_avg_score_for_assign_per_class_section_and_assign_id,
            audit_category,
            cte_grouping,
            code_type,
            audit_flag_name
    ),

    student_valid_flags as (
        select
            academic_year,
            region,
            schoolid,
            `quarter`,
            week_number_quarter as audit_qt_week_number,
            assignment_category_term,
            sectionid,
            teacher_number,
            assignmentid as teacher_assign_id,
            studentid,
            student_number,
            student_name,
            grade_level,
            salesforce_id,
            ktc_cohort,
            enroll_status,
            cohort,
            gender,
            ethnicity,
            advisory,
            year_in_school,
            year_in_network,
            rn_undergrad,
            is_out_of_district,
            is_retained_year,
            is_retained_ever,
            lunch_status,
            gifted_and_talented,
            iep_status,
            lep_status,
            is_504,
            is_counseling_services,
            is_student_athlete,
            ada,
            ada_above_or_at_80,
            date_enrolled,
            category_quarter_percent_grade,
            category_quarter_average_all_courses,
            quarter_course_percent_grade,
            quarter_course_grade_points,
            quarter_conduct,
            quarter_comment_value,
            scorepoints as raw_score,
            score_entered,
            assign_final_score_percent,
            is_exempt,
            is_expected_late,
            is_expected_missing,
            is_expected_academic_dishonesty,
            audit_category,
            cte_grouping,
            code_type,
            audit_flag_name,
            audit_flag_value as flag_value,

        from {{ ref("int_tableau__gradebook_audit_flags__student") }}
        where audit_flag_value = 1
    ),

    teacher_valid_flags as (
        select
            academic_year,
            region,
            schoolid,
            `quarter`,
            week_number_quarter as audit_qt_week_number,
            assignment_category_term,
            sectionid,
            teacher_number,
            assignmentid as teacher_assign_id,

            null as studentid,
            null as student_number,
            null as student_name,
            null as grade_level,
            null as salesforce_id,
            null as ktc_cohort,
            null as enroll_status,
            null as cohort,
            null as gender,
            null as ethnicity,
            null as advisory,
            null as year_in_school,
            null as year_in_network,
            null as rn_undergrad,
            null as is_out_of_district,
            null as is_retained_year,
            null as is_retained_ever,
            null as lunch_status,
            null as gifted_and_talented,
            null as iep_status,
            null as lep_status,
            null as is_504,
            null as is_counseling_services,
            null as is_student_athlete,
            null as ada,
            null as ada_above_or_at_80,
            null as date_enrolled,

            category_quarter_percent_grade,
            category_quarter_average_all_courses,

            null as quarter_course_percent_grade,
            null as quarter_course_grade_points,
            null as quarter_conduct,
            null as quarter_comment_value,
            null as raw_score,
            null as score_entered,
            null as assign_final_score_percent,
            null as is_exempt,
            null as is_expected_late,
            null as is_expected_missing,
            null as is_expected_academic_dishonesty,

            audit_category,
            cte_grouping,
            code_type,
            audit_flag_name,
            audit_flag_value as flag_value,

        from {{ ref("int_tableau__gradebook_audit_flags__teacher") }}
        where audit_flag_value = 1
    )

select
    t.academic_year,
    t.academic_year_display,
    t.region,
    t.school_level,
    t.region_school_level,
    t.schoolid,
    t.school,
    t.quarter,
    t.semester,
    t.audit_qt_week_number,
    t.quarter_start_date,
    t.quarter_end_date,
    t.is_current_quarter,
    t.is_quarter_end_date_range,
    t.audit_start_date,
    t.audit_end_date,
    t.audit_due_date,
    t.is_current_week,
    t.assignment_category_name,
    t.assignment_category_code,
    t.assignment_category_term,
    t.expectation,
    t.notes,
    t.section_or_period,
    t.sectionid,
    t.sections_dcid,
    t.section_number,
    t.external_expression,
    t.credit_type,
    t.course_number,
    t.course_name,
    t.exclude_from_gpa,
    t.is_ap_course,
    t.teacher_number,
    t.teacher_name,
    t.teacher_tableau_username,
    t.school_leader,
    t.school_leader_tableau_username,
    t.teacher_assign_id,
    t.teacher_assign_name,
    t.teacher_assign_due_date,
    t.teacher_assign_score_type,
    t.teacher_assign_max_score,
    t.n_students,
    t.n_late,
    t.n_exempt,
    t.n_missing,
    t.n_null,
    t.n_academic_dishonesty,
    t.n_is_null_missing,
    t.n_is_null_not_missing,
    t.n_expected,
    t.n_expected_scored,
    t.total_expected_scored_section_quarter_week_category,
    t.total_expected_section_quarter_week_category,
    t.percent_graded_for_quarter_week_class,
    t.sum_totalpointvalue_section_quarter_category,
    t.teacher_running_total_assign_by_cat,
    t.teacher_avg_score_for_assign_per_class_section_and_assign_id,
    t.audit_category,
    t.cte_grouping,
    t.code_type,
    t.audit_flag_name,
    t.audit_flag_value,

    v.studentid,
    v.student_number,
    v.student_name,
    v.grade_level,
    v.salesforce_id,
    v.ktc_cohort,
    v.enroll_status,
    v.cohort,
    v.gender,
    v.ethnicity,
    v.advisory,
    v.year_in_school,
    v.year_in_network,
    v.rn_undergrad,
    v.is_out_of_district,
    v.is_retained_year,
    v.is_retained_ever,
    v.lunch_status,
    v.gifted_and_talented,
    v.iep_status,
    v.lep_status,
    v.is_504,
    v.is_counseling_services,
    v.is_student_athlete,
    v.ada,
    v.ada_above_or_at_80,
    v.date_enrolled,
    v.category_quarter_percent_grade,
    v.category_quarter_average_all_courses,
    v.quarter_course_percent_grade,
    v.quarter_course_grade_points,
    v.quarter_conduct,
    v.quarter_comment_value,
    v.raw_score,
    v.score_entered,
    v.assign_final_score_percent,
    v.is_exempt,
    v.is_expected_late,
    v.is_expected_missing,
    v.is_expected_academic_dishonesty,

    coalesce(v.flag_value, 0) as flag_value,

from student_teacher_aggs as t
left join
    student_valid_flags as v
    on t.academic_year = v.academic_year
    and t.region = v.region
    and t.schoolid = v.schoolid
    and t.quarter = v.quarter
    and t.audit_qt_week_number = v.audit_qt_week_number
    and t.sectionid = v.sectionid
    and t.teacher_number = v.teacher_number
    and t.assignment_category_term = v.assignment_category_term
    and t.teacher_assign_id = v.teacher_assign_id
    and t.audit_category = v.audit_category
    and t.cte_grouping = v.cte_grouping
    and t.audit_flag_name = v.audit_flag_name
where
    t.code_type = 'Gradebook Category'
    and t.cte_grouping = 'assignment_student'
    and t.audit_start_date <= current_date('{{ var("local_timezone") }}')
    and not t.is_current_week

union all

select
    t.academic_year,
    t.academic_year_display,
    t.region,
    t.school_level,
    t.region_school_level,
    t.schoolid,
    t.school,
    t.quarter,
    t.semester,
    t.audit_qt_week_number,
    t.quarter_start_date,
    t.quarter_end_date,
    t.is_current_quarter,
    t.is_quarter_end_date_range,
    t.audit_start_date,
    t.audit_end_date,
    t.audit_due_date,
    t.is_current_week,
    t.assignment_category_name,
    t.assignment_category_code,
    t.assignment_category_term,
    t.expectation,
    t.notes,
    t.section_or_period,
    t.sectionid,
    t.sections_dcid,
    t.section_number,
    t.external_expression,
    t.credit_type,
    t.course_number,
    t.course_name,
    t.exclude_from_gpa,
    t.is_ap_course,
    t.teacher_number,
    t.teacher_name,
    t.teacher_tableau_username,
    t.school_leader,
    t.school_leader_tableau_username,
    t.teacher_assign_id,
    t.teacher_assign_name,
    t.teacher_assign_due_date,
    t.teacher_assign_score_type,
    t.teacher_assign_max_score,
    t.n_students,
    t.n_late,
    t.n_exempt,
    t.n_missing,
    t.n_null,
    t.n_academic_dishonesty,
    t.n_is_null_missing,
    t.n_is_null_not_missing,
    t.n_expected,
    t.n_expected_scored,
    t.total_expected_scored_section_quarter_week_category,
    t.total_expected_section_quarter_week_category,
    t.percent_graded_for_quarter_week_class,
    t.sum_totalpointvalue_section_quarter_category,
    t.teacher_running_total_assign_by_cat,
    t.teacher_avg_score_for_assign_per_class_section_and_assign_id,
    t.audit_category,
    t.cte_grouping,
    t.code_type,
    t.audit_flag_name,
    t.audit_flag_value,

    v.studentid,
    v.student_number,
    v.student_name,
    v.grade_level,
    v.salesforce_id,
    v.ktc_cohort,
    v.enroll_status,
    v.cohort,
    v.gender,
    v.ethnicity,
    v.advisory,
    v.year_in_school,
    v.year_in_network,
    v.rn_undergrad,
    v.is_out_of_district,
    v.is_retained_year,
    v.is_retained_ever,
    v.lunch_status,
    v.gifted_and_talented,
    v.iep_status,
    v.lep_status,
    v.is_504,
    v.is_counseling_services,
    v.is_student_athlete,
    v.ada,
    v.ada_above_or_at_80,
    v.date_enrolled,
    v.category_quarter_percent_grade,
    v.category_quarter_average_all_courses,
    v.quarter_course_percent_grade,
    v.quarter_course_grade_points,
    v.quarter_conduct,
    v.quarter_comment_value,
    v.raw_score,
    v.score_entered,
    v.assign_final_score_percent,
    v.is_exempt,
    v.is_expected_late,
    v.is_expected_missing,
    v.is_expected_academic_dishonesty,

    coalesce(v.flag_value, 0) as flag_value,

from student_teacher_aggs as t
left join
    student_valid_flags as v
    on t.academic_year = v.academic_year
    and t.region = v.region
    and t.schoolid = v.schoolid
    and t.quarter = v.quarter
    and t.audit_qt_week_number = v.audit_qt_week_number
    and t.sectionid = v.sectionid
    and t.teacher_number = v.teacher_number
    and t.assignment_category_term = v.assignment_category_term
    and t.audit_category = v.audit_category
    and t.cte_grouping = v.cte_grouping
    and t.audit_flag_name = v.audit_flag_name
where
    t.cte_grouping = 'student_course_category'
    and t.audit_start_date <= current_date('{{ var("local_timezone") }}')
    and not t.is_current_week

union all

select
    t.academic_year,
    t.academic_year_display,
    t.region,
    t.school_level,
    t.region_school_level,
    t.schoolid,
    t.school,
    t.quarter,
    t.semester,
    t.audit_qt_week_number,
    t.quarter_start_date,
    t.quarter_end_date,
    t.is_current_quarter,
    t.is_quarter_end_date_range,
    t.audit_start_date,
    t.audit_end_date,
    t.audit_due_date,
    t.is_current_week,
    t.assignment_category_name,
    t.assignment_category_code,
    t.assignment_category_term,
    t.expectation,
    t.notes,
    t.section_or_period,
    t.sectionid,
    t.sections_dcid,
    t.section_number,
    t.external_expression,
    t.credit_type,
    t.course_number,
    t.course_name,
    t.exclude_from_gpa,
    t.is_ap_course,
    t.teacher_number,
    t.teacher_name,
    t.teacher_tableau_username,
    t.school_leader,
    t.school_leader_tableau_username,
    t.teacher_assign_id,
    t.teacher_assign_name,
    t.teacher_assign_due_date,
    t.teacher_assign_score_type,
    t.teacher_assign_max_score,
    t.n_students,
    t.n_late,
    t.n_exempt,
    t.n_missing,
    t.n_null,
    t.n_academic_dishonesty,
    t.n_is_null_missing,
    t.n_is_null_not_missing,
    t.n_expected,
    t.n_expected_scored,
    t.total_expected_scored_section_quarter_week_category,
    t.total_expected_section_quarter_week_category,
    t.percent_graded_for_quarter_week_class,
    t.sum_totalpointvalue_section_quarter_category,
    t.teacher_running_total_assign_by_cat,
    t.teacher_avg_score_for_assign_per_class_section_and_assign_id,
    t.audit_category,
    t.cte_grouping,
    t.code_type,
    t.audit_flag_name,
    t.audit_flag_value,

    v.studentid,
    v.student_number,
    v.student_name,
    v.grade_level,
    v.salesforce_id,
    v.ktc_cohort,
    v.enroll_status,
    v.cohort,
    v.gender,
    v.ethnicity,
    v.advisory,
    v.year_in_school,
    v.year_in_network,
    v.rn_undergrad,
    v.is_out_of_district,
    v.is_retained_year,
    v.is_retained_ever,
    v.lunch_status,
    v.gifted_and_talented,
    v.iep_status,
    v.lep_status,
    v.is_504,
    v.is_counseling_services,
    v.is_student_athlete,
    v.ada,
    v.ada_above_or_at_80,
    v.date_enrolled,
    v.category_quarter_percent_grade,
    v.category_quarter_average_all_courses,
    v.quarter_course_percent_grade,
    v.quarter_course_grade_points,
    v.quarter_conduct,
    v.quarter_comment_value,
    v.raw_score,
    v.score_entered,
    v.assign_final_score_percent,
    v.is_exempt,
    v.is_expected_late,
    v.is_expected_missing,
    v.is_expected_academic_dishonesty,

    coalesce(v.flag_value, 0) as flag_value,

from student_teacher_aggs as t
left join
    student_valid_flags as v
    on t.academic_year = v.academic_year
    and t.region = v.region
    and t.schoolid = v.schoolid
    and t.quarter = v.quarter
    and t.audit_qt_week_number = v.audit_qt_week_number
    and t.sectionid = v.sectionid
    and t.teacher_number = v.teacher_number
    and t.audit_category = v.audit_category
    and t.cte_grouping = v.cte_grouping
    and t.audit_flag_name = v.audit_flag_name
where
    t.code_type = 'Quarter'
    and t.cte_grouping != 'student_course_category'
    and t.audit_start_date <= current_date('{{ var("local_timezone") }}')
    and not t.is_current_week

union all

select
    t.academic_year,
    t.academic_year_display,
    t.region,
    t.school_level,
    t.region_school_level,
    t.schoolid,
    t.school,
    t.quarter,
    t.semester,
    t.audit_qt_week_number,
    t.quarter_start_date,
    t.quarter_end_date,
    t.is_current_quarter,
    t.is_quarter_end_date_range,
    t.audit_start_date,
    t.audit_end_date,
    t.audit_due_date,
    t.is_current_week,
    t.assignment_category_name,
    t.assignment_category_code,
    t.assignment_category_term,
    t.expectation,
    t.notes,
    t.section_or_period,
    t.sectionid,
    t.sections_dcid,
    t.section_number,
    t.external_expression,
    t.credit_type,
    t.course_number,
    t.course_name,
    t.exclude_from_gpa,
    t.is_ap_course,
    t.teacher_number,
    t.teacher_name,
    t.teacher_tableau_username,
    t.school_leader,
    t.school_leader_tableau_username,
    t.teacher_assign_id,
    t.teacher_assign_name,
    t.teacher_assign_due_date,
    t.teacher_assign_score_type,
    t.teacher_assign_max_score,
    t.n_students,
    t.n_late,
    t.n_exempt,
    t.n_missing,
    t.n_null,
    t.n_academic_dishonesty,
    t.n_is_null_missing,
    t.n_is_null_not_missing,
    t.n_expected,
    t.n_expected_scored,
    t.total_expected_scored_section_quarter_week_category,
    t.total_expected_section_quarter_week_category,
    t.percent_graded_for_quarter_week_class,
    t.sum_totalpointvalue_section_quarter_category,
    t.teacher_running_total_assign_by_cat,
    t.teacher_avg_score_for_assign_per_class_section_and_assign_id,
    t.audit_category,
    t.cte_grouping,
    t.code_type,
    t.audit_flag_name,
    t.audit_flag_value,

    v.studentid,
    v.student_number,
    v.student_name,
    v.grade_level,
    v.salesforce_id,
    v.ktc_cohort,
    v.enroll_status,
    v.cohort,
    v.gender,
    v.ethnicity,
    v.advisory,
    v.year_in_school,
    v.year_in_network,
    v.rn_undergrad,
    v.is_out_of_district,
    v.is_retained_year,
    v.is_retained_ever,
    v.lunch_status,
    v.gifted_and_talented,
    v.iep_status,
    v.lep_status,
    v.is_504,
    v.is_counseling_services,
    v.is_student_athlete,
    v.ada,
    v.ada_above_or_at_80,
    v.date_enrolled,
    v.category_quarter_percent_grade,
    v.category_quarter_average_all_courses,
    v.quarter_course_percent_grade,
    v.quarter_course_grade_points,
    v.quarter_conduct,
    v.quarter_comment_value,
    v.raw_score,
    v.score_entered,
    v.assign_final_score_percent,
    v.is_exempt,
    v.is_expected_late,
    v.is_expected_missing,
    v.is_expected_academic_dishonesty,

    coalesce(v.flag_value, 0) as flag_value,

from teacher_teacher_aggs as t
left join
    teacher_valid_flags as v
    on t.academic_year = v.academic_year
    and t.region = v.region
    and t.schoolid = v.schoolid
    and t.quarter = v.quarter
    and t.audit_qt_week_number = v.audit_qt_week_number
    and t.sectionid = v.sectionid
    and t.teacher_number = v.teacher_number
    and t.assignment_category_term = v.assignment_category_term
    and t.teacher_assign_id = v.teacher_assign_id
    and t.audit_category = v.audit_category
    and t.cte_grouping = v.cte_grouping
    and t.audit_flag_name = v.audit_flag_name
where
    t.code_type = 'Gradebook Category'
    and t.cte_grouping = 'class_category_assignment'
    and t.audit_start_date <= current_date('{{ var("local_timezone") }}')
    and not t.is_current_week

union all

select
    t.academic_year,
    t.academic_year_display,
    t.region,
    t.school_level,
    t.region_school_level,
    t.schoolid,
    t.school,
    t.quarter,
    t.semester,
    t.audit_qt_week_number,
    t.quarter_start_date,
    t.quarter_end_date,
    t.is_current_quarter,
    t.is_quarter_end_date_range,
    t.audit_start_date,
    t.audit_end_date,
    t.audit_due_date,
    t.is_current_week,
    t.assignment_category_name,
    t.assignment_category_code,
    t.assignment_category_term,
    t.expectation,
    t.notes,
    t.section_or_period,
    t.sectionid,
    t.sections_dcid,
    t.section_number,
    t.external_expression,
    t.credit_type,
    t.course_number,
    t.course_name,
    t.exclude_from_gpa,
    t.is_ap_course,
    t.teacher_number,
    t.teacher_name,
    t.teacher_tableau_username,
    t.school_leader,
    t.school_leader_tableau_username,
    t.teacher_assign_id,
    t.teacher_assign_name,
    t.teacher_assign_due_date,
    t.teacher_assign_score_type,
    t.teacher_assign_max_score,
    t.n_students,
    t.n_late,
    t.n_exempt,
    t.n_missing,
    t.n_null,
    t.n_academic_dishonesty,
    t.n_is_null_missing,
    t.n_is_null_not_missing,
    t.n_expected,
    t.n_expected_scored,
    t.total_expected_scored_section_quarter_week_category,
    t.total_expected_section_quarter_week_category,
    t.percent_graded_for_quarter_week_class,
    t.sum_totalpointvalue_section_quarter_category,
    t.teacher_running_total_assign_by_cat,
    t.teacher_avg_score_for_assign_per_class_section_and_assign_id,
    t.audit_category,
    t.cte_grouping,
    t.code_type,
    t.audit_flag_name,
    t.audit_flag_value,

    v.studentid,
    v.student_number,
    v.student_name,
    v.grade_level,
    v.salesforce_id,
    v.ktc_cohort,
    v.enroll_status,
    v.cohort,
    v.gender,
    v.ethnicity,
    v.advisory,
    v.year_in_school,
    v.year_in_network,
    v.rn_undergrad,
    v.is_out_of_district,
    v.is_retained_year,
    v.is_retained_ever,
    v.lunch_status,
    v.gifted_and_talented,
    v.iep_status,
    v.lep_status,
    v.is_504,
    v.is_counseling_services,
    v.is_student_athlete,
    v.ada,
    v.ada_above_or_at_80,
    v.date_enrolled,
    v.category_quarter_percent_grade,
    v.category_quarter_average_all_courses,
    v.quarter_course_percent_grade,
    v.quarter_course_grade_points,
    v.quarter_conduct,
    v.quarter_comment_value,
    v.raw_score,
    v.score_entered,
    v.assign_final_score_percent,
    v.is_exempt,
    v.is_expected_late,
    v.is_expected_missing,
    v.is_expected_academic_dishonesty,

    coalesce(v.flag_value, 0) as flag_value,

from teacher_teacher_aggs as t
left join
    teacher_valid_flags as v
    on t.academic_year = v.academic_year
    and t.region = v.region
    and t.schoolid = v.schoolid
    and t.quarter = v.quarter
    and t.audit_qt_week_number = v.audit_qt_week_number
    and t.sectionid = v.sectionid
    and t.teacher_number = v.teacher_number
    and t.assignment_category_term = v.assignment_category_term
    and t.audit_category = v.audit_category
    and t.cte_grouping = v.cte_grouping
    and t.audit_flag_name = v.audit_flag_name
where
    t.code_type = 'Gradebook Category'
    and t.cte_grouping = 'class_category'
    and t.audit_start_date <= current_date('{{ var("local_timezone") }}')
    and not t.is_current_week
