{{- config(materialized="table") -}}

select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    region_school_level,
    schoolid,
    school,
    studentid,
    student_number,
    student_name,
    grade_level,
    salesforce_id,
    ktc_cohort,
    enroll_status,
    cohort,
    gender,
    ethnicity,
    advisory,
    hos,
    year_in_school,
    year_in_network,
    rn_undergrad,
    is_out_of_district,
    is_pathways,
    is_retained_year,
    is_retained_ever,
    lunch_status,
    gifted_and_talented,
    iep_status,
    lep_status,
    is_504,
    is_counseling_services,
    is_student_athlete,
    ada,
    ada_above_or_at_80,
    date_enrolled,
    `quarter`,
    semester,
    week_number,
    quarter_start_date,
    quarter_end_date,
    cal_quarter_end_date,
    is_current_quarter,
    is_quarter_end_date_range,
    audit_start_date,
    audit_end_date,
    audit_due_date,
    assignment_category_name,
    assignment_category_code,
    assignment_category_term,
    expectation,
    notes,
    section_or_period,
    sectionid,
    sections_dcid,
    section_number,
    external_expression,
    credit_type,
    course_number,
    course_name,
    exclude_from_gpa,
    is_ap_course,
    teacher_number,
    teacher_name,
    tableau_username,
    category_quarter_percent_grade,
    category_quarter_average_all_courses,
    quarter_course_percent_grade_that_matters,
    quarter_course_grade_points_that_matters,
    quarter_citizenship,
    quarter_comment_value,
    audit_category,
    teacher_assign_id,
    teacher_assign_name,
    teacher_assign_due_date,
    teacher_assign_score_type,
    teacher_assign_max_score,
    n_students,
    n_late,
    n_exempt,
    n_missing,
    n_expected,
    n_expected_scored,
    teacher_running_total_assign_by_cat,
    teacher_avg_score_for_assign_per_class_section_and_assign_id,
    raw_score,
    score_entered,
    assign_final_score_percent,
    is_exempt,
    is_late,
    is_missing,

    coalesce(audit_flag_name, 'no_flag') as audit_flag_name,
    coalesce(audit_flag_value, 0) as audit_flag_value,
from {{ ref("int_tableau__gradebook_audit_flags") }}
where cte_grouping = 'assignment_student' and school_level != 'ES'

union all

select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    region_school_level,
    schoolid,
    school,
    studentid,
    student_number,
    student_name,
    grade_level,
    salesforce_id,
    ktc_cohort,
    enroll_status,
    cohort,
    gender,
    ethnicity,
    advisory,
    hos,
    year_in_school,
    year_in_network,
    rn_undergrad,
    is_out_of_district,
    is_pathways,
    is_retained_year,
    is_retained_ever,
    lunch_status,
    gifted_and_talented,
    iep_status,
    lep_status,
    is_504,
    is_counseling_services,
    is_student_athlete,
    ada,
    ada_above_or_at_80,
    date_enrolled,
    `quarter`,
    semester,
    week_number,
    quarter_start_date,
    quarter_end_date,
    cal_quarter_end_date,
    is_current_quarter,
    is_quarter_end_date_range,
    audit_start_date,
    audit_end_date,
    audit_due_date,
    assignment_category_name,
    assignment_category_code,
    assignment_category_term,
    expectation,
    notes,
    section_or_period,
    sectionid,
    sections_dcid,
    section_number,
    external_expression,
    credit_type,
    course_number,
    course_name,
    exclude_from_gpa,
    is_ap_course,
    teacher_number,
    teacher_name,
    tableau_username,
    category_quarter_percent_grade,
    category_quarter_average_all_courses,
    quarter_course_percent_grade_that_matters,
    quarter_course_grade_points_that_matters,
    quarter_citizenship,
    quarter_comment_value,
    audit_category,

    null as teacher_assign_id,
    null as teacher_assign_name,
    null as teacher_assign_due_date,
    null as teacher_assign_score_type,
    null as teacher_assign_max_score,
    null as n_students,
    null as n_late,
    null as n_exempt,
    null as n_missing,
    null as n_expected,
    null as n_expected_scored,
    null as teacher_running_total_assign_by_cat,
    null as teacher_avg_score_for_assign_per_class_section_and_assign_id,
    null as raw_score,
    null as score_entered,
    null as assign_final_score_percent,
    null as is_exempt,
    null as is_late,
    null as is_missing,

    coalesce(audit_flag_name, 'no_flag') as audit_flag_name,
    coalesce(audit_flag_value, 0) as audit_flag_value,
from {{ ref("int_tableau__gradebook_audit_flags") }}
where
    assignment_category_code = 'W'
    and audit_flag_name = 'w_grade_inflation'
    and cte_grouping not in ('student_course', 'student')
    and school_level != 'ES'

union all

select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    region_school_level,
    schoolid,
    school,
    studentid,
    student_number,
    student_name,
    grade_level,
    salesforce_id,
    ktc_cohort,
    enroll_status,
    cohort,
    gender,
    ethnicity,
    advisory,
    hos,
    year_in_school,
    year_in_network,
    rn_undergrad,
    is_out_of_district,
    is_pathways,
    is_retained_year,
    is_retained_ever,
    lunch_status,
    gifted_and_talented,
    iep_status,
    lep_status,
    is_504,
    is_counseling_services,
    is_student_athlete,
    ada,
    ada_above_or_at_80,
    date_enrolled,
    `quarter`,
    semester,
    week_number,
    quarter_start_date,
    quarter_end_date,
    cal_quarter_end_date,
    is_current_quarter,
    is_quarter_end_date_range,
    audit_start_date,
    audit_end_date,
    audit_due_date,
    assignment_category_name,
    assignment_category_code,
    assignment_category_term,
    expectation,
    notes,
    section_or_period,
    sectionid,
    sections_dcid,
    section_number,
    external_expression,
    credit_type,
    course_number,
    course_name,
    exclude_from_gpa,
    is_ap_course,
    teacher_number,
    teacher_name,
    tableau_username,
    category_quarter_percent_grade,
    category_quarter_average_all_courses,
    quarter_course_percent_grade_that_matters,
    quarter_course_grade_points_that_matters,
    quarter_citizenship,
    quarter_comment_value,
    audit_category,

    null as teacher_assign_id,
    null as teacher_assign_name,
    null as teacher_assign_due_date,
    null as teacher_assign_score_type,
    null as teacher_assign_max_score,
    null as n_students,
    null as n_late,
    null as n_exempt,
    null as n_missing,
    null as n_expected,
    null as n_expected_scored,
    null as teacher_running_total_assign_by_cat,
    null as teacher_avg_score_for_assign_per_class_section_and_assign_id,
    null as raw_score,
    null as score_entered,
    null as assign_final_score_percent,
    null as is_exempt,
    null as is_late,
    null as is_missing,

    coalesce(audit_flag_name, 'no_flag') as audit_flag_name,
    coalesce(audit_flag_value, 0) as audit_flag_value,
from {{ ref("int_tableau__gradebook_audit_flags") }}
where
    assignment_category_code = 'W'
    and audit_flag_name = 'qt_effort_grade_missing'
    and school_level != 'ES'

union all

select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    region_school_level,
    schoolid,
    school,
    studentid,
    student_number,
    student_name,
    grade_level,
    salesforce_id,
    ktc_cohort,
    enroll_status,
    cohort,
    gender,
    ethnicity,
    advisory,
    hos,
    year_in_school,
    year_in_network,
    rn_undergrad,
    is_out_of_district,
    is_pathways,
    is_retained_year,
    is_retained_ever,
    lunch_status,
    gifted_and_talented,
    iep_status,
    lep_status,
    is_504,
    is_counseling_services,
    is_student_athlete,
    ada,
    ada_above_or_at_80,
    date_enrolled,
    `quarter`,
    semester,
    week_number,
    quarter_start_date,
    quarter_end_date,
    cal_quarter_end_date,
    is_current_quarter,
    is_quarter_end_date_range,
    audit_start_date,
    audit_end_date,
    audit_due_date,

    null as assignment_category_name,
    null as assignment_category_code,
    null as assignment_category_term,
    null as expectation,
    null as notes,

    section_or_period,
    sectionid,
    sections_dcid,
    section_number,
    external_expression,
    credit_type,
    course_number,
    course_name,
    exclude_from_gpa,
    is_ap_course,
    teacher_number,
    teacher_name,
    tableau_username,

    null as category_quarter_percent_grade,
    null as category_quarter_average_all_courses,

    quarter_course_percent_grade_that_matters,
    quarter_course_grade_points_that_matters,
    quarter_citizenship,
    quarter_comment_value,
    audit_category,

    null as teacher_assign_id,
    null as teacher_assign_name,
    null as teacher_assign_due_date,
    null as teacher_assign_score_type,
    null as teacher_assign_max_score,
    null as n_students,
    null as n_late,
    null as n_exempt,
    null as n_missing,
    null as n_expected,
    null as n_expected_scored,
    null as teacher_running_total_assign_by_cat,
    null as teacher_avg_score_for_assign_per_class_section_and_assign_id,
    null as raw_score,
    null as score_entered,
    null as assign_final_score_percent,
    null as is_exempt,
    null as is_late,
    null as is_missing,

    coalesce(audit_flag_name, 'no_flag') as audit_flag_name,
    coalesce(audit_flag_value, 0) as audit_flag_value,
from {{ ref("int_tableau__gradebook_audit_flags") }}
where cte_grouping = 'student_course' and school_level != 'ES'

union all

select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    region_school_level,
    schoolid,
    school,
    studentid,
    student_number,
    student_name,
    grade_level,
    salesforce_id,
    ktc_cohort,
    enroll_status,
    cohort,
    gender,
    ethnicity,
    advisory,
    hos,
    year_in_school,
    year_in_network,
    rn_undergrad,
    is_out_of_district,
    is_pathways,
    is_retained_year,
    is_retained_ever,
    lunch_status,
    gifted_and_talented,
    iep_status,
    lep_status,
    is_504,
    is_counseling_services,
    is_student_athlete,
    ada,
    ada_above_or_at_80,
    date_enrolled,
    `quarter`,
    semester,
    week_number,
    quarter_start_date,
    quarter_end_date,
    cal_quarter_end_date,
    is_current_quarter,
    is_quarter_end_date_range,
    audit_start_date,
    audit_end_date,
    audit_due_date,

    null as assignment_category_name,
    null as assignment_category_code,
    null as assignment_category_term,
    null as expectation,
    null as notes,

    section_or_period,
    sectionid,
    sections_dcid,
    section_number,
    external_expression,
    credit_type,
    course_number,
    course_name,
    exclude_from_gpa,
    is_ap_course,
    teacher_number,
    teacher_name,
    tableau_username,

    null as category_quarter_percent_grade,
    null as category_quarter_average_all_courses,

    quarter_course_percent_grade_that_matters,
    quarter_course_grade_points_that_matters,

    null as quarter_citizenship,
    null as quarter_comment_value,

    audit_category,

    null as teacher_assign_id,
    null as teacher_assign_name,
    null as teacher_assign_due_date,
    null as teacher_assign_score_type,
    null as teacher_assign_max_score,
    null as n_students,
    null as n_late,
    null as n_exempt,
    null as n_missing,
    null as n_expected,
    null as n_expected_scored,
    null as teacher_running_total_assign_by_cat,
    null as teacher_avg_score_for_assign_per_class_section_and_assign_id,
    null as raw_score,
    null as score_entered,
    null as assign_final_score_percent,
    null as is_exempt,
    null as is_late,
    null as is_missing,

    coalesce(audit_flag_name, 'no_flag') as audit_flag_name,
    coalesce(audit_flag_value, 0) as audit_flag_value,
from {{ ref("int_tableau__gradebook_audit_flags") }}
where cte_grouping = 'student' and school_level != 'ES'

union all

select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    region_school_level,
    schoolid,
    school,

    null as studentid,
    null as student_number,
    null as student_name,
    null as grade_level,
    null as salesforce_id,
    null as ktc_cohort,
    null as enroll_status,
    null as cohort,
    null as gender,
    null as ethnicity,
    null as advisory,
    null as hos,
    null as year_in_school,
    null as year_in_network,
    null as rn_undergrad,
    null as is_out_of_district,
    null as is_pathways,
    null as is_retained_year,
    null as is_retained_ever,
    null as lunch_status,
    null as gifted_and_talented,
    null as iep_status,
    null as lep_status,
    null as is_504,
    null as is_counseling_services,
    null as is_student_athlete,
    null as ada,
    null as ada_above_or_at_80,
    null as date_enrolled,

    `quarter`,
    semester,
    week_number,
    quarter_start_date,
    quarter_end_date,
    cal_quarter_end_date,
    is_current_quarter,
    is_quarter_end_date_range,
    audit_start_date,
    audit_end_date,
    audit_due_date,
    assignment_category_name,
    assignment_category_code,
    assignment_category_term,
    expectation,
    notes,
    section_or_period,
    sectionid,
    sections_dcid,
    section_number,
    external_expression,
    credit_type,
    course_number,
    course_name,
    exclude_from_gpa,
    is_ap_course,
    teacher_number,
    teacher_name,
    tableau_username,

    null as category_quarter_percent_grade,
    null as category_quarter_average_all_courses,
    null as quarter_course_percent_grade_that_matters,
    null as quarter_course_grade_points_that_matters,
    null as quarter_citizenship,
    null as quarter_comment_value,

    audit_category,
    teacher_assign_id,
    teacher_assign_name,
    teacher_assign_due_date,
    teacher_assign_score_type,
    teacher_assign_max_score,

    null as n_students,
    null as n_late,
    null as n_exempt,
    null as n_missing,
    null as n_expected,
    null as n_expected_scored,
    null as teacher_running_total_assign_by_cat,
    null as teacher_avg_score_for_assign_per_class_section_and_assign_id,
    null as raw_score,
    null as score_entered,
    null as assign_final_score_percent,
    null as is_exempt,
    null as is_late,
    null as is_missing,

    coalesce(audit_flag_name, 'no_flag') as audit_flag_name,
    coalesce(audit_flag_value, 0) as audit_flag_value,
from {{ ref("int_tableau__gradebook_audit_flags") }}
where cte_grouping = 'class_category_assignment' and school_level != 'ES'

union all

select
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    region_school_level,
    schoolid,
    school,

    null as studentid,
    null as student_number,
    null as student_name,
    null as grade_level,
    null as salesforce_id,
    null as ktc_cohort,
    null as enroll_status,
    null as cohort,
    null as gender,
    null as ethnicity,
    null as advisory,
    null as hos,
    null as year_in_school,
    null as year_in_network,
    null as rn_undergrad,
    null as is_out_of_district,
    null as is_pathways,
    null as is_retained_year,
    null as is_retained_ever,
    null as lunch_status,
    null as gifted_and_talented,
    null as iep_status,
    null as lep_status,
    null as is_504,
    null as is_counseling_services,
    null as is_student_athlete,
    null as ada,
    null as ada_above_or_at_80,
    null as date_enrolled,

    `quarter`,
    semester,
    week_number,
    quarter_start_date,
    quarter_end_date,
    cal_quarter_end_date,
    is_current_quarter,
    is_quarter_end_date_range,
    audit_start_date,
    audit_end_date,
    audit_due_date,
    assignment_category_name,
    assignment_category_code,
    assignment_category_term,
    expectation,
    notes,
    section_or_period,
    sectionid,
    sections_dcid,
    section_number,
    external_expression,
    credit_type,
    course_number,
    course_name,
    exclude_from_gpa,
    is_ap_course,
    teacher_number,
    teacher_name,
    tableau_username,

    null as category_quarter_percent_grade,
    null as category_quarter_average_all_courses,
    null as quarter_course_percent_grade_that_matters,
    null as quarter_course_grade_points_that_matters,
    null as quarter_citizenship,
    null as quarter_comment_value,

    audit_category,

    null as teacher_assign_id,
    null as teacher_assign_name,
    null as teacher_assign_due_date,
    null as teacher_assign_score_type,
    null as teacher_assign_max_score,
    null as n_students,
    null as n_late,
    null as n_exempt,
    null as n_missing,
    null as n_expected,
    null as n_expected_scored,
    null as teacher_running_total_assign_by_cat,
    null as teacher_avg_score_for_assign_per_class_section_and_assign_id,
    null as raw_score,
    null as score_entered,
    null as assign_final_score_percent,
    null as is_exempt,
    null as is_late,
    null as is_missing,

    coalesce(audit_flag_name, 'no_flag') as audit_flag_name,
    coalesce(audit_flag_value, 0) as audit_flag_value,
from {{ ref("int_tableau__gradebook_audit_flags") }}
where cte_grouping = 'class_category' and school_level != 'ES'
