select
    a.id,
    a.name as aid_name,
    a.student as sf_contact_id,
    a.amount,
    a.`date` as award_date,
    a.created_date,
    a.kipp_aid_count,
    a.notes,
    a.notes_clean,
    a.fund_type,
    a.doc_type,
    a.academic_year,
    a.is_maher,
    a.`type` as aid_type,
    a.status as aid_status,

    r.student_number,
    r.lastfirst as student_name,
    r.first_name as student_first_name,
    r.last_name as student_last_name,
    r.ktc_cohort,
    r.record_type_name,
    r.es_graduated,
    r.contact_kipp_region_name as kipp_region_name,
    r.contact_owner_name as counselor_name,
    r.contact_ethnicity as ethnicity,
    r.contact_gender as gender,
    r.contact_current_kipp_student as current_kipp_student,
    r.contact_postsecondary_status as postsecondary_status,
    r.contact_high_school_graduated_from as high_school_graduated_from,
    r.contact_college_graduated_from as college_graduated_from,
    r.contact_currently_enrolled_school as currently_enrolled_school,
    r.contact_actual_hs_graduation_date as actual_hs_graduation_date,
    r.contact_actual_college_graduation_date as actual_college_graduation_date,
    r.contact_expected_college_graduation as expected_college_graduation_date,
    r.contact_college_match_display_gpa as college_match_display_gpa,
    r.contact_current_college_cumulative_gpa as current_college_cumulative_gpa,
    r.contact_kipp_ms_graduate as is_kipp_ms_graduate,
    r.contact_kipp_hs_graduate as is_kipp_hs_graduate,
    r.contact_advising_provider as advising_provider,
    r.contact_graduation_year as graduation_year,

    e.ba_pursuing_degree_type,
    e.ba_status,
    e.ba_start_date,
    e.ba_actual_end_date,
    e.ba_anticipated_graduation,
    e.ba_account_type,
    e.ba_account_name,
    e.ba_adjusted_6_year_minority_graduation_rate,
    e.aa_pursuing_degree_type,
    e.aa_status,
    e.aa_start_date,
    e.aa_actual_end_date,
    e.aa_anticipated_graduation,
    e.aa_account_type,
    e.aa_account_name,
    e.aa_adjusted_6_year_minority_graduation_rate,
    e.cur_pursuing_degree_type,
    e.cur_status,
    e.cur_start_date,
    e.cur_actual_end_date,
    e.cur_anticipated_graduation,
    e.cur_account_type,
    e.cur_school_name as cur_account_name,
    e.cur_adjusted_6_year_minority_graduation_rate,
    e.cte_pursuing_degree_type,
    e.cte_status,
    e.cte_start_date,
    e.cte_actual_end_date,
    e.cte_anticipated_graduation,
    e.cte_account_type,
    e.cte_school_name as cte_account_name,
    e.ugrad_pursuing_degree_type,
    e.ugrad_status,
    e.ugrad_start_date,
    e.ugrad_actual_end_date,
    e.ugrad_anticipated_graduation,
    e.ugrad_account_type,
    e.ugrad_account_name,
    e.ugrad_adjusted_6_year_minority_graduation_rate,

    r.contact_most_recent_iep_date is not null as is_iep,
from {{ ref("stg_kippadb__kipp_aid") }} as a
left join {{ ref("int_kippadb__roster") }} as r on a.student = r.contact_id
left join {{ ref("int_kippadb__enrollment_pivot") }} as e on a.student = e.student
