select
    g._dbt_source_relation,
    g.academic_year,
    g.plan_id,
    g.plan_name,
    g.discipline_id,
    g.discipline_name,
    g.subject_id,
    g.subject_name,
    g.teacher_name,
    g.course_number,
    g.course_name,
    g.sectionid,
    g.credit_type,
    g.letter_grade,
    g.is_transfer_grade,
    g.credit_status,
    g.earned_credits,
    g.potential_credits,

    e.region,
    e.schoolid,
    e.school,
    e.studentid,
    e.state_studentnumber,
    e.salesforce_id,
    e.student_number,
    e.student_name,
    e.grade_level,
    e.student_email,
    e.enroll_status,
    e.cohort,
    e.gender,
    e.ethnicity,
    e.dob,
    e.lunch_status,
    e.lep_status,
    e.gifted_and_talented,
    e.iep_status,
    e.is_504,
    e.is_homeless,
    e.is_out_of_district,
    e.is_self_contained,
    e.is_counseling_services,
    e.is_student_athlete,
    e.is_tutoring,
    e.year_in_network,
    e.has_fafsa,
    e.college_match_gpa,
    e.college_match_gpa_bands,
    e.contact_owner_name,
    e.ktc_cohort,
    e.ms_attended,
    e.hos,
    e.ada,
    e.ada_above_or_at_80,
    e.advisory,

    g.plan_required_credits,
    g.plan_enrolled_credits,
    g.plan_requested_credits,
    g.plan_earned_credits,
    g.plan_waived_credits,
    g.discipline_required_credits,
    g.discipline_enrolled_credits,
    g.discipline_requested_credits,
    g.discipline_earned_credits,
    g.discipline_waived_credits,
    g.subject_required_credits,
    g.subject_enrolled_credits,
    g.subject_requested_credits,
    g.subject_earned_credits,
    g.subject_waived_credits,

from {{ ref("int_extracts__student_enrollments") }} as e
inner join
    {{ ref("int_powerschool__gpprogress_grades") }} as g
    on e.students_dcid = g.studentsdcid
    and {{ union_dataset_join_clause(left_alias="e", right_alias="g") }}
    and g.plan_name in ('NJ State Diploma', 'HS Distinction Diploma')
where
    e.academic_year = {{ var("current_academic_year") }}
    and e.rn_year = 1
    and e.enroll_status = 0
    and e.grade_level >= 9
