with
    grades_and_assignments_nj as (
        select
            _dbt_source_relation,
            academic_year,
            academic_year_display,
            region,
            school_level,
            schoolid,
            school,
            studentid,
            student_number,
            student_name,
            grade_level,
            salesforce_id,
            ktc_cohort,
            enroll_status,
            cohort,
            gender,
            ethnicity,
            advisory,
            hos,
            region_school_level,
            year_in_school,
            year_in_network,
            rn_undergrad,
            is_out_of_district,
            is_pathways,
            is_retained_year,
            is_retained_ever,
            lunch_status,
            gifted_and_talented,
            iep_status,
            lep_status,
            is_504,
            is_counseling_services,
            is_student_athlete,
            ada,
            ada_above_or_at_80,
            quarter,
            semester,
            quarter_start_date,
            quarter_end_date,
            is_current_quarter,
            sectionid,
            sections_dcid,
            section_number,
            external_expression,
            section_or_period,
            date_enrolled,
            credit_type,
            course_number,
            course_name,
            exclude_from_gpa,
            teacher_number,
            teacher_name,
            tableau_username,
            tutoring_nj,
            nj_student_tier,
            quarter_course_percent_grade_that_matters,
            quarter_course_grade_points_that_matters,
            quarter_comment_value,
            category_name_code,
            category_quarter_code,
            category_quarter_percent_grade,
            category_quarter_average_all_courses,

            if(
                current_date('{{ var("local_timezone") }}')
                between (quarter_end_date - 4) and (quarter_end_date + 14),
                true,
                false
            ) as is_quarter_end_date_range,
        from {{ ref("rpt_tableau__gradebook_gpa") }}
        where
            academic_year = {{ var("current_academic_year") }}
            and enroll_status = 0
            and roster_type = 'Local'
            and quarter != 'Y1'
            and region_school_level in ('CamdenES', 'NewarkES')
    ),

    audits_es_nj as (
        select
            *,
            if(
                is_quarter_end_date_range
                and grade_level < 5
                and credit_type in ('HR', 'MATH', 'ENG')
                and quarter_comment_value is null,
                true,
                false
            ) as qt_es_comment_missing,
        from grades_and_assignments_nj
    )

select distinct
    _dbt_source_relation,
    academic_year,
    academic_year_display,
    region,
    school_level,
    schoolid,
    school,
    student_number,
    student_name,
    gender,
    grade_level,
    enroll_status,
    ethnicity,
    lep_status,
    is_504,
    is_pathways,
    iep_status,
    gifted_and_talented,
    is_counseling_services,
    is_student_athlete,
    tutoring_nj,
    nj_student_tier,
    `ada`,
    ada_above_or_at_80,
    advisory,
    hos,
    semester,
    `quarter`,
    quarter_start_date,
    quarter_end_date,
    is_current_quarter,
    course_name,
    course_number,
    section_number,
    external_expression,
    section_or_period,
    credit_type,
    teacher_number,
    teacher_name,
    tableau_username,
    exclude_from_gpa,
    quarter_course_percent_grade_that_matters,
    quarter_course_grade_points_that_matters,
    '' as quarter_citizenship,
    quarter_comment_value,
    cast(null as numeric) as category_quarter_percent_grade,
    cast(null as numeric) as category_quarter_average_all_courses,
    null as audit_qt_week_number,
    cast(null as date) as audit_start_date,
    cast(null as date) as audit_end_date,
    cast(null as date) as audit_due_date,
    '' as expected_teacher_assign_category_code,
    '' as expected_teacher_assign_category_name,
    null as audit_category_exp_audit_week_ytd,
    null as teacher_assign_id,
    '' as teacher_assign_name,
    '' as teacher_assign_score_type,
    cast(null as numeric) as teacher_assign_max_score,
    cast(null as date) as teacher_assign_due_date,
    null as teacher_assign_count,
    null as n_students,
    null as n_late,
    null as n_exempt,
    null as n_missing,
    null as n_expected,
    null as n_expected_scored,

    null as teacher_running_total_assign_by_cat,
    cast(
        null as numeric
    ) as teacher_avg_score_for_assign_per_class_section_and_assign_id,
    null as total_expected_actual_graded_assignments_by_cat_qt_audit_week_all_courses,
    null as total_expected_graded_assignments_by_cat_qt_audit_week_all_courses,
    null as total_expected_actual_graded_assignments_by_course_cat_qt_audit_week,
    null as total_expected_graded_assignments_by_course_cat_qt_audit_week,
    null as total_expected_actual_graded_assignments_by_course_assign_id_qt_audit_week,
    null as total_expected_graded_assignments_by_course_assign_id_qt_audit_week,
    cast(null as numeric) as percent_graded_completion_by_cat_qt_audit_week_all_courses,
    cast(null as numeric) as percent_graded_completion_by_cat_qt_audit_week,
    cast(null as numeric) as percent_graded_completion_by_assign_id_qt_audit_week,

    false as qt_teacher_no_missing_assignments,
    false as qt_teacher_s_total_less_200,

    date_enrolled as student_course_entry_date,
    cast(null as numeric) as assign_score_raw,
    cast(null as numeric) as assign_score_converted,
    cast(null as numeric) as assign_max_score,
    cast(null as numeric) as assign_final_score_percent,
    null as assign_is_exempt,
    null as assign_is_late,
    null as assign_is_missing,
    audit_flag_name,

    if(audit_flag_value, 1, 0) as audit_flag_value,
from
    audits_es_nj
    unpivot (audit_flag_value for audit_flag_name in (qt_es_comment_missing))
where audit_flag_value
