select
    hd.employee_number as asdf_employee_number,
    hd.adp_associate_id,
    hd.preferred_first_name,
    hd.preferred_last_name,
    hd.current_status as cur,
    hd.termination_date,
    hd.current_legal_entity,
    hd.current_location,
    hd.current_role,
    hd.current_dept,
    hd.race_ethnicity_reporting,
    hd.gender,
    hd.samaccountname,
    hd.current_manager,
    hd.manager_samaccountname,
    hd.academic_year,
    hd.historic_legal_entity,
    hd.historic_location,
    hd.historic_role,
    hd.historic_dept,
    hd.historic_salary,
    hd.code,
    hd.etr_score,
    hd.etr_tier,
    hd.so_score,
    hd.overall_score,
    hd.overall_tier,
    hd.most_recent_hire_date as hire_date,
    hd.is_hispanic,

    null as is_certified,
    null as ay_approved_absences,
    null as ay_unapproved_absences,
    null as ay_approved_tardies,
    null as ay_unapproved_tardies,
    null as ay_approved_left_early,
    null as ay_unapproved_left_early,
from {{ ref("int_people__annual_historic_data") }} as hd
