select
    _dbt_source_relation,
    finalsite_student_id,
    academic_year,
    academic_year_display,
    enrollment_year,
    region,
    schoolid,
    school,
    powerschool_student_number,
    last_name,
    first_name,
    grade_level,
    grade_level_string,
    detailed_status,
    status_start_date,
    status_end_date,
    days_in_status,
    enrollment_type,
    overall_status,
    funnel_status,
    status_category,
    offered_status,
    offered_status_detailed,
    detailed_status_ranking,
    detailed_status_branched_ranking,
    powerschool_enroll_status,
    valid_detailed_status,
    applicant_ops,
    offered_ops,
    pending_offer_ops,
    overall_conversion_ops,
    offers_to_accepted_den,
    offers_to_accepted_num,
    accepted_to_enrolled_den,
    accepted_to_enrolled_num,
    offers_to_enrolled_den,
    offers_to_enrolled_num,
    waitlisted,
    week_start_monday,
    week_end_sunday,

    first_value(detailed_status) over (
        partition by academic_year, finalsite_student_id order by status_start_date desc
    ) as latest_status,

from {{ ref("int_students__finalsite_student_roster") }}
