select
    c.school_specific_id as contact_school_specific_id,
    c.id as contact_id,
    c.owner_id as contact_owner_id,
    c.record_type_id as contact_record_type_id,
    c.description as contact_description,
    c.name as contact_name,
    c.birthdate as contact_birthdate,
    c.email as contact_email,
    c.first_name as contact_first_name,
    c.home_phone as contact_home_phone,
    c.last_name as contact_last_name,
    c.mobile_phone as contact_mobile_phone,
    c.actual_college_graduation_date as contact_actual_college_graduation_date,
    c.actual_hs_graduation_date as contact_actual_hs_graduation_date,
    c.advising_provider as contact_advising_provider,
    c.college_graduated_from as contact_college_graduated_from,
    c.college_match_display_gpa as contact_college_match_display_gpa,
    c.current_college_cumulative_gpa as contact_current_college_cumulative_gpa,
    c.current_college_semester_gpa as contact_current_college_semester_gpa,
    c.current_kipp_student as contact_current_kipp_student,
    c.currently_enrolled_school as contact_currently_enrolled_school,
    c.dep_post_hs_simple_admin as contact_dep_post_hs_simple_admin,
    c.efc_from_fafsa as contact_efc_from_fafsa,
    c.ethnicity as contact_ethnicity,
    c.expected_college_graduation as contact_expected_college_graduation,
    c.expected_hs_graduation as contact_expected_hs_graduation,
    c.full_name as contact_full_name,
    c.gender as contact_gender,
    c.has_hs_graduated_enrollment as contact_has_hs_graduated_enrollment,
    c.high_school_graduated_from as contact_high_school_graduated_from,
    c.highest_act_score as contact_highest_act_score,
    c.highest_sat_score as contact_highest_sat_score,
    c.kipp_hs_graduate as contact_kipp_hs_graduate,
    c.kipp_ms_graduate as contact_kipp_ms_graduate,
    c.kipp_region_name as contact_kipp_region_name,
    c.last_outreach as contact_last_outreach,
    c.last_successful_advisor_contact as contact_last_successful_advisor_contact,
    c.last_successful_contact as contact_last_successful_contact,
    c.latest_fafsa_date as contact_latest_fafsa_date,
    c.latest_resume as contact_latest_resume,
    c.latest_state_financial_aid_app_date
    as contact_latest_state_financial_aid_app_date,
    c.middle_school_attended as contact_middle_school_attended,
    c.most_recent_college_enrollment_name
    as contact_most_recent_college_enrollment_name,
    c.most_recent_college_enrollment_status
    as contact_most_recent_college_enrollment_status,
    c.most_recent_iep_date as contact_most_recent_iep_date,
    c.opt_out_national_contact as contact_opt_out_national_contact,
    c.opt_out_regional_contact as contact_opt_out_regional_contact,
    c.other_phone as contact_other_phone,
    c.postsecondary_status as contact_postsecondary_status,
    c.secondary_email as contact_secondary_email,
    c.postsec_advisor as contact_postsec_advisor,
    c.kipp_hs_class as contact_kipp_hs_class,
    c.mailing_address as contact_mailing_address,
    c.graduation_year as contact_graduation_year,
    c.intent_to_enlist as contact_intent_to_enlist,
    c.cte_military_interest as contact_cte_military_interest,

    u.name as contact_owner_name,
    u.email as contact_owner_email,
    u.phone as contact_owner_phone,

    rt.name as record_type_name,
    rt.description as record_type_description,
    rt.last_modified_date as record_type_last_modified_date,
    rt.is_active as record_type_is_active,
    rt.business_process_id as record_type_business_process_id,
    rt.system_modstamp as record_type_system_modstamp,
    rt.sobject_type as record_type_sobject_type,
    rt.created_by_id as record_type_created_by_id,
    rt.created_date as record_type_created_date,
    rt.developer_name as record_type_developer_name,
    rt.last_modified_by_id as record_type_last_modified_by_id,
    rt.namespace_prefix as record_type_namespace_prefix,

    psc.name as contact_postsec_advisor_name,

    c.last_name || ', ' || c.first_name as contact_lastfirst,

    (
        {{ var("current_fiscal_year") }}
        - extract(year from c.actual_hs_graduation_date)
    ) as years_out_of_hs,

from {{ ref("stg_kippadb__contact") }} as c
left join {{ ref("stg_kippadb__user") }} as u on c.owner_id = u.id
left join {{ ref("stg_kippadb__record_type") }} as rt on c.record_type_id = rt.id
left join {{ ref("stg_kippadb__contact") }} as psc on c.postsec_advisor = psc.id
