DATE_RECORD_SCHEMA = {
    "type": "record",
    "fields": [
        {"name": "date", "type": "int", "logicalType": "time-micros"},
        {"name": "timezone_type", "type": "int"},
        {"name": "timezone", "type": "string"},
    ],
}

AVRO_SCHEMA = {
    "users": [
        {"name": "DLSchoolID", "type": ["null", "int"]},
        {"name": "SchoolName", "type": ["null", "string"]},
        {"name": "DLUserID", "type": ["null", "int"]},
        {"name": "FirstName", "type": ["null", "string"]},
        {"name": "MiddleName", "type": ["null", "string"]},
        {"name": "LastName", "type": ["null", "string"]},
        {"name": "Title", "type": ["null", "string"]},
        {"name": "UserSchoolID", "type": ["null", "string"]},
        {"name": "UserRole", "type": ["null", "string"]},
        {"name": "Username", "type": ["null", "string"]},
        {"name": "Email", "type": ["null", "string"]},
        {"name": "GroupName", "type": ["null", "string"]},
    ],
    "students": [
        {"name": "StudentID", "type": ["null", "int"]},
        {"name": "DepartmentID", "type": ["null", "string"]},
        {"name": "Department", "type": ["null", "string"]},
        {"name": "GradeLevelID", "type": ["null", "int"]},
        {"name": "GradeLevel", "type": ["null", "string"]},
        {"name": "GradeLevelKey", "type": ["null", "string"]},
        {"name": "FirstName", "type": ["null", "string"]},
        {"name": "MiddleName", "type": ["null", "string"]},
        {"name": "LastName", "type": ["null", "string"]},
        {"name": "StudentSchoolID", "type": ["null", "string"]},
        {"name": "IntegrationID", "type": ["null", "string"]},
        {"name": "EnrollmentStatus", "type": ["null", "string"]},
        {"name": "BehaviorPlan", "type": ["null"]},
        {"name": "BirthDate", "type": ["null", {"type": "int", "logicalType": "date"}]},
        {"name": "Enrollment", "type": ["null"]},
        {"name": "HomeLanguageID", "type": ["null", "int"]},
        {"name": "HomeLanguage", "type": ["null", "string"]},
        {"name": "HomeroomID", "type": ["null", "int"]},
        {"name": "Homeroom", "type": ["null", "string"]},
        {"name": "IsNSLP", "type": ["null", "boolean"]},
        {"name": "Gender", "type": ["null", "string"]},
        {"name": "StreetAddress1", "type": ["null", "string"]},
        {"name": "StreetAddress2", "type": ["null", "string"]},
        {"name": "City", "type": ["null", "string"]},
        {"name": "State", "type": ["null", "string"]},
        {"name": "ZipCode", "type": ["null", "string"]},
        {"name": "PhotoFile", "type": ["null", "string"]},
        {"name": "DLPS_ValidationCode", "type": ["null", "string"]},
        {"name": "Parents", "type": ["null", {"type": "array"}]},
        {"name": "Notes", "type": ["null", {"type": "array"}]},
    ],
    "lists": [
        {"name": "ListID", "type": ["null", "int"]},
        {"name": "ListName", "type": ["null", "string"]},
        {"name": "IsDated", "type": ["null", "boolean"]},
    ],
    "terms": [
        {"name": "TermID", "type": ["null", "int"]},
        {"name": "AcademicYearID", "type": ["null", "int"]},
        {"name": "AcademicYearName", "type": ["null", "string"]},
        {"name": "SchoolID", "type": ["null", "int"]},
        {"name": "TermTypeID", "type": ["null", "int"]},
        {"name": "TermType", "type": ["null", "string"]},
        {"name": "TermName", "type": ["null", "string"]},
        {"name": "StartDate", **DATE_RECORD_SCHEMA},
        {"name": "EndDate", **DATE_RECORD_SCHEMA},
    ],
    "rosters": [
        {"name": "RosterID", "type": ["null", "int"]},
        {"name": "RosterName", "type": ["null", "string"]},
        {"name": "RosterTypeID", "type": ["null", "int"]},
        {"name": "RosterType", "type": ["null", "string"]},
        {"name": "MasterID", "type": ["null", "int"]},
        {"name": "MasterName", "type": ["null", "string"]},
        {"name": "TakeAttendance", "type": ["null", "string"]},
        {"name": "TakeClassAttendance", "type": ["null", "string"]},
        {"name": "CollectHW", "type": ["null", "string"]},
        {"name": "MarkerColor", "type": ["null", "string"]},
        {"name": "SISKey", "type": ["null", "string "]},
        {"name": "SecondaryIntegrationID", "type": ["null", "string"]},
        {"name": "ScreenSetID", "type": ["null", "int"]},
        {"name": "StudentCount", "type": ["null", "int"]},
    ],
}


def get_avro_schema(name):
    return {"type": "record", "name": name, "fields": AVRO_SCHEMA[name]}
