AVRO_SCHEMA = {
    "users": [
        {"name": "DLSchoolID", "type": ["null", "int"]},
        {"name": "SchoolName", "type": ["null", "string"]},
        {"name": "DLUserID", "type": ["null", "int"]},
        {"name": "FirstName", "type": ["null", "string"]},
        {"name": "MiddleName", "type": ["null", "string"]},
        {"name": "LastName", "type": ["null", "string"]},
        {"name": "Title", "type": ["null", "string"]},
        {"name": "UserSchoolID", "type": ["null", "string"]},
        {"name": "UserRole", "type": ["null", "string"]},
        {"name": "Username", "type": ["null", "string"]},
        {"name": "Email", "type": ["null", "string"]},
        {"name": "GroupName", "type": ["null", "string"]},
    ],
    "students": [
        {"name": "StudentID", "type": ["null", "int"]},
        {"name": "DepartmentID", "type": ["null", "string"]},
        {"name": "Department", "type": ["null", "string"]},
        {"name": "GradeLevelID", "type": ["null", "int"]},
        {"name": "GradeLevel", "type": ["null", "string"]},
        {"name": "GradeLevelKey", "type": ["null", "string"]},
        {"name": "FirstName", "type": ["null", "string"]},
        {"name": "MiddleName", "type": ["null", "string"]},
        {"name": "LastName", "type": ["null", "string"]},
        {"name": "StudentSchoolID", "type": ["null", "string"]},
        {"name": "IntegrationID", "type": ["null", "string"]},
        {"name": "EnrollmentStatus", "type": ["null", "string"]},
        {"name": "BehaviorPlan", "type": ["null"]},
        {"name": "BirthDate", "type": ["null", {"type": "int", "logicalType": "date"}]},
        {
            "name": "Enrollment",
            "type": ["null", {"type": "bytes", "logicalType": "json"}],
        },
        {"name": "HomeLanguageID", "type": ["null", "int"]},
        {"name": "HomeLanguage", "type": ["null", "string"]},
        {"name": "HomeroomID", "type": ["null", "int"]},
        {"name": "Homeroom", "type": ["null", "string"]},
        {"name": "IsNSLP", "type": ["null", "boolean"]},
        {"name": "Gender", "type": ["null", "string"]},
        {"name": "StreetAddress1", "type": ["null", "string"]},
        {"name": "StreetAddress2", "type": ["null", "string"]},
        {"name": "City", "type": ["null", "string"]},
        {"name": "State", "type": ["null", "string"]},
        {"name": "ZipCode", "type": ["null", "string"]},
        {"name": "PhotoFile", "type": ["null", "string"]},
        {"name": "DLPS_ValidationCode", "type": ["null", "string"]},
        {"name": "Parents", "type": ["null", {"type": "array"}]},
        {"name": "Notes", "type": ["null", {"type": "array"}]},
    ],
}


def get_avro_schema(name):
    return {"type": "record", "name": name, "fields": AVRO_SCHEMA[name]}
