DIAGNOSTIC_INSTRUCTION_FIELDS = [
    {"name": "academic_year", "type": ["null", "string"], "default": None},
    {"name": "class_es", "type": ["null", "string"], "default": None},
    {"name": "class_teacher_s", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_percentile_1", "type": ["null", "double"], "default": None},
    {"name": "diagnostic_percentile_2", "type": ["null", "double"], "default": None},
    {"name": "diagnostic_percentile_3", "type": ["null", "double"], "default": None},
    {"name": "diagnostic_percentile_4", "type": ["null", "double"], "default": None},
    {"name": "diagnostic_percentile_5", "type": ["null", "double"], "default": None},
    {"name": "diagnostic_rush_flag_1", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_rush_flag_2", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_rush_flag_3", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_rush_flag_4", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_rush_flag_5", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_start_date_1", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_start_date_2", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_start_date_3", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_start_date_4", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_start_date_5", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_tier_1", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_tier_2", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_tier_3", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_tier_4", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_tier_5", "type": ["null", "string"], "default": None},
    {"name": "economically_disadvantaged", "type": ["null", "string"], "default": None},
    {"name": "english_language_learner", "type": ["null", "string"], "default": None},
    {"name": "enrolled", "type": ["null", "string"], "default": None},
    {"name": "first_name", "type": ["null", "string"], "default": None},
    {"name": "hispanic_or_latino", "type": ["null", "string"], "default": None},
    {"name": "last_name", "type": ["null", "string"], "default": None},
    {"name": "migrant", "type": ["null", "string"], "default": None},
    {"name": "race", "type": ["null", "string"], "default": None},
    {"name": "report_group_s", "type": ["null", "string"], "default": None},
    {"name": "school", "type": ["null", "string"], "default": None},
    {"name": "sex", "type": ["null", "string"], "default": None},
    {"name": "special_education", "type": ["null", "string"], "default": None},
    {"name": "student_grade", "type": ["null", "string"], "default": None},
    {"name": "student_id", "type": ["null", "long"], "default": None},
    {"name": "subject", "type": ["null", "string"], "default": None},
    {"name": "user_name", "type": ["null", "string"], "default": None},
    {
        "name": "annual_stretch_growth_measure",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "annual_typical_growth_measure",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_completion_date_1",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_completion_date_2",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_completion_date_3",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_completion_date_4",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_completion_date_5",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_completion_date_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_gain_note_negative_gains_zero",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_grouping_most_recent",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_lexile_measure_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_lexile_range_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_placement_1",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_placement_2",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_placement_3",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_placement_4",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_placement_5",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_placement_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_relative_placement_1",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_relative_placement_2",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_relative_placement_3",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_relative_placement_4",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_relative_placement_5",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_relative_placement_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_scale_score_1",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_scale_score_2",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_scale_score_3",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_scale_score_4",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_scale_score_5",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_overall_scale_score_most_recent",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_percentile_most_recent",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_quantile_measure_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_quantile_range_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_rush_flag_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_start_date_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_tier_most_recent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "diagnostic_time_on_task_min_1",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_time_on_task_min_2",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_time_on_task_min_3",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_time_on_task_min_4",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_time_on_task_min_5",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "diagnostic_time_on_task_min_most_recent",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "instruction_overall_lessons_completed",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "instruction_overall_lessons_not_passed",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "instruction_overall_lessons_passed",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "instruction_overall_pass_rate",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "instruction_overall_time_on_task_min",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "number_of_completed_diagnostics_during_the_time_frame",
        "type": ["null", "long"],
        "default": None,
    },
]

DIAGNOSTIC_RESULTS_FIELDS = [
    {"name": "academic_year", "type": ["null", "string"], "default": None},
    {"name": "baseline_diagnostic_y_n", "type": ["null", "string"], "default": None},
    {"name": "class_es", "type": ["null", "string"], "default": None},
    {"name": "class_teacher_s", "type": ["null", "string"], "default": None},
    {"name": "completion_date", "type": ["null", "string"], "default": None},
    {"name": "diagnostic_gain", "type": ["null", "double"], "default": None},
    {"name": "duration_min", "type": ["null", "long"], "default": None},
    {"name": "economically_disadvantaged", "type": ["null", "string"], "default": None},
    {"name": "english_language_learner", "type": ["null", "string"], "default": None},
    {"name": "enrolled", "type": ["null", "string"], "default": None},
    {"name": "first_name", "type": ["null", "string"], "default": None},
    {"name": "geometry_placement", "type": ["null", "string"], "default": None},
    {"name": "geometry_scale_score", "type": ["null", "long"], "default": None},
    {"name": "grouping", "type": ["null", "long"], "default": None},
    {"name": "hispanic_or_latino", "type": ["null", "string"], "default": None},
    {"name": "last_name", "type": ["null", "string"], "default": None},
    {"name": "lexile_measure", "type": ["null", "string"], "default": None},
    {"name": "lexile_range", "type": ["null", "string"], "default": None},
    {"name": "migrant", "type": ["null", "string"], "default": None},
    {"name": "most_recent_diagnostic_y_n", "type": ["null", "string"], "default": None},
    {"name": "overall_placement", "type": ["null", "string"], "default": None},
    {"name": "overall_relative_placement", "type": ["null", "string"], "default": None},
    {"name": "overall_scale_score", "type": ["null", "long"], "default": None},
    {"name": "percentile", "type": ["null", "long"], "default": None},
    {"name": "phonics_placement", "type": ["null", "string"], "default": None},
    {"name": "phonics_relative_placement", "type": ["null", "string"], "default": None},
    {"name": "phonics_scale_score", "type": ["null", "double"], "default": None},
    {"name": "quantile_measure", "type": ["null", "string"], "default": None},
    {"name": "quantile_range", "type": ["null", "string"], "default": None},
    {"name": "race", "type": ["null", "string"], "default": None},
    {"name": "report_group_s", "type": ["null", "string"], "default": None},
    {"name": "rush_flag", "type": ["null", "string"], "default": None},
    {"name": "school", "type": ["null", "string"], "default": None},
    {"name": "sex", "type": ["null", "string"], "default": None},
    {"name": "special_education", "type": ["null", "string"], "default": None},
    {"name": "start_date", "type": ["null", "string"], "default": None},
    {"name": "student_grade", "type": ["null", "string"], "default": None},
    {"name": "student_id", "type": ["null", "long"], "default": None},
    {"name": "user_name", "type": ["null", "string"], "default": None},
    {"name": "vocabulary_placement", "type": ["null", "string"], "default": None},
    {"name": "vocabulary_scale_score", "type": ["null", "long"], "default": None},
    {
        "name": "algebra_and_algebraic_thinking_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "algebra_and_algebraic_thinking_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "algebra_and_algebraic_thinking_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "annual_stretch_growth_measure",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "annual_typical_growth_measure",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "geometry_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "measurement_and_data_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "measurement_and_data_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "measurement_and_data_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "mid_on_grade_level_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "number_and_operations_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "number_and_operations_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "number_and_operations_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "percent_progress_to_annual_stretch_growth",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "percent_progress_to_annual_typical_growth",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "high_frequency_words_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "high_frequency_words_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "high_frequency_words_scale_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "phonological_awareness_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "phonological_awareness_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "phonological_awareness_scale_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_comprehension_informational_text_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_informational_text_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_informational_text_scale_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_comprehension_literature_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_literature_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_literature_scale_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_comprehension_overall_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_overall_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_comprehension_overall_scale_score",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_difficulty_indicator_y_n",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "vocabulary_relative_placement",
        "type": ["null", "string"],
        "default": None,
    },
]

INSTRUCTIONAL_USAGE_FIELDS = [
    {"name": "academic_year", "type": ["null", "string"], "default": None},
    {"name": "april_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "april_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "august_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "august_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "class_es", "type": ["null", "string"], "default": None},
    {"name": "class_teacher_s", "type": ["null", "string"], "default": None},
    {"name": "december_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "december_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "economically_disadvantaged", "type": ["null", "string"], "default": None},
    {"name": "english_language_learner", "type": ["null", "string"], "default": None},
    {"name": "february_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "february_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "first_name", "type": ["null", "string"], "default": None},
    {"name": "hispanic_or_latino", "type": ["null", "string"], "default": None},
    {"name": "january_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "january_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "july_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "july_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "june_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "june_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "last_name", "type": ["null", "string"], "default": None},
    {"name": "last_week_end_date", "type": ["null", "string"], "default": None},
    {"name": "last_week_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "last_week_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "last_week_start_date", "type": ["null", "string"], "default": None},
    {"name": "last_week_time_on_task_min", "type": ["null", "long"], "default": None},
    {"name": "march_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "march_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "may_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "may_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "migrant", "type": ["null", "string"], "default": None},
    {"name": "november_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "november_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "october_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "october_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "race", "type": ["null", "string"], "default": None},
    {"name": "report_group_s", "type": ["null", "string"], "default": None},
    {"name": "school", "type": ["null", "string"], "default": None},
    {"name": "september_lessons_completed", "type": ["null", "long"], "default": None},
    {"name": "september_lessons_passed", "type": ["null", "double"], "default": None},
    {"name": "sex", "type": ["null", "string"], "default": None},
    {"name": "special_education", "type": ["null", "string"], "default": None},
    {"name": "student_grade", "type": ["null", "string"], "default": None},
    {"name": "student_id", "type": ["null", "long"], "default": None},
    {"name": "subject", "type": ["null", "string"], "default": None},
    {"name": "user_name", "type": ["null", "string"], "default": None},
    {
        "name": "april_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "august_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "december_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "february_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "january_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "july_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "june_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "march_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "may_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "november_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "october_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "september_weekly_average_time_on_task_min",
        "type": ["null", "long"],
        "default": None,
    },
]

PERSONALIZED_INSTRUCTION_FIELDS = [
    {"name": "academic_year", "type": ["null", "string"], "default": None},
    {"name": "class_es", "type": ["null", "string"], "default": None},
    {"name": "class_teacher_s", "type": ["null", "string"], "default": None},
    {"name": "completion_date", "type": ["null", "string"], "default": None},
    {"name": "domain", "type": ["null", "string"], "default": None},
    {"name": "economically_disadvantaged", "type": ["null", "string"], "default": None},
    {"name": "english_language_learner", "type": ["null", "string"], "default": None},
    {"name": "first_name", "type": ["null", "string"], "default": None},
    {"name": "hispanic_or_latino", "type": ["null", "string"], "default": None},
    {"name": "last_name", "type": ["null", "string"], "default": None},
    {"name": "lesson_grade", "type": ["null", "string"], "default": None},
    {"name": "lesson_id", "type": ["null", "string"], "default": None},
    {"name": "lesson_language", "type": ["null", "string"], "default": None},
    {"name": "lesson_level", "type": ["null", "string"], "default": None},
    {"name": "lesson_name", "type": ["null", "string"], "default": None},
    {"name": "lesson_objective", "type": ["null", "string"], "default": None},
    {"name": "migrant", "type": ["null", "string"], "default": None},
    {"name": "passed_or_not_passed", "type": ["null", "string"], "default": None},
    {"name": "race", "type": ["null", "string"], "default": None},
    {"name": "report_group_s", "type": ["null", "string"], "default": None},
    {"name": "school", "type": ["null", "string"], "default": None},
    {"name": "score", "type": ["null", "long"], "default": None},
    {"name": "sex", "type": ["null", "string"], "default": None},
    {"name": "special_education", "type": ["null", "string"], "default": None},
    {"name": "student_grade", "type": ["null", "string"], "default": None},
    {"name": "student_id", "type": ["null", "long"], "default": None},
    {"name": "subject", "type": ["null", "string"], "default": None},
    {"name": "teacher_assigned_lesson", "type": ["null", "string"], "default": None},
    {"name": "total_time_on_lesson_min", "type": ["null", "long"], "default": None},
    {"name": "user_name", "type": ["null", "string"], "default": None},
]

ASSET_FIELDS = {
    "diagnostic_and_instruction": DIAGNOSTIC_INSTRUCTION_FIELDS,
    "diagnostic_results": DIAGNOSTIC_RESULTS_FIELDS,
    "instructional_usage_data": INSTRUCTIONAL_USAGE_FIELDS,
    "personalized_instruction_by_lesson": PERSONALIZED_INSTRUCTION_FIELDS,
}
