# https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#defaultfetchtypes
ORACLE_AVRO_SCHEMA_TYPES = {
    "DB_TYPE_BINARY_DOUBLE": ["double"],
    "DB_TYPE_BINARY_FLOAT": ["float"],
    "DB_TYPE_BINARY_INTEGER": ["int"],
    "DB_TYPE_BLOB": ["bytes"],
    "DB_TYPE_BOOLEAN": ["boolean"],
    "DB_TYPE_CHAR": ["string"],
    "DB_TYPE_CLOB": ["string"],
    "DB_TYPE_DATE": [{"type": "int", "logicalType": "date"}],
    "DB_TYPE_INTERVAL_DS": [
        {"type": "fixed", "name": "datetime.timedelta", "logicalType": "duration"},
    ],
    "DB_TYPE_JSON": [{"type": "bytes", "logicalType": "json"}],
    "DB_TYPE_LONG": ["string"],
    "DB_TYPE_LONG_RAW": ["bytes"],
    "DB_TYPE_LONG_NVARCHAR": ["string"],
    "DB_TYPE_NCHAR": ["string"],
    "DB_TYPE_NCLOB": ["string"],
    "DB_TYPE_NUMBER": [
        "int",
        "double",
        {"type": "bytes", "logicalType": "decimal", "precision": 40, "scale": 40},
    ],
    "DB_TYPE_NVARCHAR": ["string"],
    "DB_TYPE_RAW": ["bytes"],
    "DB_TYPE_ROWID": ["string"],
    "DB_TYPE_TIMESTAMP": [{"type": "long", "logicalType": "timestamp-micros"}],
    "DB_TYPE_TIMESTAMP_LTZ": [{"type": "long", "logicalType": "timestamp-micros"}],
    "DB_TYPE_TIMESTAMP_TZ": [{"type": "long", "logicalType": "timestamp-micros"}],
    "DB_TYPE_UROWID": ["string"],
    "DB_TYPE_VARCHAR": ["string"],
    # "DB_TYPE_BFILE": [],
    # "DB_TYPE_CURSOR": [],
    # "DB_TYPE_INTERVAL_YM": [],
    # "DB_TYPE_OBJECT": [],
}
