select
    _dagster_partition_school_year,
    _dagster_partition_term,
    student_id,
    local_id,
    student_name,
    test_reason,
    test_oppnumber,
    primary_exceptionality,
    section_504,
    english_language_learner_ell_status,
    ethnicity,
    gender_k_12,
    gender_postsecondary_only,
    enrolled_district,
    enrolled_grade,
    enrolled_school,
    testing_location,
    safe_cast(date_taken as date) as date_taken,
    safe_cast(test_completion_date as date) as test_completion_date,
    {# student_dob, #}
    coalesce(
        fast_grade_3_ela_reading_achievement_level,
        grade_3_fast_ela_reading_achievement_level,
        fast_grade_4_ela_reading_achievement_level,
        grade_4_fast_ela_reading_achievement_level,
        fast_grade_5_ela_reading_achievement_level,
        grade_5_fast_ela_reading_achievement_level,
        fast_grade_6_ela_reading_achievement_level,
        grade_6_fast_ela_reading_achievement_level,
        fast_grade_7_ela_reading_achievement_level,
        grade_7_fast_ela_reading_achievement_level,
        fast_grade_8_ela_reading_achievement_level,
        grade_8_fast_ela_reading_achievement_level
    ) as ela_reading_achievement_level,

    coalesce(
        fast_grade_3_ela_reading_percentile_rank,
        grade_3_fast_ela_reading_percentile_rank,
        fast_grade_4_ela_reading_percentile_rank,
        grade_4_fast_ela_reading_percentile_rank,
        fast_grade_5_ela_reading_percentile_rank,
        grade_5_fast_ela_reading_percentile_rank,
        fast_grade_6_ela_reading_percentile_rank,
        grade_6_fast_ela_reading_percentile_rank,
        fast_grade_7_ela_reading_percentile_rank,
        grade_7_fast_ela_reading_percentile_rank,
        fast_grade_8_ela_reading_percentile_rank,
        grade_8_fast_ela_reading_percentile_rank
    ) as ela_reading_percentile_rank,

    coalesce(
        fast_grade_3_ela_reading_scale_score,
        grade_3_fast_ela_reading_scale_score.long_value,
        safe_cast(grade_3_fast_ela_reading_scale_score.string_value as int),
        fast_grade_4_ela_reading_scale_score,
        grade_4_fast_ela_reading_scale_score,
        fast_grade_5_ela_reading_scale_score,
        grade_5_fast_ela_reading_scale_score,
        fast_grade_6_ela_reading_scale_score,
        grade_6_fast_ela_reading_scale_score,
        fast_grade_7_ela_reading_scale_score,
        grade_7_fast_ela_reading_scale_score,
        fast_grade_8_ela_reading_scale_score,
        grade_8_fast_ela_reading_scale_score
    ) as ela_reading_scale_score,

    coalesce(
        fast_grade_3_mathematics_achievement_level,
        grade_3_fast_mathematics_achievement_level,
        fast_grade_4_mathematics_achievement_level,
        grade_4_fast_mathematics_achievement_level,
        fast_grade_5_mathematics_achievement_level,
        grade_5_fast_mathematics_achievement_level,
        fast_grade_6_mathematics_achievement_level,
        grade_6_fast_mathematics_achievement_level,
        fast_grade_7_mathematics_achievement_level,
        grade_7_fast_mathematics_achievement_level,
        fast_grade_8_mathematics_achievement_level,
        grade_8_fast_mathematics_achievement_level
    ) as mathematics_achievement_level,

    coalesce(
        fast_grade_3_mathematics_percentile_rank,
        grade_3_fast_mathematics_percentile_rank,
        fast_grade_4_mathematics_percentile_rank,
        grade_4_fast_mathematics_percentile_rank,
        fast_grade_5_mathematics_percentile_rank,
        grade_5_fast_mathematics_percentile_rank,
        fast_grade_6_mathematics_percentile_rank,
        grade_6_fast_mathematics_percentile_rank,
        fast_grade_7_mathematics_percentile_rank,
        grade_7_fast_mathematics_percentile_rank,
        fast_grade_8_mathematics_percentile_rank,
        grade_8_fast_mathematics_percentile_rank
    ) as mathematics_percentile_rank,

    coalesce(
        safe_cast(fast_grade_3_mathematics_scale_score as int),
        grade_3_fast_mathematics_scale_score.long_value,
        safe_cast(grade_3_fast_mathematics_scale_score.string_value as int),
        fast_grade_4_mathematics_scale_score.long_value,
        safe_cast(fast_grade_4_mathematics_scale_score.string_value as int),
        grade_4_fast_mathematics_scale_score.long_value,
        safe_cast(grade_4_fast_mathematics_scale_score.string_value as int),
        fast_grade_5_mathematics_scale_score.long_value,
        safe_cast(fast_grade_5_mathematics_scale_score.string_value as int),
        grade_5_fast_mathematics_scale_score.long_value,
        safe_cast(grade_5_fast_mathematics_scale_score.string_value as int),
        fast_grade_6_mathematics_scale_score.long_value,
        safe_cast(fast_grade_6_mathematics_scale_score.string_value as int),
        grade_6_fast_mathematics_scale_score.long_value,
        safe_cast(grade_6_fast_mathematics_scale_score.string_value as int),
        fast_grade_7_mathematics_scale_score.long_value,
        safe_cast(fast_grade_7_mathematics_scale_score.string_value as int),
        grade_7_fast_mathematics_scale_score.long_value,
        safe_cast(grade_7_fast_mathematics_scale_score.string_value as int),
        fast_grade_8_mathematics_scale_score.long_value,
        safe_cast(fast_grade_8_mathematics_scale_score.string_value as int),
        grade_8_fast_mathematics_scale_score.long_value,
        safe_cast(grade_8_fast_mathematics_scale_score.string_value as int)
    ) as mathematics_scale_score,

    `1_reading_prose_and_poetry_performance`,
    `2_reading_informational_text_performance`,
    `3_reading_across_genres_vocabulary_performance`,

    `1_number_sense_and_additive_reasoning_performance`,
    `1_number_sense_and_operations_and_algebraic_reasoning_performance`,
    `1_number_sense_and_operations_and_probability_performance`,
    `1_number_sense_and_operations_performance`,
    `1_number_sense_and_operations_with_whole_numbers_performance`,
    `2_number_sense_and_multiplicative_reasoning_performance`,
    `2_number_sense_and_operations_with_fractions_and_decimals_performance`,

    `2_algebraic_reasoning_performance`,
    `3_algebraic_reasoning_performance`,

    `2_proportional_reasoning_and_relationships_performance`,

    `3_fractional_reasoning_performance`,

    `3_geometric_reasoning_data_analysis_and_probability_performance`,
    `3_geometric_reasoning_measurement_and_data_analysis_and_probability_performance`,
    `3_geometric_reasoning_performance`,
    `4_geometric_reasoning_measurement_and_data_analysis_and_probability_performance`,
    `4_geometric_reasoning_performance`,

    `3_linear_relationships_data_analysis_and_functions_performance`,

    `4_data_analysis_and_probability_performance`,
from {{ source('fldoe', 'src_fldoe__fast') }}
