ADP_SFTP_HOST_IP=op://Data Team/ADP Workforce Now SFTP/ip
ADP_SFTP_PASSWORD=op://Data Team/ADP Workforce Now SFTP/password
ADP_SFTP_USERNAME=op://Data Team/ADP Workforce Now SFTP/username
ADP_WFM_APP_KEY=op://Data Team/ADP Workforce Manager API/app key
ADP_WFM_CLIENT_ID=op://Data Team/ADP Workforce Manager API/client id
ADP_WFM_CLIENT_SECRET=op://Data Team/ADP Workforce Manager API/client secret
ADP_WFM_PASSWORD=op://Data Team/ADP Workforce Manager API/password
ADP_WFM_SUBDOMAIN=op://Data Team/ADP Workforce Manager API/subdomain
ADP_WFM_USERNAME=op://Data Team/ADP Workforce Manager API/username
ADP_WFN_CLIENT_ID=op://Data Team/ADP Workforce Now API/client id
ADP_WFN_CLIENT_SECRET=op://Data Team/ADP Workforce Now API/client secret
AIRBYTE_API_KEY=op://Data Team/Airbyte API/api key
ALCHEMER_API_TOKEN_SECRET=op://Data Team/Alchemer API/token secret
ALCHEMER_API_TOKEN=op://Data Team/Alchemer API/token
AMPLIFY_DDS_PASSWORD=op://Data Team/DIBELS Data System/password_confirm
AMPLIFY_DDS_USERNAME=op://Data Team/DIBELS Data System/username
AMPLIFY_PASSWORD=op://Data Team/Amplify Service Account/password
AMPLIFY_USERNAME=op://Data Team/Amplify Service Account/username
BLISSBOOK_SFTP_HOST=op://Data Team/Blissbook SFTP/host
BLISSBOOK_SFTP_PASSWORD=op://Data Team/Blissbook SFTP/password
BLISSBOOK_SFTP_PORT=op://Data Team/Blissbook SFTP/port
BLISSBOOK_SFTP_USERNAME=op://Data Team/Blissbook SFTP/username
CLEVER_SFTP_HOST=op://Data Team/Clever SFTP - Uploads/host
CLEVER_SFTP_PASSWORD=op://Data Team/Clever SFTP - Uploads/password
CLEVER_SFTP_USERNAME=op://Data Team/Clever SFTP - Uploads/username
COUCHDROP_SFTP_HOST=op://Data Team/Couchdrop SFTP - Data Robot/URL
COUCHDROP_SFTP_PASSWORD=op://Data Team/Couchdrop SFTP - Data Robot/password
COUCHDROP_SFTP_USERNAME=op://Data Team/Couchdrop SFTP - Data Robot/username
COUPA_SFTP_HOST=op://Data Team/Coupa SFTP/host
COUPA_SFTP_PASSWORD=op://Data Team/Coupa SFTP/password
COUPA_SFTP_USERNAME=op://Data Team/Coupa SFTP/username
DAGSTER_CLOUD_AGENT_TOKEN=op://Data Team/Dagster Cloud Agent/credential
DEANSLIST_SFTP_HOST=op://Data Team/DeansList SFTP/host
DEANSLIST_SFTP_PASSWORD=op://Data Team/DeansList SFTP/password
DEANSLIST_SFTP_USERNAME=op://Data Team/DeansList SFTP/username
DEANSLIST_SUBDOMAIN=op://Data Team/DeansList API/subdomain
EDPLAN_SFTP_HOST=op://Data Team/edplan SFTP - Camden/host
EDPLAN_SFTP_PASSWORD_KIPPCAMDEN=op://Data Team/edplan SFTP - Camden/password
EDPLAN_SFTP_PASSWORD_KIPPNEWARK=op://Data Team/edplan SFTP - Newark/password
EDPLAN_SFTP_PASSWORD=op://Data Team/edplan SFTP - Camden/password
EDPLAN_SFTP_USERNAME_KIPPCAMDEN=op://Data Team/edplan SFTP - Camden/username
EDPLAN_SFTP_USERNAME_KIPPNEWARK=op://Data Team/edplan SFTP - Newark/username
EDPLAN_SFTP_USERNAME=op://Data Team/edplan SFTP - Camden/username
EGENCIA_SFTP_HOST=op://Data Team/Egencia SFTP/host
EGENCIA_SFTP_USERNAME=op://Data Team/Egencia SFTP/username
FIVETRAN_API_KEY=op://Data Team/Fivetran API/api key
FIVETRAN_API_SECRET=op://Data Team/Fivetran API/api secret
GOOGLE_DIRECTORY_DELEGATED_ACCOUNT=op://Data Team/Google Admin Service Account/customer id
GOOGLE_WORKSPACE_CUSTOMER_ID=op://Data Team/Google Admin Service Account/username
ILLUMINATE_DB_PASSWORD=op://Data Team/Illuminate ODBC/password
ILLUMINATE_SFTP_HOST=op://Data Team/Illuminate SFTP/host
ILLUMINATE_SFTP_PASSWORD=op://Data Team/Illuminate SFTP/password
ILLUMINATE_SFTP_USERNAME=op://Data Team/Illuminate SFTP/username
IREADY_SFTP_HOST=op://Data Team/iReady SFTP/host
IREADY_SFTP_PASSWORD=op://Data Team/iReady SFTP/password
IREADY_SFTP_USERNAME=op://Data Team/iReady SFTP/username
KTAF_SFTP_HOST_IP=op://Data Team/ID Auto SFTP/host
KTAF_SFTP_PASSWORD=op://Data Team/ID Auto SFTP/password
KTAF_SFTP_USERNAME=op://Data Team/ID Auto SFTP/username
LDAP_PASSWORD=op://Data Team/Active Directory Service Account/password
LDAP_PORT=op://Data Team/Active Directory Service Account/port
LDAP_USER=op://Data Team/Active Directory Service Account/username
LITTLESIS_SFTP_HOST=op://Data Team/Little SIS SFTP/host
LITTLESIS_SFTP_PORT=op://Data Team/Little SIS SFTP/port
LITTLESIS_SFTP_PASSWORD=op://Data Team/Little SIS SFTP/password
LITTLESIS_SFTP_USERNAME=op://Data Team/Little SIS SFTP/username
OP_CONNECT_TOKEN=op://Data Team/hltg4twkgkf6xc23n6pc7dqvee/credential
PS_DB_DATABASE=op://Data Team/PowerSchool DB - Newark/database
PS_DB_HOST=op://Data Team/PowerSchool DB - Newark/server
PS_DB_PASSWORD=op://Data Team/PowerSchool DB - Newark/password
PS_DB_PORT=op://Data Team/PowerSchool DB - Newark/port
PS_DB_USERNAME=op://Data Team/PowerSchool DB - Newark/username
PS_ENROLLMENT_API_KEY=op://Data Team/PowerSchool Enrollment/api key
PS_SSH_HOST=op://Data Team/PowerSchool SSH - Newark/host
PS_SSH_PASSWORD=op://Data Team/PowerSchool SSH - Newark/password
PS_SSH_PORT=op://Data Team/PowerSchool SSH - Newark/port
PS_SSH_REMOTE_BIND_HOST=op://Data Team/PowerSchool SSH - Newark/remote bind host
PS_SSH_USERNAME=op://Data Team/PowerSchool SSH - Newark/username
RENLEARN_SFTP_HOST=op://Data Team/RenLearning SFTP Exports - NJ/host
RENLEARN_SFTP_PASSWORD_KIPPMIAMI=op://Data Team/RenLearning SFTP Exports - Miami/password
RENLEARN_SFTP_PASSWORD_KIPPNJ=op://Data Team/RenLearning SFTP Exports - NJ/password
RENLEARN_SFTP_PASSWORD=op://Data Team/RenLearning SFTP Exports - NJ/password
RENLEARN_SFTP_USERNAME_KIPPMIAMI=op://Data Team/RenLearning SFTP Exports - Miami/username
RENLEARN_SFTP_USERNAME_KIPPNJ=op://Data Team/RenLearning SFTP Exports - NJ/username
RENLEARN_SFTP_USERNAME=op://Data Team/RenLearning SFTP Exports - NJ/username
SCHOOLMINT_GROW_CLIENT_ID=op://Data Team/SchooMint Grow API/client id
SCHOOLMINT_GROW_CLIENT_SECRET=op://Data Team/SchooMint Grow API/client secret
SCHOOLMINT_GROW_DISTRICT_ID=op://Data Team/SchooMint Grow API/district id
SMARTRECRUITERS_SMARTTOKEN=op://Data Team/SmartRecruiters API/smart token
TABLEAU_PERSONAL_ACCESS_TOKEN=op://Data Team/Tableau Server PAT - Dagster/credential
TABLEAU_SERVER_ADDRESS=op://Data Team/Tableau Server PAT - Dagster/hostname
TABLEAU_SITE_ID=op://Data Team/Tableau Server PAT - Dagster/site id
TABLEAU_TOKEN_NAME=op://Data Team/Tableau Server PAT - Dagster/username
TITAN_SFTP_HOST=op://Data Team/Titan SFTP - Camden/host
TITAN_SFTP_PASSWORD_KIPPCAMDEN=op://Data Team/Titan SFTP - Camden/password
TITAN_SFTP_PASSWORD_KIPPNEWARK=op://Data Team/Titan SFTP - Newark/password
TITAN_SFTP_PASSWORD=op://Data Team/Titan SFTP - Camden/password
TITAN_SFTP_USERNAME_KIPPCAMDEN=op://Data Team/Titan SFTP - Camden/username
TITAN_SFTP_USERNAME_KIPPNEWARK=op://Data Team/Titan SFTP - Newark/username
TITAN_SFTP_USERNAME=op://Data Team/Titan SFTP - Camden/username
ZENDESK_EMAIL=op://Data Team/Zendesk API/email
ZENDESK_SUBDOMAIN=op://Data Team/Zendesk API/subdomain
ZENDESK_TOKEN=op://Data Team/Zendesk API/token