ACHIEVE3K_SFTP_PASSWORD=op://Data Team/Achieve 3000 SFTP/password
ACHIEVE3K_SFTP_USERNAME=op://Data Team/Achieve 3000 SFTP/username
ADP_SFTP_PASSWORD=op://Data Team/ADP Workforce Now SFTP/password
ADP_SFTP_USERNAME=op://Data Team/ADP Workforce Now SFTP/username
ADP_WFM_APP_KEY=op://Data Team/ADP Workforce Manager API/app key
ADP_WFM_CLIENT_ID=op://Data Team/ADP Workforce Manager API/client id
ADP_WFM_CLIENT_SECRET=op://Data Team/ADP Workforce Manager API/client secret
ADP_WFM_PASSWORD=op://Data Team/ADP Workforce Manager API/password
ADP_WFM_SUBDOMAIN=op://Data Team/ADP Workforce Manager API/subdomain
ADP_WFM_USERNAME=op://Data Team/ADP Workforce Manager API/username
ADP_WFN_CLIENT_ID=op://Data Team/ADP Workforce Now API/client id
ADP_WFN_CLIENT_SECRET=op://Data Team/ADP Workforce Now API/client secret
AIRBYTE_API_KEY=op://Data Team/Airbyte API/api key
ALCHEMER_API_TOKEN_SECRET=op://Data Team/Alchemer API/token secret
ALCHEMER_API_TOKEN=op://Data Team/Alchemer API/token
AMPLIFY_PASSWORD=op://Data Team/Amplify Service Account/password
AMPLIFY_USERNAME=op://Data Team/Amplify Service Account/username
BLISSBOOK_SFTP_PASSWORD=op://Data Team/Blissbook SFTP/password
BLISSBOOK_SFTP_USERNAME=op://Data Team/Blissbook SFTP/username
CLEVER_SFTP_PASSWORD=op://Data Team/Clever SFTP - Uploads/password
CLEVER_SFTP_USERNAME=op://Data Team/Clever SFTP - Uploads/username
COUCHDROP_SFTP_PASSWORD=op://Data Team/Couchdrop SFTP - Data Robot/password
COUCHDROP_SFTP_USERNAME=op://Data Team/Couchdrop SFTP - Data Robot/username
COUPA_SFTP_PASSWORD=op://Data Team/Coupa SFTP/password
COUPA_SFTP_USERNAME=op://Data Team/Coupa SFTP/username
DEANSLIST_SFTP_PASSWORD=op://Data Team/DeansList SFTP/password
DEANSLIST_SFTP_USERNAME=op://Data Team/DeansList SFTP/username
EGENCIA_SFTP_USERNAME=op://Data Team/Egencia SFTP/username
FIVETRAN_API_KEY=op://Data Team/Fivetran API/api key
FIVETRAN_API_SECRET=op://Data Team/Fivetran API/api secret
ILLUMINATE_SFTP_PASSWORD=op://Data Team/Illuminate SFTP/password
ILLUMINATE_SFTP_USERNAME=op://Data Team/Illuminate SFTP/username
IREADY_SFTP_PASSWORD=op://Data Team/iReady SFTP/password
IREADY_SFTP_USERNAME=op://Data Team/iReady SFTP/username
KIPPCAMDEN_EDPLAN_SFTP_PASSWORD=op://Data Team/edplan SFTP - Camden/password
KIPPCAMDEN_EDPLAN_SFTP_USERNAME=op://Data Team/edplan SFTP - Camden/username
KIPPCAMDEN_PS_DB_PASSWORD=op://Data Team/PowerSchool DB - Camden/password
KIPPCAMDEN_PS_SSH_PASSWORD=op://Data Team/PowerSchool SSH - Camden/password
KIPPCAMDEN_PS_SSH_PORT=op://Data Team/PowerSchool SSH - Camden/port
KIPPCAMDEN_PS_SSH_REMOTE_BIND_HOST=op://Data Team/PowerSchool SSH - Camden/remote bind host
KIPPCAMDEN_PS_SSH_USERNAME=op://Data Team/PowerSchool SSH - Camden/username
KIPPCAMDEN_TITAN_SFTP_PASSWORD=op://Data Team/Titan SFTP - Camden/password
KIPPCAMDEN_TITAN_SFTP_USERNAME=op://Data Team/Titan SFTP - Camden/username
KIPPMIAMI_PS_DB_PASSWORD=op://Data Team/PowerSchool DB - Miami/password
KIPPMIAMI_PS_SSH_PASSWORD=op://Data Team/PowerSchool SSH - Miami/password
KIPPMIAMI_PS_SSH_PORT=op://Data Team/PowerSchool SSH - Miami/port
KIPPMIAMI_PS_SSH_REMOTE_BIND_HOST=op://Data Team/PowerSchool SSH - Miami/remote bind host
KIPPMIAMI_PS_SSH_USERNAME=op://Data Team/PowerSchool SSH - Miami/username
KIPPMIAMI_RENLEARN_SFTP_PASSWORD=op://Data Team/RenLearning SFTP Exports - Miami/password
KIPPMIAMI_RENLEARN_SFTP_USERNAME=op://Data Team/RenLearning SFTP Exports - Miami/username
KIPPNEWARK_EDPLAN_SFTP_PASSWORD=op://Data Team/edplan SFTP - Newark/password
KIPPNEWARK_EDPLAN_SFTP_USERNAME=op://Data Team/edplan SFTP - Newark/username
KIPPNEWARK_PS_DB_PASSWORD=op://Data Team/PowerSchool DB - Newark/password
KIPPNEWARK_PS_SSH_PASSWORD=op://Data Team/PowerSchool SSH - Newark/password
KIPPNEWARK_PS_SSH_PORT=op://Data Team/PowerSchool SSH - Newark/port
KIPPNEWARK_PS_SSH_REMOTE_BIND_HOST=op://Data Team/PowerSchool SSH - Newark/remote bind host
KIPPNEWARK_PS_SSH_USERNAME=op://Data Team/PowerSchool SSH - Newark/username
KIPPNEWARK_TITAN_SFTP_PASSWORD=op://Data Team/Titan SFTP - Newark/password
KIPPNEWARK_TITAN_SFTP_USERNAME=op://Data Team/Titan SFTP - Newark/username
KIPPNJ_RENLEARN_SFTP_PASSWORD=op://Data Team/RenLearning SFTP Exports - NJ/password
KIPPNJ_RENLEARN_SFTP_USERNAME=op://Data Team/RenLearning SFTP Exports - NJ/username
KTAF_SFTP_PASSWORD=op://Data Team/ID Auto SFTP/password
KTAF_SFTP_USERNAME=op://Data Team/ID Auto SFTP/username
LDAP_PASSWORD=op://Data Team/Active Directory Service Account/password
LDAP_USER=op://Data Team/Active Directory Service Account/username
LITTLESIS_SFTP_PASSWORD=op://Data Team/Little SIS SFTP/password
LITTLESIS_SFTP_USERNAME=op://Data Team/Little SIS SFTP/username
OP_CONNECT_TOKEN=op://Data Team/hltg4twkgkf6xc23n6pc7dqvee/credential
SCHOOLMINT_GROW_CLIENT_ID=op://Data Team/SchooMint Grow API/client id
SCHOOLMINT_GROW_CLIENT_SECRET=op://Data Team/SchooMint Grow API/client secret
SCHOOLMINT_GROW_DISTRICT_ID=op://Data Team/SchooMint Grow API/district id
SMARTRECRUITERS_SMARTTOKEN=op://Data Team/SmartRecruiters API/smart token
ZENDESK_EMAIL=op://Data Team/Zendesk API/email
ZENDESK_TOKEN=op://Data Team/Zendesk API/token