ACHIEVE3K_SFTP_PASSWORD=op://Data Team/Achieve 3000 SFTP/password
ACHIEVE3K_SFTP_USERNAME=op://Data Team/Achieve 3000 SFTP/username
ADP_SFTP_PASSWORD=op://Data Team/ADP Workforce Now SFTP/password
ADP_SFTP_USERNAME=op://Data Team/ADP Workforce Now SFTP/username
ADP_WFM_APP_KEY=op://Data Team/ADP Workforce Manager API/app key
ADP_WFM_CLIENT_ID=op://Data Team/ADP Workforce Manager API/client id
ADP_WFM_CLIENT_SECRET=op://Data Team/ADP Workforce Manager API/client secret
ADP_WFM_PASSWORD=op://Data Team/ADP Workforce Manager API/password
ADP_WFM_SUBDOMAIN=op://Data Team/ADP Workforce Manager API/subdomain
ADP_WFM_USERNAME=op://Data Team/ADP Workforce Manager API/username
ADP_WFN_CLIENT_ID=op://Data Team/ADP Workforce Now API/client id
ADP_WFN_CLIENT_SECRET=op://Data Team/ADP Workforce Now API/client secret
AIRBYTE_API_KEY=op://Data Team/Airbyte API/api key
ALCHEMER_API_TOKEN_SECRET=op://Data Team/Alchemer API/token secret
ALCHEMER_API_TOKEN=op://Data Team/Alchemer API/token
AMPLIFY_PASSWORD=op://Data Team/Amplify Service Account/password
AMPLIFY_USERNAME=op://Data Team/Amplify Service Account/username
BLISSBOOK_SFTP_PASSWORD=op://Data Team/Blissbook SFTP/password
BLISSBOOK_SFTP_USERNAME=op://Data Team/Blissbook SFTP/username
CLEVER_SFTP_PASSWORD=op://Data Team/Clever SFTP - Uploads/password
CLEVER_SFTP_USERNAME=op://Data Team/Clever SFTP - Uploads/username
COUCHDROP_SFTP_PASSWORD=op://Data Team/Couchdrop SFTP - Data Robot/password
COUCHDROP_SFTP_USERNAME=op://Data Team/Couchdrop SFTP - Data Robot/username
COUPA_SFTP_PASSWORD=op://Data Team/Coupa SFTP/password
COUPA_SFTP_USERNAME=op://Data Team/Coupa SFTP/username
DAGSTER_CLOUD_AGENT_TOKEN=op://Data Team/Dagster Cloud Agent/credential
DEANSLIST_SFTP_PASSWORD=op://Data Team/DeansList SFTP/password
DEANSLIST_SFTP_USERNAME=op://Data Team/DeansList SFTP/username
EDPLAN_SFTP_PASSWORD=op://Data Team/edplan SFTP - Camden/password
EDPLAN_SFTP_USERNAME=op://Data Team/edplan SFTP - Camden/username
EGENCIA_SFTP_USERNAME=op://Data Team/Egencia SFTP/username
FIVETRAN_API_KEY=op://Data Team/Fivetran API/api key
FIVETRAN_API_SECRET=op://Data Team/Fivetran API/api secret
ILLUMINATE_SFTP_PASSWORD=op://Data Team/Illuminate SFTP/password
ILLUMINATE_SFTP_USERNAME=op://Data Team/Illuminate SFTP/username
ILLUMINATE_DB_PASSWORD=op://Data Team/Illuminate ODBC/password
IREADY_SFTP_PASSWORD=op://Data Team/iReady SFTP/password
IREADY_SFTP_USERNAME=op://Data Team/iReady SFTP/username
KTAF_SFTP_PASSWORD=op://Data Team/ID Auto SFTP/password
KTAF_SFTP_USERNAME=op://Data Team/ID Auto SFTP/username
LDAP_PASSWORD=op://Data Team/Active Directory Service Account/password
LDAP_USER=op://Data Team/Active Directory Service Account/username
LITTLESIS_SFTP_PASSWORD=op://Data Team/Little SIS SFTP/password
LITTLESIS_SFTP_USERNAME=op://Data Team/Little SIS SFTP/username
OP_CONNECT_TOKEN=op://Data Team/hltg4twkgkf6xc23n6pc7dqvee/credential
PS_DB_PASSWORD=op://Data Team/PowerSchool DB - Newark/password
PS_SSH_PASSWORD=op://Data Team/PowerSchool SSH - Newark/password
PS_SSH_PORT=op://Data Team/PowerSchool SSH - Newark/port
PS_SSH_REMOTE_BIND_HOST=op://Data Team/PowerSchool SSH - Newark/remote bind host
PS_SSH_USERNAME=op://Data Team/PowerSchool SSH - Newark/username
RENLEARN_SFTP_PASSWORD=op://Data Team/RenLearning SFTP Exports - NJ/password
RENLEARN_SFTP_USERNAME=op://Data Team/RenLearning SFTP Exports - NJ/username
SCHOOLMINT_GROW_CLIENT_ID=op://Data Team/SchooMint Grow API/client id
SCHOOLMINT_GROW_CLIENT_SECRET=op://Data Team/SchooMint Grow API/client secret
SCHOOLMINT_GROW_DISTRICT_ID=op://Data Team/SchooMint Grow API/district id
SMARTRECRUITERS_SMARTTOKEN=op://Data Team/SmartRecruiters API/smart token
TABLEAU_PERSONAL_ACCESS_TOKEN=op://Data Team/Tableau Server PAT - Dagster/credential
TABLEAU_TOKEN_NAME=op://Data Team/Tableau Server PAT - Dagster/username
TITAN_SFTP_PASSWORD=op://Data Team/Titan SFTP - Camden/password
TITAN_SFTP_USERNAME=op://Data Team/Titan SFTP - Camden/username
ZENDESK_EMAIL=op://Data Team/Zendesk API/email
ZENDESK_TOKEN=op://Data Team/Zendesk API/token