select
    course_id,
    syear,
    subject_id,
    school_id,
    district_id,
    title,
    short_name,
    alternate_title,
    rollover_id,
    grad_subject_id,
    grad_subject_id2,
    grad_subject_id3,
    mp,
    grade_level,
    prerequisites,
    prerequisites_2,
    prerequisites_3,
    need_approval,
    teacher_requestable,
    requests_subject,
    priority,
    description,
    occurrences,
    allow_repeat,
    homeroom,
    edfi_course_level_characteristic,
    iet_program_number,
    imported,
    uuid,
    created_at,
    updated_at,

    cast(course_hours as numeric) as course_hours,
    cast(credit_hours as numeric) as credit_hours,
    cast(length as numeric) as length,

    custom_4 as course_sequence,
    custom_2 as wdis_ocp_hours,
    custom_3 as ocp,
    custom_10 as cape,
from {{ source("focus", "courses") }}
