select
    id,
    syear,
    school_id,
    student_id,
    course_id,
    course_period_id,
    marking_period_id,
    mp,
    course_weight,
    days,
    rotation_days,
    start_date,
    end_date,
    modified_date,
    modified_by,
    age_inst_setting,
    age_online_course,
    cte_de_location,
    de_inst_type,
    de_student_type,
    online_course,
    math_intervention,
    uuid,
    created_at,
    updated_at,

    custom_5 as fefp_number,
    custom_8 as dual_enrollment_indicator,
    custom_10 as class_minutes_weekly,
    custom_22 as reading_intervention_component,
    custom_31 as basic_skills_exam,
    custom_58 as pmrn,
    custom_65 as location_of_student,
    custom_68 as eoc_exam_term,
    custom_69 as exempt_from_total_clock_hours,
    custom_87 as exclude_from_fte,
from {{ source("focus", "schedule") }}
