select
    id,
    syear,
    school_id,
    student_id,
    grade_id,
    enrollment_code,
    drop_code,
    calendar_id,
    next_school,
    graduation_requirement_program,
    program_id,
    next_year_program_id,
    team_id,
    progression_plan_category,
    hs_progression_plan_category,
    planned_high_school,
    rollover_id,
    start_date,
    end_date,
    include_in_class_rank,
    next_grade,
    imported,
    first_time_indicator,
    mid_year_promotion,
    fl_days_present,
    fl_days_absent,
    fl_days_absent_not_disc,
    custom_1 as prior_district,
    custom_2 as prior_state,
    custom_3 as prior_country,
    custom_4 as educational_choice,
    custom_6 as student_offender_transfer,
    custom_9 as second_school,
    custom_18 as resident_status_state_county,
    custom_5 as disaster_affected_student,
    uuid,
    created_at,
    updated_at,

    cast(distance_from_school as numeric) as distance_from_school,
from {{ source("focus", "student_enrollment") }}
