select
    referral_id,
    student_id,
    school_id,
    district_id,
    syear,
    staff_id,
    teacher_code,
    classroom,
    entry_date,
    referral_date,
    creation_date,
    submission_date,
    last_updated,
    suspension_begin,
    suspension_end,
    suspension_length,
    attendance_code,
    attendance_day_id,
    attendance_period_id,
    attendance_threshold_id,
    tardy_threshold_id,
    merged_referral_id,
    referral_import_key,
    discipline_code_ai,
    notification_sent,
    incomplete,
    processed,
    closed,
    dismissed,
    returned,
    display,
    comment,
    imported,
    uuid,
    created_at,
    updated_at,

    custom_10 as reason_for_referral,
    custom_51 as location,
    custom_52 as discipline_code,
    custom_56 as refer_date,
    custom_57 as context,
    custom_60 as action_taken_by,
    custom_61 as admin_comments,
    custom_78 as involved_in_hate_crime,
    custom_79 as use_of_alcohol,
    custom_80 as use_of_drugs,
    custom_81 as weapon_use,
    custom_82 as involved_in_bullying,
    custom_83 as referral_number,
    custom_200000020 as school_related_arrests,
    custom_200000021 as zero_tolerance_expulsion,
from {{ source("focus", "discipline_referrals") }}
