select
    period_id,
    rollover_id,
    school_id,
    district_id,
    syear,
    title,
    short_name,
    block,
    attendance,
    required_for_scheduling,
    conflicts_with,
    start_time,
    end_time,
    uuid,
    created_at,
    updated_at,

    cast(length as numeric) as length,
    cast(sort_order as numeric) as sort_order,
from {{ source("focus", "school_periods") }}
