select
    id,
    syear,
    school_id,
    district_id,
    title,
    short_name,
    type,
    state_code,
    default_code,
    is_daily_code,
    excused,
    tardy,
    discipline,
    not_in_class,
    denies_credit,
    chronic_absenteeism,
    truancy,
    out_of_school,
    state_attendance_type,
    color,
    sub,
    uuid,
    created_at,
    updated_at,

    cast(sort_order as numeric) as sort_order,
    cast(table_name as numeric) as table_name,
from {{ source("focus", "attendance_codes") }}
