select
    course_period_id,
    syear,
    school_id,
    course_id,
    parent_id,
    rollover_id,
    period_id,
    end_period_id,
    marking_period_id,
    teacher_id,
    co_teacher_id1,
    co_teacher_id2,
    co_teacher_id3,
    co_teacher_id4,
    co_teacher_id5,
    co_teacher_id6,
    co_teacher_id7,
    co_teacher_id8,
    co_teacher_id9,
    co_teacher_id10,
    calendar_id,
    grade_scale_id,
    standards_grade_scale_id,
    grade_posting_scheme_id,
    bell_schedule_id,
    team_id,
    location_id,
    title,
    short_name,
    custom_title,
    room,
    display_room,
    days,
    rotation_days,
    grade_levels,
    course_weight,
    mp,
    course_history_term,
    total_seats,
    filled_seats,
    sped_seats,
    ell_seats,
    credits,
    availability,
    gender_restriction,
    house_restriction,
    does_attendance,
    does_grades,
    does_gpa,
    active,
    imported,
    uuid,
    created_at,
    updated_at,

    custom_2 as fefp_number,
    custom_4 as scheduling_method,
    custom_6 as facility_type,
    custom_25 as reading_intervention_component,
    custom_22 as basic_skills_exam,
    custom_33 as location_of_student,
    custom_34 as eoc_exam_term,
    custom_5 as highly_qualified,
    custom_28 as cert_licensure_qual_status,
    custom_3 as class_minutes_weekly,
from {{ source("focus", "course_periods") }}
