select
    id,
    student_id,
    school_date,
    period_id,
    course_period_id,
    marking_period_id,
    attendance_code,
    attendance_teacher_code,
    attendance_reason,
    hourly_attendance,
    hours,
    breaks,
    break_times,
    admin,
    admin_user_id,
    mass_assigned,
    notified,
    notified_callouts,
    last_updated_user,
    last_updated_date,
    imported,
    uuid,
    created_at,
    updated_at,

    cast(break_minutes as numeric) as break_minutes,
    cast(break_out_time as numeric) as break_out_time,
    cast(minutes_absent as numeric) as minutes_absent,
    cast(minutes_present as numeric) as minutes_present,
from {{ source("focus", "attendance_period") }}
