select
    id,
    parent_id,
    syear,
    school_id,
    district_id,
    title,
    short_name,
    sort_order,
    rollover_id,
    cte_import,
    cpalms,
    guid,
    created_at,
    updated_at,
from {{ source("focus", "standard_categories_2") }}
