select
    id,
    syear,
    school_id,
    title,
    scale_id,
    credits,
    description,
    is_incomplete,
    exclude_grades,
    uuid,
    created_at,
    updated_at,

    cast(default_breakoff as numeric) as default_breakoff,
    cast(gpa_averaging_cutoff as numeric) as gpa_averaging_cutoff,
    cast(gpa_averaging_points as numeric) as gpa_averaging_points,
    cast(gpa_value as numeric) as gpa_value,
    cast(sort_order as numeric) as sort_order,
    cast(weighted_gpa_value as numeric) as weighted_gpa_value,
from {{ source("focus", "report_card_grades") }}
