select
    staff_id,
    profile_id,
    parent_id,
    rollover_id,
    erp_profile_id,
    university_id,
    current_school_id,
    current_district_id,
    district_id,
    syear,
    username,
    profile,
    title,
    ein,
    gender,
    first_name,
    middle_name,
    last_name,
    name_suffix,
    homeroom,
    erp_display_name,
    imported,
    custom_100000001 as e_mail_address,
    custom_200000001 as staff_number_identifier_local,
    custom_100000002 as phone_number,
    custom_200000002 as experience_length_years,
    custom_319000004 as active,
    custom_l801 as w4_allowances_under_17,
    custom_l802 as f_3_claim_dependent_and_other,
    custom_l790 as profile_on_non_production_sites,
    custom_2 as education,
    uuid,
    last_login,
    last_change,
    last_updated_date,
    created_at,
    updated_at,
from {{ source("focus", "users") }}
where deleted is null
