select
    id,
    district_id,
    title,
    short_name,
    data_type,
    summary_type,
    select_options,
    transcript,
    created_at,
    updated_at,

    cast(max_score as numeric) as max_score,
    cast(max_score1 as numeric) as max_score1,
    cast(max_score2 as numeric) as max_score2,
    cast(max_score3 as numeric) as max_score3,
    cast(max_score4 as numeric) as max_score4,
    cast(min_score as numeric) as min_score,
    cast(min_score1 as numeric) as min_score1,
    cast(min_score2 as numeric) as min_score2,
    cast(min_score3 as numeric) as min_score3,
    cast(min_score4 as numeric) as min_score4,
    cast(sort_order as numeric) as sort_order,
from {{ source("focus", "test_history_score_types") }}
