select
    id,
    title,
    syear,
    district_id,
    staff_id,
    schools,
    global_course,
    enabled,
    rollover_id,
    force_weighting,
    add_category,
    modify_category,
    modify_category_title,
    add_assignment,
    modify_assignment,
    add_standard,
    modify_standard,
    created,
    modified,
    created_at,
    updated_at,

    cast(drop_lowest_grade as numeric) as drop_lowest_grade,
from {{ source("focus", "gradebook_templates") }}
