select
    assignment_id,
    assignment_type_id,
    title,
    description,
    benchmarks,
    questions,
    parent_id,
    prerequisite_assignment,
    template_id,
    template_assignment_id,
    rollover_id,
    copied_from_id,
    rubric_id,
    web_page_id,
    external_api_id,
    external_api_uuid,
    learnosity_activity_id,
    examspark_exam_id,
    apex_assessment_id,
    allow_student_upload,
    no_late_turnin,
    hide_from_excluded,
    exclude_from_average,
    accessibility,
    transfer,
    allow_google_drive,
    allow_onedrive,
    uuid,
    last_updated_date,
    score_release_timestamp,
    created_at,
    updated_at,

    cast(last_updated_user as numeric) as last_updated_user,
    cast(points as numeric) as points,
from {{ source("focus", "gradebook_assignments") }}
