select
    marking_period_id,
    parent_id,
    rollover_id,
    school_id,
    syear,
    title,
    short_name,
    type,
    tuition_hours,
    year_id,
    semester_id,
    quarter_id,
    progress_period_id,
    start_date,
    end_date,
    post_start_date,
    post_end_date,
    stand_post_start_date,
    stand_post_end_date,
    grade12_post_start_date,
    grade12_post_end_date,
    registration_start_date,
    registration_end_date,
    exclude_from_api,
    exclude_from_schedule,
    uuid,
    created_at,
    updated_at,

    cast(sort_order as numeric) as sort_order,
    cast(year_fraction as numeric) as year_fraction,

    if(short_name in ('Q1', 'Q2'), 'S1', 'S2') as quarter_semester,

    current_date('{{ var("local_timezone") }}')
    between start_date and end_date as is_within_dates,
from {{ source("focus", "marking_periods") }}
