select
    id,
    school_id,
    next_grade_id,
    rollover_id,
    min_year,
    max_year,
    district_id,
    short_name,
    title,
    min_syear,
    max_syear,
    rollover,
    uuid,
    zoning,
    choice_short_name,
    pk,
    created_at,
    updated_at,

    cast(sort_order as numeric) as sort_order,
from {{ source("focus", "school_gradelevels") }}
