select
    id,
    assessment_id,
    assignment_id,
    student_id,
    attempt_id,
    config_id,
    form_id,
    syear,
    attempts,
    completed,
    completed_at,
    elapsed_time,
    last_autosave_at,
    graded,
    passed,
    released,
    released_at,
    released_by,
    discarded,
    discarded_at,
    discarded_by,
    excused,
    pending_rescore,
    score_locked,
    score_locked_at,
    similar_responses,
    is_observational,
    manually_seeded,
    seed_override,
    import_legacy_id,
    import_source,
    created_at,
    updated_at,

    cast(score_actual as numeric) as score_actual,
    cast(score_max as numeric) as score_max,
    cast(percent as numeric) as percent_score,
from {{ source("focus", "apex_sessions") }}
