select
    id,
    calendar_id,
    school_id,
    syear,
    school_date,
    minutes,
    block,
    fte_period,
    bell_schedule_id,
    imported,
    uuid,
    created_at,
    updated_at,
from {{ source("focus", "attendance_calendar") }}
