select
    id,
    school_id,
    category_id,
    title,
    short_name,
    type,
    comments,
    imported,
    display_room,
    room_description,
    square_footage,
    max_syear,
    min_syear,
    uuid,
    created_at,
    updated_at,

    cast(seats as numeric) as seats,
from {{ source("focus", "resources") }}
