select
    student_id,
    profile_id,
    university_id,
    district_id,
    first_name,
    middle_name,
    last_name,
    name_suffix,
    external_api_uuid,
    protected_student,
    incomplete,
    last_updated_date,
    last_change,
    uuid,
    created_at,
    updated_at,

    custom_53 as local_student_id,
    custom_100000101 as race_asian,
    custom_200000000 as sex,
    custom_100000104 as race_white,
    custom_100000105 as ethnicity_hispanic_or_latino,
    custom_100000100 as race_american_indian_or_alaska_native,
    custom_100000103 as race_native_hawaiian_or_other_pacific_islander,
    custom_200000005 as `language`,
    custom_100000102 as race_black_or_african_american,
    custom_837 as residence_county,
    custom_200000004 as birthdate,
    custom_861 as florida_alias,
    custom_159 as florida_student_number,
    custom_l1482 as powerschool_id,
    custom_200000012 as student_e_mail_address,
    custom_l1483 as disis_id,
    custom_200000225 as fleid_verified,
    custom_200000224 as florida_education_identifier,
    custom_546 as primary_language_spoken_in_home,
    custom_71 as free_reduced_meals_program,
    custom_65 as native_language_student,
    custom_820 as homeless_student_pk_12,
    custom_863 as idea_educational_environment,
    custom_626 as english_language_learner_pk_12,
    custom_942 as pe_waiver,
    custom_760 as graduation_option,
    custom_829 as doe_test_accommodations_access_for_ells,
    custom_698 as ese_fefp_code,
    custom_999 as gifted_eligibility,
    custom_640 as prekindergarten_program_participation,
    custom_728 as country_of_birth,
    custom_1429 as year_entered_ninth_grade,
    custom_1087 as florida_first_start_program_participant,
    custom_1086 as even_start_family_literacy_program_participant,
    custom_1050 as multi_birth_for_faster,
    custom_128 as resident_status,
    custom_132 as screening_for_hearing_grade_kg,
    custom_134 as screening_for_vision_problems,
    custom_200000207 as birth_date_verification,
    custom_200000255 as aice_diploma,
    custom_200000297 as diploma_florida_seal_of_fine_arts_designation,
    custom_2012197244 as residency_for_tuition_purposes,
    custom_202 as bright_futures_volunteer_service_requirement_met,
    custom_216 as national_merit_scholar,
    custom_217 as national_achievement_scholar,
    custom_245 as national_hispanic_scholar,
    custom_264 as aice_program_participant,
    custom_266 as ib_diploma,
    custom_267 as college_ready_diploma,
    custom_268 as differentiated_diploma,
    custom_699 as additional_school_year,
    custom_789 as migrant_status_term,
    custom_660 as basis_of_entry,
    custom_661 as first_basis_of_exit,
    custom_200000001 as single_ethnicity,
from {{ source("focus", "students") }}
where deleted is null
