select
    id,
    title,
    source_class,
    form,
    color,
    icon,
    sort_order,
    inactive,
    legacy_id,
    form_template,
    default_profiles_view,
    default_profiles_edit,
    sis,
    erp,
    completion_email_recipient,
    email_validation,
    header_background,
    header_image_id,
    district_id,
    system,
    alias,
    settings,
    application_editor_generated,
    virtual,
    short_name,
    archived,
    created_at,
    updated_at,
    focus_manage as is_focus_manage,
    state as is_state,
from {{ source("focus", "custom_field_categories") }}
where deleted is null
