select
    id,
    test_id,
    district_id,
    fas_section_id,
    title,
    short_name,
    subject_code,
    subject,
    score_types,
    transcript,
    min_scale_score,
    min_score,
    max_syear,
    graph_score,
    uuid,
    created_at,
    updated_at,

    cast(sort_order as numeric) as sort_order,
from {{ source("focus", "test_history_parts") }}
