select
    id,
    district_element_id,
    paec_school_nurse_profile,
    logo_width,
    logo_height,
    code,
    title,
    short_name,
    address,
    city,
    state,
    district_element,
    active,
    logo,
    custom_fields,
    custom_l1277 as district_email_domain,
    paec_transcript_message,
    paec_transcript_logo,
    paec_transcript_signature,
    uuid,
    seperate_site,
    created_at,
    updated_at,
from {{ source("focus", "districts") }}
