select
    id,
    syear,
    school_id,
    course_id,
    course_weight,
    rollover_id,
    student_requestable,
    student_scheduleable,
    cw_checkbox_setting_1,
    cw_checkbox_setting_2,
    cw_checkbox_setting_3,
    cw_checkbox_setting_4,
    cw_checkbox_setting_5,
    does_gpa_1,
    does_gpa_2,
    does_gpa_3,
    does_gpa_4,
    does_gpa_5,
    teacher_approve,
    imported,
    created_at,
    updated_at,

    cast(credits as numeric) as credits,
    cast(gpa_multiplier as numeric) as gpa_multiplier,
    cast(year_fraction as numeric) as year_fraction,
from {{ source("focus", "course_weights") }}
