select
    id,
    district_id,
    state_school_id,
    erp_facility_id,
    min_syear,
    max_syear,
    title,
    college_board_attending_institution_code,
    virtual,
    custom_327 as school_number,
    custom_100000001 as district_number,
    custom_100000004 as school_level,
    custom_200000321 as state,
    custom_200000326 as school_type,
    custom_50000002 as technical_center,
    custom_319000052,
    custom_200000200 as exclude_from_state_reporting,
    paec_gpa_for_transcript,
    paec_rank_for_transcript,
    uuid,
    created_at,
    updated_at,

    cast(act_organization_code as numeric) as act_organization_code,
    cast(latitude as numeric) as latitude,
    cast(longitude as numeric) as longitude,
    cast(sort_order as numeric) as sort_order,
from {{ source("focus", "schools") }}
where deleted is null
