select
    id,
    school_id,
    rollover_id,
    district_id,
    min_syear,
    max_syear,
    title,
    short_name,
    default_category,
    weight_by_credits,
    cte,
    hide_merit,
    hide_biliteracy,
    hide_scholar,
    hide_header,
    hide_industry,
    hide_finearts,
    hide_ag,
    schools,
    uuid,
    created_at,
    updated_at,

    cast(sort_order as numeric) as sort_order,
from {{ source("focus", "grad_subject_programs") }}
