select
    id,
    source_class,
    type,
    title,
    alias,
    column_name,
    description,
    default_value,
    fallback_value,
    option_query,
    computed_query,
    max_length,
    required,
    inactive,
    encrypted,
    district_id,
    uuid,
    created_at,
    updated_at,
    json as is_json,
    focus_manage as is_focus_manage,
    translate as is_translate,
    column_adopted as is_column_adopted,
from {{ source("focus", "custom_fields") }}
where deleted is null
