select
    id,
    field_id,
    column_name,
    type,
    title,
    description,
    default_value,
    fallback_value,
    max_length,
    total,
    primary_sort,
    secondary_sort,
    option_query,
    computed_query,
    sort_order,
    new_record,
    rich_text,
    fixed,
    required,
    inactive,
    system,
    imported,
    suggestion_query,
    restricted,
    help_url,
    academic_record_category,
    file_retention,
    min_width,
    max_width,
    alias,
    settings,
    notes,
    created_at,
    updated_at,
    translate as is_translate,
    visible_on_summary as is_visible_on_summary,
from {{ source("focus", "custom_field_log_columns") }}
where deleted is null
