select
    course_id,
    subject_id,
    syear,
    district_id,
    rollover_id,
    short_name,
    title,
    long_title,
    transcript_title,
    start_date,
    end_date,
    date_added,
    last_modified_date,
    grad_subject_area,
    grad_subject_area2,
    grad_subject_area3,
    subject_area,
    edfi_core_subject,
    grading_scale,
    standards_grading_scale,
    grade_posting_scheme,
    course_history_term,
    course_level,
    course_length,
    affects_gpa,
    credits,
    total_credit,
    credit_hours,
    course_hours,
    fee,
    low_grade,
    high_grade,
    gender_restriction,
    status,
    ib,
    ap,
    ell,
    certification_requirements,
    course_description,
    allow_repeat,
    homeroom,
    edfi_course_level_characteristic,
    iet_program_number,
    imported,
    uuid,
    created_at,
    updated_at,

    custom_field_3 as core_for_class_size,
    custom_field_4 as core_for_highly_qualified,
    custom_field_11,
    custom_field_5 as fefp,
    custom_field_2 as aice,
    custom_field_13 as dual_enrollment_indicator,
    custom_field_6 as course_flag_1,
    custom_field_14 as eoc_exam_required,
    custom_field_10 as vocational_program_number,
    custom_field_1 as exclude_from_fte,
from {{ source("focus", "master_courses") }}
