select
    id,
    student_id,
    school_date,
    syear,
    marking_period_id,
    daily_code,
    daily_pres_code,
    time_in,
    time_out,
    comment,
    note_approved,
    note_message,
    notified_callouts,
    admin_user_id,
    last_updated_user,
    last_updated_date,
    imported,
    uuid,
    created_at,
    updated_at,

    cast(minutes_absent as numeric) as minutes_absent,
    cast(minutes_present as numeric) as minutes_present,
    cast(state_value as numeric) as state_value,
from {{ source("focus", "attendance_day") }}
