select
    _id as school_id,
    `name`,
    district,
    created,
    lastmodified,
    archivedat,
    abbreviation,
    `address`,
    city,
    gradespan,
    highgrade,
    internalid,
    lowgrade,
    phone,
    principal,
    region,
    `state`,
    zip,
    admins,
    assistantadmins,
    noninstructionaladmins,
    observationgroups,
from {{ source("schoolmint_grow", "src_schoolmint_grow__schools") }}
where _dagster_partition_key = 'f'
