"""Regenerate docs/reference/automations.md from live Dagster definitions.

Reads schedules and sensors from every code location's Definitions object
and writes a structured Markdown catalog.

Prerequisites:
    uv sync
    uv run scripts/dbt-manifest.py  # prepare dbt manifests for all projects

Usage:
    uv run scripts/gen-automations-doc.py
"""

import logging
import warnings
from importlib import import_module
from pathlib import Path

logging.disable(logging.CRITICAL)
warnings.filterwarnings("ignore")

OUTPUT = Path("docs/reference/automations.md")

CODE_LOCATIONS = [
    ("kipptaf", "Network-wide code location covering CMO-level integrations."),
    ("kippnewark", ""),
    ("kippcamden", ""),
    ("kippmiami", ""),
    ("kipppaterson", ""),
]


def _cron_display(cron: str | list[str]) -> str:
    if isinstance(cron, list):
        return " + ".join(f"`{c}`" for c in cron)
    return f"`{cron}`"


def _interval_display(seconds: int | None) -> str:
    if seconds is None:
        return "—"
    minutes = seconds // 60
    return f"{minutes} min"


def _row(*cells: str) -> str:
    return "| " + " | ".join(cells) + " |"


def generate() -> None:
    lines = [
        "# Automations Catalog",
        "",
        "All schedules and sensors across every Dagster code location.",
        "All cron expressions use the `America/New_York` timezone.",
        "",
        "<!-- Generated by scripts/gen-automations-doc.py — do not edit manually -->",
        "",
    ]

    for code_location, description in CODE_LOCATIONS:
        try:
            mod = import_module(f"teamster.code_locations.{code_location}.definitions")
            defs = mod.defs
        except Exception as e:
            print(f"⚠  Skipping {code_location}: {e}")
            continue

        schedules = sorted(defs.schedules or [], key=lambda s: s.name)
        sensors = sorted(defs.sensors or [], key=lambda s: s.name)

        lines += [f"## {code_location}", ""]
        if description:
            lines += [description, ""]

        if schedules:
            lines += [
                "### Schedules",
                "",
                _row("Schedule", "Cron", "Description"),
                _row("---", "---", "---"),
            ]
            for sched in schedules:
                desc = getattr(sched, "description", None) or "—"
                lines.append(
                    _row(f"`{sched.name}`", _cron_display(sched.cron_schedule), desc)
                )
            lines.append("")

        if sensors:
            lines += [
                "### Sensors",
                "",
                _row("Sensor", "Min interval", "Description"),
                _row("---", "---", "---"),
            ]
            for sensor in sensors:
                interval = _interval_display(sensor.minimum_interval_seconds)
                desc = getattr(sensor, "description", None) or "—"
                lines.append(_row(f"`{sensor.name}`", interval, desc))
            lines.append("")

        lines += ["---", ""]

    # Remove trailing separator
    while lines and lines[-1] in ("---", ""):
        lines.pop()

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"✓ Written {OUTPUT}")


if __name__ == "__main__":
    generate()
