"""Regenerate docs/reference/automations.md from live Dagster definitions.

Reads schedules and sensors from every code location's Definitions object
and writes a structured Markdown catalog.

Prerequisites:
    uv sync
    uv run scripts/dbt-manifest.py  # prepare dbt manifests for all projects

Usage:
    uv run scripts/gen-automations-doc.py
"""

import logging
import warnings
from collections import defaultdict
from importlib import import_module
from pathlib import Path

from cron_descriptor import Options, get_description

# Suppress Dagster/dbt startup noise so script output stays readable
logging.disable(logging.CRITICAL)
warnings.filterwarnings("ignore")

OUTPUT = Path("docs/reference/automations.md")

CODE_LOCATIONS = [
    ("kipptaf", "Network-wide code location covering CMO-level integrations."),
    ("kippnewark", ""),
    ("kippcamden", ""),
    ("kippmiami", ""),
    ("kipppaterson", ""),
]

_CRON_ALIASES = {
    "@hourly": "0 * * * *",
    "@daily": "0 0 * * *",
    "@midnight": "0 0 * * *",
    "@weekly": "0 0 * * 0",
    "@monthly": "0 0 1 * *",
    "@yearly": "0 0 1 1 *",
    "@annually": "0 0 1 1 *",
}

_DESCRIPTOR_OPTIONS = Options()
_DESCRIPTOR_OPTIONS.use_24hour_time_format = False

_EXTRACT_KINDS = {"task", "tableau"}


def _describe_cron(cron: str) -> str:
    expanded = _CRON_ALIASES.get(cron, cron)
    return get_description(expanded, _DESCRIPTOR_OPTIONS)


def _cron_display(cron: str | list[str]) -> str:
    if isinstance(cron, list):
        return "; ".join(_describe_cron(c) for c in cron)
    return _describe_cron(cron)


def _interval_display(seconds: int | None) -> str:
    if seconds is None:
        return "—"
    if seconds < 60:
        return f"{seconds} sec"
    return f"{seconds // 60} min"


def _collapse_siblings(parent: str, leaves: list[str]) -> list[str]:
    """Collapse repository_* siblings into a single wildcard entry."""
    if sum(1 for leaf in leaves if leaf.startswith("repository_")) < 2:
        return [f"{parent}/{leaf}" if parent else leaf for leaf in leaves]

    result: list[str] = []
    repo_added = False
    for leaf in leaves:
        if leaf.startswith("repository_"):
            if not repo_added:
                result.append(f"{parent}/repository_*" if parent else "repository_*")
                repo_added = True
        else:
            result.append(f"{parent}/{leaf}" if parent else leaf)
    return result


def _format_paths(paths: list[str]) -> str:
    """Format a list of asset paths with repository_* collapsing and common prefix stripping."""
    if not paths:
        return ""

    groups: dict[str, list[str]] = defaultdict(list)
    for path in paths:
        parent, _, leaf = path.rpartition("/")
        groups[parent].append(leaf)

    collapsed: list[str] = []
    for parent, leaves in sorted(groups.items()):
        collapsed.extend(_collapse_siblings(parent, sorted(leaves)))

    if len(collapsed) == 1:
        _, _, leaf = collapsed[0].rpartition("/")
        if leaf:
            collapsed = [leaf]
    else:
        all_parts = [p.rstrip("*").rstrip("/").split("/") for p in collapsed]
        common: list[str] = []
        for segments in zip(*all_parts, strict=False):
            if len(set(segments)) == 1:
                common.append(segments[0])
            else:
                break
        if common:
            strip = len("/".join(common)) + 1
            collapsed = [p[strip:] for p in collapsed]

    return ", ".join(f"`{p}`" for p in collapsed)


def _resolve_assets(jobs: list, asset_graph, code_location: str) -> tuple[str, str]:
    """Resolve asset selections and return (regular_assets, extract_assets) display strings."""
    all_keys: set = set()
    for job in jobs:
        selection = getattr(job, "selection", None)
        if selection is None:
            continue
        try:
            all_keys |= selection.resolve(asset_graph)
        except Exception:  # nosec B110
            pass

    if not all_keys:
        return "—", ""

    def _path(k) -> str:
        return "/".join(k.path[1:]) if k.path[0] == code_location else "/".join(k.path)

    regular = sorted(
        _path(k) for k in all_keys if not asset_graph.get(k).kinds & _EXTRACT_KINDS
    )
    extracts = sorted(
        _path(k).removeprefix("extracts/")
        for k in all_keys
        if asset_graph.get(k).kinds & _EXTRACT_KINDS
    )

    return _format_paths(regular) or "—", _format_paths(extracts)


def _row(*cells: str) -> str:
    return "| " + " | ".join(cells) + " |"


def generate() -> None:
    lines = [
        "# Automations Catalog",
        "",
        "All schedules and sensors across every Dagster code location.",
        "All times use the `America/New_York` timezone.",
        "",
        "<!-- Generated by scripts/gen-automations-doc.py — do not edit manually -->",
        "",
    ]

    for code_location, description in CODE_LOCATIONS:
        try:
            mod = import_module(f"teamster.code_locations.{code_location}.definitions")
            defs = mod.defs
        except Exception as e:
            print(f"⚠  Skipping {code_location}: {e}")
            continue

        schedules = sorted(defs.schedules or [], key=lambda s: s.name)
        sensors = [
            s
            for s in sorted(defs.sensors or [], key=lambda s: s.name)
            if not s.name.endswith("__automation_condition_sensor")
        ]

        asset_graph = defs.resolve_asset_graph()

        lines += [f"## {code_location}", ""]
        if description:
            lines += [description, ""]

        extract_entries: list[tuple[str, str, str]] = []  # (name, runs, assets)
        sched_rows: list[tuple[str, str, str]] = []
        sensor_rows: list[tuple[str, str, str]] = []

        for sched in schedules:
            runs = _cron_display(sched.cron_schedule)
            assets, extracts = _resolve_assets([sched.job], asset_graph, code_location)
            if extracts:
                extract_entries.append((sched.name, runs, extracts))
            if assets != "—":
                sched_rows.append((sched.name, runs, assets))

        for sensor in sensors:
            interval = _interval_display(sensor.minimum_interval_seconds)
            try:
                jobs = sensor.jobs
            except (
                Exception
            ):  # sensor.jobs raises DagsterInvalidDefinitionError when no jobs attached
                jobs = []
            assets, extracts = _resolve_assets(jobs, asset_graph, code_location)
            if extracts:
                extract_entries.append((sensor.name, interval, extracts))
            if assets != "—":
                sensor_rows.append((sensor.name, interval, assets))

        if sched_rows:
            lines += [
                "### Schedules",
                "",
                _row("Schedule", "Runs", "Assets"),
                _row("---", "---", "---"),
            ]
            for name, runs, assets in sched_rows:
                lines.append(_row(f"`{name}`", runs, assets))
            lines.append("")

        if sensor_rows:
            lines += [
                "### Sensors",
                "",
                _row("Sensor", "Min interval", "Assets"),
                _row("---", "---", "---"),
            ]
            for name, interval, assets in sensor_rows:
                lines.append(_row(f"`{name}`", interval, assets))
            lines.append("")

        if extract_entries:
            lines += [
                "### Extracts",
                "",
                _row("Automation", "Runs", "Assets"),
                _row("---", "---", "---"),
            ]
            for name, runs, extracts in sorted(extract_entries):
                lines.append(_row(f"`{name}`", runs, extracts))
            lines.append("")

        lines += ["---", ""]

    # Remove trailing separator
    while lines and lines[-1] in ("---", ""):
        lines.pop()

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✓ Written {OUTPUT}")


if __name__ == "__main__":
    generate()
