FAST_FIELDS = [
    {
        "name": "date_taken",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {
        "name": "english_language_learner_ell_status",
        "type": ["null", "string"],
        "default": None,
    },
    {"name": "enrolled_district", "type": ["null", "string"], "default": None},
    {"name": "enrolled_grade", "type": ["null", "long"], "default": None},
    {"name": "enrolled_school", "type": ["null", "string"], "default": None},
    {"name": "ethnicity", "type": ["null", "string"], "default": None},
    {"name": "gender_k_12", "type": ["null", "string"], "default": None},
    {"name": "gender_postsecondary_only", "type": ["null", "string"], "default": None},
    {"name": "local_id", "type": ["null", "string"], "default": None},
    {"name": "primary_exceptionality", "type": ["null", "string"], "default": None},
    {"name": "section_504", "type": ["null", "string"], "default": None},
    {
        "name": "student_dob",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {"name": "student_id", "type": ["null", "string"], "default": None},
    {"name": "student_name", "type": ["null", "string"], "default": None},
    {
        "name": "test_completion_date",
        "type": ["null", "string"],
        "logicalType": "date",
        "default": None,
    },
    {"name": "test_oppnumber", "type": ["null", "string"], "default": None},
    {"name": "test_reason", "type": ["null", "string"], "default": None},
    {"name": "testing_location", "type": ["null", "string"], "default": None},
    {"name": "unnamed_23", "type": ["null", "string"], "default": None},
    {"name": "unnamed_24", "type": ["null", "string"], "default": None},
    {"name": "unnamed_25", "type": ["null", "string"], "default": None},
    {
        "name": "1_reading_prose_and_poetry_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "2_reading_informational_text_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "3_reading_across_genres_vocabulary_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "1_number_sense_and_additive_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "2_number_sense_and_multiplicative_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "3_fractional_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "4_geometric_reasoning_measurement_and_data_analysis_and_probability_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "1_number_sense_and_operations_with_whole_numbers_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "2_number_sense_and_operations_with_fractions_and_decimals_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "3_geometric_reasoning_measurement_and_data_analysis_and_probability_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "3_algebraic_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "1_number_sense_and_operations_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "2_algebraic_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "3_geometric_reasoning_data_analysis_and_probability_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "1_number_sense_and_operations_and_algebraic_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "2_proportional_reasoning_and_relationships_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "3_geometric_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "4_data_analysis_and_probability_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "1_number_sense_and_operations_and_probability_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "3_linear_relationships_data_analysis_and_functions_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "4_geometric_reasoning_performance",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_3_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_3_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_3_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_3_mathematics_scale_score",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_3_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_3_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_4_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_4_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_4_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_4_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_4_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_4_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_5_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_5_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_5_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_5_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_5_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_5_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_6_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_6_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_6_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_6_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_6_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_6_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_7_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_7_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_7_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_7_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_7_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_7_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_8_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_8_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_8_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_8_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "fast_grade_8_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "fast_grade_8_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_3_fast_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_3_fast_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_3_fast_ela_reading_scale_score",
        "type": ["null", "long", "string"],
        "default": None,
    },
    {
        "name": "grade_3_fast_mathematics_scale_score",
        "type": ["null", "long", "string"],
        "default": None,
    },
    {
        "name": "grade_3_fast_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_3_fast_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_4_fast_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_4_fast_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_4_fast_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "grade_4_fast_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "grade_4_fast_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_4_fast_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_5_fast_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_5_fast_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_5_fast_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "grade_5_fast_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "grade_5_fast_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_5_fast_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_6_fast_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_6_fast_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_6_fast_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "grade_6_fast_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "grade_6_fast_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_6_fast_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_7_fast_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_7_fast_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_7_fast_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "grade_7_fast_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "grade_7_fast_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_7_fast_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_8_fast_ela_reading_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_8_fast_ela_reading_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_8_fast_ela_reading_scale_score",
        "type": ["null", "long"],
        "default": None,
    },
    {
        "name": "grade_8_fast_mathematics_scale_score",
        "type": ["null", "string", "long"],
        "default": None,
    },
    {
        "name": "grade_8_fast_mathematics_achievement_level",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "grade_8_fast_mathematics_percentile_rank",
        "type": ["null", "string"],
        "default": None,
    },
]

FSA_FIELDS = [
    {"name": "schoolyear", "type": ["null", "long"], "default": None},
    {"name": "testname", "type": ["null", "string"], "default": None},
    {"name": "dis", "type": ["null", "long"], "default": None},
    {"name": "disname", "type": ["null", "string"], "default": None},
    {"name": "sch", "type": ["null", "long"], "default": None},
    {"name": "schname", "type": ["null", "string"], "default": None},
    {"name": "tgrade", "type": ["null", "long"], "default": None},
    {"name": "lastname", "type": ["null", "string"], "default": None},
    {"name": "firstname", "type": ["null", "string"], "default": None},
    {"name": "mi", "type": ["null", "string"], "default": None},
    {"name": "fleid", "type": ["null", "string"], "default": None},
    {"name": "scalescore", "type": ["null", "long", "string"], "default": None},
    {"name": "pass", "type": ["null", "string"], "default": None},
    {"name": "scoreflag_r", "type": ["null", "long", "string"], "default": None},
    {"name": "scoreflag_w", "type": ["null", "string"], "default": None},
    {"name": "scoreflag", "type": ["null", "long"], "default": None},
    {"name": "rptstatus", "type": ["null", "string"], "default": None},
    {"name": "conditioncode", "type": ["null", "string"], "default": None},
    {"name": "performancelevel", "type": ["null", "long", "string"], "default": None},
    {"name": "earn1_ptpos1", "type": ["null", "string"], "default": None},
    {"name": "earn2_ptpos2", "type": ["null", "string"], "default": None},
    {"name": "earn3_ptpos3", "type": ["null", "string"], "default": None},
    {"name": "earn4_ptpos4", "type": ["null", "string"], "default": None},
    {"name": "earn5_ptpos5", "type": ["null", "string"], "default": None},
    {"name": "earn_wd1_ptpos_wd1", "type": ["null", "string"], "default": None},
    {"name": "earn_wd2_ptpos_wd2", "type": ["null", "string"], "default": None},
    {"name": "earn_wd3_ptpos_wd3", "type": ["null", "string"], "default": None},
]

ASSET_FIELDS = {
    "fast": FAST_FIELDS,
    "fsa": FSA_FIELDS,
}
