USER_PERSON_FIELDS = [
    {"name": "badPwdCount", "type": ["null", "int"], "default": None},
    {"name": "c", "type": ["null", "string"], "default": None},
    {"name": "company", "type": ["null", "string"], "default": None},
    {"name": "department", "type": ["null", "string"], "default": None},
    {"name": "description", "type": ["null", "string"], "default": None},
    {"name": "displayName", "type": ["null", "string"], "default": None},
    {"name": "division", "type": ["null", "string"], "default": None},
    {"name": "dn", "type": ["null", "string"], "default": None},
    {"name": "employeeId", "type": ["null", "string"], "default": None},
    {"name": "employeeNumber", "type": ["null", "int"], "default": None},
    {"name": "facsimileTelephoneNumber", "type": ["null", "string"], "default": None},
    {"name": "givenName", "type": ["null", "string"], "default": None},
    {"name": "homeDirectory", "type": ["null", "string"], "default": None},
    {"name": "homeDrive", "type": ["null", "string"], "default": None},
    {"name": "homeMDB", "type": ["null", "string"], "default": None},
    {"name": "homePhone", "type": ["null", "string"], "default": None},
    {"name": "info", "type": ["null", "string"], "default": None},
    {"name": "initials", "type": ["null", "string"], "default": None},
    {"name": "ipPhone", "type": ["null", "string"], "default": None},
    {"name": "l", "type": ["null", "string"], "default": None},
    {"name": "lockoutTime", "type": ["null", "bool"], "default": None},
    {"name": "mail", "type": ["null", "string"], "default": None},
    {"name": "mailNickname", "type": ["null", "string"], "default": None},
    {"name": "manager", "type": ["null", "string"], "default": None},
    {"name": "middleName", "type": ["null", "string"], "default": None},
    {"name": "mobile", "type": ["null", "string"], "default": None},
    {"name": "msExchHideFromAddressLists", "type": ["null", "bool"], "default": None},
    {"name": "msExchMailboxGUID", "type": ["null", "string"], "default": None},
    {"name": "msExchMailboxTemplateLink", "type": ["null", "string"], "default": None},
    {"name": "msExchRBACPolicyLink", "type": ["null", "string"], "default": None},
    {"name": "o", "type": ["null", "string"], "default": None},
    {"name": "objectGuid", "type": ["null", "string"], "default": None},
    {"name": "objectSid", "type": ["null", "string"], "default": None},
    {"name": "pager", "type": ["null", "string"], "default": None},
    {"name": "physicalDeliveryOfficeName", "type": ["null", "string"], "default": None},
    {"name": "postalCode", "type": ["null", "string"], "default": None},
    {"name": "postOfficeBox", "type": ["null", "string"], "default": None},
    {"name": "primaryGroupID", "type": ["null", "string"], "default": None},
    {"name": "profilePath", "type": ["null", "string"], "default": None},
    {"name": "proxyAddresses", "type": ["null", "string"], "default": None},
    {"name": "pwdLastSet", "type": ["null", "bool"], "default": None},
    {"name": "sAMAccountName", "type": ["null", "string"], "default": None},
    {"name": "scriptPath", "type": ["null", "string"], "default": None},
    {"name": "sn", "type": ["null", "string"], "default": None},
    {"name": "st", "type": ["null", "string"], "default": None},
    {"name": "streetAddress", "type": ["null", "string"], "default": None},
    {"name": "telephoneNumber", "type": ["null", "string"], "default": None},
    {"name": "title", "type": ["null", "string"], "default": None},
    {"name": "unicodePwd", "type": ["null", "string"], "default": None},
    {"name": "userAccountControl", "type": ["null", "bool"], "default": None},
    {"name": "userAccountControl", "type": ["null", "bool"], "default": None},
    {"name": "userAccountControl", "type": ["null", "bool"], "default": None},
    {"name": "userAccountControl", "type": ["null", "bool"], "default": None},
    {"name": "userAccountControl", "type": ["null", "bool"], "default": None},
    {"name": "userAccountControl", "type": ["null", "bool"], "default": None},
    {"name": "userAccountControl", "type": ["null", "bool"], "default": None},
    {"name": "userPrincipalName", "type": ["null", "string"], "default": None},
    {"name": "wWWHomePage", "type": ["null", "string"], "default": None},
    {
        "name": "msExchMobileMailboxPolicyLink",
        "type": ["null", "string"],
        "default": None,
    },
    # {"name": "accountExpires", "type": ["null", "\DateTime|false"], "default": None},
    # {"name": "lockoutTime", "type": ["null", "\DateTime|false"], "default": None},
    # {"name": "pwdLastSet", "type": ["null", "\DateTime"], "default": None},
    # {"name": "whenChanged", "type": ["null", "\DateTime"], "default": None},
    # {"name": "whenCreated", "type": ["null", "\DateTime"], "default": None},
    # {"name": "memberOf", "type": ["null", "array"], "default": None},
    # {"name": "otherHomePhone", "type": ["null", "array"], "default": None},
    # {"name": "otherIpPhone", "type": ["null", "array"], "default": None},
    # {"name": "otherPager", "type": ["null", "array"], "default": None},
    # {"name": "otherTelephoneNumber", "type": ["null", "array"], "default": None},
    # {"name": "proxyAddresses", "type": ["null", "array"], "default": None},
    # {"name": "publicDelegates", "type": ["null", "array"], "default": None},
    # {"name": "servicePrincipalName", "type": ["null", "array"], "default": None},
    # {"name": "userWorkstations", "type": ["null", "array"], "default": None},
    # {
    #     "name": "otherFacsimileTelephoneNumber",
    #     "type": ["null", "array"],
    #     "default": None,
    # },
]

GROUP_FIELDS = [
    {"name": "cn", "type": ["null", "string"], "default": None},
    {"name": "description", "type": ["null", "string"], "default": None},
    {"name": "displayName", "type": ["null", "string"], "default": None},
    {"name": "dn", "type": ["null", "string"], "default": None},
    {"name": "groupType", "type": ["null", "bool"], "default": None},
    {"name": "groupType", "type": ["null", "bool"], "default": None},
    {"name": "groupType", "type": ["null", "bool"], "default": None},
    {"name": "groupType", "type": ["null", "bool"], "default": None},
    {"name": "groupType", "type": ["null", "bool"], "default": None},
    {"name": "groupType", "type": ["null", "bool"], "default": None},
    {"name": "info", "type": ["null", "string"], "default": None},
    {"name": "mail", "type": ["null", "string"], "default": None},
    {"name": "mailNickname", "type": ["null", "string"], "default": None},
    {"name": "managedBy", "type": ["null", "string"], "default": None},
    {"name": "msExchAddressBookFlags", "type": ["null", "int"], "default": None},
    {"name": "msExchHideFromAddressLists", "type": ["null", "bool"], "default": None},
    {"name": "msExchRequireAuthToSendTo", "type": ["null", "bool"], "default": None},
    {"name": "objectGuid", "type": ["null", "string"], "default": None},
    {"name": "objectSid", "type": ["null", "string"], "default": None},
    {"name": "proxyAddresses", "type": ["null", "string"], "default": None},
    {"name": "sAMAccountName", "type": ["null", "string"], "default": None},
    # {"name": "member", "type": ["null", "array"], "default": None},
    # {"name": "memberOf", "type": ["null", "array"], "default": None},
    # {"name": "proxyAddresses", "type": ["null", "array"], "default": None},
    # {"name": "whenChanged", "type": ["null", "\DateTime"], "default": None},
    # {"name": "whenCreated", "type": ["null", "\DateTime"], "default": None},
]
