select
    * except (
        attendance_type_code,
        bitmap,
        buildid,
        campusid,
        dcid,
        distuniqueid,
        exclude_ada,
        exclude_state_rpt_yn,
        excludefromclassrank,
        excludefromgpa,
        excludefromhonorroll,
        excludefromstoredgrades,
        grade_level,
        gradebooktype,
        gradescaleid,
        id,
        lastattupdate,
        maxcut,
        maxenrollment,
        no_of_students,
        noofterms,
        parent_section_id,
        pgversion,
        programid,
        rostermodser,
        schedulesectionid,
        schoolid,
        sortorder,
        teacher,
        termid,
        trackteacheratt,
        transaction_date,
        wheretaught,
        wheretaughtdistrict,
        whomodifiedid,
        comment
    ),

    comment as comment_value,

    cast(attendance_type_code as int) as attendance_type_code,
    cast(buildid as int) as buildid,
    cast(campusid as int) as campusid,
    cast(dcid as int) as dcid,
    cast(distuniqueid as int) as distuniqueid,
    cast(exclude_ada as int) as exclude_ada,
    cast(exclude_state_rpt_yn as int) as exclude_state_rpt_yn,
    cast(excludefromclassrank as int) as excludefromclassrank,
    cast(excludefromgpa as int) as excludefromgpa,
    cast(excludefromhonorroll as int) as excludefromhonorroll,
    cast(excludefromstoredgrades as int) as excludefromstoredgrades,
    cast(grade_level as int) as grade_level,
    cast(gradebooktype as int) as gradebooktype,
    cast(gradescaleid as int) as gradescaleid,
    cast(id as int) as id,
    cast(maxcut as int) as maxcut,
    cast(maxenrollment as int) as maxenrollment,
    cast(no_of_students as int) as no_of_students,
    cast(noofterms as int) as noofterms,
    cast(parent_section_id as int) as parent_section_id,
    cast(pgversion as int) as pgversion,
    cast(programid as int) as programid,
    cast(rostermodser as int) as rostermodser,
    cast(schedulesectionid as int) as schedulesectionid,
    cast(schoolid as int) as schoolid,
    cast(sortorder as int) as sortorder,
    cast(teacher as int) as teacher,
    cast(termid as int) as termid,
    cast(trackteacheratt as int) as trackteacheratt,
    cast(wheretaught as int) as wheretaught,
    cast(wheretaughtdistrict as int) as wheretaughtdistrict,
    cast(whomodifiedid as int) as whomodifiedid,

    cast(lastattupdate as date) as lastattupdate,

    cast(transaction_date as timestamp) as transaction_date,

    cast(bitmap as bytes) as bitmap,
from {{ source("powerschool_sftp", "src_powerschool__sections") }}
