select
    * except (
        dcid,
        id,
        noofcurclasses,
        sched_isteacherfree,
        sched_lunch,
        sched_maximumconsecutive,
        sched_maximumcourses,
        sched_maximumduty,
        sched_maximumfree,
        sched_maxpers,
        sched_maxpreps,
        sched_scheduled,
        sched_substitute,
        sched_teachermoreoneschool,
        sched_totalcourses,
        sched_usebuilding,
        sched_usehouse,
        schoolid,
        staffstatus,
        `status`,
        users_dcid,
        whomodifiedid,
        balance1,
        balance2,
        balance3,
        balance4,
        transaction_date
    ),

    cast(dcid as int) as dcid,
    cast(id as int) as id,
    cast(noofcurclasses as int) as noofcurclasses,
    cast(schoolid as int) as schoolid,
    cast(staffstatus as int) as staffstatus,
    cast(`status` as int) as `status`,
    cast(users_dcid as int) as users_dcid,
    cast(whomodifiedid as int) as whomodifiedid,

    cast(balance1 as float64) as balance1,
    cast(balance2 as float64) as balance2,
    cast(balance3 as float64) as balance3,
    cast(balance4 as float64) as balance4,

    cast(transaction_date as timestamp) as transaction_date,

    if(sched_isteacherfree = 'true', 1, 0) as sched_isteacherfree,
    if(sched_lunch = 'true', 1, 0) as sched_lunch,
    if(sched_maximumconsecutive = 'true', 1, 0) as sched_maximumconsecutive,
    if(sched_maximumcourses = 'true', 1, 0) as sched_maximumcourses,
    if(sched_maximumduty = 'true', 1, 0) as sched_maximumduty,
    if(sched_maximumfree = 'true', 1, 0) as sched_maximumfree,
    if(sched_maxpers = 'true', 1, 0) as sched_maxpers,
    if(sched_maxpreps = 'true', 1, 0) as sched_maxpreps,
    if(sched_scheduled = 'true', 1, 0) as sched_scheduled,
    if(sched_substitute = 'true', 1, 0) as sched_substitute,
    if(sched_teachermoreoneschool = 'true', 1, 0) as sched_teachermoreoneschool,
    if(sched_totalcourses = 'true', 1, 0) as sched_totalcourses,
    if(sched_usebuilding = 'true', 1, 0) as sched_usebuilding,
    if(sched_usehouse = 'true', 1, 0) as sched_usehouse,
from {{ source("powerschool_sftp", "src_powerschool__schoolstaff") }}
