select
    * except (
        cumulativedaysabsent,
        cumulativedayspresent,
        cumulativestateabs,
        daysopen,
        deviceowner,
        devicetype,
        homelessprimarynighttimeres,
        internetconnectivity,
        languageacquisition,
        learningenvironment,
        lep_completion_date_refused,
        lep_tf,
        reenrollmentsdcid,
        remotedaysabsent,
        remotedayspresent,
        retained_tf,
        sid_excludeenrollment,
        pid_504_tf,
        declassificationspeddate,
        districtentrydate,
        elp_screener_date,
        lepbegindate,
        lepbegindate2,
        lependdate,
        liep_parent_refusal_date,
        liependdate2,
        schoolentrydate,
        sid_entrydate,
        sid_exitdate,
        withdrawal_date,
        whencreated,
        whenmodified,
        source_file_name
    ),

    cast(cumulativedaysabsent as int) as cumulativedaysabsent,
    cast(cumulativedayspresent as int) as cumulativedayspresent,
    cast(cumulativestateabs as int) as cumulativestateabs,
    cast(daysopen as int) as daysopen,
    cast(deviceowner as int) as deviceowner,
    cast(devicetype as int) as devicetype,
    cast(homelessprimarynighttimeres as int) as homelessprimarynighttimeres,
    cast(internetconnectivity as int) as internetconnectivity,
    cast(languageacquisition as int) as languageacquisition,
    cast(learningenvironment as int) as learningenvironment,
    cast(lep_completion_date_refused as int) as lep_completion_date_refused,
    cast(lep_tf as int) as lep_tf,
    cast(reenrollmentsdcid as int) as reenrollmentsdcid,
    cast(remotedaysabsent as int) as remotedaysabsent,
    cast(remotedayspresent as int) as remotedayspresent,
    cast(retained_tf as int) as retained_tf,
    cast(sid_excludeenrollment as int) as sid_excludeenrollment,

    parse_date('%m/%d/%Y', declassificationspeddate) as declassificationspeddate,
    parse_date('%m/%d/%Y', districtentrydate) as districtentrydate,
    parse_date('%m/%d/%Y', elp_screener_date) as elp_screener_date,
    parse_date('%m/%d/%Y', lepbegindate) as lepbegindate,
    parse_date('%m/%d/%Y', lepbegindate2) as lepbegindate2,
    parse_date('%m/%d/%Y', lependdate) as lependdate,
    parse_date('%m/%d/%Y', liep_parent_refusal_date) as liep_parent_refusal_date,
    parse_date('%m/%d/%Y', liependdate2) as liependdate2,
    parse_date('%m/%d/%Y', schoolentrydate) as schoolentrydate,
    parse_date('%m/%d/%Y', sid_entrydate) as sid_entrydate,
    parse_date('%m/%d/%Y', sid_exitdate) as sid_exitdate,
    parse_date('%m/%d/%Y', withdrawal_date) as withdrawal_date,

    parse_timestamp('%m/%d/%Y', whencreated) as whencreated,
    parse_timestamp('%m/%d/%Y', whenmodified) as whenmodified,

    if(pid_504_tf = '1', true, false) as pid_504_tf,
from {{ source("powerschool_sftp", "src_powerschool__s_nj_ren_x") }}
