select
    * except (
        add_to_gpa,
        credit_hours,
        crhrweight,
        dcid,
        exclude_ada,
        excludefromclassrank,
        excludefromgpa,
        excludefromhonorroll,
        excludefromstoredgrades,
        gpa_addedvalue,
        gradescaleid,
        id,
        iscareertech,
        isfitnesscourse,
        ispewaiver,
        maxclasssize,
        maxcredit,
        programid,
        regavailable,
        sched_balanceterms,
        sched_blockstart,
        sched_closesectionaftermax,
        sched_concurrentflag,
        sched_consecutiveperiods,
        sched_consecutiveterms,
        sched_coursepackage,
        sched_do_not_print,
        sched_frequency,
        sched_labflag,
        sched_labfrequency,
        sched_labperiodspermeeting,
        sched_lengthinnumberofterms,
        sched_loadpriority,
        sched_lunchcourse,
        sched_maximumdayspercycle,
        sched_maximumenrollment,
        sched_maximumperiodsperday,
        sched_minimumdayspercycle,
        sched_minimumperiodsperday,
        sched_multiplerooms,
        sched_periodspercycle,
        sched_periodspermeeting,
        sched_repeatsallowed,
        sched_scheduled,
        sched_sectionsoffered,
        sched_substitutionallowed,
        sched_teachercount,
        sched_usepreestablishedteams,
        sched_usesectiontypes,
        sched_year,
        schoolgroup,
        schoolid,
        sectionstooffer,
        `status`,
        targetclasssize,
        transaction_date,
        vocational,
        whomodifiedid
    ),

    cast(dcid as int) as dcid,
    cast(id as int) as id,
    cast(exclude_ada as int) as exclude_ada,
    cast(excludefromclassrank as int) as excludefromclassrank,
    cast(excludefromgpa as int) as excludefromgpa,
    cast(excludefromhonorroll as int) as excludefromhonorroll,
    cast(excludefromstoredgrades as int) as excludefromstoredgrades,
    cast(gradescaleid as int) as gradescaleid,
    cast(iscareertech as int) as iscareertech,
    cast(isfitnesscourse as int) as isfitnesscourse,
    cast(ispewaiver as int) as ispewaiver,
    cast(maxclasssize as int) as maxclasssize,
    cast(programid as int) as programid,
    cast(regavailable as int) as regavailable,
    cast(sched_balanceterms as int) as sched_balanceterms,
    cast(sched_blockstart as int) as sched_blockstart,
    cast(sched_closesectionaftermax as int) as sched_closesectionaftermax,
    cast(sched_concurrentflag as int) as sched_concurrentflag,
    cast(sched_consecutiveperiods as int) as sched_consecutiveperiods,
    cast(sched_consecutiveterms as int) as sched_consecutiveterms,
    cast(sched_coursepackage as int) as sched_coursepackage,
    cast(sched_do_not_print as int) as sched_do_not_print,
    cast(sched_frequency as int) as sched_frequency,
    cast(sched_labflag as int) as sched_labflag,
    cast(sched_labfrequency as int) as sched_labfrequency,
    cast(sched_labperiodspermeeting as int) as sched_labperiodspermeeting,
    cast(sched_lengthinnumberofterms as int) as sched_lengthinnumberofterms,
    cast(sched_loadpriority as int) as sched_loadpriority,
    cast(sched_lunchcourse as int) as sched_lunchcourse,
    cast(sched_maximumdayspercycle as int) as sched_maximumdayspercycle,
    cast(sched_maximumenrollment as int) as sched_maximumenrollment,
    cast(sched_maximumperiodsperday as int) as sched_maximumperiodsperday,
    cast(sched_minimumdayspercycle as int) as sched_minimumdayspercycle,
    cast(sched_minimumperiodsperday as int) as sched_minimumperiodsperday,
    cast(sched_multiplerooms as int) as sched_multiplerooms,
    cast(sched_periodspercycle as int) as sched_periodspercycle,
    cast(sched_periodspermeeting as int) as sched_periodspermeeting,
    cast(sched_repeatsallowed as int) as sched_repeatsallowed,
    cast(sched_scheduled as int) as sched_scheduled,
    cast(sched_sectionsoffered as int) as sched_sectionsoffered,
    cast(sched_substitutionallowed as int) as sched_substitutionallowed,
    cast(sched_teachercount as int) as sched_teachercount,
    cast(sched_usepreestablishedteams as int) as sched_usepreestablishedteams,
    cast(sched_usesectiontypes as int) as sched_usesectiontypes,
    cast(sched_year as int) as sched_year,
    cast(schoolgroup as int) as schoolgroup,
    cast(schoolid as int) as schoolid,
    cast(sectionstooffer as int) as sectionstooffer,
    cast(`status` as int) as `status`,
    cast(targetclasssize as int) as targetclasssize,
    cast(vocational as int) as vocational,
    cast(whomodifiedid as int) as whomodifiedid,

    cast(add_to_gpa as float64) as add_to_gpa,
    cast(credit_hours as float64) as credit_hours,
    cast(crhrweight as float64) as crhrweight,
    cast(gpa_addedvalue as float64) as gpa_addedvalue,
    cast(maxcredit as float64) as maxcredit,

    cast(transaction_date as timestamp) as transaction_date,

{#
| prerequisites                   | STRING          |               | missing in contract   |
| sched_validextradaycombinations | STRING          |               | missing in contract   |
| custom                          |                 | STRING        | missing in definition |
| executionid                     |                 | STRING        | missing in definition |
| prerequisitesvalue              |                 | STRING        | missing in definition |
| validextradaycombinations       |                 | STRING        | missing in definition |
#}
from {{ source("powerschool_sftp", "src_powerschool__courses") }}
