select
    * except (
        allowwebaccess,
        campusid,
        classof,
        dcid,
        districtentrygradelevel,
        enroll_status,
        enrollment_schoolid,
        enrollmentcode,
        enrollmentid,
        exclude_fr_rank,
        fedethnicity,
        fedracedecline,
        fee_exemption_status,
        fteid,
        gpentryyear,
        grade_level,
        gradreqsetid,
        graduated_rank,
        graduated_schoolid,
        id,
        ldapenabled,
        next_school,
        person_id,
        phone_id,
        photoflag,
        sched_loadlock,
        sched_lockstudentschedule,
        sched_nextyeargrade,
        sched_priority,
        sched_scheduled,
        sched_yearofgraduation,
        schoolentrygradelevel,
        schoolid,
        sdatarn,
        state_enrollflag,
        state_excludefromreporting,
        student_allowwebaccess,
        student_number,
        summerschoolid,
        teachergroupid,
        tuitionpayer,
        whomodifiedid,
        wm_createtime,
        wm_tier,
        balance1,
        balance2,
        balance3,
        balance4,
        cumulative_gpa,
        cumulative_pct,
        customrank_gpa,
        fulltimeequiv_obsolete,
        lunch_id,
        membershipshare,
        simple_gpa,
        simple_pct,
        alert_disciplineexpires,
        alert_guardianexpires,
        alert_medicalexpires,
        alert_otherexpires,
        applic_response_recvd_date,
        applic_submitted_date,
        districtentrydate,
        dob,
        enrollment_transfer_date_pend,
        entrydate,
        exitdate,
        schoolentrydate,
        wm_createdate,
        wm_statusdate,
        wm_ta_date,
        transaction_date,
        enrollment_transfer_info
    ),

    cast(allowwebaccess as int) as allowwebaccess,
    cast(campusid as int) as campusid,
    cast(classof as int) as classof,
    cast(dcid as int) as dcid,
    cast(districtentrygradelevel as int) as districtentrygradelevel,
    cast(enroll_status as int) as enroll_status,
    cast(enrollment_schoolid as int) as enrollment_schoolid,
    cast(enrollmentcode as int) as enrollmentcode,
    cast(enrollmentid as int) as enrollmentid,
    cast(exclude_fr_rank as int) as exclude_fr_rank,
    cast(fedethnicity as int) as fedethnicity,
    cast(fedracedecline as int) as fedracedecline,
    cast(fee_exemption_status as int) as fee_exemption_status,
    cast(fteid as int) as fteid,
    cast(gpentryyear as int) as gpentryyear,
    cast(grade_level as int) as grade_level,
    cast(gradreqsetid as int) as gradreqsetid,
    cast(graduated_rank as int) as graduated_rank,
    cast(graduated_schoolid as int) as graduated_schoolid,
    cast(id as int) as id,
    cast(ldapenabled as int) as ldapenabled,
    cast(next_school as int) as next_school,
    cast(person_id as int) as person_id,
    cast(phone_id as int) as phone_id,
    cast(photoflag as int) as photoflag,
    cast(sched_loadlock as int) as sched_loadlock,
    cast(sched_lockstudentschedule as int) as sched_lockstudentschedule,
    cast(sched_nextyeargrade as int) as sched_nextyeargrade,
    cast(sched_priority as int) as sched_priority,
    cast(sched_scheduled as int) as sched_scheduled,
    cast(sched_yearofgraduation as int) as sched_yearofgraduation,
    cast(schoolentrygradelevel as int) as schoolentrygradelevel,
    cast(schoolid as int) as schoolid,
    cast(sdatarn as int) as sdatarn,
    cast(state_enrollflag as int) as state_enrollflag,
    cast(state_excludefromreporting as int) as state_excludefromreporting,
    cast(student_allowwebaccess as int) as student_allowwebaccess,
    cast(student_number as int) as student_number,
    cast(summerschoolid as int) as summerschoolid,
    cast(teachergroupid as int) as teachergroupid,
    cast(tuitionpayer as int) as tuitionpayer,
    cast(whomodifiedid as int) as whomodifiedid,
    cast(wm_createtime as int) as wm_createtime,
    cast(wm_tier as int) as wm_tier,

    cast(balance1 as float64) as balance1,
    cast(balance2 as float64) as balance2,
    cast(balance3 as float64) as balance3,
    cast(balance4 as float64) as balance4,
    cast(cumulative_gpa as float64) as cumulative_gpa,
    cast(cumulative_pct as float64) as cumulative_pct,
    cast(customrank_gpa as float64) as customrank_gpa,
    cast(fulltimeequiv_obsolete as float64) as fulltimeequiv_obsolete,
    cast(lunch_id as float64) as lunch_id,
    cast(membershipshare as float64) as membershipshare,
    cast(simple_gpa as float64) as simple_gpa,
    cast(simple_pct as float64) as simple_pct,

    cast(alert_disciplineexpires as date) as alert_disciplineexpires,
    cast(alert_guardianexpires as date) as alert_guardianexpires,
    cast(alert_medicalexpires as date) as alert_medicalexpires,
    cast(alert_otherexpires as date) as alert_otherexpires,
    cast(applic_response_recvd_date as date) as applic_response_recvd_date,
    cast(applic_submitted_date as date) as applic_submitted_date,
    cast(districtentrydate as date) as districtentrydate,
    cast(dob as date) as dob,
    cast(enrollment_transfer_date_pend as date) as enrollment_transfer_date_pend,
    cast(entrydate as date) as entrydate,
    cast(exitdate as date) as exitdate,
    cast(schoolentrydate as date) as schoolentrydate,
    cast(wm_createdate as date) as wm_createdate,
    cast(wm_statusdate as date) as wm_statusdate,
    cast(wm_ta_date as date) as wm_ta_date,

    cast(transaction_date as timestamp) as transaction_date,

    cast(enrollment_transfer_info as bytes) as enrollment_transfer_info,

{#
| custom                        |                 | STRING        | missing in definition |
| ethnicity_code                |                 | STRING        | missing in definition |
| executionid                   |                 | STRING        | missing in definition |
| gender_code                   |                 | STRING        | missing in definition |
| ismigrated                    |                 | INT64         | missing in definition |
#}
from {{ source("powerschool_sftp", "src_powerschool__students") }}
