select
    * except (
        asmt_exclude_ela,
        asmt_exclude_math,
        caresactfunds,
        collegecreditsearned,
        ctecollegecredits,
        cteworkbasedlearning,
        cumdaysinmembershipaddto_tf,
        cumdayspresentaddto_tf,
        cumdaystowardtruancyaddto_tf,
        cumulativestateabs,
        daysopen,
        deviceowner,
        devicetype,
        eoc_title1biology_tf,
        homelessprimarynighttimeres,
        iep_exemptpassingbiology_tf,
        iep_exemptpassinglal_tf,
        iep_exemptpassingmath_tf,
        iep_exempttakingbiology_tf,
        iep_exempttakinglal_tf,
        iep_exempttakingmath_tf,
        includeinassareport_tf,
        includeinctereport_tf,
        includeinnjsmart_tf,
        includeinstucourse_tf,
        internetconnectivity,
        languageacquisition,
        learningenvironment,
        lep_completion_date_refused,
        lep_tf,
        migrant_tf,
        military_connected_indicator,
        pid_504_tf,
        pid_accommodations_a_tf,
        pid_accommodations_b_tf,
        pid_accommodations_c_tf,
        pid_accommodations_d_tf,
        pid_apalangartsliteracy_tf,
        pid_apamath_tf,
        pid_apascience_tf,
        pid_lepexemptlal_tf,
        pid_madetape_tf,
        pid_outofdistplacement_tf,
        pid_outresidenceplacement_tf,
        pid_shortsegmenttestadmin_tf,
        pid_title1langartslit_tf,
        pid_title1math_tf,
        pid_title1science_tf,
        remotepercentageofday,
        retained_tf,
        sid_excludeenrollment,
        sla_alt_rep_paper,
        sla_alternate_location,
        sla_answer_masking,
        sla_answers_recorded_paper,
        sla_asl_video,
        sla_closed_caption,
        sla_dictionary,
        sla_directions_clarified,
        sla_exclude_tf,
        sla_frequent_breaks,
        sla_human_signer,
        sla_large_print_paper,
        sla_monitor_response,
        sla_non_screen_reader,
        sla_read_aloud,
        sla_refresh_braille,
        sla_screen_reader,
        sla_small_group,
        sla_special_equip,
        sla_specified_area,
        sla_time_of_day,
        sla_unique_accommodation,
        sla_word_prediction,
        studentsdcid,
        title1_status_tf,
        tiv_serv_aide_tf,
        tiv_serv_assist_tf,
        tiv_serv_extyear_tf,
        tiv_serv_ind_instr_tf,
        tiv_serv_indnursing_tf,
        tiv_serv_intensive_tf,
        tiv_serv_interpreter_tf,
        tiv_serv_pupil_tf,
        tiv_serv_resplacement_tf,
        adulths_nb_credits,
        cumulativedaysabsent,
        cumulativedaysinmembership,
        cumulativedayspresent,
        cumulativedaystowardtruancy,
        remotedaysabsent,
        remotedaysmembership,
        remotedayspresent,
        annual_iep_review_meeting_date,
        asmt_first_enroll_in_us_school,
        charter_date,
        datelastleadtest,
        datelastmedexam,
        dateofpolioimmun,
        declassificationspeddate,
        eligibility_determ_date,
        elp_screener_date,
        firstentrydateintoausschool,
        iep_begin_date,
        iep_end_date,
        initial_iep_meeting_date,
        lepbegindate,
        lepbegindate2,
        lependdate,
        liep_parent_refusal_date,
        liependdate2,
        parent_consent_intial_iep_date,
        parental_consent_eval_date,
        reevaluation_date,
        referral_date,
        sid_entrydate,
        sid_exitdate,
        withdrawal_date,
        whencreated,
        whenmodified,
        source_file_name
    ),

    cast(asmt_exclude_ela as int) as asmt_exclude_ela,
    cast(asmt_exclude_math as int) as asmt_exclude_math,
    cast(caresactfunds as int) as caresactfunds,
    cast(collegecreditsearned as int) as collegecreditsearned,
    cast(ctecollegecredits as int) as ctecollegecredits,
    cast(cteworkbasedlearning as int) as cteworkbasedlearning,
    cast(cumdaysinmembershipaddto_tf as int) as cumdaysinmembershipaddto_tf,
    cast(cumdayspresentaddto_tf as int) as cumdayspresentaddto_tf,
    cast(cumdaystowardtruancyaddto_tf as int) as cumdaystowardtruancyaddto_tf,
    cast(cumulativestateabs as int) as cumulativestateabs,
    cast(daysopen as int) as daysopen,
    cast(deviceowner as int) as deviceowner,
    cast(devicetype as int) as devicetype,
    cast(eoc_title1biology_tf as int) as eoc_title1biology_tf,
    cast(homelessprimarynighttimeres as int) as homelessprimarynighttimeres,
    cast(iep_exemptpassingbiology_tf as int) as iep_exemptpassingbiology_tf,
    cast(iep_exemptpassinglal_tf as int) as iep_exemptpassinglal_tf,
    cast(iep_exemptpassingmath_tf as int) as iep_exemptpassingmath_tf,
    cast(iep_exempttakingbiology_tf as int) as iep_exempttakingbiology_tf,
    cast(iep_exempttakinglal_tf as int) as iep_exempttakinglal_tf,
    cast(iep_exempttakingmath_tf as int) as iep_exempttakingmath_tf,
    cast(includeinassareport_tf as int) as includeinassareport_tf,
    cast(includeinctereport_tf as int) as includeinctereport_tf,
    cast(includeinnjsmart_tf as int) as includeinnjsmart_tf,
    cast(includeinstucourse_tf as int) as includeinstucourse_tf,
    cast(internetconnectivity as int) as internetconnectivity,
    cast(languageacquisition as int) as languageacquisition,
    cast(learningenvironment as int) as learningenvironment,
    cast(lep_completion_date_refused as int) as lep_completion_date_refused,
    cast(lep_tf as int) as lep_tf,
    cast(migrant_tf as int) as migrant_tf,
    cast(military_connected_indicator as int) as military_connected_indicator,
    cast(pid_504_tf as int) as pid_504_tf,
    cast(pid_accommodations_a_tf as int) as pid_accommodations_a_tf,
    cast(pid_accommodations_b_tf as int) as pid_accommodations_b_tf,
    cast(pid_accommodations_c_tf as int) as pid_accommodations_c_tf,
    cast(pid_accommodations_d_tf as int) as pid_accommodations_d_tf,
    cast(pid_apalangartsliteracy_tf as int) as pid_apalangartsliteracy_tf,
    cast(pid_apamath_tf as int) as pid_apamath_tf,
    cast(pid_apascience_tf as int) as pid_apascience_tf,
    cast(pid_lepexemptlal_tf as int) as pid_lepexemptlal_tf,
    cast(pid_madetape_tf as int) as pid_madetape_tf,
    cast(pid_outofdistplacement_tf as int) as pid_outofdistplacement_tf,
    cast(pid_outresidenceplacement_tf as int) as pid_outresidenceplacement_tf,
    cast(pid_shortsegmenttestadmin_tf as int) as pid_shortsegmenttestadmin_tf,
    cast(pid_title1langartslit_tf as int) as pid_title1langartslit_tf,
    cast(pid_title1math_tf as int) as pid_title1math_tf,
    cast(pid_title1science_tf as int) as pid_title1science_tf,
    cast(remotepercentageofday as int) as remotepercentageofday,
    cast(retained_tf as int) as retained_tf,
    cast(sid_excludeenrollment as int) as sid_excludeenrollment,
    cast(sla_alt_rep_paper as int) as sla_alt_rep_paper,
    cast(sla_alternate_location as int) as sla_alternate_location,
    cast(sla_answer_masking as int) as sla_answer_masking,
    cast(sla_answers_recorded_paper as int) as sla_answers_recorded_paper,
    cast(sla_asl_video as int) as sla_asl_video,
    cast(sla_closed_caption as int) as sla_closed_caption,
    cast(sla_dictionary as int) as sla_dictionary,
    cast(sla_directions_clarified as int) as sla_directions_clarified,
    cast(sla_exclude_tf as int) as sla_exclude_tf,
    cast(sla_frequent_breaks as int) as sla_frequent_breaks,
    cast(sla_human_signer as int) as sla_human_signer,
    cast(sla_large_print_paper as int) as sla_large_print_paper,
    cast(sla_monitor_response as int) as sla_monitor_response,
    cast(sla_non_screen_reader as int) as sla_non_screen_reader,
    cast(sla_read_aloud as int) as sla_read_aloud,
    cast(sla_refresh_braille as int) as sla_refresh_braille,
    cast(sla_screen_reader as int) as sla_screen_reader,
    cast(sla_small_group as int) as sla_small_group,
    cast(sla_special_equip as int) as sla_special_equip,
    cast(sla_specified_area as int) as sla_specified_area,
    cast(sla_time_of_day as int) as sla_time_of_day,
    cast(sla_unique_accommodation as int) as sla_unique_accommodation,
    cast(sla_word_prediction as int) as sla_word_prediction,
    cast(studentsdcid as int) as studentsdcid,
    cast(title1_status_tf as int) as title1_status_tf,
    cast(tiv_serv_aide_tf as int) as tiv_serv_aide_tf,
    cast(tiv_serv_assist_tf as int) as tiv_serv_assist_tf,
    cast(tiv_serv_extyear_tf as int) as tiv_serv_extyear_tf,
    cast(tiv_serv_ind_instr_tf as int) as tiv_serv_ind_instr_tf,
    cast(tiv_serv_indnursing_tf as int) as tiv_serv_indnursing_tf,
    cast(tiv_serv_intensive_tf as int) as tiv_serv_intensive_tf,
    cast(tiv_serv_interpreter_tf as int) as tiv_serv_interpreter_tf,
    cast(tiv_serv_pupil_tf as int) as tiv_serv_pupil_tf,
    cast(tiv_serv_resplacement_tf as int) as tiv_serv_resplacement_tf,

    cast(adulths_nb_credits as numeric) as adulths_nb_credits,
    cast(cumulativedaysabsent as numeric) as cumulativedaysabsent,
    cast(cumulativedaysinmembership as numeric) as cumulativedaysinmembership,
    cast(cumulativedayspresent as numeric) as cumulativedayspresent,
    cast(cumulativedaystowardtruancy as numeric) as cumulativedaystowardtruancy,
    cast(remotedaysabsent as numeric) as remotedaysabsent,
    cast(remotedaysmembership as numeric) as remotedaysmembership,
    cast(remotedayspresent as numeric) as remotedayspresent,

    parse_date(
        '%m/%d/%Y', annual_iep_review_meeting_date
    ) as annual_iep_review_meeting_date,
    parse_date(
        '%m/%d/%Y', asmt_first_enroll_in_us_school
    ) as asmt_first_enroll_in_us_school,
    parse_date('%m/%d/%Y', charter_date) as charter_date,
    parse_date('%m/%d/%Y', datelastleadtest) as datelastleadtest,
    parse_date('%m/%d/%Y', datelastmedexam) as datelastmedexam,
    parse_date('%m/%d/%Y', dateofpolioimmun) as dateofpolioimmun,
    parse_date('%m/%d/%Y', declassificationspeddate) as declassificationspeddate,
    parse_date('%m/%d/%Y', eligibility_determ_date) as eligibility_determ_date,
    parse_date('%m/%d/%Y', elp_screener_date) as elp_screener_date,
    parse_date('%m/%d/%Y', firstentrydateintoausschool) as firstentrydateintoausschool,
    parse_date('%m/%d/%Y', iep_begin_date) as iep_begin_date,
    parse_date('%m/%d/%Y', iep_end_date) as iep_end_date,
    parse_date('%m/%d/%Y', initial_iep_meeting_date) as initial_iep_meeting_date,
    parse_date('%m/%d/%Y', lepbegindate) as lepbegindate,
    parse_date('%m/%d/%Y', lepbegindate2) as lepbegindate2,
    parse_date('%m/%d/%Y', lependdate) as lependdate,
    parse_date('%m/%d/%Y', liep_parent_refusal_date) as liep_parent_refusal_date,
    parse_date('%m/%d/%Y', liependdate2) as liependdate2,
    parse_date(
        '%m/%d/%Y', parent_consent_intial_iep_date
    ) as parent_consent_intial_iep_date,
    parse_date('%m/%d/%Y', parental_consent_eval_date) as parental_consent_eval_date,
    parse_date('%m/%d/%Y', reevaluation_date) as reevaluation_date,
    parse_date('%m/%d/%Y', referral_date) as referral_date,
    parse_date('%m/%d/%Y', sid_entrydate) as sid_entrydate,
    parse_date('%m/%d/%Y', sid_exitdate) as sid_exitdate,
    parse_date('%m/%d/%Y', withdrawal_date) as withdrawal_date,

    parse_timestamp('%m/%d/%Y', whencreated) as whencreated,
    parse_timestamp('%m/%d/%Y', whenmodified) as whenmodified,
from {{ source("powerschool_sftp", "src_powerschool__s_nj_stu_x") }}
