select
    _id as user_id,
    accountingid as accounting_id,
    archivedat as archived_at,
    calendaremail as calendar_email,
    canvasid as canvas_id,
    cleverid as clever_id,
    coach,
    created,
    district,
    email,
    endofyearvisible as end_of_year_visible,
    evaluator,
    `first`,
    googleid as google_id,
    inactive,
    internalid as internal_id,
    ispracticeuser as is_practice_user,
    `last`,
    lastactivity as last_activity,
    lastmodified as last_modified,
    locked,
    `name`,
    noninstructional as non_instructional,
    oktaid as okta_id,
    pastusertypes as past_user_types,
    powerschoolid as power_school_id,
    `readonly` as `read_only`,
    showondashboards as show_on_dashboards,
    sibmeid as sibme_id,
    sibmetoken as sibme_token,
    track,
    usertag1 as user_tag_1,
    usertag2 as user_tag_2,
    usertag3 as user_tag_3,
    usertag4 as user_tag_4,
    usertag5 as user_tag_5,
    usertag6 as user_tag_6,
    usertag7 as user_tag_7,
    usertag8 as user_tag_8,
    videolicense as video_license,

    safe_cast(internalid as int) as internal_id_int,

    defaultinformation.course as default_information_course,
    defaultinformation.gradelevel as default_information_grade_level,
    defaultinformation.period as default_information_period,
    defaultinformation.school as default_information_school,

    pluconfig.enddate as plu_config_end_date,
    pluconfig.required as plu_config_required,
    pluconfig.startdate as plu_config_start_date,

    preferences.actionsdashtimeframe as preferences_actions_dash_timeframe,
    preferences.homepage as preferences_homepage,
    preferences.lastschoolselected as preferences_last_school_selected,
    preferences.showactionstepmessage as preferences_show_action_step_message,
    preferences.showdcpsmessage as preferences_show_dcps_message,
    preferences.showsystemwidemessage as preferences_show_system_wide_message,
    preferences.showtutorial as preferences_show_tutorial,
    preferences.timezone as preferences_timezone,
    preferences.timezonetext as preferences_timezone_text,
    preferences.unsubscribedto as preferences_unsubscribed_to,

    preferences.admindashboard.hidden as preferences_admin_dashboard_hidden,
    preferences.navbar.shortcuts as preferences_nav_bar_shortcuts,
    preferences.obspage.collapsedpanes as preferences_obs_page_collapsed_panes,
    preferences.obspage.panelwidth as preferences_obs_page_panel_width,

    usertype.__v as user_type__v,
    usertype._id as user_type_id,
    usertype.abbreviation as user_type_abbreviation,
    usertype.archivedat as user_type_archived_at,
    usertype.created as user_type_created,
    usertype.creator as user_type_creator,
    usertype.district as user_type_district,
    usertype.lastmodified as user_type_last_modified,
    usertype.name as user_type_name,

    usertype.expectations.exceeding as user_type_expectations_exceeding,
    usertype.expectations.exceedingaggregate
    as user_type_expectations_exceeding_aggregate,
    usertype.expectations.meeting as user_type_expectations_meeting,
    usertype.expectations.meetingaggregate as user_type_expectations_meeting_aggregate,
    usertype.expectations.summary as user_type_expectations_summary,

    {# repeated #}
    additionalemails as additional_emails,
    districts,
    endofyearlog as end_of_year_log,

    {# repeated records #}
    districtdata as district_data,
    externalintegrations as external_integrations,
    regionaladminschools as regional_admin_schools,
    roles,
from {{ source("schoolmint_grow", "src_schoolmint_grow__users") }}
where _dagster_partition_key = 'f'
