select
    _id as school_id,
    `name`,
    abbreviation,
    `address`,
    archivedat as archived_at,
    city,
    created,
    district,
    gradespan as grade_span,
    highgrade as high_grade,
    internalid as internal_id,
    lastmodified as last_modified,
    lowgrade as low_grade,
    phone,
    principal,
    region,
    `state`,
    zip,
from {{ source("schoolmint_grow", "src_schoolmint_grow__schools") }}
where _dagster_partition_key = 'f'
