STUDENT_FIELDS = [
    {"name": "activities", "type": ["null", "double"], "default": None},
    {"name": "after_school_logins", "type": ["null", "double"], "default": None},
    {"name": "average_first_try_score", "type": ["null", "double"], "default": None},
    {"name": "average_weekly_activities", "type": ["null", "string"], "default": None},
    {"name": "current_lexile_level", "type": ["null", "double"], "default": None},
    {"name": "current_reading_level", "type": ["null", "double"], "default": None},
    {"name": "district_id", "type": ["null", "long"], "default": None},
    {"name": "district_school_id", "type": ["null", "string"], "default": None},
    {"name": "district_status", "type": ["null", "string"], "default": None},
    {"name": "district", "type": ["null", "string"], "default": None},
    {"name": "editions", "type": ["null", "string"], "default": None},
    {"name": "ell", "type": ["null", "string"], "default": None},
    {"name": "expected_lexile_growth", "type": ["null", "string"], "default": None},
    {"name": "first_login", "type": ["null", "string"], "default": None},
    {"name": "grade", "type": ["null", "long"], "default": None},
    {"name": "interim_percentile_rank", "type": ["null", "string"], "default": None},
    {"name": "interim_test_date", "type": ["null", "string"], "default": None},
    {"name": "interim_test_lexile", "type": ["null", "string"], "default": None},
    {"name": "interim_test_reading_level", "type": ["null", "string"], "default": None},
    {"name": "invalid_activities", "type": ["null", "double"], "default": None},
    {"name": "language_id", "type": ["null", "long"], "default": None},
    {"name": "language", "type": ["null", "string"], "default": None},
    {"name": "last_adjustment_date", "type": ["null", "string"], "default": None},
    {"name": "last_login", "type": ["null", "string"], "default": None},
    {"name": "manual_adjustments", "type": ["null", "string"], "default": None},
    {"name": "passing_activities", "type": ["null", "double"], "default": None},
    {"name": "post_test_date", "type": ["null", "string"], "default": None},
    {"name": "post_test_lexile", "type": ["null", "string"], "default": None},
    {"name": "post_test_percentile_rank", "type": ["null", "string"], "default": None},
    {"name": "post_test_reading_level", "type": ["null", "string"], "default": None},
    {"name": "pre_test_date", "type": ["null", "string"], "default": None},
    {"name": "pre_test_lexile", "type": ["null", "string"], "default": None},
    {"name": "pre_test_percentile_rank", "type": ["null", "string"], "default": None},
    {"name": "pre_test_reading_level", "type": ["null", "string"], "default": None},
    {"name": "program_hours", "type": ["null", "double"], "default": None},
    {"name": "program", "type": ["null", "string"], "default": None},
    {"name": "purchasing_entity", "type": ["null", "string"], "default": None},
    {"name": "school_id", "type": ["null", "long"], "default": None},
    {"name": "school", "type": ["null", "string"], "default": None},
    {"name": "sped", "type": ["null", "string"], "default": None},
    {"name": "student_id", "type": ["null", "long"], "default": None},
    {"name": "student_name", "type": ["null", "string"], "default": None},
    {"name": "top_career_cluster", "type": ["null", "string"], "default": None},
    {"name": "top_career_name", "type": ["null", "string"], "default": None},
    {"name": "total_activities", "type": ["null", "double"], "default": None},
    {"name": "total_logins", "type": ["null", "double"], "default": None},
    {"name": "user_id", "type": ["null", "long"], "default": None},
    {"name": "writing_assignments", "type": ["null", "double"], "default": None},
    {
        "name": "college_and_career_readiness_current",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "college_and_career_readiness_pre_test",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "reading_connections_summarization",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_connections_generate_questions",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "reading_connections_setting_the_purpose",
        "type": ["null", "double"],
        "default": None,
    },
    {
        "name": "pre_test_normal_curve_equivalent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "interim_normal_curve_equivalent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "post_test_normal_curve_equivalent",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "college_and_career_readiness_interim_test",
        "type": ["null", "string"],
        "default": None,
    },
    {
        "name": "college_and_career_readiness_post_test",
        "type": ["null", "string"],
        "default": None,
    },
]

ASSET_FIELDS = {
    "students": STUDENT_FIELDS,
}
