select distinct
    -- noqa: disable=RF05
    course_number as `01 Course ID`,
    course_name as `02 Full Name`,
    course_name as `03 Short Name`,
    credittype as `04 Department Name`,
    null as `05 Low Grade Level ID`,
    null as `06 High Grade Level ID`,
    null as `07 Site ID List`,
    null as `08 Active`,
    null as `09 A - G Requirement Category`,
    null as `10 Course Weight`,
    null as `11 Course Description`,
    null as `12 Credits Possible`,
    null as `13 Variable Credit Class`,
    null as `14 Maximum Credits`,
    null as `15 Special Education Course`,
    null as `16 Max Capacity`,
    null as `17 Intervention Course`,
    null as `18 Nclb Instructional Level`,
    null as `19 Course Content`,
    null as `20 Education Service`,
    null as `21 Instructional Strategy`,
    null as `22 Program Funding Source`,
    null as `23 Cte Funding Provider`,
    null as `24 Tech Prep`,
from {{ ref("stg_powerschool__courses") }}
