"""Compare the deployed model against the catalog at the PINNED revision.

Comparing against the newest catalog on `main` would turn this red on every
production change, and a gate that cries wolf gets overridden.

`/meta` is generated by `CubeToMetaTransformer.compile()` and never touches
the warehouse, so this proves the deployed model IS the pinned model and
nothing whatever about the data. That is worth having on its own: the sandbox
deploys by running a command against a tagged checkout, and a deploy that
silently did not take is the failure nobody notices.
"""

from __future__ import annotations

from typing import Any


def _members(doc: dict[str, Any]) -> set[str]:
    return {
        m["name"]
        for cube in doc.get("cubes", [])
        for key in ("measures", "dimensions")
        for m in cube.get(key, [])
    }


def member_diff(live: dict[str, Any], catalog: dict[str, Any]) -> dict[str, list[str]]:
    a, b = _members(live), _members(catalog)
    return {"added": sorted(a - b), "removed": sorted(b - a)}


def exit_code(diff: dict[str, list[str]]) -> int:
    """Non-zero if the deployed surface differs from the pinned catalog.

    An ADDED member fails as loudly as a removed one. Both mean the deployed
    revision is not the pinned one, and an addition is the shape a deploy
    from the wrong checkout takes — the sandbox is pinned behind `main`, so
    drift shows up as members the catalog has not got yet.
    """
    return 1 if diff["added"] or diff["removed"] else 0


def describe(diff: dict[str, list[str]]) -> str:
    if not diff["added"] and not diff["removed"]:
        return "deployed model matches the pinned catalog member for member"
    parts = []
    if diff["removed"]:
        parts.append(f"missing from the deployment: {', '.join(diff['removed'])}")
    if diff["added"]:
        parts.append(f"not in the pinned catalog: {', '.join(diff['added'])}")
    return "; ".join(parts)
