"""Compare the deployed model against the catalog at the PINNED revision.

Comparing against the newest catalog on `main` would turn this red on every
production change, and a gate that cries wolf gets overridden.

`/meta` is generated by `CubeToMetaTransformer.compile()` and never touches
the warehouse, so this proves the deployed model IS the pinned model and
nothing whatever about the data. That is worth having on its own: the sandbox
deploys by running a command against a tagged checkout, and a deploy that
silently did not take is the failure nobody notices.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path
from typing import Any

# Published to docs/reference/ by the bump procedure, one pin covering the
# model, the snapshot and this catalog together. It is not on `main` yet —
# see the spec's Open list, "Landing cube-catalog-meta.json on main" — so
# this check tells the operator to regenerate it rather than inventing one.
CATALOG_PATH = Path("docs/reference/cube-catalog-meta.json")

REST_URL = "CUBE_SANDBOX_REST_URL"
# trunk-ignore(bandit/B105): the NAME of a variable to read, not a value
API_SECRET = "CUBE_SANDBOX_API_SECRET"

# Any resolvable identity will do: /meta is generated by
# CubeToMetaTransformer.compile() and never reads the warehouse, so the
# member list does not depend on who asks. It still has to be a signed
# identity, because checkAuth verifies before it resolves.
DEFAULT_VIEWER = "amara.fennworth@ktaf-sandbox.invalid"


def _members(doc: dict[str, Any]) -> dict[str, str]:
    """Every member's name -> declared type.

    Keyed by name alone, a dimension changing `string` to `number` diffs
    empty: the name is on both sides, so neither `added` nor `removed`
    fires and the check goes green on a model that is not the pinned one.
    A retype is also the change most likely to break a kit silently, since
    the member still exists and the query still compiles. The bump procedure
    asks for "additions, removals and retypes"; this is the third one.
    """
    return {
        m["name"]: str(m.get("type"))
        for cube in doc.get("cubes", [])
        for key in ("measures", "dimensions")
        for m in cube.get(key, [])
    }


def member_diff(live: dict[str, Any], catalog: dict[str, Any]) -> dict[str, list[str]]:
    a, b = _members(live), _members(catalog)
    return {
        "added": sorted(set(a) - set(b)),
        "removed": sorted(set(b) - set(a)),
        "retyped": sorted(
            f"{name}: {b[name]} -> {a[name]}"
            for name in set(a) & set(b)
            if a[name] != b[name]
        ),
    }


def exit_code(diff: dict[str, list[str]]) -> int:
    """Non-zero if the deployed surface differs from the pinned catalog.

    An ADDED member fails as loudly as a removed one, and a RETYPED one as
    loudly as either. All three mean the deployed revision is not the pinned
    one, and an addition is the shape a deploy from the wrong checkout takes
    — the sandbox is pinned behind `main`, so drift shows up as members the
    catalog has not got yet.
    """
    return 1 if any(diff.get(k) for k in ("added", "removed", "retyped")) else 0


def describe(diff: dict[str, list[str]]) -> str:
    if not exit_code(diff):
        return "deployed model matches the pinned catalog member for member"
    parts = []
    if diff["removed"]:
        parts.append(f"missing from the deployment: {', '.join(diff['removed'])}")
    if diff["added"]:
        parts.append(f"not in the pinned catalog: {', '.join(diff['added'])}")
    if diff.get("retyped"):
        parts.append(f"retyped since the pinned catalog: {', '.join(diff['retyped'])}")
    return "; ".join(parts)


def fetch_meta(url: str, secret: str, viewer: str = DEFAULT_VIEWER) -> dict[str, Any]:
    """The deployed model's `/meta`, as the deployment itself reports it.

    The auth path is the one documented in `src/cube/CLAUDE.md`: mint an
    HS256 token locally whose ENTIRE payload is the security context, so the
    top-level `email` claim is what `checkAuth` reads, and send it raw — no
    `Bearer` prefix. A Cube Cloud Personal Core Data API Token returns 403
    against `/meta` however it is formatted.
    """
    import jwt
    import requests

    now = int(time.time())
    token = jwt.encode({"email": viewer, "iat": now}, secret, algorithm="HS256")
    response = requests.get(
        url.rstrip("/") + "/v1/meta",
        headers={"Authorization": token},
        timeout=60,
    )
    response.raise_for_status()
    return response.json()


def load_catalog(path: Path = CATALOG_PATH) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(
            f"no pinned catalog at {path}. It is generated from the pinned "
            "revision's Cube /meta and committed as part of a bump; this check "
            "compares against it and cannot invent one."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=CATALOG_PATH)
    parser.add_argument("--viewer", default=DEFAULT_VIEWER)
    args = parser.parse_args(argv)

    missing = [name for name in (REST_URL, API_SECRET) if not os.environ.get(name)]
    if missing:
        raise SystemExit(
            "cannot reach the sandbox REST API: set "
            + " and ".join(missing)
            + ". This check reads the DEPLOYED model and has no offline mode."
        )

    live = fetch_meta(os.environ[REST_URL], os.environ[API_SECRET], args.viewer)
    diff = member_diff(live, load_catalog(args.catalog))
    print(describe(diff))
    return exit_code(diff)


if __name__ == "__main__":
    raise SystemExit(main())
