name: MkDocs GitHub Deploy

on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - .github/workflows/mkdocs-gh-deploy.yaml
      - docs/**
      - mkdocs.yml
      - "!docs/superpowers/**"

permissions:
  contents: write

jobs:
  deploy:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # https://github.com/astral-sh/setup-uv
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      # https://github.com/actions/cache
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: uv run --group docs mkdocs gh-deploy --force
