select
    id,
    `name`,
    ownerid as owner_id,
    status__c as `status`,
    student__c as student,
    category__c as category,
    createdbyid as created_by_id,
    createddate as created_date,
    resolution__c as resolution,
    action_plan__c as action_plan,
    date_closed__c as date_closed,
    date_opened__c as date_opened,
    description__c as `description`,
    systemmodstamp as system_modstamp,
    risk_factors__c as risk_factors,
    lastactivitydate as last_activity_date,
    lastmodifiedbyid as last_modified_by_id,
    lastmodifieddate as last_modified_date,
    old_system_id__c as old_system_id,
    referral_reason__c as referral_reason,
    total_days_open__c as total_days_open,
    assigned_couselor__c as assigned_couselor,
    days_since_opened__c as days_since_opened,
    external_provider__c as external_provider,
    referral_subreason__c as referral_subreason,
    counseling_case_count__c as counseling_case_count,
    external_referral_date__c as external_referral_date,
    external_referral_end_date__c as external_referral_end_date,
    date_of_last_counseling_note__c as date_of_last_counseling_note,
from {{ source("kippadb", "counseling_case") }}
where not isdeleted
